# 1. requests 모듈

* HTTP프로토콜을 사용할 수 있게 해주는 모듈
* 파이썬 기본 모듈인 urllib보다 사용이 편리
* 따로 설치 필요 pip install requests/conda install requests

# 2. requests 모듈 사용법

* 1. 모듈 불러오기: import requests
* 2. url을 변수에 저장
* 3. url파라미터를 payload 라는 변수에 딕셔너리 형태로 저장
    * payload = {파라미터1 : value, 파라미터2 : value2}
* 4. headers 도 headers 라는 변수에 딕셔너리 형태로 저장
    * headers = {파라미터1 : value, 파라미터2 : value2}
* 5. HTTP요청 보내기 get, post
    * get: r= requests.get(url, params=payload, headers=headers)
    * post: r = requests.post(url, data={key:value})
* 6. 만들어진 url 확인: print(r.url)
* 7. 응답코드확인: print(r.status_code)
* 8. 응답 요소 출력: r.text, r.content, r.json()

In [1]:
# !pip install requests
# !conda install requests

In [2]:
import requests
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 09 Dec 2025 14:49:25 +0900',
 'total': 489924,
 'start': 1,
 'display': 100,
 'items': [{'title': '아이마켓코리아 &amp; 코리아센터 2026년 이커머스 주가 분석... ',
   'link': 'https://blog.naver.com/kimengg/224103515517',
   'description': '또한, NAVER(+2.1%)가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 기대감으로 상승했던 사례처럼, 이커머스 플랫폼과 <b>핀테크</b>의 융합은 코리아센터에게도 새로운 성장 동력이 될 수 있습니다. 외국인... ',
   'bloggername': '하이디',
   'bloggerlink': 'blog.naver.com/kimengg',
   'postdate': '20251209'},
  {'title': '화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항',
   'link': 'https://dramapd.tistory.com/1085',
   'description': '주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을 펼치고 있으며, <b>핀테크</b> 기업들은 AI 기반의 맞춤형 채무 컨설팅 서비스를 제공하며 시장 경쟁에 참여하고 있습니다.... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '재테크 앱으로 하루 10분, 월 5만 원 가능할까? 캐시워크부터... ',
   'link': 'https://blog.naver.com/econonow/224103566880',
   'description': '무엇보다 국내 대표 <b>핀테크</b> 앱이라는 점에서 신뢰도도 높아 안심하고 사용할 수 있습니다. 광고 시청이나 간단한 미션 완료로 포인트를 주는 리워드앱도 인기인데요, 대표적으로는 오베이(설문조사), 캐시닥... ',
   'bloggername': '머니픽',
   'bloggerlink': 'blog.naver.com/econonow',
   'postdate': '20251209'},
  {'title': '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
   'link': 'https://ilovefamily.tistory.com/524',
   'description': '특히, <b>핀테크</b> 기술의 발전은 은행 방문 없이, 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는... 그리고 <b>핀테크</b> 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다. 특히, 고금리... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': '티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 +++',
   'link': 'https://blog.naver.com/seveneswsh/224103561542',
   'description': '살린 <b>핀테크</b> 서비스를 기본 모델로 하여, 고객이 직접 이율, 기간, 금액 등을 원하는 대로 설정하여... 소셜 <b>핀테크</b> 스타트업 입니다.우리는 사용자 간의 신용을 기반으로 한 소셜 네트워크(Social Network)를... ',
   'bloggername': '장외주식 알고해야 성투한다~!!',
   'bloggerlink': 'blog.naver.com/seveneswsh',
   'postdate': '20251209'},
  {'title': '우리카드 올인원대출 금리와 재대출 조건 총정리',
   'link': 'https://bluebeat.tistory.com/1126',
   'description': '📊 우리카드 올인원대출: 금리 &amp; 재대출 조건, <b>핀테크</b> 전문가의 심층 분석 급변하는 금융 시장 속에서... 향후 1-2년 동안은 고금리 기조가 유지될 가능성이 높으며, <b>핀테크</b> 기업들의 혁신적인 대출 상품 출시... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 사칭 인스x 코인플랫폼 조심해야... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103107061',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '다올저축은행 비상금대출 소득증빙 가능자 필수 확인사항',
   'link': 'https://bluebeat.tistory.com/1166',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 금리 인상은 대출 수요 감소로 이어졌으며, 소득 증빙 조건 강화는 대출 문턱을 높였습니다. <b>핀테크</b> 기업들은 혁신적인 기술과... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '캐노피, 대교그룹 고객사 유치…대기업 레퍼런스 확대',
   'link': 'https://blog.naver.com/hellocanopy/224103543493',
   'description': 'HR &amp; <b>핀테크</b> 업계에서 주목받는 흐름입니다. 근로자 복지 &amp; 만족도 증가 일한 즉시 정산이 가능해... 있는 <b>핀테크</b> 기반 금융 인프라로서 성장하고자 합니다. 또한, 국내에서의 사업 안정화 이후 해외, 특히... ',
   'bloggername': 'Canopy',
   'bloggerlink': 'blog.naver.com/hellocanopy',
   'postdate': '20251209'},
  {'title': '케이뱅크 신용대출 비대면 신청방법과 후기',
   'link': 'https://sibauchi.tistory.com/1143',
   'description': '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 더욱 깐깐하게 진행하고 있으며, <b>핀테크</b>... <b>핀테크</b> 기업들은 AI 기반 신용평가 모델을 고도화하여 리스크 관리 능력을 강화하고, 맞춤형 대출 상품을... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '제주 탐나는전 학생증 체크카드 소득공제, 대학생에게 얼마나... ',
   'link': 'https://blog.naver.com/moneycultreview/224103310590',
   'description': '✔✔️ 지갑을 가볍게 하고 싶은 학생 ✔✔️ 지역화폐 혜택을 받고 싶은 학생 ✔✔️ 제주 지역 소상공인을 응원하고 싶은 학생 ✔✔️ 알뜰하게 생활비를 아끼고 싶은 학생 ✔✔️ 최신 <b>핀테크</b> 서비스를... ',
   'bloggername': '머니컬 리뷰',
   'bloggerlink': 'blog.naver.com/moneycultreview',
   'postdate': '20251209'},
  {'title': '하나은행 징검다리론 한도와 금리 신청조건 총정리',
   'link': 'https://sibauchi.tistory.com/1130',
   'description': '또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로... 또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로 발전할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '태강대부 대출 절차와 이용 시 유의사항 총정리',
   'link': 'https://bluebeat.tistory.com/1123',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 고금리 시대에... 감소, <b>핀테크</b> 플랫폼을 통한 비대면 대출 증가 향후 1-2년 예상 트렌드: 금리 안정화 또는 소폭 하락 가능성... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 사칭 김민우프로 주식리딩방... ',
   'link': 'https://blog.naver.com/dgzuxzgby/224103130537',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/dgzuxzgby',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 김민우프로 사칭 리딩방 주의해야... ',
   'link': 'https://blog.naver.com/weirdo36529/224103453600',
   'description': '이유 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/weirdo36529',
   'postdate': '20251209'},
  {'title': '코인베이스의 인도 시장 재진입',
   'link': 'https://blog.naver.com/investor76/224103524083',
   'description': '사용이 빠르게 증가하고 있어 암호화폐 채택률이 매우 높을 잠재력을 가지고 있다 대규모 투자 유치 : 벤처 캐피털과 사모 펀드 자금은 인도의 <b>핀테크</b> 및 블록체인 스타트업에 지속적으로 투자하고 있다.',
   'bloggername': '시장 앞에 겸손',
   'bloggerlink': 'blog.naver.com/investor76',
   'postdate': '20251209'},
  {'title': 'KB국민카드 면접, 최종 합격하는 면접관 1:1 맞춤형 컨설팅',
   'link': 'https://blog.naver.com/05g8wbolei/224103520654',
   'description': "KB국민카드는 <b>핀테크</b>, 플랫폼 비즈니스 등 변화의 최전선에 있는 기업입니다. 과거의 은행 면접 준비하듯 '성실함'만 강조해서는 절대 합격할 수 없습니다. 오늘 이 글에서는 왜 죽어라 준비한 답변이... ",
   'bloggername': '⭐꿀팁정보⭐',
   'bloggerlink': 'blog.naver.com/05g8wbolei',
   'postdate': '20251209'},
  {'title': '싱가포르상표, 국제상표 병행이 답인 이유 4가지',
   'link': 'https://blog.naver.com/fastdesign/224103519162',
   'description': '또한 싱가포르상표는 브랜드 전략 중심의 기업(IT·헬스케어·F&amp;B·<b>핀테크</b>)이 많이 선택하기 때문에 국제상표와 자연스럽게 연결되는 시장 구조를 가지고 있습니다. 기율특허법인이 싱가포르상표 전략에 강한... ',
   'bloggername': '특허전략 파트너 기율',
   'bloggerlink': 'blog.naver.com/fastdesign',
   'postdate': '20251209'},
  {'title': 'BM특허권, 단순한 영업방법은 절대 등록받을 수 없습니다',
   'link': 'https://blog.naver.com/tm_maker/224082560561',
   'description': '즉, 온라인 플랫폼, 앱 서비스, <b>핀테크</b> 솔루션 등이 대표적인 BM특허의 형태입니다. 성공적인 권리 확보를 위한 전체 비용은 일반적으로 전문가 수수료와 관납료를 포함하여 출원 시 180~200만 원, 등록 시 180~200만... ',
   'bloggername': '마스터 상표',
   'bloggerlink': 'blog.naver.com/tm_maker',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 인스타그램 접근 코인사칭 플랫폼 출금... ',
   'link': 'https://blog.naver.com/nntto12976/224102883521',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/nntto12976',
   'postdate': '20251209'},
  {'title': '해외송금 수수료 걱정 끝 건당수수료의 장점',
   'link': 'https://blog.naver.com/e9payday/224101631252',
   'description': '최근 몇 년간 은행·<b>핀테크</b> 업체들이 이체 수수료를 대폭 낮추면서 국내 송금은 생활 속 기본... 하지만 최근에는 비용 구조를 단순화한 <b>핀테크</b> 기반 해외송금 서비스가 등장하며 상황이 크게 달라졌습니다.... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9payday',
   'postdate': '20251209'},
  {'title': '가짜 3.3 계약 &quot;피해 근로자&quot;를 위한 대응 절차 A to Z',
   'link': 'https://blog.naver.com/nomu4rang/224102260423',
   'description': '7~11) - 서울시 <b>핀테크</b>랩 인사노무 멘토 (2021.1~ ) - 산업인력공단 현장학습근로자 실태조사 점검위원 (미용업, 제조업) (2021.1~ ) - 한국장애인개발원 외부 노무전문위원 (2021.10~ ) - 코레일네트웍스 채용심사위원... ',
   'bloggername': '노동법률 전문가 박놈사',
   'bloggerlink': 'blog.naver.com/nomu4rang',
   'postdate': '20251209'},
  {'title': '해외송금 10만달러까지 증빙없이 초간편 시대',
   'link': 'https://blog.naver.com/money-study-/224103512826',
   'description': '은행을 이용하면 연간 10만 달러까지 가능했지만, 증권사나 <b>핀테크</b> 업체 같은 비은행권을 이용할 경우... #해외송금 #무증빙송금 #금융규제 #외환거래 #<b>핀테크</b> #AI반도체 #SK하이닉스 #삼성전자 #네이버 #카카오',
   'bloggername': '생활경제 톡톡',
   'bloggerlink': 'blog.naver.com/money-study-',
   'postdate': '20251209'},
  {'title': '무직자 소액대출 승인 잘되는 비대면 상품 정리',
   'link': 'https://bluebeat.tistory.com/1165',
   'description': '여러 <b>핀테크</b> 기업들이 시장에 진입하면서 경쟁은 더욱 치열해졌습니다. 정부는 가계 부채 증가를... 대부업체, <b>핀테크</b> 플랫폼 등으로 구분됩니다. 각 기관마다 대출 조건, 금리, 심사 기준 등이 다르므로, 꼼꼼히... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '중국이 미국을 제치고 AI 1인자가 될 수 있을까? 중국의 AI... ',
   'link': 'https://blog.naver.com/eunji_1104/224103506268',
   'description': '범위 <b>핀테크</b>, 클라우드, 전자상거래, IT 하드웨어 등 전반적인 홍콩 상장 빅테크 시가총액 상위 10개 종목에 집중 종목 비중 특정 종목의 비중을 10% 이내로 제한 (분산 효과) 상위 10개 종목에 균등하게... ',
   'bloggername': 'As within, So without',
   'bloggerlink': 'blog.naver.com/eunji_1104',
   'postdate': '20251209'},
  {'title': '&quot;국민연금이 빚낸다?&quot; 정부가 고환율 해결 위해 내놓은 방안',
   'link': 'https://blog.naver.com/pandainvest/224103501079',
   'description': '해외송금 <b>핀테크</b> 업체 : 건당 5000달러 / 연 5만 달러 문제는 각 업체별로 한도가 따로 적용된다는 점입니다. 여러 업체를 돌면 100만 달러 이상도 증빙 없이 해외 송금 가능했던 구조인데, 이는 은행·<b>핀테크</b> 간... ',
   'bloggername': '판다엄마 재테크기록',
   'bloggerlink': 'blog.naver.com/pandainvest',
   'postdate': '20251209'},
  {'title': '토스뱅크 아기펭귄 이거하면 5천원 준다는데 진짜?',
   'link': 'https://blog.naver.com/soo2402/224103496754',
   'description': '다른 <b>핀테크</b> 경쟁사들과 차별화되는 토스뱅크만의 강점으로 작용하고 있는 거죠. 게다가 5천원이라는 보상 자체도 부담스럽지 않으면서도, 사람들의 참여를 유도하기에 충분한 매력적인 금액이고요. 하지만... ',
   'bloggername': 'soo....',
   'bloggerlink': 'blog.naver.com/soo2402',
   'postdate': '20251209'},
  {'title': '예가람저축은행 예스론 추가대출 승인 잘되는 방법',
   'link': 'https://sibauchi.tistory.com/1176',
   'description': '<b>핀테크</b> 기업과의 경쟁 심화, 디지털 금융 서비스 확산 등도 주요 트렌드로 자리 잡을 것입니다. 예스론은 이러한 변화에 발맞춰 리스크 관리 강화, 디지털 채널 확대, 맞춤형 상품 개발 등에 집중해야 할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '2금융권 토지담보대출 상품별 금리와 신청조건 비교',
   'link': 'https://bluebeat.tistory.com/1162',
   'description': '<b>핀테크</b> 기업과의 협력을 통해 비대면 대출 프로세스를 강화하고, 고객 편의성을 높이는 전략도... 향후 2금융권 토지담보대출 시장은 <b>핀테크</b> 기술과의 융합을 통해 더욱 발전할 것으로 예상됩니다. 빅데이터... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '럭시라이프 사기 만남어플 접근 교묘한 감정 유도형 수법 분석... ',
   'link': 'https://blog.naver.com/friry96847/224103348630',
   'description': "(사칭) '#팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ",
   'bloggername': 'friry96847님의 블로그',
   'bloggerlink': 'blog.naver.com/friry96847',
   'postdate': '20251209'},
  {'title': '올원 뱅크 이체 한도 상향 신청 및 하루 송금한도 조정 방법',
   'link': 'https://sibauchi.tistory.com/1189',
   'description': '비대면 금융 서비스 이용 증가, <b>핀테크</b> 기업의 혁신적인 서비스 출시, 그리고 전통 금융기관의 디지털 전환 가속화가 주요 동인이었습니다. 특히, 모바일 뱅킹 앱의 역할이 더욱 중요해지면서 사용자 경험(UX)... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '원화 스테이블코인 인터넷뱅킹 카뱅 토뱅 케뱅 특허 선점... ',
   'link': 'https://blog.naver.com/true_insight/224103423673',
   'description': '✔ 국내 <b>핀테크</b> 성장 전략 결제·송금·자산관리 등 서비스 중심의 인터넷은행이 경쟁력을 가질 수 있습니다. ✔ 금융시장 혁신 필요 CBDC의 공공 중심 구조보다, 민간 중심 구조가 시장 속도에 적합하다는... ',
   'bloggername': '조금씩 풀어보는 서랍 속 지식꾸러미',
   'bloggerlink': 'blog.naver.com/true_insight',
   'postdate': '20251209'},
  {'title': '15억 달러 규모의 촉매제가 방금 SoFi 주식을 뒤흔들었습니다.... ',
   'link': 'https://blog.naver.com/banryeojasan/224103485795',
   'description': '<b>핀테크</b> 주식은 빠른 성장, 수익성 있는 단위 경제성, 확장적인 상품군을 결합할 수 있는 기업에... SOFI 주식 소개 2011년에 설립된 SoFi는 원스톱 모바일 뱅킹 앱을 기반으로 한 <b>핀테크</b> 회사입니다. 약 1,260만... ',
   'bloggername': '반려자산키우기',
   'bloggerlink': 'blog.naver.com/banryeojasan',
   'postdate': '20251209'},
  {'title': '박민수 핑거 부회장 “디지털자산 혁명 속 활로 찾는 나침반... ',
   'link': 'https://blog.naver.com/c9book/224103486052',
   'description': "대한민국 <b>핀테크</b> 산업을 이끄는 리더! 박민수 핑거 부회장님의 따끈따끈한 인터뷰 소식을 전해드립니다. 혼란스러운 디지털 자산 시장, 투기가 아닌 '방향'을 묻다 12월 8일, 전자신문은 인터뷰 기사를 통해... ",
   'bloggername': '클라우드나인 출판사',
   'bloggerlink': 'blog.naver.com/c9book',
   'postdate': '20251209'},
  {'title': '스타저축은행 하이론 재대출 조건과 승인 후기 확인하기',
   'link': 'https://lefthusband.tistory.com/1525',
   'description': '향후 1-2년 동안 하이론 시장은 금리 인상 추세 둔화, 정부의 가계 부채 관리 강화, <b>핀테크</b> 기술 발전... <b>핀테크</b> 기술 발전은 온라인 대출 플랫폼 활성화, 신용 평가 모델 고도화 등을 통해 하이론 시장의 효율성을... ',
   'bloggername': 'fgwaff',
   'bloggerlink': 'https://lefthusband.tistory.com/',
   'postdate': '20251209'},
  {'title': 'AI 기술 특허등록, 알고리즘도 지식재산으로 보호해야',
   'link': 'https://blog.naver.com/hongbin1814/224103482558',
   'description': '특히 SaaS·<b>핀테크</b>·이커머스 기업들은 AI가 경쟁력의 핵심이라 AI 기술 특허등록을 먼저 확보하는 전략을 사용하고 있습니다. 최근에는 네이버, 카카오, 구글, 메타뿐만 아니라 중소기업과 스타트업도 AI 기술을... ',
   'bloggername': '[유레카 지식재산보호소]',
   'bloggerlink': 'blog.naver.com/hongbin1814',
   'postdate': '20251209'},
  {'title': '피플펀드 대환대출 신청절차와 조건 알아보기',
   'link': 'https://think-tank.tistory.com/887',
   'description': '하지만, 정부의 정책 지원과 <b>핀테크</b> 기업들의 혁신적인 서비스 출시를 통해 새로운 기회가 창출될 수도 있습니다. 주요 기업들은 금리 경쟁력을 확보하기 위해 노력하는 한편, 빅데이터 분석을 통해 개인별... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '유안타증권 사기 사칭 주식리딩방 유형 실제처럼 보이지만 속은... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103104776',
   'description': '전혀다르다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '주식회사 트립퍼 사기 사칭 믿음을 악용한 허위 예약 결제... ',
   'link': 'https://blog.naver.com/ickkoju2/224103143300',
   'description': '실체 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/ickkoju2',
   'postdate': '20251209'},
  {'title': '쿠팡 회원탈퇴 방법 개선, PC 아닌 앱에서도 탈퇴 가능',
   'link': 'https://blog.naver.com/dndus01/224103474912',
   'description': '최근에는 토스, 네이버페이, 카카오페이, 삼성페이 등 <b>핀테크</b> 앱에서 클릭하면 2원, 3원 수익금 주는 배너 탓에 하루에도 여러 번씩 들락달락 거리기까지도 한다.  개선 전 쿠팡 회원 탈퇴 과정 절차 그리고... ',
   'bloggername': '램프천사의 별별여행',
   'bloggerlink': 'blog.naver.com/dndus01',
   'postdate': '20251209'},
  {'title': '용인시 처인구 남사읍 개인회생 채무조정 인가율 높은 이유',
   'link': 'https://dramapd.tistory.com/1096',
   'description': '강화 <b>핀테크</b> 기업: 데이터 기반 맞춤형 채무조정 컨설팅 서비스 개발 소규모 법률사무소: 지역 밀착형 서비스 제공 및 가격 경쟁력 강화 소비자 행동 변화: 온라인 정보 검색 및 비교 분석 활발 무료 상담 및 견적... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '해외취업 시 알아두면 좋은 저렴한 해외 송금',
   'link': 'https://blog.naver.com/wirebarley_official/224103472498',
   'description': '이런 상황에서 은행 대신 한국에서 해외로, 해외에서 한국으로 해외 송금을 할 수 있는 <b>핀테크</b> 어플을 소개해드릴게요. 와이어바알리 소개 와이어바알리는 글로벌 <b>핀테크</b> 해외송금 기업으로 한국, 미국, 캐나다... ',
   'bloggername': 'WireBarley, 글로벌 해외송금',
   'bloggerlink': 'blog.naver.com/wirebarley_official',
   'postdate': '20251209'},
  {'title': '&quot;비트코인과 CFTC 파일럿 프로그램: 디지털 자산 담보의... ',
   'link': 'https://blog.naver.com/star_handful/224103472014',
   'description': '파일럿 프로그램의 시장 반응 CFTC의 이번 발표는 암호화폐 및 <b>핀테크</b> 업계에서 긍정적인 반응을 얻고 있습니다. 코인베이스의 법률 책임자 폴 그레왈(Paul Grewal)은 이번 조치가 스테이블코인과 디지털... ',
   'bloggername': '진진돌이 파이넨스',
   'bloggerlink': 'blog.naver.com/star_handful',
   'postdate': '20251209'},
  {'title': '[에이플러스에셋] 알아보기',
   'link': 'https://blog.naver.com/star_of_self/224103471437',
   'description': '경쟁사인 인카금융서비스가 <b>핀테크</b> 플랫폼과의 제휴 등을 통해 디지털 접점을 넓히려는 시도를... 이러한 풍부한 현금 보유고는 향후 유망한 <b>핀테크</b> 기업 인수나 주주 환원(배당) 확대를 위한 재원으로... ',
   'bloggername': 'star_of_self님의 블로그',
   'bloggerlink': 'blog.naver.com/star_of_self',
   'postdate': '20251209'},
  {'title': '간추린 금융경제 뉴스제목모음 ⌚1209화13h',
   'link': 'https://blog.naver.com/misokir/224103465030',
   'description': '⏰ 1000원부터 1만원까지…롯데손보, 스키보험 ‘시즌권’ 플랜 신설 ⏰ 11兆 팔린 방카슈랑스, 내년 더 기대된다 ⏰ 1·2세대 실손보험, 받은 보험금 빼고 되팔 수 있다 ⏰ 1470원 환율에 국민연금 움직인다... ',
   'bloggername': '미키르의 분석',
   'bloggerlink': 'blog.naver.com/misokir',
   'postdate': '20251209'},
  {'title': '오늘의핫뉴스3. 불당시티와 함께 알아볼까요 유사품주의하세요... ',
   'link': 'https://blog.naver.com/kmj041217/224103464040',
   'description': '외환 제도 개편으로 증권사·카드사·<b>핀테크</b> 등을 통한 무증빙 해외 송금 한도가 연 10만 달러(약 1억 3천만 원)까지 확대되는 등 외환 관리 효율화 및 국민 편의가 제고됩니다. 3. 건설업 부진 장기화 및 소비... ',
   'bloggername': '불당시티부동산 천안시 불당동 부동산전문가',
   'bloggerlink': 'blog.naver.com/kmj041217',
   'postdate': '20251209'},
  {'title': '예가람저축은행 논스톱 대출, 24시간 즉시 입금 가능한 상품 정리',
   'link': 'https://ilovefamily.tistory.com/565',
   'description': '특히, <b>핀테크</b> 기업들의 활약으로 인해 비대면 대출 시장이 급성장했으며, 소비자들은 더욱 빠르고 편리한 대출 서비스를 요구하고 있습니다. 향후 1-2년 동안 금리 변동성이 지속될 것으로 예상되며, 개인 신용... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': 'IBM이 Confluent를 사려는 이유 3가지 (AI·데이터 스트림... ',
   'link': 'https://blog.naver.com/aaajung_/224103460914',
   'description': '2) Apache Kafka 기반 우버, 메타, <b>핀테크</b> 기업들이 다 쓰는 실시간 데이터 기술의 핵심이 바로... (AI, <b>핀테크</b>, 우버, 넷플릭스, 메타 등에서 모두 사용) ✔️왜 IBM이 Confluent를 사고 싶어하는가? AI... ',
   'bloggername': '성장기록',
   'bloggerlink': 'blog.naver.com/aaajung_',
   'postdate': '20251209'},
  {'title': '국민은행 KB국민ONE대출 자격조건과 금리 총정리',
   'link': 'https://think-tank.tistory.com/869',
   'description': '<b>핀테크</b> 기업들의 금융 시장 진출 확대는 경쟁 심화를 가져오겠지만, 동시에 새로운 대출 상품 및 서비스 개발을 촉진할 것입니다. 주요 은행들은 디지털 전환 가속화, 맞춤형 상품 개발, 그리고 리스크 관리... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '소셜버즈리포트 251209-“오늘 미국 커뮤니티, 결국 CETX에... ',
   'link': 'https://blog.naver.com/make_second_salary/224103458906',
   'description': 'TGL 1대20 리버스 스플릿 이후, 2026년 매출 가이던스를 세 배로 올리면서 “<b>핀테크</b>·디지털자산 성장 스토리 + 가격 튕김” 조합으로 커뮤니티의 레이더에 들어온 상황. DFLI·CISO·SLS 테마는... ',
   'bloggername': '재테크요원의 Second Salary HQ',
   'bloggerlink': 'blog.naver.com/make_second_salary',
   'postdate': '20251209'},
  {'title': '고양 파주 신용불량자 개인회생 카드단말기, 매출 묶일 걱정... ',
   'link': 'https://blog.naver.com/hanbitict/224103457625',
   'description': '&quot;어떻게 카드 결제 대금을 바로 주나요?&quot; &quot;이거 불법 아닌가요?&quot; 결론부터 말씀드리면, 100% 합법적인 <b>핀테크</b> 기술입니다. 저희 한빛정보통신이 제공하는 코페이 서비스는 PG사(전자결제대행사)가 자금력을... ',
   'bloggername': '한빛정보통신 코페이의 블로그',
   'bloggerlink': 'blog.naver.com/hanbitict',
   'postdate': '20251209'},
  {'title': '금융결제원 면접, 평가자 1:1 맞춤형 컨설팅 합격 전략 공개',
   'link': 'https://blog.naver.com/shit75/224103445933',
   'description': "최신 <b>핀테크</b> 기술, 블록체인 역량, 창의적인 아이디어... 물론 좋습니다. 하지만 금융결제원은 대한민국의 금융 공동망을 책임지는 핵심 인프라 기관입니다. 이곳에서 가장 중요한 가치는 '혁신' 이전에 '안정'과... ",
   'bloggername': '⭐혁신적인 핵심정보⭐',
   'bloggerlink': 'blog.naver.com/shit75',
   'postdate': '20251209'},
  {'title': "14억 인구 기반! 인도가 향후 20~30년간 '지속 성장'할 수... ",
   'link': 'https://blog.naver.com/plan_pan/224102934877',
   'description': '있어요 <b>핀테크</b> 기업도 잇달아 등장 중 한국 중국은 이미 둔화됐지만 인도는 이제 시작 이건 신흥국이 선진국으로 가고 있다는 증거예요 투자자들이 본 인도의 매력과 우리가 갈 길 개인 투자자도 쉽게 참여... ',
   'bloggername': '경제적인 고래',
   'bloggerlink': 'blog.naver.com/plan_pan',
   'postdate': '20251209'},
  {'title': '금산분리 완화 기대 예상 수혜주',
   'link': 'https://blog.naver.com/billionairementor/224103443976',
   'description': '과거에는 은행의 생활 서비스 진출이나 <b>핀테크</b> 기업의 금융업 영위 문제가 주된 쟁점이었으나, 최근 논의의 초점은 AI, 반도체 등 첨단전략산업의 경쟁력 확보를 위한 자본 조달 채널 확보로 옮겨가고... ',
   'bloggername': 'Invest And Grow Rich',
   'bloggerlink': 'blog.naver.com/billionairementor',
   'postdate': '20251209'},
  {'title': '페이팔 주식 전망: <b>핀테크</b> 대장주의 미래와 투자 전략',

In [3]:
print(type(response))

<class 'dict'>

In [4]:
response['items']

[{'title': '아이마켓코리아 &amp; 코리아센터 2026년 이커머스 주가 분석... ',
  'link': 'https://blog.naver.com/kimengg/224103515517',
  'description': '또한, NAVER(+2.1%)가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 기대감으로 상승했던 사례처럼, 이커머스 플랫폼과 <b>핀테크</b>의 융합은 코리아센터에게도 새로운 성장 동력이 될 수 있습니다. 외국인... ',
  'bloggername': '하이디',
  'bloggerlink': 'blog.naver.com/kimengg',
  'postdate': '20251209'},
 {'title': '화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항',
  'link': 'https://dramapd.tistory.com/1085',
  'description': '주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을 펼치고 있으며, <b>핀테크</b> 기업들은 AI 기반의 맞춤형 채무 컨설팅 서비스를 제공하며 시장 경쟁에 참여하고 있습니다.... ',
  'bloggername': '니은과 리을',
  'bloggerlink': 'https://dramapd.tistory.com/',
  'postdate': '20251209'},
 {'title': '재테크 앱으로 하루 10분, 월 5만 원 가능할까? 캐시워크부터... ',
  'link': 'https://blog.naver.com/econonow/224103566880',
  'description': '무엇보다 국내 대표 <b>핀테크</b> 앱이라는 점에서 신뢰도도 높아 안심하고 사용할 수 있습니다. 광고 시청이나 간단한 미션 완료로 포인트를 주는 리워드앱도 인기인데요, 대표적으로는 오베이(설문조사), 캐시닥... ',
  'bloggername': '머니픽',
  'bloggerlink': 'blog.naver.com/econonow',
  'postdate': '20251209'},
 {'title': '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
  'link': 'https://ilovefamily.tistory.com/524',
  'description': '특히, <b>핀테크</b> 기술의 발전은 은행 방문 없이, 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는... 그리고 <b>핀테크</b> 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다. 특히, 고금리... ',
  'bloggername': '과거,현재,미래, 그리고 나.',
  'bloggerlink': 'https://ilovefamily.tistory.com/',
  'postdate': '20251209'},
 {'title': '티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 +++',
  'link': 'https://blog.naver.com/seveneswsh/224103561542',
  'description': '살린 <b>핀테크</b> 서비스를 기본 모델로 하여, 고객이 직접 이율, 기간, 금액 등을 원하는 대로 설정하여... 소셜 <b>핀테크</b> 스타트업 입니다.우리는 사용자 간의 신용을 기반으로 한 소셜 네트워크(Social Network)를... ',
  'bloggername': '장외주식 알고해야 성투한다~!!',
  'bloggerlink': 'blog.naver.com/seveneswsh',
  'postdate': '20251209'},
 {'title': '우리카드 올인원대출 금리와 재대출 조건 총정리',
  'link': 'https://bluebeat.tistory.com/1126',
  'description': '📊 우리카드 올인원대출: 금리 &amp; 재대출 조건, <b>핀테크</b> 전문가의 심층 분석 급변하는 금융 시장 속에서... 향후 1-2년 동안은 고금리 기조가 유지될 가능성이 높으며, <b>핀테크</b> 기업들의 혁신적인 대출 상품 출시... ',
  'bloggername': 'bluebeat',
  'bloggerlink': 'https://bluebeat.tistory.com/',
  'postdate': '20251209'},
 {'title': 'worldswap-beams 사기 사칭 인스x 코인플랫폼 조심해야... ',
  'link': 'https://blog.naver.com/mgreatmaild18/224103107061',
  'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': 'daylaw',
  'bloggerlink': 'blog.naver.com/mgreatmaild18',
  'postdate': '20251209'},
 {'title': '다올저축은행 비상금대출 소득증빙 가능자 필수 확인사항',
  'link': 'https://bluebeat.tistory.com/1166',
  'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 금리 인상은 대출 수요 감소로 이어졌으며, 소득 증빙 조건 강화는 대출 문턱을 높였습니다. <b>핀테크</b> 기업들은 혁신적인 기술과... ',
  'bloggername': 'bluebeat',
  'bloggerlink': 'https://bluebeat.tistory.com/',
  'postdate': '20251209'},
 {'title': '캐노피, 대교그룹 고객사 유치…대기업 레퍼런스 확대',
  'link': 'https://blog.naver.com/hellocanopy/224103543493',
  'description': 'HR &amp; <b>핀테크</b> 업계에서 주목받는 흐름입니다. 근로자 복지 &amp; 만족도 증가 일한 즉시 정산이 가능해... 있는 <b>핀테크</b> 기반 금융 인프라로서 성장하고자 합니다. 또한, 국내에서의 사업 안정화 이후 해외, 특히... ',
  'bloggername': 'Canopy',
  'bloggerlink': 'blog.naver.com/hellocanopy',
  'postdate': '20251209'},
 {'title': '케이뱅크 신용대출 비대면 신청방법과 후기',
  'link': 'https://sibauchi.tistory.com/1143',
  'description': '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 더욱 깐깐하게 진행하고 있으며, <b>핀테크</b>... <b>핀테크</b> 기업들은 AI 기반 신용평가 모델을 고도화하여 리스크 관리 능력을 강화하고, 맞춤형 대출 상품을... ',
  'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  'bloggerlink': 'https://sibauchi.tistory.com/',
  'postdate': '20251209'},
 {'title': '제주 탐나는전 학생증 체크카드 소득공제, 대학생에게 얼마나... ',
  'link': 'https://blog.naver.com/moneycultreview/224103310590',
  'description': '✔✔️ 지갑을 가볍게 하고 싶은 학생 ✔✔️ 지역화폐 혜택을 받고 싶은 학생 ✔✔️ 제주 지역 소상공인을 응원하고 싶은 학생 ✔✔️ 알뜰하게 생활비를 아끼고 싶은 학생 ✔✔️ 최신 <b>핀테크</b> 서비스를... ',
  'bloggername': '머니컬 리뷰',
  'bloggerlink': 'blog.naver.com/moneycultreview',
  'postdate': '20251209'},
 {'title': '하나은행 징검다리론 한도와 금리 신청조건 총정리',
  'link': 'https://sibauchi.tistory.com/1130',
  'description': '또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로... 또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로 발전할... ',
  'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  'bloggerlink': 'https://sibauchi.tistory.com/',
  'postdate': '20251209'},
 {'title': '태강대부 대출 절차와 이용 시 유의사항 총정리',
  'link': 'https://bluebeat.tistory.com/1123',
  'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 고금리 시대에... 감소, <b>핀테크</b> 플랫폼을 통한 비대면 대출 증가 향후 1-2년 예상 트렌드: 금리 안정화 또는 소폭 하락 가능성... ',
  'bloggername': 'bluebeat',
  'bloggerlink': 'https://bluebeat.tistory.com/',
  'postdate': '20251209'},
 {'title': 'Lounge ONE 사기 라운지원 사칭 김민우프로 주식리딩방... ',
  'link': 'https://blog.naver.com/dgzuxzgby/224103130537',
  'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': '데이법률사무소',
  'bloggerlink': 'blog.naver.com/dgzuxzgby',
  'postdate': '20251209'},
 {'title': 'Lounge ONE 사기 라운지원 김민우프로 사칭 리딩방 주의해야... ',
  'link': 'https://blog.naver.com/weirdo36529/224103453600',
  'description': '이유 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
  'bloggerlink': 'blog.naver.com/weirdo36529',
  'postdate': '20251209'},
 {'title': '코인베이스의 인도 시장 재진입',
  'link': 'https://blog.naver.com/investor76/224103524083',
  'description': '사용이 빠르게 증가하고 있어 암호화폐 채택률이 매우 높을 잠재력을 가지고 있다 대규모 투자 유치 : 벤처 캐피털과 사모 펀드 자금은 인도의 <b>핀테크</b> 및 블록체인 스타트업에 지속적으로 투자하고 있다.',
  'bloggername': '시장 앞에 겸손',
  'bloggerlink': 'blog.naver.com/investor76',
  'postdate': '20251209'},
 {'title': 'KB국민카드 면접, 최종 합격하는 면접관 1:1 맞춤형 컨설팅',
  'link': 'https://blog.naver.com/05g8wbolei/224103520654',
  'description': "KB국민카드는 <b>핀테크</b>, 플랫폼 비즈니스 등 변화의 최전선에 있는 기업입니다. 과거의 은행 면접 준비하듯 '성실함'만 강조해서는 절대 합격할 수 없습니다. 오늘 이 글에서는 왜 죽어라 준비한 답변이... ",
  'bloggername': '⭐꿀팁정보⭐',
  'bloggerlink': 'blog.naver.com/05g8wbolei',
  'postdate': '20251209'},
 {'title': '싱가포르상표, 국제상표 병행이 답인 이유 4가지',
  'link': 'https://blog.naver.com/fastdesign/224103519162',
  'description': '또한 싱가포르상표는 브랜드 전략 중심의 기업(IT·헬스케어·F&amp;B·<b>핀테크</b>)이 많이 선택하기 때문에 국제상표와 자연스럽게 연결되는 시장 구조를 가지고 있습니다. 기율특허법인이 싱가포르상표 전략에 강한... ',
  'bloggername': '특허전략 파트너 기율',
  'bloggerlink': 'blog.naver.com/fastdesign',
  'postdate': '20251209'},
 {'title': 'BM특허권, 단순한 영업방법은 절대 등록받을 수 없습니다',
  'link': 'https://blog.naver.com/tm_maker/224082560561',
  'description': '즉, 온라인 플랫폼, 앱 서비스, <b>핀테크</b> 솔루션 등이 대표적인 BM특허의 형태입니다. 성공적인 권리 확보를 위한 전체 비용은 일반적으로 전문가 수수료와 관납료를 포함하여 출원 시 180~200만 원, 등록 시 180~200만... ',
  'bloggername': '마스터 상표',
  'bloggerlink': 'blog.naver.com/tm_maker',
  'postdate': '20251209'},
 {'title': 'worldswap-beams 사기 인스타그램 접근 코인사칭 플랫폼 출금... ',
  'link': 'https://blog.naver.com/nntto12976/224102883521',
  'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
  'bloggerlink': 'blog.naver.com/nntto12976',
  'postdate': '20251209'},
 {'title': '해외송금 수수료 걱정 끝 건당수수료의 장점',
  'link': 'https://blog.naver.com/e9payday/224101631252',
  'description': '최근 몇 년간 은행·<b>핀테크</b> 업체들이 이체 수수료를 대폭 낮추면서 국내 송금은 생활 속 기본... 하지만 최근에는 비용 구조를 단순화한 <b>핀테크</b> 기반 해외송금 서비스가 등장하며 상황이 크게 달라졌습니다.... ',
  'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
  'bloggerlink': 'blog.naver.com/e9payday',
  'postdate': '20251209'},
 {'title': '가짜 3.3 계약 &quot;피해 근로자&quot;를 위한 대응 절차 A to Z',
  'link': 'https://blog.naver.com/nomu4rang/224102260423',
  'description': '7~11) - 서울시 <b>핀테크</b>랩 인사노무 멘토 (2021.1~ ) - 산업인력공단 현장학습근로자 실태조사 점검위원 (미용업, 제조업) (2021.1~ ) - 한국장애인개발원 외부 노무전문위원 (2021.10~ ) - 코레일네트웍스 채용심사위원... ',
  'bloggername': '노동법률 전문가 박놈사',
  'bloggerlink': 'blog.naver.com/nomu4rang',
  'postdate': '20251209'},
 {'title': '해외송금 10만달러까지 증빙없이 초간편 시대',
  'link': 'https://blog.naver.com/money-study-/224103512826',
  'description': '은행을 이용하면 연간 10만 달러까지 가능했지만, 증권사나 <b>핀테크</b> 업체 같은 비은행권을 이용할 경우... #해외송금 #무증빙송금 #금융규제 #외환거래 #<b>핀테크</b> #AI반도체 #SK하이닉스 #삼성전자 #네이버 #카카오',
  'bloggername': '생활경제 톡톡',
  'bloggerlink': 'blog.naver.com/money-study-',
  'postdate': '20251209'},
 {'title': '무직자 소액대출 승인 잘되는 비대면 상품 정리',
  'link': 'https://bluebeat.tistory.com/1165',
  'description': '여러 <b>핀테크</b> 기업들이 시장에 진입하면서 경쟁은 더욱 치열해졌습니다. 정부는 가계 부채 증가를... 대부업체, <b>핀테크</b> 플랫폼 등으로 구분됩니다. 각 기관마다 대출 조건, 금리, 심사 기준 등이 다르므로, 꼼꼼히... ',
  'bloggername': 'bluebeat',
  'bloggerlink': 'https://bluebeat.tistory.com/',
  'postdate': '20251209'},
 {'title': '중국이 미국을 제치고 AI 1인자가 될 수 있을까? 중국의 AI... ',
  'link': 'https://blog.naver.com/eunji_1104/224103506268',
  'description': '범위 <b>핀테크</b>, 클라우드, 전자상거래, IT 하드웨어 등 전반적인 홍콩 상장 빅테크 시가총액 상위 10개 종목에 집중 종목 비중 특정 종목의 비중을 10% 이내로 제한 (분산 효과) 상위 10개 종목에 균등하게... ',
  'bloggername': 'As within, So without',
  'bloggerlink': 'blog.naver.com/eunji_1104',
  'postdate': '20251209'},
 {'title': '&quot;국민연금이 빚낸다?&quot; 정부가 고환율 해결 위해 내놓은 방안',
  'link': 'https://blog.naver.com/pandainvest/224103501079',
  'description': '해외송금 <b>핀테크</b> 업체 : 건당 5000달러 / 연 5만 달러 문제는 각 업체별로 한도가 따로 적용된다는 점입니다. 여러 업체를 돌면 100만 달러 이상도 증빙 없이 해외 송금 가능했던 구조인데, 이는 은행·<b>핀테크</b> 간... ',
  'bloggername': '판다엄마 재테크기록',
  'bloggerlink': 'blog.naver.com/pandainvest',
  'postdate': '20251209'},
 {'title': '토스뱅크 아기펭귄 이거하면 5천원 준다는데 진짜?',
  'link': 'https://blog.naver.com/soo2402/224103496754',
  'description': '다른 <b>핀테크</b> 경쟁사들과 차별화되는 토스뱅크만의 강점으로 작용하고 있는 거죠. 게다가 5천원이라는 보상 자체도 부담스럽지 않으면서도, 사람들의 참여를 유도하기에 충분한 매력적인 금액이고요. 하지만... ',
  'bloggername': 'soo....',
  'bloggerlink': 'blog.naver.com/soo2402',
  'postdate': '20251209'},
 {'title': '예가람저축은행 예스론 추가대출 승인 잘되는 방법',
  'link': 'https://sibauchi.tistory.com/1176',
  'description': '<b>핀테크</b> 기업과의 경쟁 심화, 디지털 금융 서비스 확산 등도 주요 트렌드로 자리 잡을 것입니다. 예스론은 이러한 변화에 발맞춰 리스크 관리 강화, 디지털 채널 확대, 맞춤형 상품 개발 등에 집중해야 할... ',
  'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  'bloggerlink': 'https://sibauchi.tistory.com/',
  'postdate': '20251209'},
 {'title': '2금융권 토지담보대출 상품별 금리와 신청조건 비교',
  'link': 'https://bluebeat.tistory.com/1162',
  'description': '<b>핀테크</b> 기업과의 협력을 통해 비대면 대출 프로세스를 강화하고, 고객 편의성을 높이는 전략도... 향후 2금융권 토지담보대출 시장은 <b>핀테크</b> 기술과의 융합을 통해 더욱 발전할 것으로 예상됩니다. 빅데이터... ',
  'bloggername': 'bluebeat',
  'bloggerlink': 'https://bluebeat.tistory.com/',
  'postdate': '20251209'},
 {'title': '럭시라이프 사기 만남어플 접근 교묘한 감정 유도형 수법 분석... ',
  'link': 'https://blog.naver.com/friry96847/224103348630',
  'description': "(사칭) '#팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ",
  'bloggername': 'friry96847님의 블로그',
  'bloggerlink': 'blog.naver.com/friry96847',
  'postdate': '20251209'},
 {'title': '올원 뱅크 이체 한도 상향 신청 및 하루 송금한도 조정 방법',
  'link': 'https://sibauchi.tistory.com/1189',
  'description': '비대면 금융 서비스 이용 증가, <b>핀테크</b> 기업의 혁신적인 서비스 출시, 그리고 전통 금융기관의 디지털 전환 가속화가 주요 동인이었습니다. 특히, 모바일 뱅킹 앱의 역할이 더욱 중요해지면서 사용자 경험(UX)... ',
  'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  'bloggerlink': 'https://sibauchi.tistory.com/',
  'postdate': '20251209'},
 {'title': '원화 스테이블코인 인터넷뱅킹 카뱅 토뱅 케뱅 특허 선점... ',
  'link': 'https://blog.naver.com/true_insight/224103423673',
  'description': '✔ 국내 <b>핀테크</b> 성장 전략 결제·송금·자산관리 등 서비스 중심의 인터넷은행이 경쟁력을 가질 수 있습니다. ✔ 금융시장 혁신 필요 CBDC의 공공 중심 구조보다, 민간 중심 구조가 시장 속도에 적합하다는... ',
  'bloggername': '조금씩 풀어보는 서랍 속 지식꾸러미',
  'bloggerlink': 'blog.naver.com/true_insight',
  'postdate': '20251209'},
 {'title': '15억 달러 규모의 촉매제가 방금 SoFi 주식을 뒤흔들었습니다.... ',
  'link': 'https://blog.naver.com/banryeojasan/224103485795',
  'description': '<b>핀테크</b> 주식은 빠른 성장, 수익성 있는 단위 경제성, 확장적인 상품군을 결합할 수 있는 기업에... SOFI 주식 소개 2011년에 설립된 SoFi는 원스톱 모바일 뱅킹 앱을 기반으로 한 <b>핀테크</b> 회사입니다. 약 1,260만... ',
  'bloggername': '반려자산키우기',
  'bloggerlink': 'blog.naver.com/banryeojasan',
  'postdate': '20251209'},
 {'title': '박민수 핑거 부회장 “디지털자산 혁명 속 활로 찾는 나침반... ',
  'link': 'https://blog.naver.com/c9book/224103486052',
  'description': "대한민국 <b>핀테크</b> 산업을 이끄는 리더! 박민수 핑거 부회장님의 따끈따끈한 인터뷰 소식을 전해드립니다. 혼란스러운 디지털 자산 시장, 투기가 아닌 '방향'을 묻다 12월 8일, 전자신문은 인터뷰 기사를 통해... ",
  'bloggername': '클라우드나인 출판사',
  'bloggerlink': 'blog.naver.com/c9book',
  'postdate': '20251209'},
 {'title': '스타저축은행 하이론 재대출 조건과 승인 후기 확인하기',
  'link': 'https://lefthusband.tistory.com/1525',
  'description': '향후 1-2년 동안 하이론 시장은 금리 인상 추세 둔화, 정부의 가계 부채 관리 강화, <b>핀테크</b> 기술 발전... <b>핀테크</b> 기술 발전은 온라인 대출 플랫폼 활성화, 신용 평가 모델 고도화 등을 통해 하이론 시장의 효율성을... ',
  'bloggername': 'fgwaff',
  'bloggerlink': 'https://lefthusband.tistory.com/',
  'postdate': '20251209'},
 {'title': 'AI 기술 특허등록, 알고리즘도 지식재산으로 보호해야',
  'link': 'https://blog.naver.com/hongbin1814/224103482558',
  'description': '특히 SaaS·<b>핀테크</b>·이커머스 기업들은 AI가 경쟁력의 핵심이라 AI 기술 특허등록을 먼저 확보하는 전략을 사용하고 있습니다. 최근에는 네이버, 카카오, 구글, 메타뿐만 아니라 중소기업과 스타트업도 AI 기술을... ',
  'bloggername': '[유레카 지식재산보호소]',
  'bloggerlink': 'blog.naver.com/hongbin1814',
  'postdate': '20251209'},
 {'title': '피플펀드 대환대출 신청절차와 조건 알아보기',
  'link': 'https://think-tank.tistory.com/887',
  'description': '하지만, 정부의 정책 지원과 <b>핀테크</b> 기업들의 혁신적인 서비스 출시를 통해 새로운 기회가 창출될 수도 있습니다. 주요 기업들은 금리 경쟁력을 확보하기 위해 노력하는 한편, 빅데이터 분석을 통해 개인별... ',
  'bloggername': 'think-tank.tistory.com',
  'bloggerlink': 'https://think-tank.tistory.com/',
  'postdate': '20251209'},
 {'title': '유안타증권 사기 사칭 주식리딩방 유형 실제처럼 보이지만 속은... ',
  'link': 'https://blog.naver.com/mgreatmaild18/224103104776',
  'description': '전혀다르다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': 'daylaw',
  'bloggerlink': 'blog.naver.com/mgreatmaild18',
  'postdate': '20251209'},
 {'title': '주식회사 트립퍼 사기 사칭 믿음을 악용한 허위 예약 결제... ',
  'link': 'https://blog.naver.com/ickkoju2/224103143300',
  'description': '실체 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
  'bloggername': '데이법률사무소',
  'bloggerlink': 'blog.naver.com/ickkoju2',
  'postdate': '20251209'},
 {'title': '쿠팡 회원탈퇴 방법 개선, PC 아닌 앱에서도 탈퇴 가능',
  'link': 'https://blog.naver.com/dndus01/224103474912',
  'description': '최근에는 토스, 네이버페이, 카카오페이, 삼성페이 등 <b>핀테크</b> 앱에서 클릭하면 2원, 3원 수익금 주는 배너 탓에 하루에도 여러 번씩 들락달락 거리기까지도 한다.  개선 전 쿠팡 회원 탈퇴 과정 절차 그리고... ',
  'bloggername': '램프천사의 별별여행',
  'bloggerlink': 'blog.naver.com/dndus01',
  'postdate': '20251209'},
 {'title': '용인시 처인구 남사읍 개인회생 채무조정 인가율 높은 이유',
  'link': 'https://dramapd.tistory.com/1096',
  'description': '강화 <b>핀테크</b> 기업: 데이터 기반 맞춤형 채무조정 컨설팅 서비스 개발 소규모 법률사무소: 지역 밀착형 서비스 제공 및 가격 경쟁력 강화 소비자 행동 변화: 온라인 정보 검색 및 비교 분석 활발 무료 상담 및 견적... ',
  'bloggername': '니은과 리을',
  'bloggerlink': 'https://dramapd.tistory.com/',
  'postdate': '20251209'},
 {'title': '해외취업 시 알아두면 좋은 저렴한 해외 송금',
  'link': 'https://blog.naver.com/wirebarley_official/224103472498',
  'description': '이런 상황에서 은행 대신 한국에서 해외로, 해외에서 한국으로 해외 송금을 할 수 있는 <b>핀테크</b> 어플을 소개해드릴게요. 와이어바알리 소개 와이어바알리는 글로벌 <b>핀테크</b> 해외송금 기업으로 한국, 미국, 캐나다... ',
  'bloggername': 'WireBarley, 글로벌 해외송금',
  'bloggerlink': 'blog.naver.com/wirebarley_official',
  'postdate': '20251209'},
 {'title': '&quot;비트코인과 CFTC 파일럿 프로그램: 디지털 자산 담보의... ',
  'link': 'https://blog.naver.com/star_handful/224103472014',
  'description': '파일럿 프로그램의 시장 반응 CFTC의 이번 발표는 암호화폐 및 <b>핀테크</b> 업계에서 긍정적인 반응을 얻고 있습니다. 코인베이스의 법률 책임자 폴 그레왈(Paul Grewal)은 이번 조치가 스테이블코인과 디지털... ',
  'bloggername': '진진돌이 파이넨스',
  'bloggerlink': 'blog.naver.com/star_handful',
  'postdate': '20251209'},
 {'title': '[에이플러스에셋] 알아보기',
  'link': 'https://blog.naver.com/star_of_self/224103471437',
  'description': '경쟁사인 인카금융서비스가 <b>핀테크</b> 플랫폼과의 제휴 등을 통해 디지털 접점을 넓히려는 시도를... 이러한 풍부한 현금 보유고는 향후 유망한 <b>핀테크</b> 기업 인수나 주주 환원(배당) 확대를 위한 재원으로... ',
  'bloggername': 'star_of_self님의 블로그',
  'bloggerlink': 'blog.naver.com/star_of_self',
  'postdate': '20251209'},
 {'title': '간추린 금융경제 뉴스제목모음 ⌚1209화13h',
  'link': 'https://blog.naver.com/misokir/224103465030',
  'description': '⏰ 1000원부터 1만원까지…롯데손보, 스키보험 ‘시즌권’ 플랜 신설 ⏰ 11兆 팔린 방카슈랑스, 내년 더 기대된다 ⏰ 1·2세대 실손보험, 받은 보험금 빼고 되팔 수 있다 ⏰ 1470원 환율에 국민연금 움직인다... ',
  'bloggername': '미키르의 분석',
  'bloggerlink': 'blog.naver.com/misokir',
  'postdate': '20251209'},
 {'title': '오늘의핫뉴스3. 불당시티와 함께 알아볼까요 유사품주의하세요... ',
  'link': 'https://blog.naver.com/kmj041217/224103464040',
  'description': '외환 제도 개편으로 증권사·카드사·<b>핀테크</b> 등을 통한 무증빙 해외 송금 한도가 연 10만 달러(약 1억 3천만 원)까지 확대되는 등 외환 관리 효율화 및 국민 편의가 제고됩니다. 3. 건설업 부진 장기화 및 소비... ',
  'bloggername': '불당시티부동산 천안시 불당동 부동산전문가',
  'bloggerlink': 'blog.naver.com/kmj041217',
  'postdate': '20251209'},
 {'title': '예가람저축은행 논스톱 대출, 24시간 즉시 입금 가능한 상품 정리',
  'link': 'https://ilovefamily.tistory.com/565',
  'description': '특히, <b>핀테크</b> 기업들의 활약으로 인해 비대면 대출 시장이 급성장했으며, 소비자들은 더욱 빠르고 편리한 대출 서비스를 요구하고 있습니다. 향후 1-2년 동안 금리 변동성이 지속될 것으로 예상되며, 개인 신용... ',
  'bloggername': '과거,현재,미래, 그리고 나.',
  'bloggerlink': 'https://ilovefamily.tistory.com/',
  'postdate': '20251209'},
 {'title': 'IBM이 Confluent를 사려는 이유 3가지 (AI·데이터 스트림... ',
  'link': 'https://blog.naver.com/aaajung_/224103460914',
  'description': '2) Apache Kafka 기반 우버, 메타, <b>핀테크</b> 기업들이 다 쓰는 실시간 데이터 기술의 핵심이 바로... (AI, <b>핀테크</b>, 우버, 넷플릭스, 메타 등에서 모두 사용) ✔️왜 IBM이 Confluent를 사고 싶어하는가? AI... ',
  'bloggername': '성장기록',
  'bloggerlink': 'blog.naver.com/aaajung_',
  'postdate': '20251209'},
 {'title': '국민은행 KB국민ONE대출 자격조건과 금리 총정리',
  'link': 'https://think-tank.tistory.com/869',
  'description': '<b>핀테크</b> 기업들의 금융 시장 진출 확대는 경쟁 심화를 가져오겠지만, 동시에 새로운 대출 상품 및 서비스 개발을 촉진할 것입니다. 주요 은행들은 디지털 전환 가속화, 맞춤형 상품 개발, 그리고 리스크 관리... ',
  'bloggername': 'think-tank.tistory.com',
  'bloggerlink': 'https://think-tank.tistory.com/',
  'postdate': '20251209'},
 {'title': '소셜버즈리포트 251209-“오늘 미국 커뮤니티, 결국 CETX에... ',
  'link': 'https://blog.naver.com/make_second_salary/224103458906',
  'description': 'TGL 1대20 리버스 스플릿 이후, 2026년 매출 가이던스를 세 배로 올리면서 “<b>핀테크</b>·디지털자산 성장 스토리 + 가격 튕김” 조합으로 커뮤니티의 레이더에 들어온 상황. DFLI·CISO·SLS 테마는... ',
  'bloggername': '재테크요원의 Second Salary HQ',
  'bloggerlink': 'blog.naver.com/make_second_salary',
  'postdate': '20251209'},
 {'title': '고양 파주 신용불량자 개인회생 카드단말기, 매출 묶일 걱정... ',
  'link': 'https://blog.naver.com/hanbitict/224103457625',
  'description': '&quot;어떻게 카드 결제 대금을 바로 주나요?&quot; &quot;이거 불법 아닌가요?&quot; 결론부터 말씀드리면, 100% 합법적인 <b>핀테크</b> 기술입니다. 저희 한빛정보통신이 제공하는 코페이 서비스는 PG사(전자결제대행사)가 자금력을... ',
  'bloggername': '한빛정보통신 코페이의 블로그',
  'bloggerlink': 'blog.naver.com/hanbitict',
  'postdate': '20251209'},
 {'title': '금융결제원 면접, 평가자 1:1 맞춤형 컨설팅 합격 전략 공개',
  'link': 'https://blog.naver.com/shit75/224103445933',
  'description': "최신 <b>핀테크</b> 기술, 블록체인 역량, 창의적인 아이디어... 물론 좋습니다. 하지만 금융결제원은 대한민국의 금융 공동망을 책임지는 핵심 인프라 기관입니다. 이곳에서 가장 중요한 가치는 '혁신' 이전에 '안정'과... ",
  'bloggername': '⭐혁신적인 핵심정보⭐',
  'bloggerlink': 'blog.naver.com/shit75',
  'postdate': '20251209'},
 {'title': "14억 인구 기반! 인도가 향후 20~30년간 '지속 성장'할 수... ",
  'link': 'https://blog.naver.com/plan_pan/224102934877',
  'description': '있어요 <b>핀테크</b> 기업도 잇달아 등장 중 한국 중국은 이미 둔화됐지만 인도는 이제 시작 이건 신흥국이 선진국으로 가고 있다는 증거예요 투자자들이 본 인도의 매력과 우리가 갈 길 개인 투자자도 쉽게 참여... ',
  'bloggername': '경제적인 고래',
  'bloggerlink': 'blog.naver.com/plan_pan',
  'postdate': '20251209'},
 {'title': '금산분리 완화 기대 예상 수혜주',
  'link': 'https://blog.naver.com/billionairementor/224103443976',
  'description': '과거에는 은행의 생활 서비스 진출이나 <b>핀테크</b> 기업의 금융업 영위 문제가 주된 쟁점이었으나, 최근 논의의 초점은 AI, 반도체 등 첨단전략산업의 경쟁력 확보를 위한 자본 조달 채널 확보로 옮겨가고... ',
  'bloggername': 'Invest And Grow Rich',
  'bloggerlink': 'blog.naver.com/billionairementor',
  'postdate': '20251209'},
 {'title': '페이팔 주식 전망: <b>핀테크</b> 대장주의 미래와 투자 전략',
  'link': 'https://blog.naver.com/linear_regression_/224103443872',
  'description': '페이팔은 디지털 결제 및 <b>핀테크</b> 서비스를 제공하는 글로벌 온라인 결제 플랫폼으로 잘 알려져... <b>핀테크</b> 시장에서의 현명한 투자 전략 변화무쌍한 <b>핀테크</b> 시장에서 현명한 투자 전략을 고민하는 것은... ',
  'bloggername': '코노고 KONOGO 비지니스 경제',
  'bloggerlink': 'blog.naver.com/linear_regression_',
  'postdate': '20251209'},
 {'title': '현대차 미소금융 지원프로그램과 대출신청 절차 정리',
  'link': 'https://lefthusband.tistory.com/1510',

In [5]:
import pandas as pd

In [6]:
pd.DataFrame(response['items'])

,title,link,description,bloggername,bloggerlink,postdate
0,아이마켓코리아 &amp; 코리아센터 2026년 이커머스 주가 분석...,https://blog.naver.com/kimengg/224103515517,"또한, NAVER(+2.1%)가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 ...",하이디,blog.naver.com/kimengg,20251209
1,화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항,https://dramapd.tistory.com/1085,주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을...,니은과 리을,https://dramapd.tistory.com/,20251209
2,"재테크 앱으로 하루 10분, 월 5만 원 가능할까? 캐시워크부터...",https://blog.naver.com/econonow/224103566880,무엇보다 국내 대표 <b>핀테크</b> 앱이라는 점에서 신뢰도도 높아 안심하고 사용...,머니픽,blog.naver.com/econonow,20251209
3,휴대폰 대출 간편 신청 방법과 신용 영향 분석,https://ilovefamily.tistory.com/524,"특히, <b>핀테크</b> 기술의 발전은 은행 방문 없이, 서류 제출 없이 스마트폰...","과거,현재,미래, 그리고 나.",https://ilovefamily.tistory.com/,20251209
4,티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 +++,https://blog.naver.com/seveneswsh/224103561542,"살린 <b>핀테크</b> 서비스를 기본 모델로 하여, 고객이 직접 이율, 기간, 금...",장외주식 알고해야 성투한다~!!,blog.naver.com/seveneswsh,20251209
...,...,...,...,...,...,...
95,카카오뱅크 비상금 대출 신청자격과 금리 인하 방법,https://ilovefamily.tistory.com/580,"주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 까다롭게 진행했고, <b>핀테...","과거,현재,미래, 그리고 나.",https://ilovefamily.tistory.com/,20251209
96,"대형 오피스 시장, 신도림·구로·광명, 지산왕",https://blog.naver.com/numerouno/224098242090,"1호선과 2호선의 더블 환승에 더해 GTX-B 노선 정차까지 확정되면서, 물리적 이...",지식산업센터가 대세다! [지산왕],blog.naver.com/numerouno,20251209
97,햇살론15 특례보증 신청자격과 준비서류 완벽정리,https://think-tank.tistory.com/919,"은행들은 리스크 관리에 더욱 집중하며 대출 심사를 강화하는 추세이며, <b>핀테크<...",think-tank.tistory.com,https://think-tank.tistory.com/,20251209
98,월드스왑 사기 사칭 암호화폐 차익거래 고수익을 미끼로한...,https://blog.naver.com/mgreatmaild18/224103100679,실체 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기...,daylaw,blog.naver.com/mgreatmaild18,20251209
99,농협카드 단기대출 급전 필요할 때 활용하는 방법,https://think-tank.tistory.com/893,<b>핀테크</b> 기업들의 공세적인 마케팅과 간편한 대출 절차는 기존 금융권에 긴...,think-tank.tistory.com,https://think-tank.tistory.com/,20251209

In [7]:
import re
def text_clean(text):
    # html 태그를 없애는 정규표현식
    result = re.sub(r"</?[^>]+>", "", text)
    # 한글, 영문, 숫자 외의 모든 문자 제거 후 공백으로 변환
    result = re.sub(r"[^가-힣a-zA-Z0-9]", " ", result)
    result = result.replace("  ", " ").replace("  ", " ").replace("  ", " ")
    return result

In [8]:
result = {}
for item in response['items']:
    for key, value in item.items():
        if key in ["title", "description"]:
            result.setdefault(key, []).append(text_clean(value))
        else:
            result.setdefault(key, []).append(value)
result

{'title': ['아이마켓코리아 amp 코리아센터 2026년 이커머스 주가 분석 ',
  '화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항',
  '재테크 앱으로 하루 10분 월 5만 원 가능할까 캐시워크부터 ',
  '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
  '티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 ',
  '우리카드 올인원대출 금리와 재대출 조건 총정리',
  'worldswap beams 사기 사칭 인스x 코인플랫폼 조심해야 ',
  '다올저축은행 비상금대출 소득증빙 가능자 필수 확인사항',
  '캐노피 대교그룹 고객사 유치 대기업 레퍼런스 확대',
  '케이뱅크 신용대출 비대면 신청방법과 후기',
  '제주 탐나는전 학생증 체크카드 소득공제 대학생에게 얼마나 ',
  '하나은행 징검다리론 한도와 금리 신청조건 총정리',
  '태강대부 대출 절차와 이용 시 유의사항 총정리',
  'Lounge ONE 사기 라운지원 사칭 김민우프로 주식리딩방 ',
  'Lounge ONE 사기 라운지원 김민우프로 사칭 리딩방 주의해야 ',
  '코인베이스의 인도 시장 재진입',
  'KB국민카드 면접 최종 합격하는 면접관 1 1 맞춤형 컨설팅',
  '싱가포르상표 국제상표 병행이 답인 이유 4가지',
  'BM특허권 단순한 영업방법은 절대 등록받을 수 없습니다',
  'worldswap beams 사기 인스타그램 접근 코인사칭 플랫폼 출금 ',
  '해외송금 수수료 걱정 끝 건당수수료의 장점',
  '가짜 3 3 계약 quot 피해 근로자 quot 를 위한 대응 절차 A to Z',
  '해외송금 10만달러까지 증빙없이 초간편 시대',
  '무직자 소액대출 승인 잘되는 비대면 상품 정리',
  '중국이 미국을 제치고 AI 1인자가 될 수 있을까 중국의 AI ',
  ' quot 국민연금이 빚낸다 quot 정부가 고환율 해결 위해 내놓은 방안',
  '토스뱅크 아기펭귄 이거하면 5천원 준다는데 진짜 ',
  '예가람저축은행 예스론 추가대출 승인 잘되는 방법',
  '2금융권 토지담보대출 상품별 금리와 신청조건 비교',
  '럭시라이프 사기 만남어플 접근 교묘한 감정 유도형 수법 분석 ',
  '올원 뱅크 이체 한도 상향 신청 및 하루 송금한도 조정 방법',
  '원화 스테이블코인 인터넷뱅킹 카뱅 토뱅 케뱅 특허 선점 ',
  '15억 달러 규모의 촉매제가 방금 SoFi 주식을 뒤흔들었습니다 ',
  '박민수 핑거 부회장 디지털자산 혁명 속 활로 찾는 나침반 ',
  '스타저축은행 하이론 재대출 조건과 승인 후기 확인하기',
  'AI 기술 특허등록 알고리즘도 지식재산으로 보호해야',
  '피플펀드 대환대출 신청절차와 조건 알아보기',
  '유안타증권 사기 사칭 주식리딩방 유형 실제처럼 보이지만 속은 ',
  '주식회사 트립퍼 사기 사칭 믿음을 악용한 허위 예약 결제 ',
  '쿠팡 회원탈퇴 방법 개선 PC 아닌 앱에서도 탈퇴 가능',
  '용인시 처인구 남사읍 개인회생 채무조정 인가율 높은 이유',
  '해외취업 시 알아두면 좋은 저렴한 해외 송금',
  ' quot 비트코인과 CFTC 파일럿 프로그램 디지털 자산 담보의 ',
  ' 에이플러스에셋 알아보기',
  '간추린 금융경제 뉴스제목모음 1209화13h',
  '오늘의핫뉴스3 불당시티와 함께 알아볼까요 유사품주의하세요 ',
  '예가람저축은행 논스톱 대출 24시간 즉시 입금 가능한 상품 정리',
  'IBM이 Confluent를 사려는 이유 3가지 AI 데이터 스트림 ',
  '국민은행 KB국민ONE대출 자격조건과 금리 총정리',
  '소셜버즈리포트 251209 오늘 미국 커뮤니티 결국 CETX에 ',
  '고양 파주 신용불량자 개인회생 카드단말기 매출 묶일 걱정 ',
  '금융결제원 면접 평가자 1 1 맞춤형 컨설팅 합격 전략 공개',
  '14억 인구 기반 인도가 향후 20 30년간 지속 성장 할 수 ',
  '금산분리 완화 기대 예상 수혜주',
  '페이팔 주식 전망 핀테크 대장주의 미래와 투자 전략',
  '현대차 미소금융 지원프로그램과 대출신청 절차 정리',
  '아온나샵 사기 물품 구매 사이트 포인트 출금 불가 구조 사칭 ',
  '외환은행 환율 실시간 조회와 환전수수료 절감법 알아보기',
  '미국 공립 명문 톱20 코네티컷 대학교 UConn 약대 의대 ',
  '우리은행 희망플러스 신용대출 금리 한도 정리안내',
  '디지털 경제의 불청객 성인 콘텐츠 기반 핀테크 금융 괴물 ',
  '12월08일 미국주식 시간외 391 대폭등 밤사이 터진 ',
  '해외송금 무증빙 10만달러 허용 2026년부터 바뀌는 송금 ',
  '통장사본 온라인 발급 절차와 은행별 이용가이드',
  '대출 진행 시 필수 확인해야 할 금융정보 모음',
  '신용카드 한도 상품권 할부 구매의 중요성들',
  '앨리트뱅킹 사기 Elite Banking 사칭 해외투자 플랫폼 유형 ',
  '기업은행 대출상품 한도 금리와 신청조건 정리',
  '하나은행 무직자대출 가능조건과 재대출 신청 방법',
  '알쏭달쏭 법률 핀테크부터 재택근무까지 시원하게 풀어드립니다 ',
  '원화스테이블코인 동향 2025 12 09 ',
  'stmove rb com 사기 사칭 지엘씨라이다 폐쇄형 자율주행 ',
  '소상공인 9등급도 가능한 대출 상품 조건 총정리',
  '2025년 12월 9일 동아일보 기사보기',
  ' 미국기업 Circle Internet Group',
  '하나은행 소상공인대출 금리 조건 한도 신청방법 완전정리',
  '하나은행 외국인 대출 조건 신용도별 금리 차이 정리',
  '해외송금 규제가 바뀌는 순간 돈의 흐름도 달라진다 연 ',
  '광주은행 햇살론15 신청자격과 재대출 후기',
  ' 2026년 대비 내일배움카드 2편 수강료 0원에 월 31만원 K ',
  '2026년 예산안 도대체 돈이 어디로 가고 있는가 ',
  '동두천 카드단말기 하봉암동 토스단말기 카드기등록 과정',
  '브라질 공급망 이해하기 브라질 코스트와 발전 가능성 책 리뷰 ',
  '웰컴저축은행 자동대출 신청자격과 이용절차 안내',
  '서민금융진흥원 이지론 저신용자대출 지원 대상 확인',
  '개인회생 변제금 완납 후 신용회복 절차와 금융생활 복귀법',
  '디파이 DeFi 란 무엇이며 왜 은행을 위협하는가',
  '웹개발 실무자가 자주 겪는 성능 보안 이슈 해결',
  '서초구 서초3동 개인회생 빚 부담 줄이는 채무조정 신청방법',
  '리뉴월렛 코인 상장 글로벌 연계관찰',
  '은행 창업대출 추천상품과 조건 비교',
  '규제 샌드박스 제도와 법무법인 가나다의 법률적 접근',
  'VT 사기 vindextrade com S amp P500 달러 지수거래 출금 막히는 ',
  '1억원 대출 이자 계산기 결과와 상환방법 확인',
  '삼성생명 보험금청구서 작성 전 꼭 알아야 할 핵심 포인트',
  '카카오뱅크 비상금 대출 신청자격과 금리 인하 방법',
  '대형 오피스 시장 신도림 구로 광명 지산왕',
  '햇살론15 특례보증 신청자격과 준비서류 완벽정리',
  '월드스왑 사기 사칭 암호화폐 차익거래 고수익을 미끼로한 ',
  '농협카드 단기대출 급전 필요할 때 활용하는 방법'],
 'link': ['https://blog.naver.com/kimengg/224103515517',
  'https://dramapd.tistory.com/1085',
  'https://blog.naver.com/econonow/224103566880',
  'https://ilovefamily.tistory.com/524',
  'https://blog.naver.com/seveneswsh/224103561542',
  'https://bluebeat.tistory.com/1126',
  'https://blog.naver.com/mgreatmaild18/224103107061',
  'https://bluebeat.tistory.com/1166',
  'https://blog.naver.com/hellocanopy/224103543493',
  'https://sibauchi.tistory.com/1143',
  'https://blog.naver.com/moneycultreview/224103310590',
  'https://sibauchi.tistory.com/1130',
  'https://bluebeat.tistory.com/1123',
  'https://blog.naver.com/dgzuxzgby/224103130537',
  'https://blog.naver.com/weirdo36529/224103453600',
  'https://blog.naver.com/investor76/224103524083',
  'https://blog.naver.com/05g8wbolei/224103520654',
  'https://blog.naver.com/fastdesign/224103519162',
  'https://blog.naver.com/tm_maker/224082560561',
  'https://blog.naver.com/nntto12976/224102883521',
  'https://blog.naver.com/e9payday/224101631252',
  'https://blog.naver.com/nomu4rang/224102260423',
  'https://blog.naver.com/money-study-/224103512826',
  'https://bluebeat.tistory.com/1165',
  'https://blog.naver.com/eunji_1104/224103506268',
  'https://blog.naver.com/pandainvest/224103501079',
  'https://blog.naver.com/soo2402/224103496754',
  'https://sibauchi.tistory.com/1176',
  'https://bluebeat.tistory.com/1162',
  'https://blog.naver.com/friry96847/224103348630',
  'https://sibauchi.tistory.com/1189',
  'https://blog.naver.com/true_insight/224103423673',
  'https://blog.naver.com/banryeojasan/224103485795',
  'https://blog.naver.com/c9book/224103486052',
  'https://lefthusband.tistory.com/1525',
  'https://blog.naver.com/hongbin1814/224103482558',
  'https://think-tank.tistory.com/887',
  'https://blog.naver.com/mgreatmaild18/224103104776',
  'https://blog.naver.com/ickkoju2/224103143300',
  'https://blog.naver.com/dndus01/224103474912',
  'https://dramapd.tistory.com/1096',
  'https://blog.naver.com/wirebarley_official/224103472498',
  'https://blog.naver.com/star_handful/224103472014',
  'https://blog.naver.com/star_of_self/224103471437',
  'https://blog.naver.com/misokir/224103465030',
  'https://blog.naver.com/kmj041217/224103464040',
  'https://ilovefamily.tistory.com/565',
  'https://blog.naver.com/aaajung_/224103460914',
  'https://think-tank.tistory.com/869',
  'https://blog.naver.com/make_second_salary/224103458906',
  'https://blog.naver.com/hanbitict/224103457625',
  'https://blog.naver.com/shit75/224103445933',
  'https://blog.naver.com/plan_pan/224102934877',
  'https://blog.naver.com/billionairementor/224103443976',
  'https://blog.naver.com/linear_regression_/224103443872',
  'https://lefthusband.tistory.com/1510',
  'https://blog.naver.com/nntto12976/224102889618',
  'https://sibauchi.tistory.com/1192',
  'https://blog.naver.com/shin_of_uhak/224103423585',
  'https://bluebeat.tistory.com/1154',
  'https://blog.naver.com/heraldpost/224103423423',
  'https://blog.naver.com/bekchunil/224103422491',
  'https://blog.naver.com/genieinfo/224103417096',
  'https://bluebeat.tistory.com/1120',
  'https://sibauchi.tistory.com/1155',
  'https://blog.naver.com/boom2945/224103413543',
  'https://blog.naver.com/mgreatmaild18/224103102730',
  'https://sibauchi.tistory.com/1150',
  'https://ilovefamily.tistory.com/529',
  'https://blog.naver.com/huxim5594/224103396560',
  'https://blog.naver.com/the_greatest_/224102469583',
  'https://blog.naver.com/dgzuxzgby/224103127333',
  'https://sibauchi.tistory.com/1103',
  'https://blog.naver.com/bogo6090/224103390499',
  'https://blog.naver.com/angel9141/224103390601',
  'https://lefthusband.tistory.com/1594',
  'https://ilovefamily.tistory.com/558',
  'https://blog.naver.com/sphlt187/224103078270',
  'https://sibauchi.tistory.com/1145',
  'https://blog.naver.com/wisehub_kr/224103224400',
  'https://blog.naver.com/kc7339/224102541120',
  'https://blog.naver.com/dbposdb/224087782982',
  'https://blog.naver.com/bookwalkingbook/224098552675',
  'https://think-tank.tistory.com/912',
  'https://ilovefamily.tistory.com/699',
  'https://lefthusband.tistory.com/1591',
  'https://blog.naver.com/jinfiction/224103374025',
  'https://blog.naver.com/nexpay_jobs/224081139667',
  'https://dramapd.tistory.com/1113',
  'https://blog.naver.com/hetjdk6shz/224103356349',
  'https://sibauchi.tistory.com/1157',
  'https://blog.naver.com/forward10956/224103347124',
  'https://blog.naver.com/friry96847/224103339262',
  'https://think-tank.tistory.com/871',
  'https://think-tank.tistory.com/995',
  'https://ilovefamily.tistory.com/580',
  'https://blog.naver.com/numerouno/224098242090',
  'https://think-tank.tistory.com/919',
  'https://blog.naver.com/mgreatmaild18/224103100679',
  'https://think-tank.tistory.com/893'],
 'description': ['또한 NAVER 2 1 가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 기대감으로 상승했던 사례처럼 이커머스 플랫폼과 핀테크의 융합은 코리아센터에게도 새로운 성장 동력이 될 수 있습니다 외국인 ',
  '주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을 펼치고 있으며 핀테크 기업들은 AI 기반의 맞춤형 채무 컨설팅 서비스를 제공하며 시장 경쟁에 참여하고 있습니다 ',
  '무엇보다 국내 대표 핀테크 앱이라는 점에서 신뢰도도 높아 안심하고 사용할 수 있습니다 광고 시청이나 간단한 미션 완료로 포인트를 주는 리워드앱도 인기인데요 대표적으로는 오베이 설문조사 캐시닥 ',
  '특히 핀테크 기술의 발전은 은행 방문 없이 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는 그리고 핀테크 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다 특히 고금리 ',
  '살린 핀테크 서비스를 기본 모델로 하여 고객이 직접 이율 기간 금액 등을 원하는 대로 설정하여 소셜 핀테크 스타트업 입니다 우리는 사용자 간의 신용을 기반으로 한 소셜 네트워크 Social Network 를 ',
  ' 우리카드 올인원대출 금리 amp 재대출 조건 핀테크 전문가의 심층 분석 급변하는 금융 시장 속에서 향후 1 2년 동안은 고금리 기조가 유지될 가능성이 높으며 핀테크 기업들의 혁신적인 대출 상품 출시 ',
  '합니다 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '강화 핀테크 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다 특히 금리 인상은 대출 수요 감소로 이어졌으며 소득 증빙 조건 강화는 대출 문턱을 높였습니다 핀테크 기업들은 혁신적인 기술과 ',
  'HR amp 핀테크 업계에서 주목받는 흐름입니다 근로자 복지 amp 만족도 증가 일한 즉시 정산이 가능해 있는 핀테크 기반 금융 인프라로서 성장하고자 합니다 또한 국내에서의 사업 안정화 이후 해외 특히 ',
  '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 더욱 깐깐하게 진행하고 있으며 핀테크 핀테크 기업들은 AI 기반 신용평가 모델을 고도화하여 리스크 관리 능력을 강화하고 맞춤형 대출 상품을 ',
  ' 지갑을 가볍게 하고 싶은 학생 지역화폐 혜택을 받고 싶은 학생 제주 지역 소상공인을 응원하고 싶은 학생 알뜰하게 생활비를 아끼고 싶은 학생 최신 핀테크 서비스를 ',
  '또한 핀테크 기업과의 협력을 통해 온라인 플랫폼을 강화하고 사용자 편의성을 높이는 방향으로 또한 핀테크 기업과의 협력을 통해 온라인 플랫폼을 강화하고 사용자 편의성을 높이는 방향으로 발전할 ',
  '강화 핀테크 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다 특히 고금리 시대에 감소 핀테크 플랫폼을 통한 비대면 대출 증가 향후 1 2년 예상 트렌드 금리 안정화 또는 소폭 하락 가능성 ',
  '합니다 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '이유 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '사용이 빠르게 증가하고 있어 암호화폐 채택률이 매우 높을 잠재력을 가지고 있다 대규모 투자 유치 벤처 캐피털과 사모 펀드 자금은 인도의 핀테크 및 블록체인 스타트업에 지속적으로 투자하고 있다 ',
  'KB국민카드는 핀테크 플랫폼 비즈니스 등 변화의 최전선에 있는 기업입니다 과거의 은행 면접 준비하듯 성실함 만 강조해서는 절대 합격할 수 없습니다 오늘 이 글에서는 왜 죽어라 준비한 답변이 ',
  '또한 싱가포르상표는 브랜드 전략 중심의 기업 IT 헬스케어 F amp B 핀테크 이 많이 선택하기 때문에 국제상표와 자연스럽게 연결되는 시장 구조를 가지고 있습니다 기율특허법인이 싱가포르상표 전략에 강한 ',
  '즉 온라인 플랫폼 앱 서비스 핀테크 솔루션 등이 대표적인 BM특허의 형태입니다 성공적인 권리 확보를 위한 전체 비용은 일반적으로 전문가 수수료와 관납료를 포함하여 출원 시 180 200만 원 등록 시 180 200만 ',
  ' 사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '최근 몇 년간 은행 핀테크 업체들이 이체 수수료를 대폭 낮추면서 국내 송금은 생활 속 기본 하지만 최근에는 비용 구조를 단순화한 핀테크 기반 해외송금 서비스가 등장하며 상황이 크게 달라졌습니다 ',
  '7 11 서울시 핀테크랩 인사노무 멘토 2021 1 산업인력공단 현장학습근로자 실태조사 점검위원 미용업 제조업 2021 1 한국장애인개발원 외부 노무전문위원 2021 10 코레일네트웍스 채용심사위원 ',
  '은행을 이용하면 연간 10만 달러까지 가능했지만 증권사나 핀테크 업체 같은 비은행권을 이용할 경우 해외송금 무증빙송금 금융규제 외환거래 핀테크 AI반도체 SK하이닉스 삼성전자 네이버 카카오',
  '여러 핀테크 기업들이 시장에 진입하면서 경쟁은 더욱 치열해졌습니다 정부는 가계 부채 증가를 대부업체 핀테크 플랫폼 등으로 구분됩니다 각 기관마다 대출 조건 금리 심사 기준 등이 다르므로 꼼꼼히 ',
  '범위 핀테크 클라우드 전자상거래 IT 하드웨어 등 전반적인 홍콩 상장 빅테크 시가총액 상위 10개 종목에 집중 종목 비중 특정 종목의 비중을 10 이내로 제한 분산 효과 상위 10개 종목에 균등하게 ',
  '해외송금 핀테크 업체 건당 5000달러 연 5만 달러 문제는 각 업체별로 한도가 따로 적용된다는 점입니다 여러 업체를 돌면 100만 달러 이상도 증빙 없이 해외 송금 가능했던 구조인데 이는 은행 핀테크 간 ',
  '다른 핀테크 경쟁사들과 차별화되는 토스뱅크만의 강점으로 작용하고 있는 거죠 게다가 5천원이라는 보상 자체도 부담스럽지 않으면서도 사람들의 참여를 유도하기에 충분한 매력적인 금액이고요 하지만 ',
  '핀테크 기업과의 경쟁 심화 디지털 금융 서비스 확산 등도 주요 트렌드로 자리 잡을 것입니다 예스론은 이러한 변화에 발맞춰 리스크 관리 강화 디지털 채널 확대 맞춤형 상품 개발 등에 집중해야 할 ',
  '핀테크 기업과의 협력을 통해 비대면 대출 프로세스를 강화하고 고객 편의성을 높이는 전략도 향후 2금융권 토지담보대출 시장은 핀테크 기술과의 융합을 통해 더욱 발전할 것으로 예상됩니다 빅데이터 ',
  ' 사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '비대면 금융 서비스 이용 증가 핀테크 기업의 혁신적인 서비스 출시 그리고 전통 금융기관의 디지털 전환 가속화가 주요 동인이었습니다 특히 모바일 뱅킹 앱의 역할이 더욱 중요해지면서 사용자 경험 UX ',
  ' 국내 핀테크 성장 전략 결제 송금 자산관리 등 서비스 중심의 인터넷은행이 경쟁력을 가질 수 있습니다 금융시장 혁신 필요 CBDC의 공공 중심 구조보다 민간 중심 구조가 시장 속도에 적합하다는 ',
  '핀테크 주식은 빠른 성장 수익성 있는 단위 경제성 확장적인 상품군을 결합할 수 있는 기업에 SOFI 주식 소개 2011년에 설립된 SoFi는 원스톱 모바일 뱅킹 앱을 기반으로 한 핀테크 회사입니다 약 1 260만 ',
  '대한민국 핀테크 산업을 이끄는 리더 박민수 핑거 부회장님의 따끈따끈한 인터뷰 소식을 전해드립니다 혼란스러운 디지털 자산 시장 투기가 아닌 방향 을 묻다 12월 8일 전자신문은 인터뷰 기사를 통해 ',
  '향후 1 2년 동안 하이론 시장은 금리 인상 추세 둔화 정부의 가계 부채 관리 강화 핀테크 기술 발전 핀테크 기술 발전은 온라인 대출 플랫폼 활성화 신용 평가 모델 고도화 등을 통해 하이론 시장의 효율성을 ',
  '특히 SaaS 핀테크 이커머스 기업들은 AI가 경쟁력의 핵심이라 AI 기술 특허등록을 먼저 확보하는 전략을 사용하고 있습니다 최근에는 네이버 카카오 구글 메타뿐만 아니라 중소기업과 스타트업도 AI 기술을 ',
  '하지만 정부의 정책 지원과 핀테크 기업들의 혁신적인 서비스 출시를 통해 새로운 기회가 창출될 수도 있습니다 주요 기업들은 금리 경쟁력을 확보하기 위해 노력하는 한편 빅데이터 분석을 통해 개인별 ',
  '전혀다르다 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '실체 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '최근에는 토스 네이버페이 카카오페이 삼성페이 등 핀테크 앱에서 클릭하면 2원 3원 수익금 주는 배너 탓에 하루에도 여러 번씩 들락달락 거리기까지도 한다 개선 전 쿠팡 회원 탈퇴 과정 절차 그리고 ',
  '강화 핀테크 기업 데이터 기반 맞춤형 채무조정 컨설팅 서비스 개발 소규모 법률사무소 지역 밀착형 서비스 제공 및 가격 경쟁력 강화 소비자 행동 변화 온라인 정보 검색 및 비교 분석 활발 무료 상담 및 견적 ',
  '이런 상황에서 은행 대신 한국에서 해외로 해외에서 한국으로 해외 송금을 할 수 있는 핀테크 어플을 소개해드릴게요 와이어바알리 소개 와이어바알리는 글로벌 핀테크 해외송금 기업으로 한국 미국 캐나다 ',
  '파일럿 프로그램의 시장 반응 CFTC의 이번 발표는 암호화폐 및 핀테크 업계에서 긍정적인 반응을 얻고 있습니다 코인베이스의 법률 책임자 폴 그레왈 Paul Grewal 은 이번 조치가 스테이블코인과 디지털 ',
  '경쟁사인 인카금융서비스가 핀테크 플랫폼과의 제휴 등을 통해 디지털 접점을 넓히려는 시도를 이러한 풍부한 현금 보유고는 향후 유망한 핀테크 기업 인수나 주주 환원 배당 확대를 위한 재원으로 ',
  ' 1000원부터 1만원까지 롯데손보 스키보험 시즌권 플랜 신설 11 팔린 방카슈랑스 내년 더 기대된다 1 2세대 실손보험 받은 보험금 빼고 되팔 수 있다 1470원 환율에 국민연금 움직인다 ',
  '외환 제도 개편으로 증권사 카드사 핀테크 등을 통한 무증빙 해외 송금 한도가 연 10만 달러 약 1억 3천만 원 까지 확대되는 등 외환 관리 효율화 및 국민 편의가 제고됩니다 3 건설업 부진 장기화 및 소비 ',
  '특히 핀테크 기업들의 활약으로 인해 비대면 대출 시장이 급성장했으며 소비자들은 더욱 빠르고 편리한 대출 서비스를 요구하고 있습니다 향후 1 2년 동안 금리 변동성이 지속될 것으로 예상되며 개인 신용 ',
  '2 Apache Kafka 기반 우버 메타 핀테크 기업들이 다 쓰는 실시간 데이터 기술의 핵심이 바로 AI 핀테크 우버 넷플릭스 메타 등에서 모두 사용 왜 IBM이 Confluent를 사고 싶어하는가 AI ',
  '핀테크 기업들의 금융 시장 진출 확대는 경쟁 심화를 가져오겠지만 동시에 새로운 대출 상품 및 서비스 개발을 촉진할 것입니다 주요 은행들은 디지털 전환 가속화 맞춤형 상품 개발 그리고 리스크 관리 ',
  'TGL 1대20 리버스 스플릿 이후 2026년 매출 가이던스를 세 배로 올리면서 핀테크 디지털자산 성장 스토리 가격 튕김 조합으로 커뮤니티의 레이더에 들어온 상황 DFLI CISO SLS 테마는 ',
  ' quot 어떻게 카드 결제 대금을 바로 주나요 quot quot 이거 불법 아닌가요 quot 결론부터 말씀드리면 100 합법적인 핀테크 기술입니다 저희 한빛정보통신이 제공하는 코페이 서비스는 PG사 전자결제대행사 가 자금력을 ',
  '최신 핀테크 기술 블록체인 역량 창의적인 아이디어 물론 좋습니다 하지만 금융결제원은 대한민국의 금융 공동망을 책임지는 핵심 인프라 기관입니다 이곳에서 가장 중요한 가치는 혁신 이전에 안정 과 ',
  '있어요 핀테크 기업도 잇달아 등장 중 한국 중국은 이미 둔화됐지만 인도는 이제 시작 이건 신흥국이 선진국으로 가고 있다는 증거예요 투자자들이 본 인도의 매력과 우리가 갈 길 개인 투자자도 쉽게 참여 ',
  '과거에는 은행의 생활 서비스 진출이나 핀테크 기업의 금융업 영위 문제가 주된 쟁점이었으나 최근 논의의 초점은 AI 반도체 등 첨단전략산업의 경쟁력 확보를 위한 자본 조달 채널 확보로 옮겨가고 ',
  '페이팔은 디지털 결제 및 핀테크 서비스를 제공하는 글로벌 온라인 결제 플랫폼으로 잘 알려져 핀테크 시장에서의 현명한 투자 전략 변화무쌍한 핀테크 시장에서 현명한 투자 전략을 고민하는 것은 ',
  '그리고 핀테크 플랫폼의 성장이라는 복합적인 요인에 의해 크게 흔들렸습니다 특히 고금리 시대에 하지만 동시에 핀테크 기업들은 데이터 기반의 맞춤형 대출 상품을 출시하며 시장 경쟁을 심화시키고 ',
  ' 사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  ' 또한 핀테크 기업들은 혁신적인 환전 플랫폼을 선보이며 기존 은행들과의 경쟁을 심화시키고 있습니다 이러한 경쟁은 소비자들에게 더욱 유리한 조건을 제공할 가능성이 높습니다 소비자 행동 변화 역시 ',
  'UConn은 특히 약대 Pre Med 비즈니스 데이터 분석 핀테크 FinTech 분야로 유명하고 의대 약대 보건 비즈니스 데이터 핀테크까지 전방위적으로 강한 학교입니다 특히 한국 ',
  '또한 핀테크 기업과의 협력을 통해 비대면 채널을 강화하고 중저신용자를 위한 맞춤형 상품 개발에 주력하고 있습니다 소비자들은 금리 변동에 민감하게 반응하며 대출 금리를 꼼꼼히 비교하고 상환 능력을 ',
  ' E WHO뉴스32 80 20 수익분배의 역설 온리팬스 https www justeconomix com news articleView html idxno 148911',
  '넷캐피탈 NCPL amp 엑시큐어 XCUR 73 의 유혹 상승률 NCPL 73 XCUR 72 정체 NCPL은 소형 핀테크 XCUR는 바이오 동전주 Penny Stock 입니다 팩트체크 NCPL 최근 실적은 적자 확대였습니다 뚜렷한 대형 ',
  '은행이든 핀테크든 합쳐서 10만달러까지 무증빙 송금 가능해진다고요 송금할 때마다 증빙 서류 quot 지금은 은행은 10만달러 증권사 핀테크는 각각 5만달러로 따로따로 한도가 있죠 그리고 은행을 하나 ',
  '주요 은행들은 API Application Programming Interface 개방을 통해 핀테크 기업들과 협력하여 더욱 편리하고 핀테크 기업들은 사용자 경험 개선에 집중하여 UI UX 디자인을 혁신하고 간편 결제 간편 송금 등 편리한 ',
  '핀테크 기업들은 AI 기반 신용 평가 모델을 개발하여 대출 심사의 정확성을 높이고 맞춤형 대출 상품을 제공하는 데 주력하고 있습니다 소비자들은 금리 변동에 대한 위험을 줄이기 위해 고정 금리 대출이나 ',
  '자연스럽게 핀테크 즉 금융 기술 산업 쪽에도 시선이 모이고 있죠 요즘은 비트코인 주식 부동산 등 아직 불확실한 미래나 금리 인상 같은 변수 앞에서도 핀테크 산업은 어둠을 밝히는 등대처럼 새로운 길을 ',
  '있다 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '또한 핀테크 기업들의 대출 시장 진출이 활발해지면서 경쟁이 심화되고 소비자들은 더욱 다양한 향후 대출 시장은 디지털 전환과 핀테크 기술의 발전으로 인해 더욱 편리하고 다양한 상품과 서비스를 ',
  '하지만 동시에 핀테크 기업들의 혁신적인 대출 상품 출시와 정부의 서민 금융 지원 확대 정책은 새로운 온라인 플랫폼 경쟁 심화 핀테크 기업들의 온라인 플랫폼을 통한 대출 서비스 경쟁이 더욱 심화될 ',
  '알쏭달쏭 법률 핀테크부터 재택근무까지 시원하게 풀어드립니다 알쏭달쏭 법률 핀테크부터 재택근무까지 시원하게 풀어드립니다 핀테크와 법 복잡한 금융의 세계 법으로 안전하게 지켜봐요 눈 깜짝할 새 ',
  '하지만 동시에 핀테크 가상자산기업과의 협력을 열어두었다 즉 은행 중심의 안정성과 기술 중심의 혁신을 모두 품으려는 구조다 그래서 지금 한국 금융권에서는 협력과 경쟁이 얽혀 있는 묘한 긴장감이 ',
  '실체 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '도입 핀테크 기업과의 협력 강화 소비자 행동 변화 대출 심사 강화에 따른 자금 확보 어려움 증가 대출 핀테크 기업의 간편 대출 장점 빠른 심사 간편한 절차 단점 높은 금리 짧은 상환 기간 실제 사례 ',
  '증권사 핀테크업체서도 년10만달러 무증빙 해외송금 제일좋은전람 광주창업박람회 참가문의 010  보고창업 영업대행 문의전화 1544 8094 소운나키토김밥 창업문의 1533 6163 남진식당 가맹점문의 1544 ',
  'Circle Internet Group CRCL 회사 개요 및 재무 성과 회사 개요 Circle Internet Group CRCL 은 2013년에 설립된 미국 뉴욕 기반 핀테크 기업으로 스테이블코인 및 블록체인 애플리케이션을 ',
  ' 하나은행 소상공인대출 완벽 해부 금리 조건 한도부터 신청까지 안녕하세요 전문 기술 분석가입니다 오늘 우리는 급변하는 경제 환경 속에서 소상공인들에게 든든한 버팀목이 되어줄 하나은행의 ',
  '동시에 핀테크 기업의 등장으로 온라인 대출 플랫폼이 활성화되면서 외국인들이 더욱 편리하게 대출 향후에는 핀테크 기술을 활용한 맞춤형 대출 상품 개발 인공지능 기반의 신용 평가 시스템 도입 그리고 ',
  '지금까지는 은행 증권 핀테크 등 송금업권에 따라 제출 서류가 달랐고 일정 금액 이상 송금할 때는 과거에는 은행을 이용할 때와 핀테크 기업을 이용할 때 요구되는 절차가 달랐고 동일한 금액을 ',
  '그리고 핀테크의 성장이라는 삼중고를 겪었습니다 금리 인상은 대출 수요를 위축시키고 연체율 핀테크 기업들은 간편한 대출 심사 및 실행 시스템을 통해 시장 점유율을 확대하고 있지만 고금리 논란과 ',
  ' 배울 수 있는 분야 코딩 SW개발 빅데이터 인공지능 AI 핀테크 실감형 콘텐츠 VR AR 드론 스마트공장 등 미래 유망 직종이 총망라되어 있습니다 2 왜 국비지원의 꽃 이라 불릴까 3가지 파격 혜택 ',
  '키워드 유망 분야 복지 확대 헬스케어 교육 지역화폐 플랫폼 농식품 지역자립 로컬푸드 스마트팜 기본소득 바우처 결제 인프라 핀테크 정부는 경제성장보다 사회 안전망 강화 를 우선한 예산 ',
  '특히 최근에는 토스와 같은 핀테크 기반의 스마트 단말기가 등장하면서 기존의 복잡했던 설치 및 등록 과정이 간소화되고 있습니다 게다가 디자인도 심플하면서도 깔끔하다 보니 많은 분들이 선호하고 ',
  '브라질은 농산업 에너지 철광석 핀테크가 고르게 발전한 나라다 대두 옥수수 유칼립투스 커피 대도시를 중심으로 인터넷 인프라가 갖춰지고 저렴한 스마트폰이 보급되면서 핀테크 산업 역시 빠르게 ',
  '강화 핀테크 기업의 성장 등 다양한 요인에 의해 큰 변화를 겪었습니다 특히 고금리 시대에 핀테크 기업들은 인공지능 AI 기반의 신용 평가 모델을 도입하여 리스크 관리를 강화하고 맞춤형 대출 상품을 ',
  '변화 핀테크 기업의 등장 등 다양한 요인에 의해 끊임없이 변화해왔습니다 특히 금리 인상 은 저신용자들의 상환 부담을 가중시키고 대출 문턱을 더욱 높이는 결과를 초래했습니다 핀테크 기업들은 데이터 ',
  ' 개인회생 완납 후 신용회복과 금융생활 복귀 당신의 성공적인 재기를 위한 기술 분석 최근 고금리 기조와 불안정한 경제 상황이 지속되면서 가계 부채 문제가 사회 전반의 중요한 이슈로 부각되고 ',
  '디 디파이 DeFi 를 한 문장으로 정의하면 이렇게 정리할 수 있다 은행 창구 대신 코드가 돌아가는 인터넷 시대의 금융 시스템 은행처럼 예금 대출 송금 투자 같은 일을 하는데 창구 직원도 점포도 ',
  '혁신상품 핀테크 부문 수상 등 실적 가입자 약 3만 5천명 결제금액 약 6천억원 거래건수 약 1천 4백만건 앱다운로드 약 5만건 현장 적용 시나리오 1인 PT 필라테스 정기결제 세팅으로 ',
  '향후 서초3동의 채무조정 시장은 핀테크 기술을 활용한 온라인 상담 및 서류 간소화 서비스가 더욱 활성화될 것으로 예상됩니다 9 개인회생 성공의 열쇠를 쥐다 활용 팁과 주의사항 개인회생 신청 시 성공 ',
  '해외 서비스 핀테크 기업 글로벌 가상자산 기반 결제 플랫폼 등과의 연동은 리뉴월렛 코인 사용성을 급격히 확대할 수 있다 사용 범위가 넓어질수록 토큰은 단순 투자 대상이 아니라 글로벌 서비스에서 ',
  '그리고 핀테크 기업의 성장이라는 거센 파도를 맞았습니다 금리 인상은 창업자들의 초기 부담을 가중시켰고 정부의 창업 지원 정책은 특정 분야에 집중되는 경향을 보였습니다 핀테크 기업들은 간편한 대출 ',
  '예를 들어 핀테크나 블록체인 기술을 활용한 서비스는 기존 금융 규제와 충돌할 수 있기 때문에 규제 샌드박스의 적용을 통해 법적 안전망을 확보할 수 있어요 규제 샌드박스 제도에 참여하는 기업은 일정 ',
  ' 사칭 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '핀테크 기업들은 빅데이터 분석을 통해 개인별 맞춤형 금리 정보를 제공하고 온라인 대출 플랫폼을 핀테크 기업들의 온라인 대출 플랫폼 확대로 인해 대출 상품 접근성이 높아지고 개인 맞춤형 금리 정보 ',
  ' 현재 보험 시장은 핀테크 기술의 발전과 함께 간편 청구를 위한 다양한 시도가 이루어지고 핀테크 기술과의 융합을 통해 청구 절차가 간소화되고 처리 속도가 획기적으로 개선된 것이 주요 특징입니다 ',
  '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 까다롭게 진행했고 핀테크 기업들은 혁신적인 주요 은행들은 건전성 확보에 주력하며 대출 문턱을 높이고 핀테크 기업들은 생존을 위한 수익성 ',
  '1호선과 2호선의 더블 환승에 더해 GTX B 노선 정차까지 확정되면서 물리적 이동성이 가장 중요해지는 금융 핀테크 데이터 기반 기업들의 선호도가 꾸준히 상승하고 있다 실제로 플랫폼 운영사나 대형 IT ',
  '은행들은 리스크 관리에 더욱 집중하며 대출 심사를 강화하는 추세이며 핀테크 기업들은 자체 이를 해결하기 위해 정부는 금리 인하 및 신청 절차 간소화를 추진하고 있으며 핀테크 기업들은 온라인 ',
  '실체 팀미션사기 주식사기 코인사기 스캠사기 사칭사기 공모주사기 투자사기 투자사기대응법 투자사기법적대응 사기피해회복 사기피해대응 사기피해전문변호사 핀테크전문 사기피해전문 ',
  '핀테크 기업들의 공세적인 마케팅과 간편한 대출 절차는 기존 금융권에 긴장감을 불어넣었으며 플랫폼 또한 핀테크 기업과의 경쟁 심화에 따른 과도한 마케팅 경쟁을 지양하고 건전한 금융 생태계를 '],
 'bloggername': ['하이디',
  '니은과 리을',
  '머니픽',
  '과거,현재,미래, 그리고 나.',
  '장외주식 알고해야 성투한다~!!',
  'bluebeat',
  'daylaw',
  'bluebeat',
  'Canopy',
  "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  '머니컬 리뷰',
  "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
  'bluebeat',
  '데이법률사무소',

In [9]:
df = pd.DataFrame(result)
df.to_csv("./data/requests로naver_api데이터수집.csv", index=False, encoding="utf-8-sig")

# python-dotenv로 api key 안전하게 사용하기
* .env 파일에 환경변수를 저장하고 python 코드에서 자동으로 불러오는 모듈
* pip install python-dotenv
* .env 파일을 만들어서 변수=값 형태로 내용 저장

In [13]:
from dotenv import load_dotenv
import os
load_dotenv()
import requests

user_id = os.getenv("")
user_secret = os.getenv("")
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {
    "X-Naver-Client-Id": "",
    "X-Naver-Client-Secret": ""
}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 09 Dec 2025 14:54:57 +0900',
 'total': 489927,
 'start': 1,
 'display': 100,
 'items': [{'title': '[2026 트렌드] 저비용으로 MZ세대 만족도를 높이는 2026년... ',
   'link': 'https://blog.naver.com/paywatch_kr/224103583600',
   'description': '복지로, <b>핀테크</b>로 간편하게. 페이워치 Paywatch 기업은 도입비 없이 인사 담당자는 채용 걱정 없이 임직원은 월급, 복지 고민 없게! 일하는 모든 사람을 위한 회사복지 솔루션 글로벌 <b>핀테크</b> 기업, 페이워치와... ',
   'bloggername': '금융을 복지처럼, 핀테크로 간편하게. 페이워치',
   'bloggerlink': 'blog.naver.com/paywatch_kr',
   'postdate': '20251209'},
  {'title': '✅ [두산에너빌리티(034020)] 1년 +270% 찍은 ‘K-원전·에너지... ',
   'link': 'https://blog.naver.com/salem04/224103580556',
   'description': 'HWH 같은 <b>핀테크</b>/컨설팅 복합 모델이 아니라, “에너지 인프라·원전·플랜트 하드웨어+EPC”를 동시에 영위하는 초대형 인프라 플레이어로 보는 것이 맞습니다. 4️⃣ 재무와 밸류에이션 – 이미... ',
   'bloggername': '경제 자유를 위한 공부',
   'bloggerlink': 'blog.naver.com/salem04',
   'postdate': '20251209'},
  {'title': '주담대 최저금리, 한도 계산기 및 갈아타기 조건 알아봄',
   'link': 'https://blog.naver.com/shiner2004/224103578897',
   'description': '여러 은행의 주담대 상품을 비교해 주는 <b>핀테크</b> 앱을 활용하는 것도 좋은 방법임. 또 은행연합회 소비자포털에 가면 은행별 가계 대출금리도 살펴볼 수 있으니 살펴보면 더 도움될 거임. 은행에 직접 가기 전... ',
   'bloggername': '직장인 10억 프로젝트',
   'bloggerlink': 'blog.naver.com/shiner2004',
   'postdate': '20251209'},
  {'title': '아이마켓코리아 &amp; 코리아센터 2026년 이커머스 주가 분석... ',
   'link': 'https://blog.naver.com/kimengg/224103515517',
   'description': '또한, NAVER(+2.1%)가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 기대감으로 상승했던 사례처럼, 이커머스 플랫폼과 <b>핀테크</b>의 융합은 코리아센터에게도 새로운 성장 동력이 될 수 있습니다. 외국인... ',
   'bloggername': '하이디',
   'bloggerlink': 'blog.naver.com/kimengg',
   'postdate': '20251209'},
  {'title': '화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항',
   'link': 'https://dramapd.tistory.com/1085',
   'description': '주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을 펼치고 있으며, <b>핀테크</b> 기업들은 AI 기반의 맞춤형 채무 컨설팅 서비스를 제공하며 시장 경쟁에 참여하고 있습니다.... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '재테크 앱으로 하루 10분, 월 5만 원 가능할까? 캐시워크부터... ',
   'link': 'https://blog.naver.com/econonow/224103566880',
   'description': '무엇보다 국내 대표 <b>핀테크</b> 앱이라는 점에서 신뢰도도 높아 안심하고 사용할 수 있습니다. 광고 시청이나 간단한 미션 완료로 포인트를 주는 리워드앱도 인기인데요, 대표적으로는 오베이(설문조사), 캐시닥... ',
   'bloggername': '머니픽',
   'bloggerlink': 'blog.naver.com/econonow',
   'postdate': '20251209'},
  {'title': '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
   'link': 'https://ilovefamily.tistory.com/524',
   'description': '특히, <b>핀테크</b> 기술의 발전은 은행 방문 없이, 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는... 그리고 <b>핀테크</b> 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다. 특히, 고금리... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': '티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 +++',
   'link': 'https://blog.naver.com/seveneswsh/224103561542',
   'description': '살린 <b>핀테크</b> 서비스를 기본 모델로 하여, 고객이 직접 이율, 기간, 금액 등을 원하는 대로 설정하여... 소셜 <b>핀테크</b> 스타트업 입니다.우리는 사용자 간의 신용을 기반으로 한 소셜 네트워크(Social Network)를... ',
   'bloggername': '장외주식 알고해야 성투한다~!!',
   'bloggerlink': 'blog.naver.com/seveneswsh',
   'postdate': '20251209'},
  {'title': '우리카드 올인원대출 금리와 재대출 조건 총정리',
   'link': 'https://bluebeat.tistory.com/1126',
   'description': '📊 우리카드 올인원대출: 금리 &amp; 재대출 조건, <b>핀테크</b> 전문가의 심층 분석 급변하는 금융 시장 속에서... 향후 1-2년 동안은 고금리 기조가 유지될 가능성이 높으며, <b>핀테크</b> 기업들의 혁신적인 대출 상품 출시... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 사칭 인스x 코인플랫폼 조심해야... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103107061',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '다올저축은행 비상금대출 소득증빙 가능자 필수 확인사항',
   'link': 'https://bluebeat.tistory.com/1166',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 금리 인상은 대출 수요 감소로 이어졌으며, 소득 증빙 조건 강화는 대출 문턱을 높였습니다. <b>핀테크</b> 기업들은 혁신적인 기술과... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '캐노피, 대교그룹 고객사 유치…대기업 레퍼런스 확대',
   'link': 'https://blog.naver.com/hellocanopy/224103543493',
   'description': 'HR &amp; <b>핀테크</b> 업계에서 주목받는 흐름입니다. 근로자 복지 &amp; 만족도 증가 일한 즉시 정산이 가능해... 있는 <b>핀테크</b> 기반 금융 인프라로서 성장하고자 합니다. 또한, 국내에서의 사업 안정화 이후 해외, 특히... ',
   'bloggername': 'Canopy',
   'bloggerlink': 'blog.naver.com/hellocanopy',
   'postdate': '20251209'},
  {'title': '케이뱅크 신용대출 비대면 신청방법과 후기',
   'link': 'https://sibauchi.tistory.com/1143',
   'description': '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 더욱 깐깐하게 진행하고 있으며, <b>핀테크</b>... <b>핀테크</b> 기업들은 AI 기반 신용평가 모델을 고도화하여 리스크 관리 능력을 강화하고, 맞춤형 대출 상품을... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '제주 탐나는전 학생증 체크카드 소득공제, 대학생에게 얼마나... ',
   'link': 'https://blog.naver.com/moneycultreview/224103310590',
   'description': '✔✔️ 지갑을 가볍게 하고 싶은 학생 ✔✔️ 지역화폐 혜택을 받고 싶은 학생 ✔✔️ 제주 지역 소상공인을 응원하고 싶은 학생 ✔✔️ 알뜰하게 생활비를 아끼고 싶은 학생 ✔✔️ 최신 <b>핀테크</b> 서비스를... ',
   'bloggername': '머니컬 리뷰',
   'bloggerlink': 'blog.naver.com/moneycultreview',
   'postdate': '20251209'},
  {'title': '하나은행 징검다리론 한도와 금리 신청조건 총정리',
   'link': 'https://sibauchi.tistory.com/1130',
   'description': '또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로... 또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로 발전할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '태강대부 대출 절차와 이용 시 유의사항 총정리',
   'link': 'https://bluebeat.tistory.com/1123',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 고금리 시대에... 감소, <b>핀테크</b> 플랫폼을 통한 비대면 대출 증가 향후 1-2년 예상 트렌드: 금리 안정화 또는 소폭 하락 가능성... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 사칭 김민우프로 주식리딩방... ',
   'link': 'https://blog.naver.com/dgzuxzgby/224103130537',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/dgzuxzgby',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 김민우프로 사칭 리딩방 주의해야... ',
   'link': 'https://blog.naver.com/weirdo36529/224103453600',
   'description': '이유 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/weirdo36529',
   'postdate': '20251209'},
  {'title': '코인베이스의 인도 시장 재진입',
   'link': 'https://blog.naver.com/investor76/224103524083',
   'description': '사용이 빠르게 증가하고 있어 암호화폐 채택률이 매우 높을 잠재력을 가지고 있다 대규모 투자 유치 : 벤처 캐피털과 사모 펀드 자금은 인도의 <b>핀테크</b> 및 블록체인 스타트업에 지속적으로 투자하고 있다.',
   'bloggername': '시장 앞에 겸손',
   'bloggerlink': 'blog.naver.com/investor76',
   'postdate': '20251209'},
  {'title': 'KB국민카드 면접, 최종 합격하는 면접관 1:1 맞춤형 컨설팅',
   'link': 'https://blog.naver.com/05g8wbolei/224103520654',
   'description': "KB국민카드는 <b>핀테크</b>, 플랫폼 비즈니스 등 변화의 최전선에 있는 기업입니다. 과거의 은행 면접 준비하듯 '성실함'만 강조해서는 절대 합격할 수 없습니다. 오늘 이 글에서는 왜 죽어라 준비한 답변이... ",
   'bloggername': '⭐꿀팁정보⭐',
   'bloggerlink': 'blog.naver.com/05g8wbolei',
   'postdate': '20251209'},
  {'title': '싱가포르상표, 국제상표 병행이 답인 이유 4가지',
   'link': 'https://blog.naver.com/fastdesign/224103519162',
   'description': '또한 싱가포르상표는 브랜드 전략 중심의 기업(IT·헬스케어·F&amp;B·<b>핀테크</b>)이 많이 선택하기 때문에 국제상표와 자연스럽게 연결되는 시장 구조를 가지고 있습니다. 기율특허법인이 싱가포르상표 전략에 강한... ',
   'bloggername': '특허전략 파트너 기율',
   'bloggerlink': 'blog.naver.com/fastdesign',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 인스타그램 접근 코인사칭 플랫폼 출금... ',
   'link': 'https://blog.naver.com/nntto12976/224102883521',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/nntto12976',
   'postdate': '20251209'},
  {'title': '가짜 3.3 계약 &quot;피해 근로자&quot;를 위한 대응 절차 A to Z',
   'link': 'https://blog.naver.com/nomu4rang/224102260423',
   'description': '7~11) - 서울시 <b>핀테크</b>랩 인사노무 멘토 (2021.1~ ) - 산업인력공단 현장학습근로자 실태조사 점검위원 (미용업, 제조업) (2021.1~ ) - 한국장애인개발원 외부 노무전문위원 (2021.10~ ) - 코레일네트웍스 채용심사위원... ',
   'bloggername': '노동법률 전문가 박놈사',
   'bloggerlink': 'blog.naver.com/nomu4rang',
   'postdate': '20251209'},
  {'title': 'BM특허권, 단순한 영업방법은 절대 등록받을 수 없습니다',
   'link': 'https://blog.naver.com/tm_maker/224082560561',
   'description': '즉, 온라인 플랫폼, 앱 서비스, <b>핀테크</b> 솔루션 등이 대표적인 BM특허의 형태입니다. 성공적인 권리 확보를 위한 전체 비용은 일반적으로 전문가 수수료와 관납료를 포함하여 출원 시 180~200만 원, 등록 시 180~200만... ',
   'bloggername': '마스터 상표',
   'bloggerlink': 'blog.naver.com/tm_maker',
   'postdate': '20251209'},
  {'title': '해외송금 수수료 걱정 끝 건당수수료의 장점',
   'link': 'https://blog.naver.com/e9payday/224101631252',
   'description': '최근 몇 년간 은행·<b>핀테크</b> 업체들이 이체 수수료를 대폭 낮추면서 국내 송금은 생활 속 기본... 하지만 최근에는 비용 구조를 단순화한 <b>핀테크</b> 기반 해외송금 서비스가 등장하며 상황이 크게 달라졌습니다.... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9payday',
   'postdate': '20251209'},
  {'title': '해외송금 10만달러까지 증빙없이 초간편 시대',
   'link': 'https://blog.naver.com/money-study-/224103512826',
   'description': '은행을 이용하면 연간 10만 달러까지 가능했지만, 증권사나 <b>핀테크</b> 업체 같은 비은행권을 이용할 경우... #해외송금 #무증빙송금 #금융규제 #외환거래 #<b>핀테크</b> #AI반도체 #SK하이닉스 #삼성전자 #네이버 #카카오',
   'bloggername': '생활경제 톡톡',
   'bloggerlink': 'blog.naver.com/money-study-',
   'postdate': '20251209'},
  {'title': '무직자 소액대출 승인 잘되는 비대면 상품 정리',
   'link': 'https://bluebeat.tistory.com/1165',
   'description': '여러 <b>핀테크</b> 기업들이 시장에 진입하면서 경쟁은 더욱 치열해졌습니다. 정부는 가계 부채 증가를... 대부업체, <b>핀테크</b> 플랫폼 등으로 구분됩니다. 각 기관마다 대출 조건, 금리, 심사 기준 등이 다르므로, 꼼꼼히... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '중국이 미국을 제치고 AI 1인자가 될 수 있을까? 중국의 AI... ',
   'link': 'https://blog.naver.com/eunji_1104/224103506268',
   'description': '범위 <b>핀테크</b>, 클라우드, 전자상거래, IT 하드웨어 등 전반적인 홍콩 상장 빅테크 시가총액 상위 10개 종목에 집중 종목 비중 특정 종목의 비중을 10% 이내로 제한 (분산 효과) 상위 10개 종목에 균등하게... ',
   'bloggername': 'As within, So without',
   'bloggerlink': 'blog.naver.com/eunji_1104',
   'postdate': '20251209'},
  {'title': '&quot;국민연금이 빚낸다?&quot; 정부가 고환율 해결 위해 내놓은 방안',
   'link': 'https://blog.naver.com/pandainvest/224103501079',
   'description': '해외송금 <b>핀테크</b> 업체 : 건당 5000달러 / 연 5만 달러 문제는 각 업체별로 한도가 따로 적용된다는 점입니다. 여러 업체를 돌면 100만 달러 이상도 증빙 없이 해외 송금 가능했던 구조인데, 이는 은행·<b>핀테크</b> 간... ',
   'bloggername': '판다엄마 재테크기록',
   'bloggerlink': 'blog.naver.com/pandainvest',
   'postdate': '20251209'},
  {'title': '토스뱅크 아기펭귄 이거하면 5천원 준다는데 진짜?',
   'link': 'https://blog.naver.com/soo2402/224103496754',
   'description': '다른 <b>핀테크</b> 경쟁사들과 차별화되는 토스뱅크만의 강점으로 작용하고 있는 거죠. 게다가 5천원이라는 보상 자체도 부담스럽지 않으면서도, 사람들의 참여를 유도하기에 충분한 매력적인 금액이고요. 하지만... ',
   'bloggername': 'soo....',
   'bloggerlink': 'blog.naver.com/soo2402',
   'postdate': '20251209'},
  {'title': '예가람저축은행 예스론 추가대출 승인 잘되는 방법',
   'link': 'https://sibauchi.tistory.com/1176',
   'description': '<b>핀테크</b> 기업과의 경쟁 심화, 디지털 금융 서비스 확산 등도 주요 트렌드로 자리 잡을 것입니다. 예스론은 이러한 변화에 발맞춰 리스크 관리 강화, 디지털 채널 확대, 맞춤형 상품 개발 등에 집중해야 할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '2금융권 토지담보대출 상품별 금리와 신청조건 비교',
   'link': 'https://bluebeat.tistory.com/1162',
   'description': '<b>핀테크</b> 기업과의 협력을 통해 비대면 대출 프로세스를 강화하고, 고객 편의성을 높이는 전략도... 향후 2금융권 토지담보대출 시장은 <b>핀테크</b> 기술과의 융합을 통해 더욱 발전할 것으로 예상됩니다. 빅데이터... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '럭시라이프 사기 만남어플 접근 교묘한 감정 유도형 수법 분석... ',
   'link': 'https://blog.naver.com/friry96847/224103348630',
   'description': "(사칭) '#팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ",
   'bloggername': 'friry96847님의 블로그',
   'bloggerlink': 'blog.naver.com/friry96847',
   'postdate': '20251209'},
  {'title': '올원 뱅크 이체 한도 상향 신청 및 하루 송금한도 조정 방법',
   'link': 'https://sibauchi.tistory.com/1189',
   'description': '비대면 금융 서비스 이용 증가, <b>핀테크</b> 기업의 혁신적인 서비스 출시, 그리고 전통 금융기관의 디지털 전환 가속화가 주요 동인이었습니다. 특히, 모바일 뱅킹 앱의 역할이 더욱 중요해지면서 사용자 경험(UX)... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '원화 스테이블코인 인터넷뱅킹 카뱅 토뱅 케뱅 특허 선점... ',
   'link': 'https://blog.naver.com/true_insight/224103423673',
   'description': '✔ 국내 <b>핀테크</b> 성장 전략 결제·송금·자산관리 등 서비스 중심의 인터넷은행이 경쟁력을 가질 수 있습니다. ✔ 금융시장 혁신 필요 CBDC의 공공 중심 구조보다, 민간 중심 구조가 시장 속도에 적합하다는... ',
   'bloggername': '조금씩 풀어보는 서랍 속 지식꾸러미',
   'bloggerlink': 'blog.naver.com/true_insight',
   'postdate': '20251209'},
  {'title': '15억 달러 규모의 촉매제가 방금 SoFi 주식을 뒤흔들었습니다.... ',
   'link': 'https://blog.naver.com/banryeojasan/224103485795',
   'description': '<b>핀테크</b> 주식은 빠른 성장, 수익성 있는 단위 경제성, 확장적인 상품군을 결합할 수 있는 기업에... SOFI 주식 소개 2011년에 설립된 SoFi는 원스톱 모바일 뱅킹 앱을 기반으로 한 <b>핀테크</b> 회사입니다. 약 1,260만... ',
   'bloggername': '반려자산키우기',
   'bloggerlink': 'blog.naver.com/banryeojasan',
   'postdate': '20251209'},
  {'title': '박민수 핑거 부회장 “디지털자산 혁명 속 활로 찾는 나침반... ',
   'link': 'https://blog.naver.com/c9book/224103486052',
   'description': "대한민국 <b>핀테크</b> 산업을 이끄는 리더! 박민수 핑거 부회장님의 따끈따끈한 인터뷰 소식을 전해드립니다. 혼란스러운 디지털 자산 시장, 투기가 아닌 '방향'을 묻다 12월 8일, 전자신문은 인터뷰 기사를 통해... ",
   'bloggername': '클라우드나인 출판사',
   'bloggerlink': 'blog.naver.com/c9book',
   'postdate': '20251209'},
  {'title': '스타저축은행 하이론 재대출 조건과 승인 후기 확인하기',
   'link': 'https://lefthusband.tistory.com/1525',
   'description': '향후 1-2년 동안 하이론 시장은 금리 인상 추세 둔화, 정부의 가계 부채 관리 강화, <b>핀테크</b> 기술 발전... <b>핀테크</b> 기술 발전은 온라인 대출 플랫폼 활성화, 신용 평가 모델 고도화 등을 통해 하이론 시장의 효율성을... ',
   'bloggername': 'fgwaff',
   'bloggerlink': 'https://lefthusband.tistory.com/',
   'postdate': '20251209'},
  {'title': 'AI 기술 특허등록, 알고리즘도 지식재산으로 보호해야',
   'link': 'https://blog.naver.com/hongbin1814/224103482558',
   'description': '특히 SaaS·<b>핀테크</b>·이커머스 기업들은 AI가 경쟁력의 핵심이라 AI 기술 특허등록을 먼저 확보하는 전략을 사용하고 있습니다. 최근에는 네이버, 카카오, 구글, 메타뿐만 아니라 중소기업과 스타트업도 AI 기술을... ',
   'bloggername': '[유레카 지식재산보호소]',
   'bloggerlink': 'blog.naver.com/hongbin1814',
   'postdate': '20251209'},
  {'title': '피플펀드 대환대출 신청절차와 조건 알아보기',
   'link': 'https://think-tank.tistory.com/887',
   'description': '하지만, 정부의 정책 지원과 <b>핀테크</b> 기업들의 혁신적인 서비스 출시를 통해 새로운 기회가 창출될 수도 있습니다. 주요 기업들은 금리 경쟁력을 확보하기 위해 노력하는 한편, 빅데이터 분석을 통해 개인별... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '유안타증권 사기 사칭 주식리딩방 유형 실제처럼 보이지만 속은... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103104776',
   'description': '전혀다르다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '주식회사 트립퍼 사기 사칭 믿음을 악용한 허위 예약 결제... ',
   'link': 'https://blog.naver.com/ickkoju2/224103143300',
   'description': '실체 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/ickkoju2',
   'postdate': '20251209'},
  {'title': '쿠팡 회원탈퇴 방법 개선, PC 아닌 앱에서도 탈퇴 가능',
   'link': 'https://blog.naver.com/dndus01/224103474912',
   'description': '최근에는 토스, 네이버페이, 카카오페이, 삼성페이 등 <b>핀테크</b> 앱에서 클릭하면 2원, 3원 수익금 주는 배너 탓에 하루에도 여러 번씩 들락달락 거리기까지도 한다.  개선 전 쿠팡 회원 탈퇴 과정 절차 그리고... ',
   'bloggername': '램프천사의 별별여행',
   'bloggerlink': 'blog.naver.com/dndus01',
   'postdate': '20251209'},
  {'title': '용인시 처인구 남사읍 개인회생 채무조정 인가율 높은 이유',
   'link': 'https://dramapd.tistory.com/1096',
   'description': '강화 <b>핀테크</b> 기업: 데이터 기반 맞춤형 채무조정 컨설팅 서비스 개발 소규모 법률사무소: 지역 밀착형 서비스 제공 및 가격 경쟁력 강화 소비자 행동 변화: 온라인 정보 검색 및 비교 분석 활발 무료 상담 및 견적... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '해외취업 시 알아두면 좋은 저렴한 해외 송금',
   'link': 'https://blog.naver.com/wirebarley_official/224103472498',
   'description': '이런 상황에서 은행 대신 한국에서 해외로, 해외에서 한국으로 해외 송금을 할 수 있는 <b>핀테크</b> 어플을 소개해드릴게요. 와이어바알리 소개 와이어바알리는 글로벌 <b>핀테크</b> 해외송금 기업으로 한국, 미국, 캐나다... ',
   'bloggername': 'WireBarley, 글로벌 해외송금',
   'bloggerlink': 'blog.naver.com/wirebarley_official',
   'postdate': '20251209'},
  {'title': '&quot;비트코인과 CFTC 파일럿 프로그램: 디지털 자산 담보의... ',
   'link': 'https://blog.naver.com/star_handful/224103472014',
   'description': '파일럿 프로그램의 시장 반응 CFTC의 이번 발표는 암호화폐 및 <b>핀테크</b> 업계에서 긍정적인 반응을 얻고 있습니다. 코인베이스의 법률 책임자 폴 그레왈(Paul Grewal)은 이번 조치가 스테이블코인과 디지털... ',
   'bloggername': '진진돌이 파이넨스',
   'bloggerlink': 'blog.naver.com/star_handful',
   'postdate': '20251209'},
  {'title': '[에이플러스에셋] 알아보기',
   'link': 'https://blog.naver.com/star_of_self/224103471437',
   'description': '경쟁사인 인카금융서비스가 <b>핀테크</b> 플랫폼과의 제휴 등을 통해 디지털 접점을 넓히려는 시도를... 이러한 풍부한 현금 보유고는 향후 유망한 <b>핀테크</b> 기업 인수나 주주 환원(배당) 확대를 위한 재원으로... ',
   'bloggername': 'star_of_self님의 블로그',
   'bloggerlink': 'blog.naver.com/star_of_self',
   'postdate': '20251209'},
  {'title': '간추린 금융경제 뉴스제목모음 ⌚1209화13h',
   'link': 'https://blog.naver.com/misokir/224103465030',
   'description': '⏰ 1000원부터 1만원까지…롯데손보, 스키보험 ‘시즌권’ 플랜 신설 ⏰ 11兆 팔린 방카슈랑스, 내년 더 기대된다 ⏰ 1·2세대 실손보험, 받은 보험금 빼고 되팔 수 있다 ⏰ 1470원 환율에 국민연금 움직인다... ',
   'bloggername': '미키르의 분석',
   'bloggerlink': 'blog.naver.com/misokir',
   'postdate': '20251209'},
  {'title': '오늘의핫뉴스3. 불당시티와 함께 알아볼까요 유사품주의하세요... ',
   'link': 'https://blog.naver.com/kmj041217/224103464040',
   'description': '외환 제도 개편으로 증권사·카드사·<b>핀테크</b> 등을 통한 무증빙 해외 송금 한도가 연 10만 달러(약 1억 3천만 원)까지 확대되는 등 외환 관리 효율화 및 국민 편의가 제고됩니다. 3. 건설업 부진 장기화 및 소비... ',
   'bloggername': '불당시티부동산 천안시 불당동 부동산전문가',
   'bloggerlink': 'blog.naver.com/kmj041217',
   'postdate': '20251209'},
  {'title': '예가람저축은행 논스톱 대출, 24시간 즉시 입금 가능한 상품 정리',
   'link': 'https://ilovefamily.tistory.com/565',
   'description': '특히, <b>핀테크</b> 기업들의 활약으로 인해 비대면 대출 시장이 급성장했으며, 소비자들은 더욱 빠르고 편리한 대출 서비스를 요구하고 있습니다. 향후 1-2년 동안 금리 변동성이 지속될 것으로 예상되며, 개인 신용... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': 'IBM이 Confluent를 사려는 이유 3가지 (AI·데이터 스트림... ',
   'link': 'https://blog.naver.com/aaajung_/224103460914',
   'description': '2) Apache Kafka 기반 우버, 메타, <b>핀테크</b> 기업들이 다 쓰는 실시간 데이터 기술의 핵심이 바로... (AI, <b>핀테크</b>, 우버, 넷플릭스, 메타 등에서 모두 사용) ✔️왜 IBM이 Confluent를 사고 싶어하는가? AI... ',
   'bloggername': '성장기록',
   'bloggerlink': 'blog.naver.com/aaajung_',
   'postdate': '20251209'},
  {'title': '국민은행 KB국민ONE대출 자격조건과 금리 총정리',
   'link': 'https://think-tank.tistory.com/869',
   'description': '<b>핀테크</b> 기업들의 금융 시장 진출 확대는 경쟁 심화를 가져오겠지만, 동시에 새로운 대출 상품 및 서비스 개발을 촉진할 것입니다. 주요 은행들은 디지털 전환 가속화, 맞춤형 상품 개발, 그리고 리스크 관리... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '소셜버즈리포트 251209-“오늘 미국 커뮤니티, 결국 CETX에... ',
   'link': 'https://blog.naver.com/make_second_salary/224103458906',
   'description': 'TGL 1대20 리버스 스플릿 이후, 2026년 매출 가이던스를 세 배로 올리면서 “<b>핀테크</b>·디지털자산 성장 스토리 + 가격 튕김” 조합으로 커뮤니티의 레이더에 들어온 상황. DFLI·CISO·SLS 테마는... ',
   'bloggername': '재테크요원의 Second Salary HQ',
   'bloggerlink': 'blog.naver.com/make_second_salary',
   'postdate': '20251209'},
  {'title': '고양 파주 신용불량자 개인회생 카드단말기, 매출 묶일 걱정... ',
   'link': 'https://blog.naver.com/hanbitict/224103457625',
   'description': '&quot;어떻게 카드 결제 대금을 바로 주나요?&quot; &quot;이거 불법 아닌가요?&quot; 결론부터 말씀드리면, 100% 합법적인 <b>핀테크</b> 기술입니다. 저희 한빛정보통신이 제공하는 코페이 서비스는 PG사(전자결제대행사)가 자금력을... ',
   'bloggername': '한빛정보통신 코페이의 블로그',
   'bloggerlink': 'blog.naver.com/hanbitict',
   'postdate': '20251209'},

In [14]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

user_id = os.getenv("")
user_secret = os.getenv("")
url = "https://openapi.naver.com/v1/search/blog"
keyword = "핀테크"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200

{'lastBuildDate': 'Tue, 09 Dec 2025 14:56:05 +0900',
 'total': 489927,
 'start': 1,
 'display': 100,
 'items': [{'title': '정부지원통합대출 대상자와 신청절차 알아보기',
   'link': 'https://lefthusband.tistory.com/1561',
   'description': '셋째, <b>핀테크</b> 기업과의 협업 이 더욱 강화될 것입니다. 금융기관들은 <b>핀테크</b> 기업의 혁신적인 기술과 서비스를 활용하여 고객 경험을 개선하고, 새로운 상품을 개발할 것입니다. 주요 기업들은 이러한 시장... ',
   'bloggername': 'fgwaff',
   'bloggerlink': 'https://lefthusband.tistory.com/',
   'postdate': '20251209'},
  {'title': '[2026 트렌드] 저비용으로 MZ세대 만족도를 높이는 2026년... ',
   'link': 'https://blog.naver.com/paywatch_kr/224103583600',
   'description': '복지로, <b>핀테크</b>로 간편하게. 페이워치 Paywatch 기업은 도입비 없이 인사 담당자는 채용 걱정 없이 임직원은 월급, 복지 고민 없게! 일하는 모든 사람을 위한 회사복지 솔루션 글로벌 <b>핀테크</b> 기업, 페이워치와... ',
   'bloggername': '금융을 복지처럼, 핀테크로 간편하게. 페이워치',
   'bloggerlink': 'blog.naver.com/paywatch_kr',
   'postdate': '20251209'},
  {'title': '✅ [두산에너빌리티(034020)] 1년 +270% 찍은 ‘K-원전·에너지... ',
   'link': 'https://blog.naver.com/salem04/224103580556',
   'description': 'HWH 같은 <b>핀테크</b>/컨설팅 복합 모델이 아니라, “에너지 인프라·원전·플랜트 하드웨어+EPC”를 동시에 영위하는 초대형 인프라 플레이어로 보는 것이 맞습니다. 4️⃣ 재무와 밸류에이션 – 이미... ',
   'bloggername': '경제 자유를 위한 공부',
   'bloggerlink': 'blog.naver.com/salem04',
   'postdate': '20251209'},
  {'title': '주담대 최저금리, 한도 계산기 및 갈아타기 조건 알아봄',
   'link': 'https://blog.naver.com/shiner2004/224103578897',
   'description': '여러 은행의 주담대 상품을 비교해 주는 <b>핀테크</b> 앱을 활용하는 것도 좋은 방법임. 또 은행연합회 소비자포털에 가면 은행별 가계 대출금리도 살펴볼 수 있으니 살펴보면 더 도움될 거임. 은행에 직접 가기 전... ',
   'bloggername': '직장인 10억 프로젝트',
   'bloggerlink': 'blog.naver.com/shiner2004',
   'postdate': '20251209'},
  {'title': '아이마켓코리아 &amp; 코리아센터 2026년 이커머스 주가 분석... ',
   'link': 'https://blog.naver.com/kimengg/224103515517',
   'description': '또한, NAVER(+2.1%)가 자회사 네이버파이낸셜과 두나무 간 포괄적 주식교환 기대감으로 상승했던 사례처럼, 이커머스 플랫폼과 <b>핀테크</b>의 융합은 코리아센터에게도 새로운 성장 동력이 될 수 있습니다. 외국인... ',
   'bloggername': '하이디',
   'bloggerlink': 'blog.naver.com/kimengg',
   'postdate': '20251209'},
  {'title': '화성시 남양읍 개인회생 연체중 채무조정 신청 시 유의사항',
   'link': 'https://dramapd.tistory.com/1085',
   'description': '주요 금융기관들은 리스크 관리 강화와 함께 채무조정 지원 프로그램을 확대하는 전략을 펼치고 있으며, <b>핀테크</b> 기업들은 AI 기반의 맞춤형 채무 컨설팅 서비스를 제공하며 시장 경쟁에 참여하고 있습니다.... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '재테크 앱으로 하루 10분, 월 5만 원 가능할까? 캐시워크부터... ',
   'link': 'https://blog.naver.com/econonow/224103566880',
   'description': '무엇보다 국내 대표 <b>핀테크</b> 앱이라는 점에서 신뢰도도 높아 안심하고 사용할 수 있습니다. 광고 시청이나 간단한 미션 완료로 포인트를 주는 리워드앱도 인기인데요, 대표적으로는 오베이(설문조사), 캐시닥... ',
   'bloggername': '머니픽',
   'bloggerlink': 'blog.naver.com/econonow',
   'postdate': '20251209'},
  {'title': '휴대폰 대출 간편 신청 방법과 신용 영향 분석',
   'link': 'https://ilovefamily.tistory.com/524',
   'description': '특히, <b>핀테크</b> 기술의 발전은 은행 방문 없이, 서류 제출 없이 스마트폰 앱 하나로 대출을 받을 수 있는... 그리고 <b>핀테크</b> 기업들의 활약이라는 삼박자가 맞물리면서 역동적인 변화를 겪었습니다. 특히, 고금리... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': '티웨이브 티웨이브주식 티웨이브장외주식 정보 공유 +++',
   'link': 'https://blog.naver.com/seveneswsh/224103561542',
   'description': '살린 <b>핀테크</b> 서비스를 기본 모델로 하여, 고객이 직접 이율, 기간, 금액 등을 원하는 대로 설정하여... 소셜 <b>핀테크</b> 스타트업 입니다.우리는 사용자 간의 신용을 기반으로 한 소셜 네트워크(Social Network)를... ',
   'bloggername': '장외주식 알고해야 성투한다~!!',
   'bloggerlink': 'blog.naver.com/seveneswsh',
   'postdate': '20251209'},
  {'title': '우리카드 올인원대출 금리와 재대출 조건 총정리',
   'link': 'https://bluebeat.tistory.com/1126',
   'description': '📊 우리카드 올인원대출: 금리 &amp; 재대출 조건, <b>핀테크</b> 전문가의 심층 분석 급변하는 금융 시장 속에서... 향후 1-2년 동안은 고금리 기조가 유지될 가능성이 높으며, <b>핀테크</b> 기업들의 혁신적인 대출 상품 출시... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 사칭 인스x 코인플랫폼 조심해야... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103107061',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '다올저축은행 비상금대출 소득증빙 가능자 필수 확인사항',
   'link': 'https://bluebeat.tistory.com/1166',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 금리 인상은 대출 수요 감소로 이어졌으며, 소득 증빙 조건 강화는 대출 문턱을 높였습니다. <b>핀테크</b> 기업들은 혁신적인 기술과... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '캐노피, 대교그룹 고객사 유치…대기업 레퍼런스 확대',
   'link': 'https://blog.naver.com/hellocanopy/224103543493',
   'description': 'HR &amp; <b>핀테크</b> 업계에서 주목받는 흐름입니다. 근로자 복지 &amp; 만족도 증가 일한 즉시 정산이 가능해... 있는 <b>핀테크</b> 기반 금융 인프라로서 성장하고자 합니다. 또한, 국내에서의 사업 안정화 이후 해외, 특히... ',
   'bloggername': 'Canopy',
   'bloggerlink': 'blog.naver.com/hellocanopy',
   'postdate': '20251209'},
  {'title': '케이뱅크 신용대출 비대면 신청방법과 후기',
   'link': 'https://sibauchi.tistory.com/1143',
   'description': '주요 시중은행들은 리스크 관리를 강화하며 대출 심사를 더욱 깐깐하게 진행하고 있으며, <b>핀테크</b>... <b>핀테크</b> 기업들은 AI 기반 신용평가 모델을 고도화하여 리스크 관리 능력을 강화하고, 맞춤형 대출 상품을... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '제주 탐나는전 학생증 체크카드 소득공제, 대학생에게 얼마나... ',
   'link': 'https://blog.naver.com/moneycultreview/224103310590',
   'description': '✔✔️ 지갑을 가볍게 하고 싶은 학생 ✔✔️ 지역화폐 혜택을 받고 싶은 학생 ✔✔️ 제주 지역 소상공인을 응원하고 싶은 학생 ✔✔️ 알뜰하게 생활비를 아끼고 싶은 학생 ✔✔️ 최신 <b>핀테크</b> 서비스를... ',
   'bloggername': '머니컬 리뷰',
   'bloggerlink': 'blog.naver.com/moneycultreview',
   'postdate': '20251209'},
  {'title': '하나은행 징검다리론 한도와 금리 신청조건 총정리',
   'link': 'https://sibauchi.tistory.com/1130',
   'description': '또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로... 또한, <b>핀테크</b> 기업과의 협력을 통해 온라인 플랫폼을 강화하고, 사용자 편의성을 높이는 방향으로 발전할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '태강대부 대출 절차와 이용 시 유의사항 총정리',
   'link': 'https://bluebeat.tistory.com/1123',
   'description': '강화, <b>핀테크</b> 기업의 성장 등 다양한 요인으로 인해 큰 변화를 겪었습니다. 특히, 고금리 시대에... 감소, <b>핀테크</b> 플랫폼을 통한 비대면 대출 증가 향후 1-2년 예상 트렌드: 금리 안정화 또는 소폭 하락 가능성... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 사칭 김민우프로 주식리딩방... ',
   'link': 'https://blog.naver.com/dgzuxzgby/224103130537',
   'description': '합니다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/dgzuxzgby',
   'postdate': '20251209'},
  {'title': 'Lounge ONE 사기 라운지원 김민우프로 사칭 리딩방 주의해야... ',
   'link': 'https://blog.naver.com/weirdo36529/224103453600',
   'description': '이유 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/weirdo36529',
   'postdate': '20251209'},
  {'title': '코인베이스의 인도 시장 재진입',
   'link': 'https://blog.naver.com/investor76/224103524083',
   'description': '사용이 빠르게 증가하고 있어 암호화폐 채택률이 매우 높을 잠재력을 가지고 있다 대규모 투자 유치 : 벤처 캐피털과 사모 펀드 자금은 인도의 <b>핀테크</b> 및 블록체인 스타트업에 지속적으로 투자하고 있다.',
   'bloggername': '시장 앞에 겸손',
   'bloggerlink': 'blog.naver.com/investor76',
   'postdate': '20251209'},
  {'title': 'KB국민카드 면접, 최종 합격하는 면접관 1:1 맞춤형 컨설팅',
   'link': 'https://blog.naver.com/05g8wbolei/224103520654',
   'description': "KB국민카드는 <b>핀테크</b>, 플랫폼 비즈니스 등 변화의 최전선에 있는 기업입니다. 과거의 은행 면접 준비하듯 '성실함'만 강조해서는 절대 합격할 수 없습니다. 오늘 이 글에서는 왜 죽어라 준비한 답변이... ",
   'bloggername': '⭐꿀팁정보⭐',
   'bloggerlink': 'blog.naver.com/05g8wbolei',
   'postdate': '20251209'},
  {'title': '싱가포르상표, 국제상표 병행이 답인 이유 4가지',
   'link': 'https://blog.naver.com/fastdesign/224103519162',
   'description': '또한 싱가포르상표는 브랜드 전략 중심의 기업(IT·헬스케어·F&amp;B·<b>핀테크</b>)이 많이 선택하기 때문에 국제상표와 자연스럽게 연결되는 시장 구조를 가지고 있습니다. 기율특허법인이 싱가포르상표 전략에 강한... ',
   'bloggername': '특허전략 파트너 기율',
   'bloggerlink': 'blog.naver.com/fastdesign',
   'postdate': '20251209'},
  {'title': 'worldswap-beams 사기 인스타그램 접근 코인사칭 플랫폼 출금... ',
   'link': 'https://blog.naver.com/nntto12976/224102883521',
   'description': '(사칭) #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '⚠️데이 법률사무소 피해금 회수 전담팀⚠️',
   'bloggerlink': 'blog.naver.com/nntto12976',
   'postdate': '20251209'},
  {'title': '가짜 3.3 계약 &quot;피해 근로자&quot;를 위한 대응 절차 A to Z',
   'link': 'https://blog.naver.com/nomu4rang/224102260423',
   'description': '7~11) - 서울시 <b>핀테크</b>랩 인사노무 멘토 (2021.1~ ) - 산업인력공단 현장학습근로자 실태조사 점검위원 (미용업, 제조업) (2021.1~ ) - 한국장애인개발원 외부 노무전문위원 (2021.10~ ) - 코레일네트웍스 채용심사위원... ',
   'bloggername': '노동법률 전문가 박놈사',
   'bloggerlink': 'blog.naver.com/nomu4rang',
   'postdate': '20251209'},
  {'title': '해외송금 수수료 걱정 끝 건당수수료의 장점',
   'link': 'https://blog.naver.com/e9payday/224101631252',
   'description': '최근 몇 년간 은행·<b>핀테크</b> 업체들이 이체 수수료를 대폭 낮추면서 국내 송금은 생활 속 기본... 하지만 최근에는 비용 구조를 단순화한 <b>핀테크</b> 기반 해외송금 서비스가 등장하며 상황이 크게 달라졌습니다.... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9payday',
   'postdate': '20251209'},
  {'title': 'BM특허권, 단순한 영업방법은 절대 등록받을 수 없습니다',
   'link': 'https://blog.naver.com/tm_maker/224082560561',
   'description': '즉, 온라인 플랫폼, 앱 서비스, <b>핀테크</b> 솔루션 등이 대표적인 BM특허의 형태입니다. 성공적인 권리 확보를 위한 전체 비용은 일반적으로 전문가 수수료와 관납료를 포함하여 출원 시 180~200만 원, 등록 시 180~200만... ',
   'bloggername': '마스터 상표',
   'bloggerlink': 'blog.naver.com/tm_maker',
   'postdate': '20251209'},
  {'title': '해외송금 10만달러까지 증빙없이 초간편 시대',
   'link': 'https://blog.naver.com/money-study-/224103512826',
   'description': '은행을 이용하면 연간 10만 달러까지 가능했지만, 증권사나 <b>핀테크</b> 업체 같은 비은행권을 이용할 경우... #해외송금 #무증빙송금 #금융규제 #외환거래 #<b>핀테크</b> #AI반도체 #SK하이닉스 #삼성전자 #네이버 #카카오',
   'bloggername': '생활경제 톡톡',
   'bloggerlink': 'blog.naver.com/money-study-',
   'postdate': '20251209'},
  {'title': '무직자 소액대출 승인 잘되는 비대면 상품 정리',
   'link': 'https://bluebeat.tistory.com/1165',
   'description': '여러 <b>핀테크</b> 기업들이 시장에 진입하면서 경쟁은 더욱 치열해졌습니다. 정부는 가계 부채 증가를... 대부업체, <b>핀테크</b> 플랫폼 등으로 구분됩니다. 각 기관마다 대출 조건, 금리, 심사 기준 등이 다르므로, 꼼꼼히... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '중국이 미국을 제치고 AI 1인자가 될 수 있을까? 중국의 AI... ',
   'link': 'https://blog.naver.com/eunji_1104/224103506268',
   'description': '범위 <b>핀테크</b>, 클라우드, 전자상거래, IT 하드웨어 등 전반적인 홍콩 상장 빅테크 시가총액 상위 10개 종목에 집중 종목 비중 특정 종목의 비중을 10% 이내로 제한 (분산 효과) 상위 10개 종목에 균등하게... ',
   'bloggername': 'As within, So without',
   'bloggerlink': 'blog.naver.com/eunji_1104',
   'postdate': '20251209'},
  {'title': '&quot;국민연금이 빚낸다?&quot; 정부가 고환율 해결 위해 내놓은 방안',
   'link': 'https://blog.naver.com/pandainvest/224103501079',
   'description': '해외송금 <b>핀테크</b> 업체 : 건당 5000달러 / 연 5만 달러 문제는 각 업체별로 한도가 따로 적용된다는 점입니다. 여러 업체를 돌면 100만 달러 이상도 증빙 없이 해외 송금 가능했던 구조인데, 이는 은행·<b>핀테크</b> 간... ',
   'bloggername': '판다엄마 재테크기록',
   'bloggerlink': 'blog.naver.com/pandainvest',
   'postdate': '20251209'},
  {'title': '토스뱅크 아기펭귄 이거하면 5천원 준다는데 진짜?',
   'link': 'https://blog.naver.com/soo2402/224103496754',
   'description': '다른 <b>핀테크</b> 경쟁사들과 차별화되는 토스뱅크만의 강점으로 작용하고 있는 거죠. 게다가 5천원이라는 보상 자체도 부담스럽지 않으면서도, 사람들의 참여를 유도하기에 충분한 매력적인 금액이고요. 하지만... ',
   'bloggername': 'soo....',
   'bloggerlink': 'blog.naver.com/soo2402',
   'postdate': '20251209'},
  {'title': '예가람저축은행 예스론 추가대출 승인 잘되는 방법',
   'link': 'https://sibauchi.tistory.com/1176',
   'description': '<b>핀테크</b> 기업과의 경쟁 심화, 디지털 금융 서비스 확산 등도 주요 트렌드로 자리 잡을 것입니다. 예스론은 이러한 변화에 발맞춰 리스크 관리 강화, 디지털 채널 확대, 맞춤형 상품 개발 등에 집중해야 할... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '2금융권 토지담보대출 상품별 금리와 신청조건 비교',
   'link': 'https://bluebeat.tistory.com/1162',
   'description': '<b>핀테크</b> 기업과의 협력을 통해 비대면 대출 프로세스를 강화하고, 고객 편의성을 높이는 전략도... 향후 2금융권 토지담보대출 시장은 <b>핀테크</b> 기술과의 융합을 통해 더욱 발전할 것으로 예상됩니다. 빅데이터... ',
   'bloggername': 'bluebeat',
   'bloggerlink': 'https://bluebeat.tistory.com/',
   'postdate': '20251209'},
  {'title': '원화 스테이블코인 인터넷뱅킹 카뱅 토뱅 케뱅 특허 선점... ',
   'link': 'https://blog.naver.com/true_insight/224103423673',
   'description': '✔ 국내 <b>핀테크</b> 성장 전략 결제·송금·자산관리 등 서비스 중심의 인터넷은행이 경쟁력을 가질 수 있습니다. ✔ 금융시장 혁신 필요 CBDC의 공공 중심 구조보다, 민간 중심 구조가 시장 속도에 적합하다는... ',
   'bloggername': '조금씩 풀어보는 서랍 속 지식꾸러미',
   'bloggerlink': 'blog.naver.com/true_insight',
   'postdate': '20251209'},
  {'title': '올원 뱅크 이체 한도 상향 신청 및 하루 송금한도 조정 방법',
   'link': 'https://sibauchi.tistory.com/1189',
   'description': '비대면 금융 서비스 이용 증가, <b>핀테크</b> 기업의 혁신적인 서비스 출시, 그리고 전통 금융기관의 디지털 전환 가속화가 주요 동인이었습니다. 특히, 모바일 뱅킹 앱의 역할이 더욱 중요해지면서 사용자 경험(UX)... ',
   'bloggername': "Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평",
   'bloggerlink': 'https://sibauchi.tistory.com/',
   'postdate': '20251209'},
  {'title': '럭시라이프 사기 만남어플 접근 교묘한 감정 유도형 수법 분석... ',
   'link': 'https://blog.naver.com/friry96847/224103348630',
   'description': "(사칭) '#팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ",
   'bloggername': 'friry96847님의 블로그',
   'bloggerlink': 'blog.naver.com/friry96847',
   'postdate': '20251209'},
  {'title': '15억 달러 규모의 촉매제가 방금 SoFi 주식을 뒤흔들었습니다.... ',
   'link': 'https://blog.naver.com/banryeojasan/224103485795',
   'description': '<b>핀테크</b> 주식은 빠른 성장, 수익성 있는 단위 경제성, 확장적인 상품군을 결합할 수 있는 기업에... SOFI 주식 소개 2011년에 설립된 SoFi는 원스톱 모바일 뱅킹 앱을 기반으로 한 <b>핀테크</b> 회사입니다. 약 1,260만... ',
   'bloggername': '반려자산키우기',
   'bloggerlink': 'blog.naver.com/banryeojasan',
   'postdate': '20251209'},
  {'title': '박민수 핑거 부회장 “디지털자산 혁명 속 활로 찾는 나침반... ',
   'link': 'https://blog.naver.com/c9book/224103486052',
   'description': "대한민국 <b>핀테크</b> 산업을 이끄는 리더! 박민수 핑거 부회장님의 따끈따끈한 인터뷰 소식을 전해드립니다. 혼란스러운 디지털 자산 시장, 투기가 아닌 '방향'을 묻다 12월 8일, 전자신문은 인터뷰 기사를 통해... ",
   'bloggername': '클라우드나인 출판사',
   'bloggerlink': 'blog.naver.com/c9book',
   'postdate': '20251209'},
  {'title': '스타저축은행 하이론 재대출 조건과 승인 후기 확인하기',
   'link': 'https://lefthusband.tistory.com/1525',
   'description': '향후 1-2년 동안 하이론 시장은 금리 인상 추세 둔화, 정부의 가계 부채 관리 강화, <b>핀테크</b> 기술 발전... <b>핀테크</b> 기술 발전은 온라인 대출 플랫폼 활성화, 신용 평가 모델 고도화 등을 통해 하이론 시장의 효율성을... ',
   'bloggername': 'fgwaff',
   'bloggerlink': 'https://lefthusband.tistory.com/',
   'postdate': '20251209'},
  {'title': 'AI 기술 특허등록, 알고리즘도 지식재산으로 보호해야',
   'link': 'https://blog.naver.com/hongbin1814/224103482558',
   'description': '특히 SaaS·<b>핀테크</b>·이커머스 기업들은 AI가 경쟁력의 핵심이라 AI 기술 특허등록을 먼저 확보하는 전략을 사용하고 있습니다. 최근에는 네이버, 카카오, 구글, 메타뿐만 아니라 중소기업과 스타트업도 AI 기술을... ',
   'bloggername': '[유레카 지식재산보호소]',
   'bloggerlink': 'blog.naver.com/hongbin1814',
   'postdate': '20251209'},
  {'title': '피플펀드 대환대출 신청절차와 조건 알아보기',
   'link': 'https://think-tank.tistory.com/887',
   'description': '하지만, 정부의 정책 지원과 <b>핀테크</b> 기업들의 혁신적인 서비스 출시를 통해 새로운 기회가 창출될 수도 있습니다. 주요 기업들은 금리 경쟁력을 확보하기 위해 노력하는 한편, 빅데이터 분석을 통해 개인별... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '주식회사 트립퍼 사기 사칭 믿음을 악용한 허위 예약 결제... ',
   'link': 'https://blog.naver.com/ickkoju2/224103143300',
   'description': '실체 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': '데이법률사무소',
   'bloggerlink': 'blog.naver.com/ickkoju2',
   'postdate': '20251209'},
  {'title': '유안타증권 사기 사칭 주식리딩방 유형 실제처럼 보이지만 속은... ',
   'link': 'https://blog.naver.com/mgreatmaild18/224103104776',
   'description': '전혀다르다 #팀미션사기 #주식사기 #코인사기 #스캠사기 #사칭사기 #공모주사기 #투자사기 #투자사기대응법 #투자사기법적대응 #사기피해회복 #사기피해대응 #사기피해전문변호사 #<b>핀테크</b>전문 #사기피해전문... ',
   'bloggername': 'daylaw',
   'bloggerlink': 'blog.naver.com/mgreatmaild18',
   'postdate': '20251209'},
  {'title': '쿠팡 회원탈퇴 방법 개선, PC 아닌 앱에서도 탈퇴 가능',
   'link': 'https://blog.naver.com/dndus01/224103474912',
   'description': '최근에는 토스, 네이버페이, 카카오페이, 삼성페이 등 <b>핀테크</b> 앱에서 클릭하면 2원, 3원 수익금 주는 배너 탓에 하루에도 여러 번씩 들락달락 거리기까지도 한다.  개선 전 쿠팡 회원 탈퇴 과정 절차 그리고... ',
   'bloggername': '램프천사의 별별여행',
   'bloggerlink': 'blog.naver.com/dndus01',
   'postdate': '20251209'},
  {'title': '용인시 처인구 남사읍 개인회생 채무조정 인가율 높은 이유',
   'link': 'https://dramapd.tistory.com/1096',
   'description': '강화 <b>핀테크</b> 기업: 데이터 기반 맞춤형 채무조정 컨설팅 서비스 개발 소규모 법률사무소: 지역 밀착형 서비스 제공 및 가격 경쟁력 강화 소비자 행동 변화: 온라인 정보 검색 및 비교 분석 활발 무료 상담 및 견적... ',
   'bloggername': '니은과 리을',
   'bloggerlink': 'https://dramapd.tistory.com/',
   'postdate': '20251209'},
  {'title': '해외취업 시 알아두면 좋은 저렴한 해외 송금',
   'link': 'https://blog.naver.com/wirebarley_official/224103472498',
   'description': '이런 상황에서 은행 대신 한국에서 해외로, 해외에서 한국으로 해외 송금을 할 수 있는 <b>핀테크</b> 어플을 소개해드릴게요. 와이어바알리 소개 와이어바알리는 글로벌 <b>핀테크</b> 해외송금 기업으로 한국, 미국, 캐나다... ',
   'bloggername': 'WireBarley, 글로벌 해외송금',
   'bloggerlink': 'blog.naver.com/wirebarley_official',
   'postdate': '20251209'},
  {'title': '&quot;비트코인과 CFTC 파일럿 프로그램: 디지털 자산 담보의... ',
   'link': 'https://blog.naver.com/star_handful/224103472014',
   'description': '파일럿 프로그램의 시장 반응 CFTC의 이번 발표는 암호화폐 및 <b>핀테크</b> 업계에서 긍정적인 반응을 얻고 있습니다. 코인베이스의 법률 책임자 폴 그레왈(Paul Grewal)은 이번 조치가 스테이블코인과 디지털... ',
   'bloggername': '진진돌이 파이넨스',
   'bloggerlink': 'blog.naver.com/star_handful',
   'postdate': '20251209'},
  {'title': '[에이플러스에셋] 알아보기',
   'link': 'https://blog.naver.com/star_of_self/224103471437',
   'description': '경쟁사인 인카금융서비스가 <b>핀테크</b> 플랫폼과의 제휴 등을 통해 디지털 접점을 넓히려는 시도를... 이러한 풍부한 현금 보유고는 향후 유망한 <b>핀테크</b> 기업 인수나 주주 환원(배당) 확대를 위한 재원으로... ',
   'bloggername': 'star_of_self님의 블로그',
   'bloggerlink': 'blog.naver.com/star_of_self',
   'postdate': '20251209'},
  {'title': '간추린 금융경제 뉴스제목모음 ⌚1209화13h',
   'link': 'https://blog.naver.com/misokir/224103465030',
   'description': '⏰ 1000원부터 1만원까지…롯데손보, 스키보험 ‘시즌권’ 플랜 신설 ⏰ 11兆 팔린 방카슈랑스, 내년 더 기대된다 ⏰ 1·2세대 실손보험, 받은 보험금 빼고 되팔 수 있다 ⏰ 1470원 환율에 국민연금 움직인다... ',
   'bloggername': '미키르의 분석',
   'bloggerlink': 'blog.naver.com/misokir',
   'postdate': '20251209'},
  {'title': '오늘의핫뉴스3. 불당시티와 함께 알아볼까요 유사품주의하세요... ',
   'link': 'https://blog.naver.com/kmj041217/224103464040',
   'description': '외환 제도 개편으로 증권사·카드사·<b>핀테크</b> 등을 통한 무증빙 해외 송금 한도가 연 10만 달러(약 1억 3천만 원)까지 확대되는 등 외환 관리 효율화 및 국민 편의가 제고됩니다. 3. 건설업 부진 장기화 및 소비... ',
   'bloggername': '불당시티부동산 천안시 불당동 부동산전문가',
   'bloggerlink': 'blog.naver.com/kmj041217',
   'postdate': '20251209'},
  {'title': '예가람저축은행 논스톱 대출, 24시간 즉시 입금 가능한 상품 정리',
   'link': 'https://ilovefamily.tistory.com/565',
   'description': '특히, <b>핀테크</b> 기업들의 활약으로 인해 비대면 대출 시장이 급성장했으며, 소비자들은 더욱 빠르고 편리한 대출 서비스를 요구하고 있습니다. 향후 1-2년 동안 금리 변동성이 지속될 것으로 예상되며, 개인 신용... ',
   'bloggername': '과거,현재,미래, 그리고 나.',
   'bloggerlink': 'https://ilovefamily.tistory.com/',
   'postdate': '20251209'},
  {'title': 'IBM이 Confluent를 사려는 이유 3가지 (AI·데이터 스트림... ',
   'link': 'https://blog.naver.com/aaajung_/224103460914',
   'description': '2) Apache Kafka 기반 우버, 메타, <b>핀테크</b> 기업들이 다 쓰는 실시간 데이터 기술의 핵심이 바로... (AI, <b>핀테크</b>, 우버, 넷플릭스, 메타 등에서 모두 사용) ✔️왜 IBM이 Confluent를 사고 싶어하는가? AI... ',
   'bloggername': '성장기록',
   'bloggerlink': 'blog.naver.com/aaajung_',
   'postdate': '20251209'},
  {'title': '국민은행 KB국민ONE대출 자격조건과 금리 총정리',
   'link': 'https://think-tank.tistory.com/869',
   'description': '<b>핀테크</b> 기업들의 금융 시장 진출 확대는 경쟁 심화를 가져오겠지만, 동시에 새로운 대출 상품 및 서비스 개발을 촉진할 것입니다. 주요 은행들은 디지털 전환 가속화, 맞춤형 상품 개발, 그리고 리스크 관리... ',
   'bloggername': 'think-tank.tistory.com',
   'bloggerlink': 'https://think-tank.tistory.com/',
   'postdate': '20251209'},
  {'title': '소셜버즈리포트 251209-“오늘 미국 커뮤니티, 결국 CETX에... ',
   'link': 'https://blog.naver.com/make_second_salary/224103458906',
   'description': 'TGL 1대20 리버스 스플릿 이후, 2026년 매출 가이던스를 세 배로 올리면서 “<b>핀테크</b>·디지털자산 성장 스토리 + 가격 튕김” 조합으로 커뮤니티의 레이더에 들어온 상황. DFLI·CISO·SLS 테마는... ',
   'bloggername': '재테크요원의 Second Salary HQ',
   'bloggerlink': 'blog.naver.com/make_second_salary',
   'postdate': '20251209'},
  {'title': '고양 파주 신용불량자 개인회생 카드단말기, 매출 묶일 걱정... ',

# 네이버 API에서 수집가능한 최대 자료 모두 수집하기

In [15]:
start_num = 1
for i in range(1, 11):
    if start_num < 901:
        start_num += 100
        print(start_num)
    elif start_num >= 901:
        start_num += 99
        print(start_num)

101
201
301
401
501
601
701
801
901
1000

In [16]:
# while 문을 이용해야 함
page = 1
if response['total'] // 100 > 10:
    page = 10
else:
    page = response['total'] // 100 + 1

In [17]:
99 // 100 +1

1

# for문을 이용해 최대한 수집하기
* naver api는 start 파라미터 최대값 1000
* 1페이지당 100개씩 수집시 최대 11페이지까지 수집 가능

In [18]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

num = 1
all_data = []
for page in range(11):
    user_id = os.getenv("")
    user_secret = os.getenv("")
    url = "https://openapi.naver.com/v1/search/blog"
    keyword = "핀테크"
    payload = dict(query=keyword, display=100, start=num, sort="date")
    headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response = r.json()
    all_data.append(pd.DataFrame(response['items']))    
    
    if num < 901:
        num += 100
    elif num >= 901:
        num += 99
    print(num)

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
200
101
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=date
200
201
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=date
200
301
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=date
200
401
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=date
200
501
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=date
200
601
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=date
200
701
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=date
200
801
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=date
200
901
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=date
200
1000
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=date
200
1099

In [19]:
final_result = pd.concat(all_data)
final_result

,title,link,description,bloggername,bloggerlink,postdate
0,이커머스 주식 관련주 테마주 대장주 수혜주 정리,https://blog.naver.com/aselstan/224103589923,"세틀뱅크: 간편결제, 가상계좌 등 <b>핀테크</b> 솔루션을 제공하여 온라인 결제...",아셀,blog.naver.com/aselstan,20251209
1,"️ “내년 비트코인, 사상 최고가 노리지만…8만4000달러...",https://blog.naver.com/merteous/224103589619,상장사·채굴주·거래소·<b>핀테크</b>·반도체(특히 AI·고성능 GPU) 등 관련...,AI가 말아주는 경제뉴스,blog.naver.com/merteous,20251209
2,국민은행 현금서비스 이용조건과 상환방법 안내,https://sibauchi.tistory.com/1149,"인상, <b>핀테크</b> 기업의 성장, 그리고 소비 심리 변화 등 다양한 요인으로...",Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평,https://sibauchi.tistory.com/,20251209
3,정부지원통합대출 대상자와 신청절차 알아보기,https://lefthusband.tistory.com/1561,"셋째, <b>핀테크</b> 기업과의 협업 이 더욱 강화될 것입니다. 금융기관들은 <...",fgwaff,https://lefthusband.tistory.com/,20251209
4,[2026 트렌드] 저비용으로 MZ세대 만족도를 높이는 2026년...,https://blog.naver.com/paywatch_kr/224103583600,"복지로, <b>핀테크</b>로 간편하게. 페이워치 Paywatch 기업은 도입비 없...","금융을 복지처럼, 핀테크로 간편하게. 페이워치",blog.naver.com/paywatch_kr,20251209
...,...,...,...,...,...,...
95,청년취업 사관학교 2025 AI 인재 페스티벌 오픈 캠퍼스(동작)...,https://blog.naver.com/mom4u5119/224100262130,네이버 카카오 라인 쿠팡 배달의 민족 당근 마켓 토스 국내 주요 it <b>핀테크<...,또 하면 되지 - 은설 작가의 라이팅 챌린지,blog.naver.com/mom4u5119,20251206
96,네이버의 급여 원천,https://blog.naver.com/bonami514/224100259145,"<b>핀테크</b>: 네이버페이, 금융 서비스에서 발생하는 거래 수수료. 콘텐츠(I...","맑고 푸른, Good life & my life",blog.naver.com/bonami514,20251206
97,2025년 12월 06일 13:30 - 기술적 분석 - 미국 전체 종목...,https://blog.naver.com/thdtjsdn1/224100250210,이 블로그는 다크테마로 되있지만 네이버 블로그 모바일이 다크모드를 지원안합니다. P...,thdtjsdn.blogspot.com,blog.naver.com/thdtjsdn1,20251206
98,네이버 역대 의장,https://blog.naver.com/bonami514/224100243379,향후 네이버는 AI·클라우드·<b>핀테크</b>·커머스·글로벌 확장을 핵심 전략으로...,"맑고 푸른, Good life & my life",blog.naver.com/bonami514,20251206
99,금리인하요구권 자동 신청 서비스: 복잡한 절차 없이 간편하게...,https://blog.naver.com/soulnet77/224100241477,2025년 현재 다양한 <b>핀테크</b> 기업과 은행들이 자동 신청 서비스를 제공...,하나비,blog.naver.com/soulnet77,20251206

# while문을 이용해서 수집페이지까지 자동화 하기

In [20]:
from dotenv import load_dotenv
import os
load_dotenv(dotenv_path="./data/.env_naver")
import requests

total_page = 1
page = 1
num = 1

all_data = []
while page <= total_page:
    user_id = os.getenv("")
    user_secret = os.getenv("")
    url = f"https://openapi.naver.com/v1/search/blog"
    keyword = "핀테크"
    payload = dict(query=keyword, display=100, start=num, sort="date")
    headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
#     print(r.status_code)
    response = r.json()
    all_data.append(response['items'])

    # 전체 페이지 계산
    if response['total'] // 100 > 11:
        total_page = 11
    else:
        total_page = response['total'] // 100 + 1
        
    # page 증가
    page += 1
    
    #num이 1000되도록 
    if num < 901:
        num += 100
    elif num >= 901:
        num += 99

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=date
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=date

In [21]:
len(all_data)

11

In [22]:
result = {}
for page in all_data:
    for item in page:
        for key, value in item.items():
            if key in ["title", "description"]:
                result.setdefault(key, []).append(text_clean(value))
            else:
                result.setdefault(key, []).append(value)
final_df = pd.DataFrame(result)
final_df

,title,link,description,bloggername,bloggerlink,postdate
0,이커머스 주식 관련주 테마주 대장주 수혜주 정리,https://blog.naver.com/aselstan/224103589923,세틀뱅크 간편결제 가상계좌 등 핀테크 솔루션을 제공하여 온라인 결제 인프라를 지원합...,아셀,blog.naver.com/aselstan,20251209
1,내년 비트코인 사상 최고가 노리지만 8만4000달러,https://blog.naver.com/merteous/224103589619,상장사 채굴주 거래소 핀테크 반도체 특히 AI 고성능 GPU 등 관련 섹터 주가에 ...,AI가 말아주는 경제뉴스,blog.naver.com/merteous,20251209
2,국민은행 현금서비스 이용조건과 상환방법 안내,https://sibauchi.tistory.com/1149,인상 핀테크 기업의 성장 그리고 소비 심리 변화 등 다양한 요인으로 인해 큰 변화를...,Falconer's Teatime :: 이제는 말하고 말겠다-라멘토 비평,https://sibauchi.tistory.com/,20251209
3,정부지원통합대출 대상자와 신청절차 알아보기,https://lefthusband.tistory.com/1561,셋째 핀테크 기업과의 협업 이 더욱 강화될 것입니다 금융기관들은 핀테크 기업의 혁신...,fgwaff,https://lefthusband.tistory.com/,20251209
4,2026 트렌드 저비용으로 MZ세대 만족도를 높이는 2026년,https://blog.naver.com/paywatch_kr/224103583600,복지로 핀테크로 간편하게 페이워치 Paywatch 기업은 도입비 없이 인사 담당자는...,"금융을 복지처럼, 핀테크로 간편하게. 페이워치",blog.naver.com/paywatch_kr,20251209
...,...,...,...,...,...,...
1095,청년취업 사관학교 2025 AI 인재 페스티벌 오픈 캠퍼스 동작,https://blog.naver.com/mom4u5119/224100262130,네이버 카카오 라인 쿠팡 배달의 민족 당근 마켓 토스 국내 주요 it 핀테크 유통기...,또 하면 되지 - 은설 작가의 라이팅 챌린지,blog.naver.com/mom4u5119,20251206
1096,네이버의 급여 원천,https://blog.naver.com/bonami514/224100259145,핀테크 네이버페이 금융 서비스에서 발생하는 거래 수수료 콘텐츠 IP 네이버 웹툰 웹...,"맑고 푸른, Good life & my life",blog.naver.com/bonami514,20251206
1097,2025년 12월 06일 13 30 기술적 분석 미국 전체 종목,https://blog.naver.com/thdtjsdn1/224100250210,이 블로그는 다크테마로 되있지만 네이버 블로그 모바일이 다크모드를 지원안합니다 PC...,thdtjsdn.blogspot.com,blog.naver.com/thdtjsdn1,20251206
1098,네이버 역대 의장,https://blog.naver.com/bonami514/224100243379,향후 네이버는 AI 클라우드 핀테크 커머스 글로벌 확장을 핵심 전략으로 삼아 생활 ...,"맑고 푸른, Good life & my life",blog.naver.com/bonami514,20251206
1099,금리인하요구권 자동 신청 서비스 복잡한 절차 없이 간편하게,https://blog.naver.com/soulnet77/224100241477,2025년 현재 다양한 핀테크 기업과 은행들이 자동 신청 서비스를 제공하고 있으며 ...,하나비,blog.naver.com/soulnet77,20251206

In [23]:
final_df.to_csv("./data/네이버api수집1100개.csv", index=False, encoding="utf-8-sig")