# 네이버 API에서 키워드를 입력받아 블로그, 뉴스, 책 데이터 수집
# 각각의 카테고리별로 csv 파일로 저장
# 파일명에는 수집날짜가 자동으로 파일명에 포함되도록
# 반복되는 부분은 함수를 이용해서 중복 줄이기

In [4]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os
import re
from datetime import datetime
load_dotenv(dotenv_path="./data/.env_db")

True

In [6]:
def text_clean(text):
    # html 태그를 없애는 정규표현식
    result = re.sub(r"</?[^>]+>", "", text)
    # 한글, 영문, 숫자 외의 모든 문자 제거 후 공백으로 변환
    result = re.sub(r"[^가-힣a-zA-Z0-9]", " ", result)
    result = result.replace("  ", " ").replace("  ", " ").replace("  ", " ")
    return result

# 1.페이지 수집

In [7]:
keyword = input("검색할 키워드를 입력해 주세요")

검색할 키워드를 입력해 주세요부동산

In [8]:
user_id = os.getenv("")
user_secret = os.getenv("")
url = f"https://openapi.naver.com/v1/search/news"
payload = dict(query=keyword, display=100, start=1, sort="date")
headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
r = requests.get(url, params=payload, headers=headers)
response = r.json()

total_page = response['total'] // 100 + 1

result = {}
for item in response['items']:
#     print(item)
    for key, value in item.items():
        if key in ['title', 'description']:
            result.setdefault(key, []).append(text_clean(value))
        else:
            result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

,title,originallink,link,description,pubDate
0,기획 수출 7000억달러 시대 쏠림 착시 심화,http://www.m-i.kr/news/articleView.html?idxno=...,http://www.m-i.kr/news/articleView.html?idxno=...,일반기계 8 6 468억달러 는 최대 시장인 미국의 관세 정책 불확실성과 중국의 부...,"Tue, 09 Dec 2025 15:04:00 +0900"
1,빈민vs부민 갈라치기 한 토허제 강남3구 용산 연일 불기둥,https://biz.newdaily.co.kr/site/data/html/2025...,https://biz.newdaily.co.kr/site/data/html/2025...,반면 10 15부동산대책 으로 서울 아파트 거래량은 큰폭으로 줄었다 서울부동산정보광...,"Tue, 09 Dec 2025 15:04:00 +0900"
2,내 집 사고 싶어도 못사게 한 대책 서울시 10 15 정책 때렸다 부,https://biz.heraldcorp.com/article/10632869?re...,https://n.news.naver.com/mnews/article/016/000...,약 20분 분량으로 서울시는 시민들에게 부동산 정책을 제대로 알리기 위해 영상을 기...,"Tue, 09 Dec 2025 15:02:00 +0900"
3,AI 버블 맞아 이것 잘 살펴야 헤지펀드 대부 의 경고,http://www.edaily.co.kr/news/newspath.asp?news...,https://n.news.naver.com/mnews/article/018/000...,또한 그는 벤처캐피털 사모펀드 상업용 부동산 등 저금리 시대에 빌린 돈이 고금리 압...,"Tue, 09 Dec 2025 15:02:00 +0900"
4,편의성 희소성 직통 역세권 인기 평균 매매가격 48 상승,http://www.enewstoday.co.kr/news/articleView.h...,http://www.enewstoday.co.kr/news/articleView.h...,9일 부동산인포가 서울 시내 직통 역세권 아파트 19곳을 조사한 결과에 따르면 최근...,"Tue, 09 Dec 2025 15:01:00 +0900"
...,...,...,...,...,...
94,금투협회장 선거 목전 서유석 이현승 황성엽 3색 리더십 향방은,https://www.meconomynews.com/news/articleView....,https://www.meconomynews.com/news/articleView....,서 후보는 quot 증권사 자산운용사 부동산신탁사 선물사 등을 모두 아우르는 폭넓은...,"Tue, 09 Dec 2025 14:26:00 +0900"
95,서울역 남산 서리풀 등 마지막 요지 통째 중국 자본 품으로,https://realty.chosun.com/site/data/html_dir/2...,https://realty.chosun.com/site/data/html_dir/2...,중국계 사모펀드 힐하우스 국내 부동산 운용사 1위 이지스를 삼켰다 서울역 남산 서리...,"Tue, 09 Dec 2025 14:26:00 +0900"
96,흥국생명 이지스자산운용 매각 불공정 법적 대응 예고,https://biz.chosun.com/stock/finance/2025/12/0...,https://n.news.naver.com/mnews/article/366/000...,흥국생명은 이번 힐하우스로의 우선협상대상자 선정은 한국의 부동산 투자 플랫폼을 노린...,"Tue, 09 Dec 2025 14:25:00 +0900"
97,윤종영 경기도의원 지방세 줄고 국고보조금이 더 많아 경기도 재정,https://www.seoul.co.kr/news/publicnews/local_...,https://n.news.naver.com/mnews/article/081/000...,이에 대해 허승범 경기도 기획조정실장은 올해를 기준으로 처음 역전된 상황임을 인정하...,"Tue, 09 Dec 2025 14:25:00 +0900"
98,외국인 투기거래 근절 국토부 거래신고 자금출처 따진다,https://news.tf.co.kr/read/economy/2270547.htm,https://n.news.naver.com/mnews/article/629/000...,국토부는 이같은 내용을 담은 부동산거래신고법 시행령 이 공포됐다고 9일 밝혔다 시행...,"Tue, 09 Dec 2025 14:25:00 +0900"

# 전체페이지 수집

In [10]:
keyword = input("검색할 키워드를 입력해 주세요")


blog_data = []
news_data = []
book_data = []

category = ['blog', 'news', 'book']

for cate in category:
    page_num = 1
    total_page = 1
    start_num = 1
    while page_num <= total_page:
        print(cate, page_num, total_page, end="\r")
        user_id = os.getenv("")
        user_secret = os.getenv("")
        url = f"https://openapi.naver.com/v1/search/{cate}"
        payload = dict(query=keyword, display=100, start=start_num, sort="date")
        headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
        r = requests.get(url, params=payload, headers=headers)
        response = r.json()

        result = {}
        for item in response['items']:

            for key, value in item.items():
                if key in ['title', 'description']:
                    result.setdefault(key, []).append(text_clean(value))
                else:
                    result.setdefault(key, []).append(value)
        
        if cate == 'blog':
            blog_data.append(pd.DataFrame(result))
        elif cate == 'news':
            news_data.append(pd.DataFrame(result))
        elif cate == 'book':
            book_data.append(pd.DataFrame(result))

        total_page = response['total'] // 100 + 1
        if total_page > 11:
            total_page = 11
        else:
            total_page = response['total'] // 100 + 1


        page_num += 1

        if start_num < 901:
            start_num += 100
        elif start_num > 900:
            start_num += 99

            
            
blog_df = pd.concat(blog_data)
news_df = pd.concat(news_data)
book_df = pd.concat(book_data)

blog_df = blog_df.reset_index(drop=True)
news_df = news_df.reset_index(drop=True)
book_df = book_df.reset_index(drop=True)

display(blog_df)
display(news_df)
display(book_df)

검색할 키워드를 입력해 주세요부동산

,title,link,description,bloggername,bloggerlink,postdate
0,복현동 복현태왕아너스 아파트 106동 108 84 매매 12 15층,https://blog.naver.com/lh6973/224103601180,해당포스팅은 네이버부동산에서 소유자가 검증된 확인매물 입니다 2565969304 복...,대구 북구 영광부동산공인중개사사무소,blog.naver.com/lh6973,20251209
1,남구 야음동 소개글 올립니다,https://blog.naver.com/zzangbujang/224103600731,일잘하는 부동산 원하시는 매물 원스톱 브리핑 중개 가능 언제든지 편하게 문의 전화...,따스한장소공인중개사사무소,blog.naver.com/zzangbujang,20251209
2,창원주택매매 5억 신월동 반지하 20평 N 24658,https://blog.naver.com/landtop10/224103600485,미래부동산중개사무소 소재지 창원시 의창구 봉곡동 31 2번지 1층 고려동물병원 옆 ...,미래부동산,blog.naver.com/landtop10,20251209
3,Ripple Wallet 리플월렛 리플코인 사기,https://blog.naver.com/alymppdyi/224103599929,법률사무소담덕 담덕법률사무소 강남변호사 강남법률사무소 선릉법률사무소 역삼법률사무소...,법률사무소 담덕,blog.naver.com/alymppdyi,20251209
4,코너건물 약 50평 임대 보증금1억에 525만원 l 단골부동산,https://blog.naver.com/dangoal365/224103599911,연신내 상가전문 단골부동산 하경목 공인중개사 안녕하세요 은평구 상가전문 단골부동산 ...,연신내 단골부동산,blog.naver.com/dangoal365,20251209
...,...,...,...,...,...,...
1095,청주 금니 치금 매입 최고가 가격으로 팔기,https://blog.naver.com/kwanghak29/224103508926,현재 본업은 부동산 사무실을 운영 중인 공인중개사입니다 금거래소 창업을 생각하고 있...,공장★창고 달인부동산,blog.naver.com/kwanghak29,20251209
1096,다가구 전세 세대분리 청약 영향까지 꼼꼼하게 알아보기,https://blog.naver.com/cityload3/224103508432,왜 부동산에서는 이런 내용을 미리 말해주지 않을까 실제로 많은 분들이 전세 계약을 ...,야옹이의 경제스토리,blog.naver.com/cityload3,20251209
1097,대전 유성구 신성동 원룸 방과 거실이 분리되어 있고,https://blog.naver.com/jukelee1101/224103508347,대표 손현길 042 862 2862 010 대전광역시 유성구 신성로 84번길 51...,jukelee1101님의블로그,blog.naver.com/jukelee1101,20251209
1098,토지거래허가구역이냐 조정대상지역이냐,https://blog.naver.com/sunghohkr/224103508455,토지거래허가구역이냐 조정대상지역이냐 부동산이 토지거래허가구역이냐 조정대상지역이냐에 ...,세무사 공인중개사 행정사,blog.naver.com/sunghohkr,20251209
1099,마산명도소송변호사 점유 회복 대응은,https://blog.naver.com/mhja243/224103508786,마산명도소송변호사 점유 회복 대응은 명도소송은 부동산 임대차 관계에서 가장 빈번하게...,함께하는 법률공부,blog.naver.com/mhja243,20251209

,title,originallink,link,description,pubDate
0,기획 수출 7000억달러 시대 쏠림 착시 심화,http://www.m-i.kr/news/articleView.html?idxno=...,http://www.m-i.kr/news/articleView.html?idxno=...,일반기계 8 6 468억달러 는 최대 시장인 미국의 관세 정책 불확실성과 중국의 부...,"Tue, 09 Dec 2025 15:04:00 +0900"
1,나이스신용평가 내년 건설업 업황 부진 전망,https://www.cstimes.com/news/articleView.html?...,https://www.cstimes.com/news/articleView.html?...,이러한 흐름은 착공 및 기성 감소 고물가 등에 따라 내년에도 이어질 것이라며 quo...,"Tue, 09 Dec 2025 15:04:00 +0900"
2,BNK금융 빈대인 2기 체제 돌입 실적 개선 해양금융 비전 제시,https://www.cstimes.com/news/articleView.html?...,https://www.cstimes.com/news/articleView.html?...,취임 직후 발생한 경남은행 3000억원대 횡령 사건 이후 BNK금융은 부동산 프로젝...,"Tue, 09 Dec 2025 15:04:00 +0900"
3,국립공주대 부동산학과 2025 진로 토크 콘서트 개최,http://www.veritas-a.com/news/articleView.html...,http://www.veritas-a.com/news/articleView.html...,국립공주대 총장 임경호 부동산학과 학과장 심희철 는 산업과학대학 산업과학관에서 재학...,"Tue, 09 Dec 2025 15:04:00 +0900"
4,빈민vs부민 갈라치기 한 토허제 강남3구 용산 연일 불기둥,https://biz.newdaily.co.kr/site/data/html/2025...,https://biz.newdaily.co.kr/site/data/html/2025...,반면 10 15부동산대책 으로 서울 아파트 거래량은 큰폭으로 줄었다 서울부동산정보광...,"Tue, 09 Dec 2025 15:04:00 +0900"
...,...,...,...,...,...
1095,재산 1조설 김재중 마흔 앞두고 결국 일 냈다 국민효자 에서 선한,https://www.tenasia.co.kr/article/2025120811834,https://m.entertain.naver.com/article/312/0000...,당시 김재중은 quot 차도 부동산도 있었던 거를 팔고 다른 것도 사고 이랬을 건데...,"Mon, 08 Dec 2025 20:32:00 +0900"
1096,미리보는 이데일리 신문 발레파킹 분리수거 현실 된 AI발 주거 혁신,http://www.edaily.co.kr/news/newspath.asp?news...,https://n.news.naver.com/mnews/article/018/000...,부동산 GTX 집값상승 효과 입증돼 2개 노선 교차 청량리 억소리 내년 SOC 예...,"Mon, 08 Dec 2025 20:31:00 +0900"
1097,헬로 이슈토크 경기도지사 경기도교육감 선거 누가 나올까,http://news.lghellovision.net/news/articleView...,http://news.lghellovision.net/news/articleView...,이재필 기자 우선 부동산 이슈를 꼽을 수 있을 것 같습니다 제8회 전국동시지방선거...,"Mon, 08 Dec 2025 20:30:00 +0900"
1098,SC이슈 사짜 냄새 났다 박나래 의혹에 기안84 과거 발언도 재조,https://www.sportschosun.com/entertainment/202...,https://m.entertain.naver.com/article/076/0004...,박나래는 지난 3일 전 매니저 2인으로부터 부동산 가압류 신청과 함께 직장 내 괴롭...,"Mon, 08 Dec 2025 20:30:00 +0900"
1099,엄마야 집값 진짜 오르는 기가 부산 울산 경남권에 무슨 일이,https://www.segye.com/newsView/20251208502850?...,https://n.news.naver.com/mnews/article/022/000...,침체한 지방 부동산 시장이 바닥을 확인한 것 아니냐는 전망이 나온다 다만 부산을 비...,"Mon, 08 Dec 2025 20:29:00 +0900"

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,2026 박문각 법무사 1차 김기찬 부동산등기법 기본서 법무사 법원승진 등기사무직 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_579440...,김기찬,54000,박문각,20260120,9791175195196,2026 법무사 부동산등기법 기본서 제5판 교재를 통해 공부하는 수험생들의 법무사 ...
1,2026 경록 주택관리사 기본서 1차 회계원리,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_565726...,경록 주택관리사 교재편찬위원회^신한부동산연구소,37800,경록,20260105,9791194560326,경록 100 합격프로젝트 1 경록 교재 시리즈의 특징 1 경록교재는 누구나 신문을 ...
2,2026 경록 주택관리사 1차 회차별 기출문제,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_565726...,경록 주택관리사 교재편찬위원회^신한부동산연구소,26100,경록,20260105,9791194560296,경록 또 100 적중 노리는 주택관리사 기출문제집 출간되었다 첫째 이 책의 출판 형...
3,2026 경록 주택관리사 기본서 1차 민법,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_565726...,경록 주택관리사 교재편찬위원회^신한부동산연구소,39600,경록,20260105,9791194560340,경록 100 합격프로젝트 1 경록교재 시리즈의 특징 1 경록교재는 누구나 신문을 읽...
4,2026 경록 주택관리사 기본서 1차 공동주택시설개론,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_565726...,경록 주택관리사 교재편찬위원회^신한부동산연구소,38700,경록,20260105,9791194560333,경록 100 합격프로젝트 1 경록교재 시리즈의 특징 1 경록교재는 누구나 신문을 읽...
...,...,...,...,...,...,...,...,...,...
1095,부동산공법 입문,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_462591...,장형진,17100,문운당,20240228,9791156926979,이 책은 부동산공법에 대해 다룬 도서입니다 기초적이고 전반적인 내용을 학습할 수 있...
1096,압구정 재건축의 현황과 미래가치,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_462842...,김용식^김재희,22500,좋은땅,20240228,9791138827997,압구정 재건축 아파트는 글로벌 서울의 정점을 찍을 수 있는 프로젝트이다 서울의 최고...
1097,신방수 세무사의 가족 간 부동산 거래 세무 가이드북,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_459568...,신방수,20700,두드림미디어,20240226,9791193210468,국내 최초 가족 부동산 세무 가이드북 매매 상속 증여 법인 선택과 절세 포인트 최근...
1098,제4판 부동산 신탁 실무 해설,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_463617...,장중식,24500,부크크(bookk),20240226,9791141073725,부동산 신탁업에 종사하는 실무자들을 위한 실무해설서입니다
1099,부동산 프롭테크,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_458256...,문상덕,23400,법문사,20240225,9788918914725,부동산 프롭테크 전반에 대한 이해를 돕고 국내 프롭테크의 전망과 발전을 위한 통찰력...

In [11]:
news_data

[                                                title  \
 0                           기획 수출 7000억달러 시대 쏠림 착시 심화
 1                             나이스신용평가 내년 건설업 업황 부진 전망
 2                 BNK금융 빈대인 2기 체제 돌입 실적 개선 해양금융 비전 제시
 3                       국립공주대 부동산학과 2025 진로 토크 콘서트 개최
 4                    빈민vs부민 갈라치기 한 토허제 강남3구 용산 연일 불기둥
 ..                                                ...
 95   quot 와인잔 던지고 24시간 대기 quot 박나래 갑질 폭로 매니저에 합의서 6장
 96         한은 GDP 대비 가계신용 비중 10 P 생산부문 옮기면 성장률 0 2 P
 97                   서울역 남산 서리풀 등 마지막 요지 통째 중국 자본 품으로
 98                       대통령의 주택시장 항복선언 서민들에게 축복이 되려면
 99                 금투협회장 선거 목전 서유석 이현승 황성엽 3색 리더십 향방은

                                          originallink  \
 0   http://www.m-i.kr/news/articleView.html?idxno=...
 1   https://www.cstimes.com/news/articleView.html?...
 2   https://www.cstimes.com/news/articleView.html?...
 3   http://www.veritas-a.com/news/articleView.html...
 4   https://biz.newdaily.co.kr/site/data/html/2025...
 ..                                                ...
 95  https://radio.ytn.co.kr/program/?f=2&id=106275...
 96  https://biz.heraldcorp.com/article/10632814?re...
 97  https://realty.chosun.com/site/data/html_dir/2...
 98  https://realty.chosun.com/site/data/html_dir/2...
 99  https://www.meconomynews.com/news/articleView....

                                                  link  \
 0   http://www.m-i.kr/news/articleView.html?idxno=...
 1   https://www.cstimes.com/news/articleView.html?...
 2   https://www.cstimes.com/news/articleView.html?...
 3   http://www.veritas-a.com/news/articleView.html...
 4   https://biz.newdaily.co.kr/site/data/html/2025...
 ..                                                ...
 95  https://radio.ytn.co.kr/program/?f=2&id=106275...
 96  https://n.news.naver.com/mnews/article/016/000...
 97  https://realty.chosun.com/site/data/html_dir/2...
 98  https://realty.chosun.com/site/data/html_dir/2...
 99  https://www.meconomynews.com/news/articleView....

                                           description  \
 0   일반기계 8 6 468억달러 는 최대 시장인 미국의 관세 정책 불확실성과 중국의 부...
 1   이러한 흐름은 착공 및 기성 감소 고물가 등에 따라 내년에도 이어질 것이라며 quo...
 2   취임 직후 발생한 경남은행 3000억원대 횡령 사건 이후 BNK금융은 부동산 프로젝...
 3   국립공주대 총장 임경호 부동산학과 학과장 심희철 는 산업과학대학 산업과학관에서 재학...
 4   반면 10 15부동산대책 으로 서울 아파트 거래량은 큰폭으로 줄었다 서울부동산정보광...
 ..                                                ...
 95  부동산 가압류 신청을 넣었는데 왜냐하면 본인들이 받을 돈이 있다 손해배상 청구 소송...
 96   헤럴드DB 헤럴드경제 김벼리 기자 정부가 생산적 금융 대전환 에 속도를 내는 가운...
 97  중국계 사모펀드 힐하우스 국내 부동산 운용사 1위 이지스를 삼켰다 서울역 남산 서리...
 98  역사에서 교훈을 얻지 못하면 미래가 없다는 말은 부동산 정책에도 적용된다 정권이 끝...
 99  서 후보는 quot 증권사 자산운용사 부동산신탁사 선물사 등을 모두 아우르는 폭넓은...

                             pubDate
 0   Tue, 09 Dec 2025 15:04:00 +0900
 1   Tue, 09 Dec 2025 15:04:00 +0900
 2   Tue, 09 Dec 2025 15:04:00 +0900
 3   Tue, 09 Dec 2025 15:04:00 +0900
 4   Tue, 09 Dec 2025 15:04:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 14:30:00 +0900
 96  Tue, 09 Dec 2025 14:29:00 +0900
 97  Tue, 09 Dec 2025 14:26:00 +0900
 98  Tue, 09 Dec 2025 14:26:00 +0900
 99  Tue, 09 Dec 2025 14:26:00 +0900

 [100 rows x 5 columns],
                                             title  \
 0                   직통 역세권 아파트가 시세 이끈다 5년간 48 껑충
 1                    흥국생명 이지스자산운용 매각 불공정 법적 대응 예고
 2            윤종영 경기도의원 지방세 줄고 국고보조금이 더 많아 경기도 재정
 3                  태광그룹의 몽니 흥국생명 이지스 인수전 법적 대응 예고
 4                   외국인 투기거래 근절 국토부 거래신고 자금출처 따진다
 ..                                            ...
 95                외국인도 내년 2월부터 토허구역 주택매입시 자금출처 추적
 96      오세훈 quot 부동산 공급 국토부와 절반 가량 논의 진전 정비사업 허들
 97  신상진 성남시장 quot 대장동 범죄로 취득된 단돈 1원까지도 꼭 환수 quot
 98                      한국금융학회 한국은행 공동 정책 심포지엄 개최
 99     흥국생명 quot 이지스자산운용 매각 절차 불공정 법적 대응 검토 quot

                                          originallink  \
 0      https://news.tf.co.kr/read/economy/2270520.htm
 1   https://biz.chosun.com/stock/finance/2025/12/0...
 2   https://www.seoul.co.kr/news/publicnews/local_...
 3   https://www.bloter.net/news/articleView.html?i...
 4      https://news.tf.co.kr/read/economy/2270547.htm
 ..                                                ...
 95  https://biz.newdaily.co.kr/site/data/html/2025...
 96      http://www.fnnews.com/news/202512082223192282
 97  https://www.incheonilbo.com/news/articleView.h...
 98   https://m.skyedaily.com/news_view.html?ID=292667
 99  http://www.biztribune.co.kr/news/articleView.h...

                                                  link  \
 0   https://n.news.naver.com/mnews/article/629/000...
 1   https://n.news.naver.com/mnews/article/366/000...
 2   https://n.news.naver.com/mnews/article/081/000...
 3   https://n.news.naver.com/mnews/article/293/000...
 4   https://n.news.naver.com/mnews/article/629/000...
 ..                                                ...
 95  https://biz.newdaily.co.kr/site/data/html/2025...
 96  https://n.news.naver.com/mnews/article/014/000...
 97  https://www.incheonilbo.com/news/articleView.h...
 98   https://m.skyedaily.com/news_view.html?ID=292667
 99  http://www.biztribune.co.kr/news/articleView.h...

                                           description  \
 0   9일 부동산시장 분석업체 부동산인포가 서울 시내 직통 역세권 아파트 19곳을 조사한...
 1   흥국생명은 이번 힐하우스로의 우선협상대상자 선정은 한국의 부동산 투자 플랫폼을 노린...
 2   이에 대해 허승범 경기도 기획조정실장은 올해를 기준으로 처음 역전된 상황임을 인정하...
 3   국내 1위 부동산 자산운용사인 이지스자산운용의 매각 우선협상대상자로 글로벌 사모펀드...
 4   국토부는 이같은 내용을 담은 부동산거래신고법 시행령 이 공포됐다고 9일 밝혔다 시행...
 ..                                                ...
 95  국토교통부는 9일 이같은 내용을 담은 부동산거래신고법 시행령 을 공포 내년 2월10...
 96  오세훈 서울시장이 quot 부동산 공급 부지를 두고 국토부가 제시한 부지 중에 한 ...
 97  가압류 경과에 대해서는 quot 시는 대장동 일당의 재산을 동결하기 위해 부동산처분...
 98  황인도 한국은행 경제연구원 금융통화연구실장은 신용이 가계 부동산 등이 아닌 기업 등...
 99  또한 quot 이번 결정은 국내 부동산 운용사 매각을 둘러싼 시장 신뢰를 심각하게 ...

                             pubDate
 0   Tue, 09 Dec 2025 14:25:00 +0900
 1   Tue, 09 Dec 2025 14:25:00 +0900
 2   Tue, 09 Dec 2025 14:25:00 +0900
 3   Tue, 09 Dec 2025 14:25:00 +0900
 4   Tue, 09 Dec 2025 14:25:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 13:48:00 +0900
 96  Tue, 09 Dec 2025 13:47:00 +0900
 97  Tue, 09 Dec 2025 13:46:00 +0900
 98  Tue, 09 Dec 2025 13:46:00 +0900
 99  Tue, 09 Dec 2025 13:46:00 +0900

 [100 rows x 5 columns],
                                          title  \
 0      제2의 팔란티어 빅베어AI UAE에 중동 사무실 설립 스타게이트 낙수
 1   흥국생명 quot 이지스자산운용 매각 절차 불공정 법적 대응 검토 quot
 2             수도권 아파트 분양 전망 2년 만에 최저 인천 미분양 증가
 3              전국 지식산업센터 역대급 한파 3분기 거래 5년래 최저치
 4            정부 외국인 부동산 투기 차단 총력 거래신고 의무 대폭 강화
 ..                                         ...
 95    에스엘플랫폼 SLP 더 보타닉 세운명동의 운영 성공으로 호텔 사업의 위
 96       데일리토픽 가계부채 vs 주택공급 정부 정책 엇박자에 재건축 재개
 97             나신평 내년 건설업 부진 전망에 신용등급 방향성 부정적
 98               성남시 대장동 민간업자 가압류 7건 담보 제공 명령
 99         오후 뉴스브리핑 3 71억 BTC 피싱 사기 공모자 유죄 인정

                                          originallink  \
 0   https://www.theguru.co.kr/news/article.html?no...
 1   http://www.biztribune.co.kr/news/articleView.h...
 2      https://www.ajunews.com/view/20251209132502899
 3   https://www.sisajournal.com/news/articleView.h...
 4   https://www.ebn.co.kr/news/articleView.html?id...
 ..                                                ...
 95    https://www.dt.co.kr/article/12034113?ref=naver
 96  http://www.finomy.com/news/articleView.html?id...
 97  https://www.getnews.co.kr/news/articleView.htm...
 98  https://gg.newdaily.co.kr/site/data/html/2025/...
 99      https://www.tokenpost.kr/news/briefing/312675

                                                  link  \
 0   https://www.theguru.co.kr/news/article.html?no...
 1   http://www.biztribune.co.kr/news/articleView.h...
 2      https://www.ajunews.com/view/20251209132502899
 3   https://n.news.naver.com/mnews/article/586/000...
 4   https://www.ebn.co.kr/news/articleView.html?id...
 ..                                                ...
 95  https://n.news.naver.com/mnews/article/029/000...
 96  http://www.finomy.com/news/articleView.html?id...
 97  https://www.getnews.co.kr/news/articleView.htm...
 98  https://gg.newdaily.co.kr/site/data/html/2025/...
 99      https://www.tokenpost.kr/news/briefing/312675

                                           description  \
 0   IHC는 아부다비 왕실 소유 투자회사로 부동산 개발 관리 농업 식품 헬스케어 정보기...
 1   또한 quot 이번 결정은 국내 부동산 운용사 매각을 둘러싼 시장 신뢰를 심각하게 ...
 2   주산연은 quot 고강도 수요 규제로 수도권 분양 시장이 잠잠한 가운데 지역별 부동...
 3   9일 부동산플래닛에 따르면 지난 3분기 전국 지식산업센터 거래량은 520건 거래 금...
 4   국토교통부는 이 같은 내용의 부동산거래신고법 시행령 이 이달 9일 공포돼 내년 2월...
 ..                                                ...
 95  디벨로퍼 신영그룹의 부동산 서비스 플랫폼 기업 에스엘플랫폼 SLP 이 위탁 운영 중...
 96  한 부동산 전문가는 quot 이주비 대출은 개인 대출처럼 보이지만 실제로는 도시정비...
 97  이같은 흐름은 착공 및 기성 감소 고물가 등에 따라 내년에도 이어질 것이라며 quo...
 98  가압류에 대한 법원의 결정사항을 보면 남욱의 경우 엔에스제이홀딩스 명의 은행 5개 ...
 99  이외에도 현물 ETF 유입 부족 중국 트레이더들의 이탈 미 연준 금리 인하 가능성 ...

                             pubDate
 0   Tue, 09 Dec 2025 13:46:00 +0900
 1   Tue, 09 Dec 2025 13:46:00 +0900
 2   Tue, 09 Dec 2025 13:46:00 +0900
 3   Tue, 09 Dec 2025 13:45:00 +0900
 4   Tue, 09 Dec 2025 13:44:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 12:12:00 +0900
 96  Tue, 09 Dec 2025 12:08:00 +0900
 97  Tue, 09 Dec 2025 12:08:00 +0900
 98  Tue, 09 Dec 2025 12:06:00 +0900
 99  Tue, 09 Dec 2025 12:04:00 +0900

 [100 rows x 5 columns],
                                           title  \
 0                         10 15 여파 자산 양극화 전국 확산
 1                 외국인 수도권 토허구역 집살 때 자금조달계획서 의무화
 2   다가구 구분거처 반영하니 주택수 307만호 껑충 quot 취약계층 주거 현실
 3                   한국부동산마케팅협회 부동산 빅데이터 역량 강화한다
 4                             우크라이나가 직면한 제국적 분할
 ..                                          ...
 95   오세훈 quot 주택공급 부지 국토부 제안 중 절반 정도 의견일치 quot
 96   GS건설 VS 포스코이앤씨 6800억 서초 진흥아파트 재건축 격돌 예고 정
 97                흥국생명 이지스자산 매각 불공정 제기 법적 대응 예고
 98            과천 분당만 남았다 quot 경기도 규제지역 사실상 해제권
 99             차기 신협중앙회장 선거 돌입 자산건전성 개선 과제로 종합

                                          originallink  \
 0   https://www.munhwa.com/article/11552874?ref=naver
 1   https://www.munhwa.com/article/11552872?ref=naver
 2      https://www.ajunews.com/view/20251209091916605
 3               https://www.mk.co.kr/article/11487567
 4                https://newscham.net/articles/114856
 ..                                                ...
 95  https://www.mt.co.kr/society/2025/12/09/202512...
 96  https://www.smarttoday.co.kr/news/articleView....
 97  http://www.iminju.net/news/articleView.html?id...
 98  https://www.kgnews.co.kr/news/article.html?no=...
 99  https://www.newsis.com/view/NISX20251209_00034...

                                                  link  \
 0   https://n.news.naver.com/mnews/article/021/000...
 1   https://n.news.naver.com/mnews/article/021/000...
 2      https://www.ajunews.com/view/20251209091916605
 3   https://n.news.naver.com/mnews/article/009/000...
 4                https://newscham.net/articles/114856
 ..                                                ...
 95  https://n.news.naver.com/mnews/article/008/000...
 96  https://www.smarttoday.co.kr/news/articleView....
 97  http://www.iminju.net/news/articleView.html?id...
 98  https://www.kgnews.co.kr/news/article.html?no=...
 99  https://n.news.naver.com/mnews/article/003/001...

                                           description  \
 0   10 15 부동산 대책 여파로 서울 진입 문턱이 높아지자 수도권으로 향하던 수요가 ...
 1   국토교통부는 9일 이 같은 내용을 담은 부동산거래신고법 시행령 이 공포됐다고 밝혔다...
 2   데이터처 부가자료 첫 공표 서울 관악 광진구 등 주거취약 아주경제 박기락 기자 ki...
 3   한국부동산마케팅협회는 서울 강남구의 건설회관에서 두레시닝과 데이터 및 인공지능 AI...
 4   챙기는 부동산 거래처럼 들린다 그러나 우크라이나의 지렛대가 약해지면서 우크라이나는 ...
 ..                                                ...
 95  오세훈 서울시장은 quot 부동산 공급을 최대한 많이 하기 위해 국토부와 서울시가 ...
 96  일대 부동산 전문가들도 GS건설과 포스코이앤씨의 경쟁 구도가 확정적이라며 현장 분위...
 97  이번 결정을 두고 흥국생명은 quot 한국 부동산 투자 플랫폼을 노린 중국계 사모펀...
 98  9일 업계와 부동산 통계에 따르면 경기 규제지역 가운데 최근 3개월 집값 상승률이 ...
 99  신협은 대부업 자회사인 KCU NPL 대부 를 출범하고 부동산 프로젝트파이낸싱 PF...

                             pubDate
 0   Tue, 09 Dec 2025 12:03:00 +0900
 1   Tue, 09 Dec 2025 12:03:00 +0900
 2   Tue, 09 Dec 2025 12:02:00 +0900
 3   Tue, 09 Dec 2025 12:01:00 +0900
 4   Tue, 09 Dec 2025 12:00:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 11:15:00 +0900
 96  Tue, 09 Dec 2025 11:14:00 +0900
 97  Tue, 09 Dec 2025 11:14:00 +0900
 98  Tue, 09 Dec 2025 11:14:00 +0900
 99  Tue, 09 Dec 2025 11:14:00 +0900

 [100 rows x 5 columns],
                                                 title  \
 0                    차기 신협중앙회장 선거 돌입 자산건전성 개선 과제로 종합
 1                   과천 분당만 남았다 quot 경기도 규제지역 사실상 해제권
 2              국내 부동산 1위 운용사 이지스 중국계 힐하우스가 품나 대주주 심사
 3                        신상진 성남시장 대장동 범죄수익 환수 조치 기자회견
 4                   장철민 의원 도시정비사업 신탁사 교체 취소법 대표발의 지지
 ..                                                ...
 95                    법원 대장동 가압류 추진 성남도개공에 7건 담보제공 명령
 96                        국토부 공공택지서 공공분양 최대 35 제한 없앤다
 97   quot 더 이상 숨길 곳은 없다 quot 성남시 대장동 일당 5673억 원 가압...
 98               계약금 없어도 일단 덤빈다 서울 청약자 절반이 매달리는 강남 로
 99                       금융권 대출 한파 속 연 12 적금 상품이 있다고

                                          originallink  \
 0   https://www.newsis.com/view/NISX20251209_00034...
 1   https://www.kgnews.co.kr/news/article.html?no=...
 2   https://www.chosun.com/economy/money/2025/12/0...
 3   https://www.joongdo.co.kr/web/view.php?key=202...
 4   https://biz.heraldcorp.com/article/10632588?re...
 ..                                                ...
 95  https://www.yna.co.kr/view/AKR2025120905420006...
 96  https://news.einfomax.co.kr/news/articleView.h...
 97  https://www.dailian.co.kr/news/view/1583684/?s...
 98              https://www.mk.co.kr/article/11487488
 99  https://www.gukjenews.com/news/articleView.htm...

                                                  link  \
 0   https://n.news.naver.com/mnews/article/003/001...
 1   https://www.kgnews.co.kr/news/article.html?no=...
 2   https://n.news.naver.com/mnews/article/023/000...
 3   https://www.joongdo.co.kr/web/view.php?key=202...
 4   https://n.news.naver.com/mnews/article/016/000...
 ..                                                ...
 95  https://n.news.naver.com/mnews/article/001/001...
 96  https://news.einfomax.co.kr/news/articleView.h...
 97  https://n.news.naver.com/mnews/article/119/000...
 98  https://n.news.naver.com/mnews/article/009/000...
 99  https://www.gukjenews.com/news/articleView.htm...

                                           description  \
 0   신협은 대부업 자회사인 KCU NPL 대부 를 출범하고 부동산 프로젝트파이낸싱 PF...
 1   9일 업계와 부동산 통계에 따르면 경기 규제지역 가운데 최근 3개월 집값 상승률이 ...
 2   국내 최대 부동산 자산운용사인 이지스자산운용의 새 주인이 중국계 사모펀드 PEF 힐...
 3   이와 관련 대장동 일당의 재산을 동결하기 위해 부동산처분 금지 가처분 2건 포함 1...
 4   또한 변경 또는 지정 취소가 고시되는 즉시 기존 신탁업자에게 신탁 등기된 부동산의 ...
 ..                                                ...
 95  성남도시개발공사 성남도개공 가 지난 1일 대장동 민간업자들의 부동산과 예금 14건을...
 96  한 업계 관계자는 quot 공공분양을 통해 주택 공급이 늘어나는 효과가 있을 것으로...
 97  남욱 씨의 계좌 예금 약 300억 원 과 제주도 부동산 정영학 씨가 보유한 약 64...
 98  9일 부동산R114에 따르면 지난 5일 기준 올해 강남 서초 송파구 등 강남 3구 ...
 99  부동산 아파트 전경 기준금리 인하 기대가 약화되면서 시장금리가 오르자 시중은행의 예...

                             pubDate
 0   Tue, 09 Dec 2025 11:14:00 +0900
 1   Tue, 09 Dec 2025 11:14:00 +0900
 2   Tue, 09 Dec 2025 11:13:00 +0900
 3   Tue, 09 Dec 2025 11:12:00 +0900
 4   Tue, 09 Dec 2025 11:12:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 10:40:00 +0900
 96  Tue, 09 Dec 2025 10:40:00 +0900
 97  Tue, 09 Dec 2025 10:39:00 +0900
 98  Tue, 09 Dec 2025 10:38:00 +0900
 99  Tue, 09 Dec 2025 10:38:00 +0900

 [100 rows x 5 columns],
                                             title  \
 0            계약금 없어도 일단 덤빈다 서울 청약자 절반이 매달리는 강남 로
 1   흥국생명 이지스자산운용 매각 선정 절차 quot 불공정 불투명 quot 법적 대
 2               영끌 막차 탄 30대 10월 서울 아파트 매매 중 37 차지
 3                           미국 자산 3분의 1 베이비붐이 삼켰다
 4        quot 에너지는 생존 문제 화이트리스트 규제 체계부터 바꿔야 quot
 ..                                            ...
 95          토허구역 집 사는 외국인 자금조달계획서 제출해야 내년 2월부터 시
 96           중국계 사모펀드 이지스 새주인 후보 흥국생명 매각절차 공정 못해
 97                  직통 역세권 아파트 집값 껑충 5년간 평균 48 올라
 98                  건축비 인상에 분양가도 급격한 상승세 실수요자 비상
 99              외국인 수도권 주택 매입 더 까다로워진다 자금조달계획서 내야

                                          originallink  \
 0               https://www.mk.co.kr/article/11487488
 1      https://news.tf.co.kr/read/economy/2270441.htm
 2   https://www.chosun.com/economy/real_estate/202...
 3   https://www.fortunekorea.co.kr/news/articleVie...
 4   https://www.ohmynews.com/NWS_Web/View/at_pg.as...
 ..                                                ...
 95  https://www.pointdaily.co.kr/news/articleView....
 96  https://www.g-enews.com/view.php?ud=2025120909...
 97  https://www.asiatime.co.kr/article/20251209500064
 98  http://www.ikld.kr/news/articleView.html?idxno...
 99  https://www.pinpointnews.co.kr/news/articleVie...

                                                  link  \
 0   https://n.news.naver.com/mnews/article/009/000...
 1   https://n.news.naver.com/mnews/article/629/000...
 2   https://n.news.naver.com/mnews/article/023/000...
 3   https://www.fortunekorea.co.kr/news/articleVie...
 4   https://n.news.naver.com/mnews/article/047/000...
 ..                                                ...
 95  https://www.pointdaily.co.kr/news/articleView....
 96  https://www.g-enews.com/view.php?ud=2025120909...
 97  https://www.asiatime.co.kr/article/20251209500064
 98  http://www.ikld.kr/news/articleView.html?idxno...
 99  https://www.pinpointnews.co.kr/news/articleVie...

                                           description  \
 0   9일 부동산R114에 따르면 지난 5일 기준 올해 강남 서초 송파구 등 강남 3구 ...
 1   이번 선정 결과를 두고 quot 한국 부동산 투자 플랫폼을 겨냥한 중국계 사모펀드와...
 2   9일 한국부동산원 매입자 연령대별 아파트 매매 거래 현황에 따르면 10월 서울 아파...
 3   있지만 부동산 시장에서는 같은 행운을 누리지 못했다 2008년 금융위기 이후 신규 ...
 4   한편 개혁신당 포럼 주경야독 은 매주 월요일 오후 6시 30분 국회의원회관에서 열리...
 ..                                                ...
 95  국토교통부는 이러한 내용을 담은 부동산거래신고법 시행령 개정안을 9일 공포했으며 2...
 96  국내 최대 부동산 자산운용사인 이지스자산운용 매각전에서 중국계 사모펀드 PEF 운용...
 97  직통 역세권 집값 사진 부동산인포 9일 부동산시장 분석업체 부동산인포가 서울 시내 ...
 98  부동산R114에 따르면 지난 2년간 전국의 3 3 당 평균 분양가는 2023년 1 ...
 99  정부가 외국인의 국내 부동산 투기 차단을 위해 체류자격과 자금조달 내역 등 거래 신...

                             pubDate
 0   Tue, 09 Dec 2025 10:38:00 +0900
 1   Tue, 09 Dec 2025 10:37:00 +0900
 2   Tue, 09 Dec 2025 10:37:00 +0900
 3   Tue, 09 Dec 2025 10:36:00 +0900
 4   Tue, 09 Dec 2025 10:36:00 +0900
 ..                              ...
 95  Tue, 09 Dec 2025 10:12:00 +0900
 96  Tue, 09 Dec 2025 10:12:00 +0900
 97  Tue, 09 Dec 2025 10:12:00 +0900
 98  Tue, 09 Dec 2025 10:12:00 +0900
 99  Tue, 09 Dec 2025 10:12:00 +0900

 [100 rows x 5 columns],
                                          title  \
 0        토허구역 집 사는 외국인 자금조달계획서 제출해야 내년 2월부터 시
 1                직통 역세권 아파트 집값 껑충 5년간 평균 48 올라
 2   흥국생명 quot 이지스운용 입찰에 법적대응 입찰금액 유출 가능성 quot
 3                      Weekly ETF QQQ에 6조원 쏠렸다
 4           강남3구 분상제 아파트 청약 열기 올해 평균경쟁률 271대 1
 ..                                         ...
 95                   외국인도 서울에 집 살 때 자금조달계획서 내야
 96   흥국생명 quot 이지스자산운용 우선협상대상자 선정에 강한 유감 quot
 97    AI MY 뉴스 미 국채금리 달러 동반 상승 중국증시 부담 속 투자전략
 98                          이지스운용 인수 승자의 저주 우려
 99        이지스운용 인수 우협대상자에 외국계 PEF 힐하우스 1 1조 베팅

                                          originallink  \
 0   https://www.pointdaily.co.kr/news/articleView....
 1   https://www.asiatime.co.kr/article/20251209500064
 2   https://www.yna.co.kr/view/AKR2025120905300000...
 3   http://www.globalepic.co.kr/view.php?ud=202512...
 4   https://www.asiatoday.co.kr/view.php?key=20251...
 ..                                                ...
 95  https://www.chosun.com/economy/real_estate/202...
 96  https://www.pinpointnews.co.kr/news/articleVie...
 97   https://www.newspim.com/news/view/20251209000167
 98  https://www.kbanker.co.kr/news/articleView.htm...
 99         https://www.etoday.co.kr/news/view/2534080

                                                  link  \
 0   https://www.pointdaily.co.kr/news/articleView....
 1   https://www.asiatime.co.kr/article/20251209500064
 2   https://n.news.naver.com/mnews/article/001/001...
 3   http://www.globalepic.co.kr/view.php?ud=202512...

In [12]:
news_df = pd.concat(news_data)

In [13]:
news_df

,title,originallink,link,description,pubDate
0,기획 수출 7000억달러 시대 쏠림 착시 심화,http://www.m-i.kr/news/articleView.html?idxno=...,http://www.m-i.kr/news/articleView.html?idxno=...,일반기계 8 6 468억달러 는 최대 시장인 미국의 관세 정책 불확실성과 중국의 부...,"Tue, 09 Dec 2025 15:04:00 +0900"
1,나이스신용평가 내년 건설업 업황 부진 전망,https://www.cstimes.com/news/articleView.html?...,https://www.cstimes.com/news/articleView.html?...,이러한 흐름은 착공 및 기성 감소 고물가 등에 따라 내년에도 이어질 것이라며 quo...,"Tue, 09 Dec 2025 15:04:00 +0900"
2,BNK금융 빈대인 2기 체제 돌입 실적 개선 해양금융 비전 제시,https://www.cstimes.com/news/articleView.html?...,https://www.cstimes.com/news/articleView.html?...,취임 직후 발생한 경남은행 3000억원대 횡령 사건 이후 BNK금융은 부동산 프로젝...,"Tue, 09 Dec 2025 15:04:00 +0900"
3,국립공주대 부동산학과 2025 진로 토크 콘서트 개최,http://www.veritas-a.com/news/articleView.html...,http://www.veritas-a.com/news/articleView.html...,국립공주대 총장 임경호 부동산학과 학과장 심희철 는 산업과학대학 산업과학관에서 재학...,"Tue, 09 Dec 2025 15:04:00 +0900"
4,빈민vs부민 갈라치기 한 토허제 강남3구 용산 연일 불기둥,https://biz.newdaily.co.kr/site/data/html/2025...,https://biz.newdaily.co.kr/site/data/html/2025...,반면 10 15부동산대책 으로 서울 아파트 거래량은 큰폭으로 줄었다 서울부동산정보광...,"Tue, 09 Dec 2025 15:04:00 +0900"
...,...,...,...,...,...
95,재산 1조설 김재중 마흔 앞두고 결국 일 냈다 국민효자 에서 선한,https://www.tenasia.co.kr/article/2025120811834,https://m.entertain.naver.com/article/312/0000...,당시 김재중은 quot 차도 부동산도 있었던 거를 팔고 다른 것도 사고 이랬을 건데...,"Mon, 08 Dec 2025 20:32:00 +0900"
96,미리보는 이데일리 신문 발레파킹 분리수거 현실 된 AI발 주거 혁신,http://www.edaily.co.kr/news/newspath.asp?news...,https://n.news.naver.com/mnews/article/018/000...,부동산 GTX 집값상승 효과 입증돼 2개 노선 교차 청량리 억소리 내년 SOC 예...,"Mon, 08 Dec 2025 20:31:00 +0900"
97,헬로 이슈토크 경기도지사 경기도교육감 선거 누가 나올까,http://news.lghellovision.net/news/articleView...,http://news.lghellovision.net/news/articleView...,이재필 기자 우선 부동산 이슈를 꼽을 수 있을 것 같습니다 제8회 전국동시지방선거...,"Mon, 08 Dec 2025 20:30:00 +0900"
98,SC이슈 사짜 냄새 났다 박나래 의혹에 기안84 과거 발언도 재조,https://www.sportschosun.com/entertainment/202...,https://m.entertain.naver.com/article/076/0004...,박나래는 지난 3일 전 매니저 2인으로부터 부동산 가압류 신청과 함께 직장 내 괴롭...,"Mon, 08 Dec 2025 20:30:00 +0900"
99,엄마야 집값 진짜 오르는 기가 부산 울산 경남권에 무슨 일이,https://www.segye.com/newsView/20251208502850?...,https://n.news.naver.com/mnews/article/022/000...,침체한 지방 부동산 시장이 바닥을 확인한 것 아니냐는 전망이 나온다 다만 부산을 비...,"Mon, 08 Dec 2025 20:29:00 +0900"

# 코드를 함수화

In [14]:
def naver_api(keyword, cate):
    page_num = 1
    total_page = 1
    start_num = 1
    
    result = {}
    while page_num <= total_page:
        print(cate, page_num, total_page, end="\r")
        user_id = os.getenv("")
        user_secret = os.getenv("")
        url = f"https://openapi.naver.com/v1/search/{cate}"
        payload = dict(query=keyword, display=100, start=start_num, sort="date")
        headers = {"X-Naver-Client-Id" : "", "X-Naver-Client-Secret" : ""}
        r = requests.get(url, params=payload, headers=headers)
        response = r.json()

        
        for item in response['items']:

            for key, value in item.items():
                if key in ['title', 'description']:
                    result.setdefault(key, []).append(text_clean(value))
                else:
                    result.setdefault(key, []).append(value)
        
        
        
        total_page = response['total'] // 100 + 1
        if total_page > 11:
            total_page = 11
        else:
            total_page = response['total'] // 100 + 1


        page_num += 1

        if start_num < 901:
            start_num += 100
        elif start_num > 900:
            start_num += 99

    return pd.DataFrame(result)

In [15]:
today = datetime.today()
today

datetime.datetime(2025, 12, 9, 15, 8, 44, 933526)

In [16]:
date = f"{today.year}{today.month:02d}{today.day:02d}"
date

'20251209'

In [17]:
keyword = input("검색어를 입력하세요")
date = f"{today.year}{today.month:02d}{today.day:02d}"
for cate in category:
    result = naver_api(keyword, cate)
    result.to_csv(f"./data/{keyword}_{cate}_{date}.csv", index=False, encoding="utf-8-sig")

검색어를 입력하세요핀테크