# YES24에서 베스트셀러 정보 수직하기

In [16]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [17]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = bs(r.content, 'lxml')
response

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200

<!DOCTYPE html>
<html lang="ko">
<head><link href="https://m.yes24.com/Home/Best?DispNo=001" media="only screen and(max-width: 640px)" rel="alternate"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" http-equiv="Accept-CH"/>
<meta content="86400" http-equiv="Accept-CH-Lifetime"/>
<meta content="unsafe-url" name="referrer"/>
<meta content="width=1170" name="viewport"/>
<title> 국내도서 종합 베스트 - 예스24 </title>
<meta content="예스24" name="title"/>
<meta content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." name="description"/>
<meta content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" name="keywords"/>
<link href="//www.yes24.com/OpensearchDescription.xml" rel="search" title="YES24" type="application/opensearchdescription+xml"/>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/util.js?v=20251114_a" type="text/javascript"></script>
<script charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20250702" type="text/javascript"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20251120" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1" type="text/javascript"></script>
<link charset="euc-kr" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20251208" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" rel="stylesheet" type="text/css"/>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		// dfinery 디파이너리 위한 설정 값
		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
<script src="https://www.yes24.com/javascript/common.js?v=20251120" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20250709" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfineryHelper.js?v=20251031" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20251202d" type="text/javascript"></script>
<script defer="" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20251202d" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20251202d"></script>
<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20251202d"></script>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager -->
<script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
<!-- End Google Tag Manager -->
<!-- RTB HOUSE 메인 태깅 코드 -->
<script>
	    (function(w,d,dn,t){w[dn]=w[dn]||[];w[dn].push({eventType:'init',value:t,dc:'asia'});
	    var f=d.getElementsByTagName('script')[0],c=d.createElement('script');c.async=true;
	    c.src='https://tags.creativecdn.com/ld87UMn0bZ6wjXtzlyVc.js';
	    f.parentNode.insertBefore(c,f);})(window,document,'rtbhEvents','ld87UMn0bZ6wjXtzlyVc');
	    (rtbhEvents = window.rtbhEvents || []).push({});
    </script>
<!-- End RTB HOUSE 메인 태깅 코드 -->
<script async="" src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>
<link href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20251208" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?ver=20251022" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/best/best.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/></head>
<body>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
<dt>콘텐츠 바로가기</dt>
<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>
<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div class="" id="yesWrap">
<div id="yesHeaderArea" style="">
<!-- ########## TOPBANNER 영역 시작 ########## -->
<section>
<div id="upperBnWrap" style="display:none;">
<div id="upperBnRoll">
<div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#acefc1"><a href="https://event.yes24.com/onlyApp" onclick="setWcode('001');"><img alt="도서앱" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_L_01.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#b0e7f3"><a href="https://event.yes24.com/present?eventNo=265086" onclick="setWcode('001');"><img alt="망토담요" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#fbd0f3"><a href="https://event.yes24.com/yesBenefit" onclick="setWcode('001');"><img alt="12월혜택" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_L_02.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#b7c1f4"><a href="https://event.yes24.com/present?eventNo=265086" onclick="setWcode('001');"><img alt="텀블러" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#f7e7b7"><a href="https://event.yes24.com/goodbye/2025" onclick="setWcode('001');"><img alt="연말결산" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_L_03.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#f1bec0"><a href="https://event.yes24.com/present?eventNo=265086" onclick="setWcode('001');"><img alt="책집게" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/1126_topbn_480x50_R_03.png" width="480"/></a></div>
</div>
</div>
</div>
<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
</div>
</section>
<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
<!-- ########## TOPBANNER 영역 끝 ########## -->
<!-- ########## HEADER 영역 시작 ########## -->
<div id="yHeader">
<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');"><svg aria-label="YES24" role="img" type="image/svg+xml"><image alt="YES24" height="103" src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/></svg></a></h1>
<div id="yHeaderWrap">
<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
<div class="yHeaderTop">
<h2 class="yBlind">YES24 카테고리 리스트</h2>
<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" title="국내도서"><em class="txt">국내도서</em></a></li><li class="cate002"><a href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" title="외국도서"><em class="txt">외국도서</em></a></li><li class="cate018"><a href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" title="중고샵"><em class="txt">중고샵</em></a></li><li class="cate017"><a href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" title="eBook"><em class="txt">eBook</em></a></li><li class="cateCrC"><a href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" title="크레마클럽"><em class="txt">크레마클럽</em><em class="ico_newSup"></em></a></li><li class="cate003"><a href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" title="CD/LP"><em class="txt">CD/LP</em></a></li><li class="cate004"><a href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" title="DVD/Blu-ray"><em class="txt">DVD/BD</em></a></li><li class="cate006"><a href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" title="GIFT"><em class="txt"><u>문구</u>/GIFT</em></a><span class="gSticker"><a href="https://event.yes24.com/diaryShop">2026 다이어리</a></span></li><li class="cateENT"><a href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank" title="티켓"><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
<h2 class="yBlind">YES24 유틸메뉴</h2>
<ul class="utilLi">
<li id="LoginText">
<input id="hdfLoginYn" type="hidden" value="N"/>
<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>
</li>
<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>
<li class="myPgGrp">
<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
<dl class="myPgDl">
<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
<dd>
<ul>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
</ul>
</dd>
</dl>
</li>
<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')"><em class="txt">카트</em></a></li>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
</ul>
<dl class="globalYesInfoDl">
<dt><a href="javascript:void(0);"><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
<dd>
<div class="globalYesInfoContArea">
<div class="globalYesInfoCont">
<p class="yesInfo_tit">Global YES24는?</p>
<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
<div class="yesInfo_globalTxt">
<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
<a class="btnC btn_blue" href="https://global.yes24.com" onclick="setWcode('001_016_002')" target="_blank"><span class="bWrap"><em class="txt">English</em></span></a>
<p class="globalTxt_des">
									 作为出售正规 K-POP/K-Drama 相关(CD,图书,DVD) 韩流商品的网站, 支持 中文/英文 等海外结账方式
									</p>
<a class="btnC btn_blue" href="https://cn.yes24.com" onclick="setWcode('001_016_003')" target="_blank"><span class="bWrap"><em class="txt">中文</em></span></a>
<p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
<a class="btnC btn_blue" href="http://ticket.yes24.com/English?Gcode=009_205" onclick="setWcode('001_016_004')" target="_blank"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
</div>
</div>
</div>
</dd>
</dl>
</div>
<!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
<hr/>
<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
<div class="yHeaderMid">
<div class="yesSearch">
<form accept-charset="utf-8" action="//www.yes24.com/product/search?" id="yesSForm" method="get" name="HeadForm" onsubmit="return check_search();">
<input id="keywordAd" name="keywordAd" type="hidden" value=""/>
<input id="keyword" name="keyword" type="hidden"/>
<input id="domain" name="domain" type="hidden" value="ALL"/>
<input id="qdomain" name="qdomain" type="hidden" value="전체"/>
<fieldset>
<legend>검색</legend>
<span class="schIpt">
<label><input accesskey="s" autocomplete="off" class="iptTxt" id="query" maxlength="80" name="query" onblur="blurSearchBar();" onfocus="showLatestSearchList();" onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();" onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" style="ime-mode: active;" title="YES24 검색어 입력" type="text" value=""/></label>
</span>
<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">
<script charset="euc-kr" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" type="text/javascript"></script>
<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>
</div>
<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");

In [22]:
book_list = response.select("#yesBestList > li")
book_list

[<li class="" data-goods-no="166390503" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">1</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/166390503" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="최소한의 삼국지" border="0" class="lazy" data-original="https://image.yes24.com/goods/166390503/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(166390503); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/166390503" onclick="wiseLogV2('BS', '001_005_001', ''); ">최소한의 삼국지</a>
 <span class="gd_nameE">최태성의 삼국지 고전 특강</span>
 <a class="bgYUI ico_nWin" href="/product/goods/166390503" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">최소한의 삼국지 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25ED%2583%259C%25EC%2584%25B1&amp;authorNo=154511&amp;author=최태성" target="">최태성</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2584%25B1%25EC%259B%2590&amp;authorNo=312081&amp;author=이성원" target="">이성원</a> 감수
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%94%84%eb%9f%b0%ed%8a%b8%ed%8e%98%ec%9d%b4%ec%a7%80&amp;query=%25ED%2594%2584%25EB%259F%25B0%25ED%258A%25B8%25ED%258E%2598%25EC%259D%25B4%25EC%25A7%2580">프런트페이지</a></span>
 <span class="authPub info_date">2025년 11월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/class?eventNo=264804">1/10(토) 강연 입장권 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">17,550</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">19,500</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>970원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 253,095
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/166390503?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">42</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">10.0</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (17건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (17건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (8건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B3%25A0%25EC%25A0%2584%25EC%259D%25BD%25EA%25B8%25B0&amp;hashNm=%ea%b3%a0%ec%a0%84%ec%9d%bd%ea%b8%b0" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '고전읽기', '166390503','912');">#고전읽기</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B6%2588%25EB%25A9%25B8%25EC%259D%2598%25EA%25B3%25A0%25EC%25A0%2584&amp;hashNm=%eb%b6%88%eb%a9%b8%ec%9d%98%ea%b3%a0%ec%a0%84" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '불멸의고전', '166390503','2506');">#불멸의고전</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B3%25A0%25EC%25A0%2584%25EC%259D%25BD%25EC%2596%25B4%25EC%25A3%25BC%25EB%258A%2594%25EC%25B1%2585&amp;hashNm=%ea%b3%a0%ec%a0%84%ec%9d%bd%ec%96%b4%ec%a3%bc%eb%8a%94%ec%b1%85" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '고전읽어주는책', '166390503','2864');">#고전읽어주는책</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%2598%25EB%25A3%25BB%25EB%25B0%25A4%25EC%2597%2590%25EB%2581%259D%25EB%2582%25B4%25EB%258A%2594%25EC%2582%25BC%25EA%25B5%25AD%25EC%25A7%2580&amp;hashNm=%ed%95%98%eb%a3%bb%eb%b0%a4%ec%97%90%eb%81%9d%eb%82%b4%eb%8a%94%ec%82%bc%ea%b5%ad%ec%a7%80" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '하룻밤에끝내는삼국지', '166390503','2868');">#하룻밤에끝내는삼국지</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2582%25BC%25EA%25B5%25AD%25EC%25A7%2580&amp;hashNm=%ec%82%bc%ea%b5%ad%ec%a7%80" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '삼국지', '166390503','4799');">#삼국지</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="txt"><a href="https://event.yes24.com/present?eventNo=265086">12월의 굿즈 : 산리오 캐릭터즈 망토 담요/책 집게/파스텔 텀블러</a></span>
 <span class="date">(25.11.28 ~ 25.12.31)</span>
 </div>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/167892129">eBook <span class="relG_num">13,700원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="166390503" id="ordChk_166390503" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_166390503" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('166390503'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('166390503'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('166390503', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('166390503', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" name="btnList" onclick="order_payment.addMyListV3('166390503', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_166390503" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":166390503,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"최소한의 삼국지","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001014","goodsSortNm":"인문","goodsAuth":"&lt;최태성&gt; 저/&lt;이성원&gt; 감수","shopPrice":19500.00,"salePrice":17550.00,"discountShopPrice":1950.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="153064968" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">2</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="트렌드 코리아 2026" border="0" class="lazy" data-original="https://image.yes24.com/goods/153064968/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(153064968); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 <span class="gd_keynote" id="spanGdKeynote">
 <a class="iconC tBook" href="/24/Category/More/001014?ElemNo=13&amp;ElemSeq=1&amp;Gcode=000_030_001"><em class="txt">오늘의책</em></a>
 <!-- 클래스24 상품일 경우 -->
 </span>
 <script type="text/javascript">
         if ($('#spanGdKeynote').children().length == 0) {
             $('#spanGdKeynote').remove();
         }
     </script>
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); ">트렌드 코리아 2026</a>
 <span class="gd_nameE">2026 대한민국 소비트렌드 전망</span>
 <a class="bgYUI ico_nWin" href="/product/goods/153064968" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">트렌드 코리아 2026 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%259C%25EB%258F%2584&amp;authorNo=133431&amp;author=김난도" target="">김난도</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%25AF%25B8%25EC%2598%2581&amp;authorNo=140108&amp;author=전미영" target="">전미영</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25EC%25A7%2580%25ED%2598%259C&amp;authorNo=157166&amp;author=최지혜" target="">최지혜</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EC%25A0%2595%25EC%259C%25A4&amp;authorNo=236190&amp;author=권정윤" target="">권정윤</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EB%258B%25A4%25ED%2598%259C&amp;authorNo=295621&amp;author=한다혜" target="">한다혜</a> 저 외 7명
                                         <span class="moreAuthArea">
 <span class="moreAuthBtn"><a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.cCont_listArea'),event);">정보 더 보기/감추기</a></span>
 <span class="moreAuthLi">
 <span class="moreAuthLiCont">
 <ul>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%259C%25EB%258F%2584&amp;authorNo=133431&amp;author=김난도" target="">김난도</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%25AF%25B8%25EC%2598%2581&amp;authorNo=140108&amp;author=전미영" target="">전미영</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25EC%25A7%2580%25ED%2598%259C&amp;authorNo=157166&amp;author=최지혜" target="">최지혜</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EC%25A0%2595%25EC%259C%25A4&amp;authorNo=236190&amp;author=권정윤" target="">권정윤</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EB%258B%25A4%25ED%2598%259C&amp;authorNo=295621&amp;author=한다혜" target="">한다혜</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%2598%259C%25EC%259B%2590&amp;authorNo=361117&amp;author=이혜원" target="">이혜원</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2588%2598%25EC%25A7%2584&amp;authorNo=190906&amp;author=이수진" target="">이수진</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259C%25A0%25ED%2598%2584&amp;authorNo=190905&amp;author=서유현" target="">서유현</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2584%25EB%258B%25A4%25ED%2598%2584&amp;authorNo=409052&amp;author=전다현" target="">전다현</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%25A4%2580%25EC%2598%2581&amp;authorNo=140104&amp;author=이준영" target="">이준영</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%2596%25A5%25EC%259D%2580&amp;authorNo=140106&amp;author=이향은" target="">이향은</a></li>
 <li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%2582%2598%25EC%259D%2580&amp;authorNo=483435&amp;author=김나은" target="">김나은</a></li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%af%b8%eb%9e%98%ec%9d%98%ec%b0%bd&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%259D%2598%25EC%25B0%25BD">미래의창</a></span>
 <span class="authPub info_date">2025년 09월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=264732">[단독] 육각 노크펜 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,000</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">20,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,000원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 533,376
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/153064968?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">164</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.2</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (82건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (5건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (67건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (10건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=2026%25EB%25A5%25BC%25EC%2598%2588%25EC%25B8%25A1%25ED%2595%2598%25EB%258B%25A4&amp;hashNm=2026%eb%a5%bc%ec%98%88%ec%b8%a1%ed%95%98%eb%8b%a4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '2026를예측하다', '153064968','8951');">#2026를예측하다</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%258A%25B8%25EB%25A0%258C%25EB%2593%259C%25ED%2582%25A4%25EC%259B%258C%25EB%2593%259C&amp;hashNm=%ed%8a%b8%eb%a0%8c%eb%93%9c%ed%82%a4%ec%9b%8c%eb%93%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '트렌드키워드', '153064968','782');">#트렌드키워드</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2586%258C%25EB%25B9%2584%25ED%258A%25B8%25EB%25A0%258C%25EB%2593%259C&amp;hashNm=%ec%86%8c%eb%b9%84%ed%8a%b8%eb%a0%8c%eb%93%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '소비트렌드', '153064968','645');">#소비트렌드</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2581%25AC%25EB%25A0%2588%25EB%25A7%2588%25ED%2581%25B4%25EB%259F%25BD%25EC%2597%2590%25EC%259E%2588%25EC%2596%25B4%25EC%259A%2594&amp;hashNm=%ed%81%ac%eb%a0%88%eb%a7%88%ed%81%b4%eb%9f%bd%ec%97%90%ec%9e%88%ec%96%b4%ec%9a%94" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '크레마클럽에있어요', '153064968','5392');">#크레마클럽에있어요</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EB%258B%25AC%25EC%259D%2598%25EA%25B5%25BF%25EC%25A6%2588&amp;hashNm=%ec%9d%b4%eb%8b%ac%ec%9d%98%ea%b5%bf%ec%a6%88" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '이달의굿즈', '153064968','6788');">#이달의굿즈</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">선착순</em></span>
 <span class="iconC"><em class="txt">경품</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="txt"><a href="https://event.yes24.com/template?EventNo=265051">2025 베스트셀러 트렌드: 가장 많은 사랑을 받은 책은?</a></span>
 <span class="date">(25.12.01 ~ 25.12.31)</span>
 </div>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/155311099">eBook <span class="relG_num">14,000원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="153064968" id="ordChk_153064968" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_153064968" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('153064968'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('153064968'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('153064968', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>

In [23]:
len(book_list)

120

# li 1개는 1권의 정보
* 책 제목, 저자, 출판사, 출간일, 가격, 평점, 리뷰수

In [24]:
def text_clean(text):
    text = text.replace("\n", "").replace("\r", "").replace(",", "").replace("저", "").replace("역", "").strip()
    return text

In [25]:
# 책 제목
book_title = book_list[0].select_one(".gd_name").text

In [26]:
book_list[0].select_one(".authPub.info_auth").text

'\n최태성 저/이성원 감수\r\n                            '

In [28]:
text_clean(book_list[7].select_one(".authPub.info_auth").text)

'최태성'

In [30]:
# 저자와 역자가 같이 있을 때 저자
text_clean(book_list[1].select_one(".authPub.info_auth").text.split("/")[0])

'김난도 전미영 최지혜 권정윤 한다혜  외 7명                                        정보 더 보기'

In [31]:
# 저자와 역자가 같이 있을 때 역자
text_clean(book_list[1].select_one(".authPub.info_auth").text.split("/")[1])

'감추기김난도전미영최지혜권정윤한다혜이혜원이수진서유현전다현이준영이향은김나은'

In [32]:
# 저자가 1명일 때
author = text_clean(book_list[2].select_one(".authPub.info_auth").text)

In [33]:
# 출판사
publisher = book_list[0].select_one(".authPub.info_pub > a").text

In [34]:
# 출간일
pub_date = book_list[0].select_one(".authPub.info_date").text

In [35]:
# 책 가격
price = int(book_list[0].select_one(".yes_b").text.replace(",", ""))

In [36]:
# 평점
rating = float(book_list[0].select_one(".rating_grade > .yes_b").text)

In [37]:
# 리뷰수
n_reviews = int(book_list[0].select_one(".rating_rvCount > a > em.txC_blue").text)

In [38]:
print(book_title, author, publisher, pub_date,  price, rating, n_reviews)

최소한의 삼국지 태수 프런트페이지 2025년 11월 17550 10.0 42

# 페이지 전체에 있는 책 정보 하나로 모으기

In [39]:
result = {}
keys = ['제목', '저자', '출판사', '출간일', '가격', '평점', '리뷰수']
for idx ,book in enumerate(book_list):
    print(f"{idx+1}/{len(book_list)}")
    book_title = book.select_one(".gd_name").text
    author = text_clean(book.select_one(".authPub.info_auth").text)
    publisher = book.select_one(".authPub.info_pub > a").text
    pub_date = book.select_one(".authPub.info_date").text
    price = int(book.select_one(".yes_b").text.replace(",", ""))
    rating = float(book.select_one(".rating_grade > .yes_b").text) if book.select_one(".rating_grade > .yes_b") != None else 0
    n_reviews = int(book.select_one(".rating_rvCount > a > em.txC_blue").text.replace(",", "")) if book.select_one(".rating_rvCount > a > em.txC_blue") != None else 0
    values = (book_title, author, publisher, pub_date,  price, rating, n_reviews)
    for key, value in zip(keys, values):
        result.setdefault(key, []).append(value)

df = pd.DataFrame(result)
df

1/120
2/120
3/120
4/120
5/120
6/120
7/120
8/120
9/120
10/120
11/120
12/120
13/120
14/120
15/120
16/120
17/120
18/120
19/120
20/120
21/120
22/120
23/120
24/120
25/120
26/120
27/120
28/120
29/120
30/120
31/120
32/120
33/120
34/120
35/120
36/120
37/120
38/120
39/120
40/120
41/120
42/120
43/120
44/120
45/120
46/120
47/120
48/120
49/120
50/120
51/120
52/120
53/120
54/120
55/120
56/120
57/120
58/120
59/120
60/120
61/120
62/120
63/120
64/120
65/120
66/120
67/120
68/120
69/120
70/120
71/120
72/120
73/120
74/120
75/120
76/120
77/120
78/120
79/120
80/120
81/120
82/120
83/120
84/120
85/120
86/120
87/120
88/120
89/120
90/120
91/120
92/120
93/120
94/120
95/120
96/120
97/120
98/120
99/120
100/120
101/120
102/120
103/120
104/120
105/120
106/120
107/120
108/120
109/120
110/120
111/120
112/120
113/120
114/120
115/120
116/120
117/120
118/120
119/120
120/120

,제목,저자,출판사,출간일,가격,평점,리뷰수
0,최소한의 삼국지,최태성 /이성원 감수,프런트페이지,2025년 11월,17550,10.0,42
1,트렌드 코리아 2026,김난도 전미영 최지혜 권정윤 한다혜 외 7명 ...,미래의창,2025년 09월,18000,9.2,164
2,어른의 행복은 조용하다,태수,페이지2북스,2024년 11월,16020,9.5,405
3,혼모노,성해나,창비,2025년 03월,16200,9.1,688
4,박곰희 연금 부자 수업 (10만 부 기념 스페셜 에디션),박곰희,인플루엔셜,2025년 06월,18900,9.7,189
...,...,...,...,...,...,...,...
115,정승제의 수학 대모험 1,설민석 조영선 글/최진규 박지영 그림/정승제 감수,단꿈아이,2025년 11월,14400,9.9,137
116,슈뻘맨의 숨은 과학 찾기 7,슈뻘맨 원/서후 글/류수형 그림/샌드박스 네트워크 정재형 감수,미래엔아이세움,2025년 11월,15120,10.0,5
117,마일리지 아워,최유나,북로망스,2025년 11월,19800,9.9,27
118,세이노의 가르침,세이노(SayNo),데이원,2023년 03월,6480,9.0,2802
119,비범한 평범,조수용,레퍼런스 바이 비(REFERENCE by B),2025년 11월,19800,8.0,2

1. 베스트셀러 전체 책 가져오기
2. 저자/역자 구분하기
3. 저자가 여러명일 경우 저자 모두 추출해서 가져오기
4. 원저, 그림, 역자, 감수가 있을 경우에도 모두 분리하기
5. 책 상세페이지 링크도 수집
------------------------------------------------------------
1. 상세페이지로 들어가 품목 정보에서 페이지수 추출
2. 카테고리 분류 내용 가져오기
3. 책소개 글 가져오기

In [40]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [41]:
author_list = []

for page in range(1,10):
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = bs(r.content, 'lxml')
    book_list = response.select("#yesBestList > li")
    print(f"{page+1}/9 페이지 수집중                 ")
    
    for idx, book in enumerate(book_list):
        print(f"{idx+1}/{len(book_list)} 자료 수집중", end="\r")
        result = dict(책제목="", 저 = "", 원저 = "", 글 = "", 역 = "", 글그림 = "", 사진 = "", 감수="",
                            그림 = "", 공저 = "", 기획="")
        result['책제목'] = book.select_one(".gd_name").text
        # 저자추출
        if "/" not in book.select_one(".authPub.info_auth").text:
            result['저'] = text_clean(book.select_one(".authPub.info_auth").text) 
        elif "/" in book.select_one(".authPub.info_auth").text:
            n_item = len(book.select_one(".authPub.info_auth").text.split("/"))
            items = book.select_one(".authPub.info_auth").text.split("/")
    #         print(idx, n_item, items, end="\n\n")
            if n_item == 2 and "정보 더 보기" in items[0]:
                result['저'] = text_clean(book.select_one(".moreAuthLiCont").text.replace("\n", " "))
            elif n_item >= 2 and "정보 더 보기" not in items[0]:
                for item in items:
    #                 print(item.split()[-1])
                    author_key = item.split()[-1]
                    result[author_key] = " ".join(item.split()[:-1])


        result['출판사'] = book.select_one(".authPub.info_pub > a").text
        result['출간일'] = book.select_one(".authPub.info_date").text
        result['가격'] = int(book.select_one(".yes_b").text.replace(",", ""))
        result['평점'] = float(book.select_one(".rating_grade > .yes_b").text) if book.select_one(".rating_grade > .yes_b") != None else 0
        result['리뷰수'] = int(text_clean(book.select_one(".rating_rvCount > a > em.txC_blue").text)) if book.select_one(".rating_rvCount > a > em.txC_blue") != None else 0
        result['상세링크'] = "https://www.yes24.com"+ book.select_one(".info_row.info_name > .gd_name")['href']

        author_list.append(result)
    
    time.sleep(3)
    
    
    
df = pd.DataFrame(author_list)
df

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
2/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
3/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
4/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
5/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
6/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
7/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
8/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
9/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200
10/9 페이지 수집중

,책제목,저,원저,글,역,글그림,사진,감수,그림,공저,...,평점,리뷰수,상세링크,편,등저,편저,해설,편역,보기,이정모
0,최소한의 삼국지,최태성,,,,,,이성원,,,...,10.0,42,https://www.yes24.com/product/goods/166390503,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,트렌드 코리아 2026,김난도 전미영 최지혜 권정윤 한다혜 이혜원 이수진 서유현 전다현 이준영 이향은 김나은,,,,,,,,,...,9.2,164,https://www.yes24.com/product/goods/153064968,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,어른의 행복은 조용하다,태수,,,,,,,,,...,9.5,405,https://www.yes24.com/product/goods/136298166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,혼모노,성해나,,,,,,,,,...,9.1,688,https://www.yes24.com/product/goods/143911524,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,박곰희 연금 부자 수업 (10만 부 기념 스페셜 에디션),박곰희,,,,,,,,,...,9.7,189,https://www.yes24.com/product/goods/148032819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,최고의 주식 최적의 타이밍,윌리엄 J. 오닐,,,,,,,,,...,9.2,171,https://www.yes24.com/product/goods/7240183,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,불꽃 수영 대회,,,신현경,,,,,노예지,,...,9.9,151,https://www.yes24.com/product/goods/141180543,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,"돈, 뜨겁게 사랑하고 차갑게 다루어라",앙드레 코스톨라니,,,한윤진,,,,,,...,10.0,1,https://www.yes24.com/product/goods/167475858,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,제1회 안타까운 동물 자랑 대회,,,,이선희,,,,"시모마 아야에, 가와무라 후유미, 도쿠나가 아키코",,...,9.9,25,https://www.yes24.com/product/goods/160088937,NaN,NaN,NaN,NaN,NaN,이마이즈미 타다아키 감수 외 1명 정보 더,감추기 시모마 아야에 가와무라 후유미 도쿠나가 아키코 이선희 이마이즈미 타다아키
999,재활용의 거짓말,문관식,,,,,,,,,...,9.9,14,https://www.yes24.com/product/goods/154750530,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 상세페이지 수집하기

In [42]:
def detail_extraction(url):
    r =requests.get(url)
    soup = bs(r.content, 'lxml')
    book_page = soup.select_one(".infoSetCont_wrap > div > table > tbody > tr:nth-child(2) > td").text.split()[0][:-1] if soup.select_one(".infoSetCont_wrap > div > table > tbody > tr:nth-child(2) > td") != None else 0
    category = text_clean(soup.select_one("div.infoSetCont_wrap > dl:nth-child(1) > dd > ul").text).replace(">", " ").replace("/", " ") if soup.select_one("div.infoSetCont_wrap > dl:nth-child(1) > dd > ul") != None else "카테고리 없음"
    description = text_clean(soup.select_one(".infoWrap_txtInner").text) if soup.select_one(".infoWrap_txtInner") != None else "책소개 없음"
    return book_page, category, description

In [43]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [44]:
author_list = []

for page in range(1,10):
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = bs(r.content, 'lxml')
    book_list = response.select("#yesBestList > li")
    print(f"{page+1}/9 페이지 수집중                 ")
    
    for idx, book in enumerate(book_list):
        print(f"{idx+1}/{len(book_list)} 자료 수집중", end="\r")
        result = dict(책제목="", 저 = "", 원저 = "", 글 = "", 역 = "", 글그림 = "", 사진 = "", 감수="",
                            그림 = "", 공저 = "", 기획="")
        result['책제목'] = book.select_one(".gd_name").text
        # 저자추출
        if "/" not in book.select_one(".authPub.info_auth").text:
            result['저'] = text_clean(book.select_one(".authPub.info_auth").text) 
        elif "/" in book.select_one(".authPub.info_auth").text:
            n_item = len(book.select_one(".authPub.info_auth").text.split("/"))
            items = book.select_one(".authPub.info_auth").text.split("/")
    #         print(idx, n_item, items, end="\n\n")
            if n_item == 2 and "정보 더 보기" in items[0]:
                result['저'] = text_clean(book.select_one(".moreAuthLiCont").text.replace("\n", " "))
            elif n_item >= 2 and "정보 더 보기" not in items[0]:
                for item in items:
    #                 print(item.split()[-1])
                    author_key = item.split()[-1]
                    result[author_key] = " ".join(item.split()[:-1])


        result['출판사'] = book.select_one(".authPub.info_pub > a").text
        result['출간일'] = book.select_one(".authPub.info_date").text
        result['가격'] = int(book.select_one(".yes_b").text.replace(",", ""))
        result['평점'] = float(book.select_one(".rating_grade > .yes_b").text) if book.select_one(".rating_grade > .yes_b") != None else 0
        result['리뷰수'] = int(text_clean(book.select_one(".rating_rvCount > a > em.txC_blue").text)) if book.select_one(".rating_rvCount > a > em.txC_blue") != None else 0
        result['상세링크'] = "https://www.yes24.com"+ book.select_one(".info_row.info_name > .gd_name")['href']
        book_page, category, description = detail_extraction(result['상세링크'])
        result['페이지수'] = book_page
        result['카테고리'] = category
        result['description'] = description
        
        author_list.append(result)
    
    time.sleep(3)
    
    
    
df = pd.DataFrame(author_list)
df

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
2/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
3/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
4/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
5/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
6/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
7/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
8/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
9/9 페이지 수집중
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200
10/9 페이지 수집중

,책제목,저,원저,글,역,글그림,사진,감수,그림,공저,...,페이지수,카테고리,description,편,등저,편저,해설,편역,보기,이정모
0,최소한의 삼국지,최태성,,,,,,이성원,,,...,352,국내도서 인문 인문 교양 교양으로 읽는 인문 국내도서 인문 독서 비평 고전 읽기 ...,★★★ 대한민국 대표 지식 스토리텔러 ★★★★★★ 700만이 선택한 명강사 신간 ★...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,트렌드 코리아 2026,김난도 전미영 최지혜 권정윤 한다혜 이혜원 이수진 서유현 전다현 이준영 이향은 김나은,,,,,,,,,...,400,국내도서 경제 경영 마케팅 세일즈 트렌드 미래예측,HORSE POWERAI 대전환의 시대 무엇을 준비해야 하는가? 세상은 작용과 반작...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,어른의 행복은 조용하다,태수,,,,,,,,,...,288,국내도서 에세이 삶의 자세와 지혜 국내도서 에세이 한국 에세이,행복을 찾는 방법이 아니라불행에 대한 수비력을 길러주는58가지 인생 이야기《1cm ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,혼모노,성해나,,,,,,,,,...,368,국내도서 소설 시 희곡 한국소설 한국 단편소설,“‘몰입’의 파티다. 영화로 만들고 싶은 작품들로 가득하다.” -배우 박정민‘202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,박곰희 연금 부자 수업 (10만 부 기념 스페셜 에디션),박곰희,,,,,,,,,...,300,국내도서 경제 경영 투자 재테크 재테크일반,“연금 투자야말로 평범한 사람들이 부자가 되는 확실한 방법이다!”출간 6개월 만에 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,최고의 주식 최적의 타이밍,윌리엄 J. 오닐,,,,,,,,,...,432,국내도서 경제 경영 투자 재테크 주식 증권,1988년 미국에서 처음 출간되자마자 성공 투자의 비결을 너무나도 정확하고 냉정하게...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,불꽃 수영 대회,,,신현경,,,,,노예지,,...,양,국내도서 어린이 1-2학년 1-2학년 그림 동화책 1-2학년 창작동화 국내도서 어...,뜨거운 인기! 28주 연속 서점 베스트셀러 〈야옹이 수영 교실〉 시리즈 3권 출간2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,"돈, 뜨겁게 사랑하고 차갑게 다루어라",앙드레 코스톨라니,,,한윤진,,,,,,...,양,국내도서 경제 경영 투자 재테크 주식 증권,앙드레 코스톨라니 투자총서 시리즈 25주년 기념양장본 특별판 출시 - 3종 한정 ‘...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,제1회 안타까운 동물 자랑 대회,,,,이선희,,,,"시모마 아야에, 가와무라 후유미, 도쿠나가 아키코",,...,176,국내도서 어린이 3-4학년 3-4학년 학습 3-4학년 과학 환경 국내도서 어린이 ...,일본 530만 부 초베스트셀러 동물도감!자랑할수록 안타깝기만 한 동물들의 진화 이야...,NaN,NaN,NaN,NaN,NaN,이마이즈미 타다아키 감수 외 1명 정보 더,감추기 시모마 아야에 가와무라 후유미 도쿠나가 아키코 이선희 이마이즈미 타다아키
999,재활용의 거짓말,문관식,,,,,,,,,...,208,국내도서 사회 정치 생태 환경 환경문제,★★★2023년 올해의 환경인상 수상배우 김석훈 환경재단 최열 이사장 강력 추천재활...,NaN,NaN,NaN,NaN,NaN,NaN,NaN