In [6]:
import pandas as pd
import requests
import re
import time
from bs4 import BeautifulSoup as bs
from dbio3 import to_db, load_data

# 뉴스목록, 날짜, id수집

In [7]:
url1 = "https://fintech.or.kr/web/board/boardContentsList.do"

In [8]:
payload = dict(miv_pageNo=1, mode='W', board_id=6)

In [9]:
r1 = requests.get(url1, params=payload)
print(r1.status_code)
soup = bs(r1.content, "lxml")
soup

200

<html><head><script language="javascript">
$(document).ready(function(){

	// 댓글수 노출여부 확인후 숨기기(미구현)

		$(".comment_cnt").hide();


	// 답변 노출여부 확인후 숨기기(미구현)

		$(".reply_status").hide();


	// 모바일 전용 페이지 숨기지
	//$(".mobile_list").hide();

	$(function() {

	});

	$("#searchtxt").keydown(function(key) {
		if (key.keyCode == 13) {
			search();
		}
	});
});
</script>
</head><body><div class="boardlist_top">
<ul class="box">
<li class="select">
<div class="optionbox">
<select id="searchkey" name="searchkey">
<option value="I">전체</option>
<option value="T">제목</option>
<option value="C">내용</option>
</select>
</div>
</li>
<li class="input">
<div class="inpbox"><input class="txt" id="searchtxt" name="searchtxt" placeholder="검색어 입력" title="검색어 입력" type="text" value=""/></div>
</li>
<li class="button">
<button class="btn3 bg_blue" onclick="search();" title="검색" type="button">검색</button>
<!-- <button type="button" class="btn3 bg_gray" title="재검색">재검색</button> -->
</li>
</ul>
</div>
<!--// list_table_area -->
<div class="boardlist">
<table>
<caption>게시판 목록</caption>
<colgroup>
<col style="width: 10%;"/>
<col style="width: 75%;"/>
<col style="width: 15%;"/>
</colgroup>
<thead>
<tr>
<th class="first" scope="col">
								번호



























								</th>
<th class="" scope="col">


								제목

























								</th>
<th class="last" scope="col">























								작성일




								</th>
</tr>
</thead>
<tbody>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('961c6a72b1d0486e86711b77872a7471')">[세종테크노파크] 2025년 세종테크밸리 첨단기업 유치 임차료 지원사업 희망기업(임차기업) 모집 공고</a>
</td>
<td class="last">





























								2025-12-08








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')">[금융보안원] 「데이터허브」 이용 안내</a>
</td>
<td class="last">





























								2025-09-17








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')">[국무조정실] 규제개혁신문고 제도 안내</a>
</td>
<td class="last">





























								2024-02-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')">[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')">[신용보증기금] 스타트업 지원 업무 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')">[한국무역보험공사] K-Sure 수출컨설팅 사업 안내</a>
</td>
<td class="last">





























								2022-06-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')">[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내</a>
</td>
<td class="last">





























								2021-12-03








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')">[웰컴저축은행] 마이데이터 서비스 제휴 솔루션</a>
</td>
<td class="last">





























								2021-04-07








































							</td>
</tr>
<tr>
<td class="first">




									6859




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('31c875b19d884ba5aab60d1cfae1411a')">[12/09 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-09








































							</td>
</tr>
<tr>
<td class="first">




									6858




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('6e8f6c4a35394b3f851c156b71ca33b7')">[12/08 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-08








































							</td>
</tr>
<tr>
<td class="first">




									6857




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('796323edef8b4ca79c0a2bbf17a262c3')">[12/05 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-05








































							</td>
</tr>
<tr>
<td class="first">




									6856




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('778f539d67bd409daaaba7ad7dc09aa5')">[12/04 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-04








































							</td>
</tr>
<tr>
<td class="first">




									6855




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('9bc42721d9a84e6295893e5b0ee07581')">[12/03 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-03








































							</td>
</tr>
<tr>
<td class="first">




									6854




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('c23ab5f950854287905dfeb7f6f94664')">[12/02 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-02








































							</td>
</tr>
<tr>
<td class="first">




									6853




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('ca4e219afc7747ec941b31d5eff7cb1f')">[12/01 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-12-01








































							</td>
</tr>
</tbody>
</table>
<!-- mobile -->
<ul class="list">
<li class="notice_line">
<a href="javascript:contentsView('961c6a72b1d0486e86711b77872a7471')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[세종테크노파크] 2025년 세종테크밸리 첨단기업 유치 임차료 지원사업 희망기업(임차기업) 모집 공고



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-08</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[금융보안원] 「데이터허브」 이용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-09-17</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[국무조정실] 규제개혁신문고 제도 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2024-02-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[신용보증기금] 스타트업 지원 업무 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국무역보험공사] K-Sure 수출컨설팅 사업 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-06-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-12-03</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[웰컴저축은행] 마이데이터 서비스 제휴 솔루션



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-04-07</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('31c875b19d884ba5aab60d1cfae1411a')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/09 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-09</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('6e8f6c4a35394b3f851c156b71ca33b7')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/08 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-08</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('796323edef8b4ca79c0a2bbf17a262c3')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/05 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-05</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('778f539d67bd409daaaba7ad7dc09aa5')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/04 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-04</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('9bc42721d9a84e6295893e5b0ee07581')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/03 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-03</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('c23ab5f950854287905dfeb7f6f94664')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/02 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-02</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('ca4e219afc7747ec941b31d5eff7cb1f')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[12/01 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-12-01</li>
</ul>
</a>
</li>
</ul>
<!--//mobile -->
</div>
<!--// list_table_area -->
<!-- button_area -->
<div class="btn_box ar">
</div>
<!--// button_area -->
<!-- paging_area -->
<div class="paging web_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a><a href="javascript:go_Page(6);" title="6">6</a><a href="javascript:go_Page(7);" title="7">7</a><a href="javascript:go_Page(8);" title="8">8</a><a href="javascript:go_Page(9);" title="9">9</a><a href="javascript:go_Page(10);" title="10">10</a></span><button class="btn-paging-next" onclick="go_Page(11);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(458)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area -->
<!-- paging_area -->
<div class="paging mobile_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a></span><button class="btn-paging-next" onclick="go_Page(6);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(458)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area --></body></html>

mobile용

In [10]:
len(soup.select("ul.list > li > a"))

15

Web용은 Table 안에

In [11]:
# 제목과 뉴스 id 
soup.select("a.txtl")

[<a class="txtl" href="javascript:contentsView('961c6a72b1d0486e86711b77872a7471')">[세종테크노파크] 2025년 세종테크밸리 첨단기업 유치 임차료 지원사업 희망기업(임차기업) 모집 공고</a>,
 <a class="txtl" href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')">[금융보안원] 「데이터허브」 이용 안내</a>,
 <a class="txtl" href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')">[국무조정실] 규제개혁신문고 제도 안내</a>,
 <a class="txtl" href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')">[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내</a>,
 <a class="txtl" href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')">[신용보증기금] 스타트업 지원 업무 안내</a>,
 <a class="txtl" href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')">[한국무역보험공사] K-Sure 수출컨설팅 사업 안내</a>,
 <a class="txtl" href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')">[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내</a>,
 <a class="txtl" href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')">[웰컴저축은행] 마이데이터 서비스 제휴 솔루션</a>,
 <a class="txtl" href="javascript:contentsView('31c875b19d884ba5aab60d1cfae1411a')">[12/09 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('6e8f6c4a35394b3f851c156b71ca33b7')">[12/08 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('796323edef8b4ca79c0a2bbf17a262c3')">[12/05 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('778f539d67bd409daaaba7ad7dc09aa5')">[12/04 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('9bc42721d9a84e6295893e5b0ee07581')">[12/03 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('c23ab5f950854287905dfeb7f6f94664')">[12/02 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('ca4e219afc7747ec941b31d5eff7cb1f')">[12/01 핀테크 주요뉴스]</a>]

web용은 Table 안에

In [12]:
# 제목과 뉴스 id 
soup.select("a.txtl")[0]['href'].split("'")[1]

'961c6a72b1d0486e86711b77872a7471'

In [13]:
# 날짜
soup.select("td.last")[0].text.strip()

'2025-12-08'

# news list id와 날짜 모으기

In [14]:
contents_id_list = []
for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
    date = date.text.strip()
    contents_id = content_list['href'].split("'")[1]
    contents_id_list.append((date, contents_id))
contents_id_list

[('2025-12-08', '961c6a72b1d0486e86711b77872a7471'),
 ('2025-09-17', 'b4b0b17c318d45158645c81c1472e29a'),
 ('2024-02-20', '51cb0e37c4064f2a985436e2ae3378df'),
 ('2022-12-19', '3c24d05040984c79a7cdfd2c921952eb'),
 ('2022-12-19', '25f4360d5b9847a996828099e8d52ade'),
 ('2022-06-20', '9c16609a99ad4c55914ffa9a7f2d58b7'),
 ('2021-12-03', '6b14460b5adc480aa050c4c535af8b72'),
 ('2021-04-07', 'd4cbbeb3f9b3444cbf1856b48f9f2926'),
 ('2025-12-09', '31c875b19d884ba5aab60d1cfae1411a'),
 ('2025-12-08', '6e8f6c4a35394b3f851c156b71ca33b7'),
 ('2025-12-05', '796323edef8b4ca79c0a2bbf17a262c3'),
 ('2025-12-04', '778f539d67bd409daaaba7ad7dc09aa5'),
 ('2025-12-03', '9bc42721d9a84e6295893e5b0ee07581'),
 ('2025-12-02', 'c23ab5f950854287905dfeb7f6f94664'),
 ('2025-12-01', 'ca4e219afc7747ec941b31d5eff7cb1f')]

In [15]:
# newslist의 url
url2 = "https://fintech.or.kr/web/board/boardContentsView.do"

In [16]:
# news list의 payload
payload2 = dict(miv_pageNo=1, mode="W", contents_id="39547f2a0ee34a5097ff4e92f6df9f6e", board_id=6, searchkey="I")

In [17]:
r2 = requests.get(url2, params=payload2)
print(r2.status_code)
soup2 = bs(r2.content,'lxml')
soup2

200

<!DOCTYPE html>
<html lang="ko" xml:lang="ko">
<head>
<title>


		핀테크 포털 - 한국핀테크지원센터

		</title>
<meta content="핀테크 생태계 활성화로 금융의 혁신과 성장을 지원합니다.." name="description"/>
<meta content="핀테크 포털 - 한국핀테크지원센터" name="keywords"/>
<meta content="http://fintech.or.kr/images/preview_page.png" property="og:image"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" name="viewport"/>
<meta content="XpressEngine" name="Generator"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="o8yb702i79l2intg1e9ov2hyavzbji" name="facebook-domain-verification"/>
<!-- <link rel="shortcut icon" href="/images/web/favicon.ico" type="image/x-icon"> -->
<!-- <link rel="icon" href="/images/web/favicon.ico" type="image/x-icon"> -->
<link href="/css/web/default.css?ver=20200916" rel="stylesheet" type="text/css"/>
<link href="/css/web/reset.css?ver=20210629" rel="stylesheet" type="text/css"/>
<link href="/css/web/font.css" rel="stylesheet" type="text/css"/>
<link href="/css/web/contents.css?ver=20211018" rel="stylesheet" type="text/css"/>
<link href="/css/web/table.css?ver=202110181" rel="stylesheet" type="text/css"/>
<link href="/css/web/slick.css?ver=20210530" rel="stylesheet" type="text/css"/>
<link href="/css/web/jquery-ui.min.css?ver=1" rel="stylesheet" type="text/css"/>
<link href="/css/web/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/css/common.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/js/jquery.ui.monthpicker.js" type="text/javascript"></script>
<script src="/js/jquery.dropselect.js" type="text/javascript"></script>
<script src="/js/accordion.js" type="text/javascript"></script>
<script src="/js/loadingoverlay.min.js" type="text/javascript"></script>
<script type="text/javascript">

			$(document).ready(function() {
				$(".mobile_gnb").accordion({
					accordion:true,
					speed: 0,
				});
			});

			var g_http_url   = "null";
			var g_https_url  = "null";
			var g_user_no	= "";

			var g_menu_1	 = "";  	//메뉴1
			var g_menu_2	 = "";  	//메뉴2
			var g_menu_3	 = "";  	//메뉴3
			var g_menu_4	 = "";  	//메뉴4
			var g_cmm_param  = "?miv_pageNo=1&amp;mode=W&amp;contents_id=39547f2a0ee34a5097ff4e92f6df9f6e&amp;board_id=6&amp;searchkey=I";
			var homepage 	 = "null";
			var tabTitle 	 = "한국핀테크지원센터 홈페이지";

			var g_topmenu_id = "";  		//topmenu_id
			var g_submenu_id = "";  		//submenu_id



			var g_menu_navi_nm 	= "";  	//menu_navi_nm ( 구분자 # )
			var g_menu_navi_id 	= "";  	//menu_navi_id ( 구분자 # )

			function goPortalLogin() {
				if(g_user_no != ""){
				    $("#PORTALID").val("");
				    frmP.target="_blank";
				    frmP.method="post";
				    frmP.action="https://finedu.fintech.or.kr/FLMSApps/LmsLogin";
				    //frmP.action="http://103.244.108.212:8080/FLMSApps/imsiLogin.jsp";
				    //frmP.action="http://103.244.108.212:8080/FLMSApps/LmsLogin";
				    frmP.submit();
				}else{
					window.open('https://finedu.fintech.or.kr/FLMSApps/jsp/Common/LmsMain/fin-top.jsp');
				}
			 }
		</script>
<!--[if lt IE 9]>
			<script src="js/vendor/html5shiv.js"></script>
			<script src="js/vendor/respond.min.js"></script>
		<![endif]-->
<script src="/assets/jquery/jquery.form.js" type="text/javascript"></script>
<script type="text/javascript">
			// ready
			$(document).ready(function(){
				// 메뉴 조회

				// 네이게이션의 서브 메뉴 조회

				// 메뉴가 없을 경우 아래 로직 실행



					var uri = "/web/board/boardContentsView.do";
					var page_id = " ";
					var board_id = "6 ";
					var company_id = " ";
					$.ajax({
						type : "POST",
						url : "/web/menu/selectFrontMenuList_pre.do",
						dataType : 'json',
						data : {uri : uri, page_id : page_id, board_id : board_id, company_id :company_id},
						async : false,
						success : function(data) {
							g_topmenu_id = data.menu_info.topmenu_id;  		//topmenu_id
							g_submenu_id = data.menu_info.menu_id;  		//submenu_id
							g_menu_navi_nm = data.menu_info.menu_navi;  		//menu_navi_id ( 구분자 #1 )
							g_menu_navi_id = data.menu_info.menu_navi_id;  		//menu_navi_nm ( 구분자 # )
							g_menu_2 = data.menu_info.up_menu_id2;
							$(".contents_title").eq(0).html("");
							$(".contents_title").eq(0).prepend('<h2 tabindex="0">'+data.menu_info.menu_nm+'</h2>');
							$("#lnb_area_h2").html(data.menu_info.up_menu_nm1);
							lnbAreaSetting(g_topmenu_id);
							$("#ajax_nav").html(data.g_menu_navi);
						    loadMenu(homepage,'S');
						    loadNaviMenu();
						}
					});




				function lnbAreaSetting(mId){
					var bgSub = "";
					if ( mId =='1000'){bgSub="sub1";}
					if ( mId =='2000'){bgSub="sub2";}
					if ( mId =='3000'){bgSub="sub3";}
					if ( mId =='4000'){bgSub="sub4";}
					if ( mId =='5000'){bgSub="sub5";}
					if ( mId =='6000'){bgSub="sub6";}
					if ( mId =='7000'){bgSub="sub7";}
					if ( mId =='8000'){bgSub="sub8";}
					if ( mId =='9000'){bgSub="sub9";}
					if ( mId =='9400'){bgSub="sub10";}
					if ( mId =='10000'){bgSub="sub1";}
					$("#lnb_area_div").removeClass();
					$("#lnb_area_div").addClass("lnb_area");
					$("#lnb_area_div").addClass(bgSub);
				}


				//$("#language").show();
				//메인링크 변경시
				//$("#mainLink").change(function() {
				//	location.href = $(this).val();
				//});

				//$("#tabLink1,#selBrdId").change(function() {
				//	location.href = $(this).val();
				//});
			});
		</script>
<script src="/js/web_main.js?ver=20200916" type="text/javascript"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-181533868-1"></script>
<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-181533868-1');
		</script>
<!-- Facebook Pixel Code -->
<script>
		!function(f,b,e,v,n,t,s)
		{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};
		if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
		n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];
		s.parentNode.insertBefore(t,s)}(window, document,'script',
		'https://connect.facebook.net/en_US/fbevents.js');
		fbq('init', '606167354025125');
		fbq('track', 'PageView');
		</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=606167354025125&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
</head>
<body id="sub">
<dl class="skipnavi">
<dt>메뉴 건너띄기</dt>
<dd>
<!--  2021/12/1   반복영역 건너뛰기  -->
<a href="#topMenu">상단메뉴 바로가기..</a>
<a href="#Content">본문 바로가기</a>
</dd>
</dl>
<div id="wrap">
<script>

   var test="false";
</script>
<!-- S: toparea pc-->
<div class="toparea" id="header">
<div class="top_nav">
<ul>
<!-- 로그인 전 -->
<li><a href="javascript:goPage('9100', '', '');" title="로그인">로그인</a></li>
<li><a href="javascript:goPage('9300', '', '');" title="회원가입">회원가입</a></li>
<!--// 로그인 전 -->
<li><a href="/web/user/enMain.do" title="ENG">ENG</a></li>
<!-- <li><a href="javascript:alert('준비중입니다.');" title="ENG">ENG</a></li> -->
</ul>
</div>
<div class="topmenu">
<h1>
<a href="/" title="메인으로 이동"></a>
</h1>
<a href="#n" id="topMenu" style="position: absolute; width: 0; height: 0; overflow: hidden;" tabindex="-1">상단메뉴 시작</a> <!--  2021/12/1  반복영역 건너뛰기 -->
<ul class="gnb" id="gnb">
<!-- 탑메뉴 1뎁스 2뎁스 까지 나옴  -->
</ul>
<div class="bg-topmenu-on"></div>
<button class="total_search" onclick="goPage('9999','','');" type="button"></button>
<button class="all_menu" type="button">
<span class="line line1"></span>
<span class="line line2"></span>
<span class="line line3"></span>
</button>
<div class="all_menu_area">
<ul class="menu_list" id="sitemap_box">
</ul>
</div>
</div>
<button class="btn-category-holder" onclick="mobileMenuToggle('open')" title="모바일 메뉴 열림" type="button">
<span class="line line1"></span>
<span class="line line2"></span>
<span class="line line3"></span>
</button>
<div class="mobile-category">
<div class="mobild_menu">
<button class="close" onclick="mobileMenuToggle('close')" title="모바일 메뉴 닫기" type="button"></button>
<div class="top_nav">
<ul>
<!-- 로그인 전 -->
<li><a href="javascript:goPage('9100', '', '');" title="로그인">로그인</a></li>
<li><a href="javascript:goPage('9300', '', '');" title="회원가입">회원가입</a></li>
<!-- 로그인 후 -->
<!-- <li><a href="javascript:void(alert('준비중입니다.'));" title="ENG">ENG</a></li> -->
</ul>
</div>
<div class="search_box">
<input placeholder="검색어를 입력하세요" title="검색어를 입력하세요" type="text"/>
<button title="검색" type="button"></button>
</div>
<ul class="mobile_gnb" id="MobileTopMenu">
<!-- 모바일 메뉴 -->
</ul>
</div>
</div>
</div>
<!-- //E: toparea -->
<!--//S: lnb -->
<div class="lnb_area sub1" id="lnb_area_div">
<h2 id="lnb_area_h2"></h2>
<div class="lnb web">
<ul class="list" id="NaviSubMenu">
<!-- 웹 서브메뉴 (2뎁스▼|2뎁스▼|2뎁스▼|2뎁스▼|2뎁스▼) -->
</ul>
</div>
<div class="lnb mobile">
<ul class="list" id="NaviSubMenu2">
<!-- 모바일 서브메뉴 (1뎁스▼|2뎁스▼|3뎁스▼)-->
</ul>
</div>
</div>
<!--//E: lnb -->
<!-- S: midarea -->
<div class="midarea">
<!--//S: contentsarea -->
<div class="contentsarea">
<a href="#n" id="Content" style="position: absolute; width: 0; height: 0; overflow: hidden;" tabindex="-1">본문 시작</a><!--  2021/12/1  반복영역 건너뛰기   -->
<nav id="ajax_nav">
<!-- <ul>
				<li class="home"><a href="/" title="메인 페이지로 이동">HOME</a></li>
				<li><a href="../main.html" title="메인 페이지로 이동">센터소개</a></li>
				<li><span>인사말</span></li>
			</ul> -->
</nav>
<div class="contents_title"><h2 tabindex="01"></h2></div>
<!-- 내용 -->
<script language="javascript">
var boardContentsListPageUrl 	= "/web/board/boardContentsListPage.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var boardContentsWriteUrl 		= "/web/board/boardContentsWrite.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var boardContentsViewUrl 		= "/web/board/boardContentsView.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var deleteBoardContentsUrl 		= "/web/board/deleteBoardContents.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var chkCommentUrl 				= "/web/board/chkComment.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var saveCommentUrl 				= "/web/board/saveComment.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var deleteCommentUrl 			= "/web/board/deleteComment.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var boardCommentListUrl 		= "/web/board/boardCommentList.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var saveSatisfyUrl 				= "/web/board/saveSatisfy.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var saveRecommendUrl 			= "/web/board/saveRecommend.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var loadRecommendUrl 			= "/web/board/loadRecommend.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";
var passPopupUrl 				= "/web/board/boardContentsPassPopup.do;jsessionid=E9521F5E484F05CC20190D43E78B8EA6.fintech";

var cmt_el;
var cmt_commentid;
var mode;

//목록으로
function list(){
	var f = document.writeFrm;

	f.target = "_self";
	f.action = boardContentsListPageUrl;
	f.submit();
}

//게시물 수정
function contentsEdit(){
	var f = document.writeFrm;

	f.target = "_self";
	f.action = boardContentsWriteUrl;
	f.submit();
}

//게시물 삭제
function contentsDelete(){

	var url = deleteBoardContentsUrl;
	var f = document.writeFrm;

	// 패스워드가 있는 경우 페이지로 보낸다.



	if (confirm('게시물을 삭제하시겠습니까?')) {
		$.ajax({
			type: "POST",
			url: url,
			data :jQuery("#writeFrm").serialize(),
			dataType: 'json',
			success:function(data){
				alert(data.message);
				if(data.success == "true"){
					goList();
				}
			}
		});
	}

}

//답글 쓰기
function contentsReply(){
	var f = document.writeFrm;

	$("#mode").val("R");

	f.target = "_self";
	f.action = boardContentsWriteUrl;
	f.submit();
}

//게시물 뷰
function contentsView(contentsid){
	var f = document.writeFrm;

	$("#contents_id").val(contentsid);

	f.target = "_self";
	f.action = boardContentsViewUrl;
	f.submit();
}

// 만족도 저장
function saveSatisfy(){

	// 로그인 여부 확인하기
	var sid = "";
	var yn  = "N";
	if(sid == ""){
		alert("로그인이 후 참여 가능합니다.");
		goPage('9100', '', '');
		return;
	}

	if(yn == "Y"){
		alert("이미 참여하였습니다.");
		return;
	}

	var url = saveSatisfyUrl;
	if (confirm('만족도를 저장하시겠습니까?')) {
		$.ajax({
			type: "POST",
			url: url,
			data :jQuery("#satisfyFrm").serialize(),
			dataType: 'json',
			success:function(data){
				alert(data.message);
				if(data.success == "true"){
					$(".satisfaction_area").hide();
				}
			}
		});
	}
}

// 추천하기
function saveRecommend(){

	// 로그인 여부 확인하기
	var sid = "";
	if(sid == ""){
		alert("로그인이 후 참여 가능합니다.");
		goPage('9100', '', '');
		return;
	}

	var url = saveRecommendUrl;
	$.ajax({
		type: "POST",
		url: url,
		data : {
			contents_id : "39547f2a0ee34a5097ff4e92f6df9f6e",
			recommend_yn : $("#recommend_yn").val()
		},
		dataType: 'json',
		success:function(data){
			alert(data.message);
			// 추천가져오기
			loadRecommend();
		}
	});
}

// 추천가져오기
function loadRecommend(){
	var url = loadRecommendUrl;
	$.ajax({
		type: "POST",
		url: url,
		data : {
			contents_id : "39547f2a0ee34a5097ff4e92f6df9f6e",
		},
		dataType: 'json',
		success:function(data){
			if(data.recommend_yn == "Y"){
				$("#recommend_cnt").html(data.recommend_cnt);
				$("#recommend_yn").val(data.recommend_yn);
				$(".btn_recommend").addClass("pick");
			}else{
				$("#recommend_cnt").html(data.recommend_cnt);
				$("#recommend_yn").val(data.recommend_yn);
				$(".btn_recommend").removeClass("pick");
			}
		}
	});
}

</script>
<form id="writeFrm" method="post" name="writeFrm" onsubmit="return false;">
<input id="mode" name="mode" type="hidden" value="E"/>
<input id="board_id" name="board_id" type="hidden" value="6"/>
<input id="contents_id" name="contents_id" type="hidden" value="39547f2a0ee34a5097ff4e92f6df9f6e"/>
<input id="recommend_yn" name="recommend_yn" type="hidden" value=""/>
<input id="miv_pageNo" name="miv_pageNo" type="hidden" value="1"/>
<input id="s_reply_ststus" name="s_reply_ststus" type="hidden" value=""/>
<input id="s_searchkey" name="s_searchkey" type="hidden" value="I"/>
<input id="s_searchtxt" name="s_searchtxt" type="hidden" value=""/>
<input id="s_cate_id" name="s_cate_id" type="hidden" value=""/>
</form>
<!--//S: 게시판 상세 -->
<div class="board_detail">
<div class="title_box">
<h3>
			[11/26 핀테크 주요뉴스]
		</h3>
<ul class="list">
<li>작성일 : 2025-11-26</li>
</ul>
</div>
<!-- view_area -->
<ul class="list">
</ul>
<!-- view_area -->
<!-- view_area -->
<!-- editor -->
<div class="content" style="min-height:300px;"><meta charset="utf-8"/>
<title>한국핀테크지원센터 오늘의 핀테크 뉴스</title>
<table background="https://fintech.or.kr/contents/commoneditor/2023060509104055668f3c-4a91-42e6-8c10-b38683dddbd4.jpg" border="0" cellpadding="0" cellspacing="0" height="546" style="margin-left:auto;margin-right:auto;" width="800">
<tbody>
<tr>
<td height="100" width="250"> </td>
<td height="100" width="300"><p align="center" style="font-family: 'Malgun Gothic'; font-weight: bolder; color: #FFFFFF; font-size:large;">2025년 11월 26일 수요일</p></td>
<td height="100" width="250"> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
</tr>
</tbody>
</table>
<table style="width:800px;margin-left:auto;margin-right:auto;table-layout:fixed;overflow-wrap:break-word;word-break:normal;">
<tbody><tr style="padding:0px;width:800px;height:57px;">
<td style="padding:0px;width:800px;height:57px;">
<br/>
<img height="57" src="https://fintech.or.kr/contents/commoneditor/20230605091104a13db107-e4a5-45c8-8a58-0a7709898024.jpg" width="800"/><br/>
</td>
</tr>
<tr style="width:800px;height:10px;"> <td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">1. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&amp;contents_id=ba9a817cc8434910a4c6f47ff2e19099&amp;menu_id=6300" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모집(~12.8.)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">2. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=1&amp;contents_id=1506a705524144328f7f1a6e88785b11&amp;menu_id=6100" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크산업협회] 네트워킹 행사 '핀테크 커넥팅 데이 2025' 개최(11.26.) ※신청: ~11.20.</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">3. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&amp;contents_id=e04c846efa67421db116e5533c0d8bd2&amp;menu_id=6300" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">4. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=1&amp;contents_id=abc17a4ab12d4c79ae94d177994b4d57&amp;menu_id=6100" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr style="padding:0px;width:800px;height:57px;">
<td style="padding:0px;width:800px;height:57px;">
<br/>
<img height="57" src="https://fintech.or.kr/contents/commoneditor/20230605091116ca5c2c72-878f-4e89-b389-6ac5193954ae.jpg" width="800"/><br/>
</td>
</tr>
<tr style="width:800px;height:10px;"> <td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">1. </span><a href="https://n.news.naver.com/mnews/article/008/0005282738?sid=101" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">"부산을 해양금융 허브로"…금감원·부산시·해진공·조선업계 총집결</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"> (머니투데이, 11/25) </span></td>
</tr>

In [18]:
# 뉴스 리스트 목록
soup2.select("tbody td a")[0].text

"[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모집(~12.8.)"

In [19]:
soup2.select("tbody td a")[0]['href']

'https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&contents_id=ba9a817cc8434910a4c6f47ff2e19099&menu_id=6300'

In [20]:
soup2.select("tbody td a")[6]['href']

'https://n.news.naver.com/mnews/article/003/0013620831?sid=101'

# 위에서 개별 작업한 코드 모으기

In [21]:
# 핀테크 뉴스 리스트, 날짜, content_id 수집
contents_id_list = []
for page in range(1, 20):
    url1 = "https://fintech.or.kr/web/board/boardContentsList.do"
    payload = dict(miv_pageNo=page, mode='W', board_id=6)
    r1 = requests.post(url1, data=payload)
    print(r1.status_code)
    soup = bs(r1.content, "lxml")

    for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
        date = date.text.strip()
        contents_id = content_list['href'].split("'")[1]
        contents_id_list.append((date, contents_id))
    time.sleep(2)

result = {}
# 날짜별 뉴스 리스트의 세부 뉴스 제목, 링크
for idx, (date, content_id) in enumerate(contents_id_list):
    print(f"{idx+1}/{len(contents_id_list)} 수집중", end="\r")
    url2 = "https://fintech.or.kr/web/board/boardContentsView.do"
    payload2 = dict(miv_pageNo=1, mode="W", contents_id=content_id, board_id=6, searchkey="I")
    r2 = requests.get(url2, params=payload2)
#     print(r2.status_code)
    soup2 = bs(r2.content,'lxml')

    for td in soup2.select("tbody td a"): 
        if "https://n.news.naver.com" in td['href'] or "https://fintech.or.kr/web/" in td['href']:
            result.setdefault('date', []).append(date)
            result.setdefault('제목', []).append(td.text)
            result.setdefault('뉴스링크', []).append(td['href'])
            
df = pd.DataFrame(result)
df

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

,date,제목,뉴스링크
0,2025-12-09,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...
1,2025-12-09,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...
2,2025-12-09,"금융위, 새도약기금 소각식…""취약층 연체채권 1.1조 소각""",https://n.news.naver.com/mnews/article/003/001...
3,2025-12-09,한·일 금융감독 정례회의…국제금융협력 포럼도 개최,https://n.news.naver.com/mnews/article/277/000...
4,2025-12-09,"해외투자 급증에… 금감원, 키움·하나증권 영업 실태 점검",https://n.news.naver.com/mnews/article/366/000...
...,...,...,...
11702,2025-01-02,"""당장 돈 안되고 성능향상 기대 못 미쳐도""… 세계는 AI인프라 `영끌`",https://n.news.naver.com/mnews/article/029/000...
11703,2025-01-02,트럼프 2.0시대 중국…미 동맹국 이탈 기대하며 버티기[다시 만난 트럼프②],https://n.news.naver.com/mnews/article/032/000...
11704,2025-01-02,'美 51번째 주' 모욕 당했는데…트럼프에 찍소리 못하는 이유 [김리안의 에네르기파...,https://n.news.naver.com/mnews/article/015/000...
11705,2025-01-02,[산업은행] 2025년 상반기 KDB NextONE 참여 스타트업 모집(서울/부산)...,https://fintech.or.kr/web/board/boardContentsV...
11706,2025-01-02,[우리금융그룹] 디노랩 부산 1기 참여 스타트업 모집(~25.1.12),https://fintech.or.kr/web/board/boardContentsV...

# 세부링크로 들어가서 뉴스 본문 수집

In [22]:
df2 = df[df['date'] > "2025-01-01"].copy()

In [23]:
df2['뉴스링크'][6]

'https://n.news.naver.com/mnews/article/119/0003034561?sid=101'

In [24]:
# 핀테크 지원센터 글
r3 = requests.get(df2['뉴스링크'][0])
soup3 = bs(r3.content, 'lxml')
soup3.select_one("div.content").text

'안녕하세요.\xa0한국핀테크지원센터입니다.2025년 금융특화 계층별\xa0AI역량강화 과정\xa0‘핀테크를 통한 금융\xa0AI\xa0트렌드와 혁신 사례’이 아래 일정으로 진행됩니다.많은 관심과 참여 바랍니다.\xa0□\xa0(교육대상)\xa0금융·인공지능에 관심 있는 누구나\xa0□\xa0(교육기간)\xa0~ 2025.12.31.(수)\xa0상시\xa0□\xa0(교육방식)\xa0온라인 수강(https://fintech.ekma.co.kr)\xa0□\xa0(교 육 비)\xa0전액지원\xa0□\xa0(교육혜택)\xa0수강 과정 코스별 한국핀테크지원센터 수료증 발급\xa0□\xa0(커리큘럼)\xa0차수강의명강사1핀테크 비즈니스 현황 및 트렌드SK증권 서영수 상무2핀테크 비즈니스\xa0AI\xa0활용 현황자본시장연구원 이성복 선임연구위원3핀테크 비즈니스\xa0AI\xa0혁신 사례한국오라클 김현웅 본부장4금융분야의\xa0AI\xa0도입을 위한 규제법무법인 덕수 신하나 변호사5간편결제 사례한국핀테크산업협회 이근주 회장6자산관리 사례자본시장연구원 이성복 선임연구위원7여신 분야\xa0AI\xa0사례길진세 한국금융연수원 강사8은행 분야\xa0AI\xa0사례길진세 한국금융연수원 강사9인슈어테크 사례1네이버 최욱동 리더10인슈어테크 사례2네이버 최욱동 리더👉\xa0교육신청 바로가기'

In [25]:
# 네이버뉴스 글
r3 = requests.get(df2['뉴스링크'][6])
soup3 = bs(r3.content, 'lxml')
soup3.select_one("#dic_area").text

'\n금융상품·부채관리 등 실생활 금융교육대학생 금융 이해력 제고\n\n\n\n금융감독원이 전국 대학을 대상으로 2026년 1학기 ‘실용금융’ 강좌 개설 지원 신청을 받는다.ⓒ연합뉴스[데일리안 = 김민환 기자] 금융감독원은 전국 대학을 대상으로 2026년 1학기 ‘실용금융’ 강좌 개설 지원 신청을 받는다고 9일 밝혔다. 오는 31일까지 신청을 접수해 강좌를 개설하는 대학에 금융교육 교수 인력과 교재, 온라인 강좌 자료 등을 지원할 예정이다.‘실용금융’은 금융상품 이해, 부채 및 신용관리, 연금, 보험, 금융소비자 보호 제도 등 실생활에 필요한 금융지식을 다루는 강좌로, 금감원은 2016년부터 해당 강좌를 개설하는 대학을 대상으로 지원 사업을 운영해 왔다.올해 2학기에는 전국 65개 대학에서 76개 실용금융 강좌가 개설돼 약 4748명이 수강 중이며, 수강생을 대상으로 한 설문조사에서 금융 이해도 향상과 강의 만족도가 높은 것으로 나타났다.금감원은 대학의 방식에 따라 금융 관련 현장 경험을 갖춘 금감원 직원의 직접 출강, 학생용 교재 제공, 교수 보조자료 지원, 정규 온라인 강좌용 강의 영상과 학습 자료 제공 등 다양한 형태로 지원할 계획이다.신청은 금감원 e-금융교육센터 홈페이지를 통해 온라인으로 가능하며, 기타문의는 금감원 금융교육국을 통해 안내받을 수 있다.\n\t\t'

In [26]:
df2['뉴스본문'] = ""
df2

,date,제목,뉴스링크,뉴스본문
0,2025-12-09,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...,
1,2025-12-09,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...,
2,2025-12-09,"금융위, 새도약기금 소각식…""취약층 연체채권 1.1조 소각""",https://n.news.naver.com/mnews/article/003/001...,
3,2025-12-09,한·일 금융감독 정례회의…국제금융협력 포럼도 개최,https://n.news.naver.com/mnews/article/277/000...,
4,2025-12-09,"해외투자 급증에… 금감원, 키움·하나증권 영업 실태 점검",https://n.news.naver.com/mnews/article/366/000...,
...,...,...,...,...
11702,2025-01-02,"""당장 돈 안되고 성능향상 기대 못 미쳐도""… 세계는 AI인프라 `영끌`",https://n.news.naver.com/mnews/article/029/000...,
11703,2025-01-02,트럼프 2.0시대 중국…미 동맹국 이탈 기대하며 버티기[다시 만난 트럼프②],https://n.news.naver.com/mnews/article/032/000...,
11704,2025-01-02,'美 51번째 주' 모욕 당했는데…트럼프에 찍소리 못하는 이유 [김리안의 에네르기파...,https://n.news.naver.com/mnews/article/015/000...,
11705,2025-01-02,[산업은행] 2025년 상반기 KDB NextONE 참여 스타트업 모집(서울/부산)...,https://fintech.or.kr/web/board/boardContentsV...,
11706,2025-01-02,[우리금융그룹] 디노랩 부산 1기 참여 스타트업 모집(~25.1.12),https://fintech.or.kr/web/board/boardContentsV...,

In [ ]:
for idx, link in enumerate(df2['뉴스링크'][:10]):
    print(f"{idx+1}/{len(df2['뉴스링크'][:10])} 수집중", end="\r")
    r4 = requests.get(link)
    soup4 = bs(r4.content, 'lxml')
    if "https://fintech.or.kr/web/" in link:
        r3 = requests.get(link)
        soup3 = bs(r3.content, 'lxml')
        article = soup3.select_one("div.content").text
        df2.loc[idx, '뉴스본문'] = article
    elif "https://n.news.naver.com" in link:
        r3 = requests.get(link)
        soup3 = bs(r3.content, 'lxml')
        article = soup3.select_one("#dic_area").text
        df2.loc[idx, '뉴스본문'] = article
    to_db("fintech_news", "news_articles", df2.loc[[idx], :])
    time.sleep(3)
df2

In [27]:
df2['뉴스본문']

0
1
2
3
4
        ..
11702
11703
11704
11705
11706
Name: 뉴스본문, Length: 11707, dtype: object

In [28]:
df2.to_csv("./data/fintech_news.csv")

In [29]:
df2 = pd.read_csv("./data/fintech_news.csv", index_col=0)
df2

,date,제목,뉴스링크,뉴스본문
0,2025-12-09,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...,NaN
1,2025-12-09,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...,NaN
2,2025-12-09,"금융위, 새도약기금 소각식…""취약층 연체채권 1.1조 소각""",https://n.news.naver.com/mnews/article/003/001...,NaN
3,2025-12-09,한·일 금융감독 정례회의…국제금융협력 포럼도 개최,https://n.news.naver.com/mnews/article/277/000...,NaN
4,2025-12-09,"해외투자 급증에… 금감원, 키움·하나증권 영업 실태 점검",https://n.news.naver.com/mnews/article/366/000...,NaN
...,...,...,...,...
11702,2025-01-02,"""당장 돈 안되고 성능향상 기대 못 미쳐도""… 세계는 AI인프라 `영끌`",https://n.news.naver.com/mnews/article/029/000...,NaN
11703,2025-01-02,트럼프 2.0시대 중국…미 동맹국 이탈 기대하며 버티기[다시 만난 트럼프②],https://n.news.naver.com/mnews/article/032/000...,NaN
11704,2025-01-02,'美 51번째 주' 모욕 당했는데…트럼프에 찍소리 못하는 이유 [김리안의 에네르기파...,https://n.news.naver.com/mnews/article/015/000...,NaN
11705,2025-01-02,[산업은행] 2025년 상반기 KDB NextONE 참여 스타트업 모집(서울/부산)...,https://fintech.or.kr/web/board/boardContentsV...,NaN
11706,2025-01-02,[우리금융그룹] 디노랩 부산 1기 참여 스타트업 모집(~25.1.12),https://fintech.or.kr/web/board/boardContentsV...,NaN

In [32]:
# !pip install sqlalchemy pymysql

In [33]:
# !pip install python-dotenv

In [ ]:
df3 = load_data("fintech_news", "news_articles")
df3