In [1]:
import pandas as pd
import requests
import re
import time
from bs4 import BeautifulSoup as bs
from dbio3 import to_db, load_data

# 뉴스목록, 날짜, id수집

In [3]:
url1 = "https://fintech.or.kr/web/board/boardContentsList.do"

In [ ]:
miv_pageNo=2&miv_pageSize=&total_cnt=&LISTOP=&mode=W&contents_id=&board_id=6&p_reg_userno=

In [4]:
payload = dict(miv_pageNo=1, mode='W', board_id=6)

In [5]:
r1 = requests.get(url1, params=payload)
print(r1.status_code)
soup = bs(r1.content, "lxml")
soup

200

<html><head><script language="javascript">
$(document).ready(function(){

	// 댓글수 노출여부 확인후 숨기기(미구현)

		$(".comment_cnt").hide();


	// 답변 노출여부 확인후 숨기기(미구현)

		$(".reply_status").hide();


	// 모바일 전용 페이지 숨기지
	//$(".mobile_list").hide();

	$(function() {

	});

	$("#searchtxt").keydown(function(key) {
		if (key.keyCode == 13) {
			search();
		}
	});
});
</script>
</head><body><div class="boardlist_top">
<ul class="box">
<li class="select">
<div class="optionbox">
<select id="searchkey" name="searchkey">
<option value="I">전체</option>
<option value="T">제목</option>
<option value="C">내용</option>
</select>
</div>
</li>
<li class="input">
<div class="inpbox"><input class="txt" id="searchtxt" name="searchtxt" placeholder="검색어 입력" title="검색어 입력" type="text" value=""/></div>
</li>
<li class="button">
<button class="btn3 bg_blue" onclick="search();" title="검색" type="button">검색</button>
<!-- <button type="button" class="btn3 bg_gray" title="재검색">재검색</button> -->
</li>
</ul>
</div>
<!--// list_table_area -->
<div class="boardlist">
<table>
<caption>게시판 목록</caption>
<colgroup>
<col style="width: 10%;"/>
<col style="width: 75%;"/>
<col style="width: 15%;"/>
</colgroup>
<thead>
<tr>
<th class="first" scope="col">
								번호



























								</th>
<th class="" scope="col">


								제목

























								</th>
<th class="last" scope="col">























								작성일




								</th>
</tr>
</thead>
<tbody>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('bf1b44ca61d74074a455cf21e180451c')">[경기도] 미래콘텐츠 성과공유회(AXR)에 초대합니다. (11/20(목) ~ 21(금))</a>
</td>
<td class="last">





























								2025-11-12








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('d4ad01f29e27456bacd3bf33c0668232')">[우리금융그룹] 2026 디노랩 서울 7기/부산 2기/경남 3기 모집(~12/03)</a>
</td>
<td class="last">





























								2025-11-12








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')">[금융보안원] 「데이터허브」 이용 안내</a>
</td>
<td class="last">





























								2025-09-17








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')">[국무조정실] 규제개혁신문고 제도 안내</a>
</td>
<td class="last">





























								2024-02-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')">[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')">[신용보증기금] 스타트업 지원 업무 안내</a>
</td>
<td class="last">





























								2022-12-19








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')">[한국무역보험공사] K-Sure 수출컨설팅 사업 안내</a>
</td>
<td class="last">





























								2022-06-20








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')">[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내</a>
</td>
<td class="last">





























								2021-12-03








































							</td>
</tr>
<tr>
<td class="first">
<span class="notice">공지</span>
</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')">[웰컴저축은행] 마이데이터 서비스 제휴 솔루션</a>
</td>
<td class="last">





























								2021-04-07








































							</td>
</tr>
<tr>
<td class="first">




									6849




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('62ec460f84a24e54bb51311c81fdfb1c')">[11/27 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-27








































							</td>
</tr>
<tr>
<td class="first">




									6848




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('39547f2a0ee34a5097ff4e92f6df9f6e')">[11/26 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-26








































							</td>
</tr>
<tr>
<td class="first">




									6847




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('933a27b8c60a4499957e17ac74649983')">[11/25 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-25








































							</td>
</tr>
<tr>
<td class="first">




									6846




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('084feb7185844e6fa6d7ff981c514de0')">[11/24 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-24








































							</td>
</tr>
<tr>
<td class="first">




									6845




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('edd05197dbf749118cd7d16918ab3cc4')">[11/21 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-21








































							</td>
</tr>
<tr>
<td class="first">




									6844




































































							</td>
<td class="txtl title">
<a class="txtl" href="javascript:contentsView('12c003b7478b4c359c558ecc1edcc342')">[11/20 핀테크 주요뉴스]</a>
</td>
<td class="last">





























								2025-11-20








































							</td>
</tr>
</tbody>
</table>
<!-- mobile -->
<ul class="list">
<li class="notice_line">
<a href="javascript:contentsView('bf1b44ca61d74074a455cf21e180451c')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[경기도] 미래콘텐츠 성과공유회(AXR)에 초대합니다. (11/20(목) ~ 21(금))



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-12</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('d4ad01f29e27456bacd3bf33c0668232')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[우리금융그룹] 2026 디노랩 서울 7기/부산 2기/경남 3기 모집(~12/03)



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-12</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[금융보안원] 「데이터허브」 이용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-09-17</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[국무조정실] 규제개혁신문고 제도 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2024-02-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[신용보증기금] 스타트업 지원 업무 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-12-19</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국무역보험공사] K-Sure 수출컨설팅 사업 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2022-06-20</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-12-03</li>
</ul>
</a>
</li>
<li class="notice_line">
<a href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">
<span class="notice">[공지]</span>








									[웰컴저축은행] 마이데이터 서비스 제휴 솔루션



								</div>
</div>
<ul class="name">
<li>작성일 : 2021-04-07</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('62ec460f84a24e54bb51311c81fdfb1c')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/27 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-27</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('39547f2a0ee34a5097ff4e92f6df9f6e')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/26 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-26</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('933a27b8c60a4499957e17ac74649983')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/25 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-25</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('084feb7185844e6fa6d7ff981c514de0')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/24 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-24</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('edd05197dbf749118cd7d16918ab3cc4')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/21 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-21</li>
</ul>
</a>
</li>
<li class="">
<a href="javascript:contentsView('12c003b7478b4c359c558ecc1edcc342')" title="상세 페이지로 이동">
<div class="title_box">
<div class="title">











									[11/20 핀테크 주요뉴스]



								</div>
</div>
<ul class="name">
<li>작성일 : 2025-11-20</li>
</ul>
</a>
</li>
</ul>
<!--//mobile -->
</div>
<!--// list_table_area -->
<!-- button_area -->
<div class="btn_box ar">
</div>
<!--// button_area -->
<!-- paging_area -->
<div class="paging web_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a><a href="javascript:go_Page(6);" title="6">6</a><a href="javascript:go_Page(7);" title="7">7</a><a href="javascript:go_Page(8);" title="8">8</a><a href="javascript:go_Page(9);" title="9">9</a><a href="javascript:go_Page(10);" title="10">10</a></span><button class="btn-paging-next" onclick="go_Page(11);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(458)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area -->
<!-- paging_area -->
<div class="paging mobile_only">
<div class="box"><button class="btn-paging-first" onclick="go_Page(1)" title="처음" type="button">처음</button><button class="btn-paging-pre" onclick="return false;" title="이전" type="button">이전</button><span><a class="on" href="javascript:;">1</a><a href="javascript:go_Page(2);" title="2">2</a><a href="javascript:go_Page(3);" title="3">3</a><a href="javascript:go_Page(4);" title="4">4</a><a href="javascript:go_Page(5);" title="5">5</a></span><button class="btn-paging-next" onclick="go_Page(6);" title="다음" type="button">다음</button><button class="btn-paging-last" onclick="go_Page(458)" title="마지막" type="button">마지막</button></div>
</div>
<!--// paging_area --></body></html>

mobile용

In [6]:
len(soup.select("ul.list > li > a"))

15

In [7]:
# 제목과 뉴스 id 
soup.select("a.txtl")

[<a class="txtl" href="javascript:contentsView('bf1b44ca61d74074a455cf21e180451c')">[경기도] 미래콘텐츠 성과공유회(AXR)에 초대합니다. (11/20(목) ~ 21(금))</a>,
 <a class="txtl" href="javascript:contentsView('d4ad01f29e27456bacd3bf33c0668232')">[우리금융그룹] 2026 디노랩 서울 7기/부산 2기/경남 3기 모집(~12/03)</a>,
 <a class="txtl" href="javascript:contentsView('b4b0b17c318d45158645c81c1472e29a')">[금융보안원] 「데이터허브」 이용 안내</a>,
 <a class="txtl" href="javascript:contentsView('51cb0e37c4064f2a985436e2ae3378df')">[국무조정실] 규제개혁신문고 제도 안내</a>,
 <a class="txtl" href="javascript:contentsView('3c24d05040984c79a7cdfd2c921952eb')">[기술보증기금] 핀테크 기업을 위한 주요 보증상품 안내</a>,
 <a class="txtl" href="javascript:contentsView('25f4360d5b9847a996828099e8d52ade')">[신용보증기금] 스타트업 지원 업무 안내</a>,
 <a class="txtl" href="javascript:contentsView('9c16609a99ad4c55914ffa9a7f2d58b7')">[한국무역보험공사] K-Sure 수출컨설팅 사업 안내</a>,
 <a class="txtl" href="javascript:contentsView('6b14460b5adc480aa050c4c535af8b72')">[한국예탁결제원] 예탁결제원 보유 데이터 활용 안내</a>,
 <a class="txtl" href="javascript:contentsView('d4cbbeb3f9b3444cbf1856b48f9f2926')">[웰컴저축은행] 마이데이터 서비스 제휴 솔루션</a>,
 <a class="txtl" href="javascript:contentsView('62ec460f84a24e54bb51311c81fdfb1c')">[11/27 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('39547f2a0ee34a5097ff4e92f6df9f6e')">[11/26 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('933a27b8c60a4499957e17ac74649983')">[11/25 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('084feb7185844e6fa6d7ff981c514de0')">[11/24 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('edd05197dbf749118cd7d16918ab3cc4')">[11/21 핀테크 주요뉴스]</a>,
 <a class="txtl" href="javascript:contentsView('12c003b7478b4c359c558ecc1edcc342')">[11/20 핀테크 주요뉴스]</a>]

web용은 Table 안에

In [8]:
# 제목과 뉴스 id 
soup.select("a.txtl")[0]['href'].split("'")[1]

'bf1b44ca61d74074a455cf21e180451c'

In [9]:
# 날짜
soup.select("td.last")[0].text.strip()

'2025-11-12'

# news list id와 날짜 모으기

In [10]:
contents_id_list = []
for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
    date = date.text.strip()
    contents_id = content_list['href'].split("'")[1]
    contents_id_list.append((date, contents_id))
contents_id_list

[('2025-11-12', 'bf1b44ca61d74074a455cf21e180451c'),
 ('2025-11-12', 'd4ad01f29e27456bacd3bf33c0668232'),
 ('2025-09-17', 'b4b0b17c318d45158645c81c1472e29a'),
 ('2024-02-20', '51cb0e37c4064f2a985436e2ae3378df'),
 ('2022-12-19', '3c24d05040984c79a7cdfd2c921952eb'),
 ('2022-12-19', '25f4360d5b9847a996828099e8d52ade'),
 ('2022-06-20', '9c16609a99ad4c55914ffa9a7f2d58b7'),
 ('2021-12-03', '6b14460b5adc480aa050c4c535af8b72'),
 ('2021-04-07', 'd4cbbeb3f9b3444cbf1856b48f9f2926'),
 ('2025-11-27', '62ec460f84a24e54bb51311c81fdfb1c'),
 ('2025-11-26', '39547f2a0ee34a5097ff4e92f6df9f6e'),
 ('2025-11-25', '933a27b8c60a4499957e17ac74649983'),
 ('2025-11-24', '084feb7185844e6fa6d7ff981c514de0'),
 ('2025-11-21', 'edd05197dbf749118cd7d16918ab3cc4'),
 ('2025-11-20', '12c003b7478b4c359c558ecc1edcc342')]

In [11]:
# newslist의 url
url2 = "https://fintech.or.kr/web/board/boardContentsView.do"

In [12]:
# news list의 payload
payload2 = dict(miv_pageNo=1, mode="W", contents_id="39547f2a0ee34a5097ff4e92f6df9f6e", board_id=6, searchkey="I")

In [13]:
r2 = requests.get(url2, params=payload2)
print(r2.status_code)
soup2 = bs(r2.content,'lxml')
soup2

200

<!DOCTYPE html>
<html lang="ko" xml:lang="ko">
<head>
<title>


		핀테크 포털 - 한국핀테크지원센터

		</title>
<meta content="핀테크 생태계 활성화로 금융의 혁신과 성장을 지원합니다.." name="description"/>
<meta content="핀테크 포털 - 한국핀테크지원센터" name="keywords"/>
<meta content="http://fintech.or.kr/images/preview_page.png" property="og:image"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" name="viewport"/>
<meta content="XpressEngine" name="Generator"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="o8yb702i79l2intg1e9ov2hyavzbji" name="facebook-domain-verification"/>
<!-- <link rel="shortcut icon" href="/images/web/favicon.ico" type="image/x-icon"> -->
<!-- <link rel="icon" href="/images/web/favicon.ico" type="image/x-icon"> -->
<link href="/css/web/default.css?ver=20200916" rel="stylesheet" type="text/css"/>
<link href="/css/web/reset.css?ver=20210629" rel="stylesheet" type="text/css"/>
<link href="/css/web/font.css" rel="stylesheet" type="text/css"/>
<link href="/css/web/contents.css?ver=20211018" rel="stylesheet" type="text/css"/>
<link href="/css/web/table.css?ver=202110181" rel="stylesheet" type="text/css"/>
<link href="/css/web/slick.css?ver=20210530" rel="stylesheet" type="text/css"/>
<link href="/css/web/jquery-ui.min.css?ver=1" rel="stylesheet" type="text/css"/>
<link href="/css/web/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/css/common.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/js/jquery.ui.monthpicker.js" type="text/javascript"></script>
<script src="/js/jquery.dropselect.js" type="text/javascript"></script>
<script src="/js/accordion.js" type="text/javascript"></script>
<script src="/js/loadingoverlay.min.js" type="text/javascript"></script>
<script type="text/javascript">

			$(document).ready(function() {
				$(".mobile_gnb").accordion({
					accordion:true,
					speed: 0,
				});
			});

			var g_http_url   = "null";
			var g_https_url  = "null";
			var g_user_no	= "";

			var g_menu_1	 = "";  	//메뉴1
			var g_menu_2	 = "";  	//메뉴2
			var g_menu_3	 = "";  	//메뉴3
			var g_menu_4	 = "";  	//메뉴4
			var g_cmm_param  = "?miv_pageNo=1&amp;mode=W&amp;contents_id=39547f2a0ee34a5097ff4e92f6df9f6e&amp;board_id=6&amp;searchkey=I";
			var homepage 	 = "null";
			var tabTitle 	 = "한국핀테크지원센터 홈페이지";

			var g_topmenu_id = "";  		//topmenu_id
			var g_submenu_id = "";  		//submenu_id



			var g_menu_navi_nm 	= "";  	//menu_navi_nm ( 구분자 # )
			var g_menu_navi_id 	= "";  	//menu_navi_id ( 구분자 # )

			function goPortalLogin() {
				if(g_user_no != ""){
				    $("#PORTALID").val("");
				    frmP.target="_blank";
				    frmP.method="post";
				    frmP.action="https://finedu.fintech.or.kr/FLMSApps/LmsLogin";
				    //frmP.action="http://103.244.108.212:8080/FLMSApps/imsiLogin.jsp";
				    //frmP.action="http://103.244.108.212:8080/FLMSApps/LmsLogin";
				    frmP.submit();
				}else{
					window.open('https://finedu.fintech.or.kr/FLMSApps/jsp/Common/LmsMain/fin-top.jsp');
				}
			 }
		</script>
<!--[if lt IE 9]>
			<script src="js/vendor/html5shiv.js"></script>
			<script src="js/vendor/respond.min.js"></script>
		<![endif]-->
<script src="/assets/jquery/jquery.form.js" type="text/javascript"></script>
<script type="text/javascript">
			// ready
			$(document).ready(function(){
				// 메뉴 조회

				// 네이게이션의 서브 메뉴 조회

				// 메뉴가 없을 경우 아래 로직 실행



					var uri = "/web/board/boardContentsView.do";
					var page_id = " ";
					var board_id = "6 ";
					var company_id = " ";
					$.ajax({
						type : "POST",
						url : "/web/menu/selectFrontMenuList_pre.do",
						dataType : 'json',
						data : {uri : uri, page_id : page_id, board_id : board_id, company_id :company_id},
						async : false,
						success : function(data) {
							g_topmenu_id = data.menu_info.topmenu_id;  		//topmenu_id
							g_submenu_id = data.menu_info.menu_id;  		//submenu_id
							g_menu_navi_nm = data.menu_info.menu_navi;  		//menu_navi_id ( 구분자 #1 )
							g_menu_navi_id = data.menu_info.menu_navi_id;  		//menu_navi_nm ( 구분자 # )
							g_menu_2 = data.menu_info.up_menu_id2;
							$(".contents_title").eq(0).html("");
							$(".contents_title").eq(0).prepend('<h2 tabindex="0">'+data.menu_info.menu_nm+'</h2>');
							$("#lnb_area_h2").html(data.menu_info.up_menu_nm1);
							lnbAreaSetting(g_topmenu_id);
							$("#ajax_nav").html(data.g_menu_navi);
						    loadMenu(homepage,'S');
						    loadNaviMenu();
						}
					});




				function lnbAreaSetting(mId){
					var bgSub = "";
					if ( mId =='1000'){bgSub="sub1";}
					if ( mId =='2000'){bgSub="sub2";}
					if ( mId =='3000'){bgSub="sub3";}
					if ( mId =='4000'){bgSub="sub4";}
					if ( mId =='5000'){bgSub="sub5";}
					if ( mId =='6000'){bgSub="sub6";}
					if ( mId =='7000'){bgSub="sub7";}
					if ( mId =='8000'){bgSub="sub8";}
					if ( mId =='9000'){bgSub="sub9";}
					if ( mId =='9400'){bgSub="sub10";}
					if ( mId =='10000'){bgSub="sub1";}
					$("#lnb_area_div").removeClass();
					$("#lnb_area_div").addClass("lnb_area");
					$("#lnb_area_div").addClass(bgSub);
				}


				//$("#language").show();
				//메인링크 변경시
				//$("#mainLink").change(function() {
				//	location.href = $(this).val();
				//});

				//$("#tabLink1,#selBrdId").change(function() {
				//	location.href = $(this).val();
				//});
			});
		</script>
<script src="/js/web_main.js?ver=20200916" type="text/javascript"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-181533868-1"></script>
<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-181533868-1');
		</script>
<!-- Facebook Pixel Code -->
<script>
		!function(f,b,e,v,n,t,s)
		{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};
		if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
		n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];
		s.parentNode.insertBefore(t,s)}(window, document,'script',
		'https://connect.facebook.net/en_US/fbevents.js');
		fbq('init', '606167354025125');
		fbq('track', 'PageView');
		</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=606167354025125&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
</head>
<body id="sub">
<dl class="skipnavi">
<dt>메뉴 건너띄기</dt>
<dd>
<!--  2021/12/1   반복영역 건너뛰기  -->
<a href="#topMenu">상단메뉴 바로가기..</a>
<a href="#Content">본문 바로가기</a>
</dd>
</dl>
<div id="wrap">
<script>

   var test="false";
</script>
<!-- S: toparea pc-->
<div class="toparea" id="header">
<div class="top_nav">
<ul>
<!-- 로그인 전 -->
<li><a href="javascript:goPage('9100', '', '');" title="로그인">로그인</a></li>
<li><a href="javascript:goPage('9300', '', '');" title="회원가입">회원가입</a></li>
<!--// 로그인 전 -->
<li><a href="/web/user/enMain.do" title="ENG">ENG</a></li>
<!-- <li><a href="javascript:alert('준비중입니다.');" title="ENG">ENG</a></li> -->
</ul>
</div>
<div class="topmenu">
<h1>
<a href="/" title="메인으로 이동"></a>
</h1>
<a href="#n" id="topMenu" style="position: absolute; width: 0; height: 0; overflow: hidden;" tabindex="-1">상단메뉴 시작</a> <!--  2021/12/1  반복영역 건너뛰기 -->
<ul class="gnb" id="gnb">
<!-- 탑메뉴 1뎁스 2뎁스 까지 나옴  -->
</ul>
<div class="bg-topmenu-on"></div>
<button class="total_search" onclick="goPage('9999','','');" type="button"></button>
<button class="all_menu" type="button">
<span class="line line1"></span>
<span class="line line2"></span>
<span class="line line3"></span>
</button>
<div class="all_menu_area">
<ul class="menu_list" id="sitemap_box">
</ul>
</div>
</div>
<button class="btn-category-holder" onclick="mobileMenuToggle('open')" title="모바일 메뉴 열림" type="button">
<span class="line line1"></span>
<span class="line line2"></span>
<span class="line line3"></span>
</button>
<div class="mobile-category">
<div class="mobild_menu">
<button class="close" onclick="mobileMenuToggle('close')" title="모바일 메뉴 닫기" type="button"></button>
<div class="top_nav">
<ul>
<!-- 로그인 전 -->
<li><a href="javascript:goPage('9100', '', '');" title="로그인">로그인</a></li>
<li><a href="javascript:goPage('9300', '', '');" title="회원가입">회원가입</a></li>
<!-- 로그인 후 -->
<!-- <li><a href="javascript:void(alert('준비중입니다.'));" title="ENG">ENG</a></li> -->
</ul>
</div>
<div class="search_box">
<input placeholder="검색어를 입력하세요" title="검색어를 입력하세요" type="text"/>
<button title="검색" type="button"></button>
</div>
<ul class="mobile_gnb" id="MobileTopMenu">
<!-- 모바일 메뉴 -->
</ul>
</div>
</div>
</div>
<!-- //E: toparea -->
<!--//S: lnb -->
<div class="lnb_area sub1" id="lnb_area_div">
<h2 id="lnb_area_h2"></h2>
<div class="lnb web">
<ul class="list" id="NaviSubMenu">
<!-- 웹 서브메뉴 (2뎁스▼|2뎁스▼|2뎁스▼|2뎁스▼|2뎁스▼) -->
</ul>
</div>
<div class="lnb mobile">
<ul class="list" id="NaviSubMenu2">
<!-- 모바일 서브메뉴 (1뎁스▼|2뎁스▼|3뎁스▼)-->
</ul>
</div>
</div>
<!--//E: lnb -->
<!-- S: midarea -->
<div class="midarea">
<!--//S: contentsarea -->
<div class="contentsarea">
<a href="#n" id="Content" style="position: absolute; width: 0; height: 0; overflow: hidden;" tabindex="-1">본문 시작</a><!--  2021/12/1  반복영역 건너뛰기   -->
<nav id="ajax_nav">
<!-- <ul>
				<li class="home"><a href="/" title="메인 페이지로 이동">HOME</a></li>
				<li><a href="../main.html" title="메인 페이지로 이동">센터소개</a></li>
				<li><span>인사말</span></li>
			</ul> -->
</nav>
<div class="contents_title"><h2 tabindex="01"></h2></div>
<!-- 내용 -->
<script language="javascript">
var boardContentsListPageUrl 	= "/web/board/boardContentsListPage.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var boardContentsWriteUrl 		= "/web/board/boardContentsWrite.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var boardContentsViewUrl 		= "/web/board/boardContentsView.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var deleteBoardContentsUrl 		= "/web/board/deleteBoardContents.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var chkCommentUrl 				= "/web/board/chkComment.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var saveCommentUrl 				= "/web/board/saveComment.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var deleteCommentUrl 			= "/web/board/deleteComment.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var boardCommentListUrl 		= "/web/board/boardCommentList.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var saveSatisfyUrl 				= "/web/board/saveSatisfy.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var saveRecommendUrl 			= "/web/board/saveRecommend.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var loadRecommendUrl 			= "/web/board/loadRecommend.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";
var passPopupUrl 				= "/web/board/boardContentsPassPopup.do;jsessionid=182C2FA29786B8BDBF82BAE5F18C88FF.fintech";

var cmt_el;
var cmt_commentid;
var mode;

//목록으로
function list(){
	var f = document.writeFrm;

	f.target = "_self";
	f.action = boardContentsListPageUrl;
	f.submit();
}

//게시물 수정
function contentsEdit(){
	var f = document.writeFrm;

	f.target = "_self";
	f.action = boardContentsWriteUrl;
	f.submit();
}

//게시물 삭제
function contentsDelete(){

	var url = deleteBoardContentsUrl;
	var f = document.writeFrm;

	// 패스워드가 있는 경우 페이지로 보낸다.



	if (confirm('게시물을 삭제하시겠습니까?')) {
		$.ajax({
			type: "POST",
			url: url,
			data :jQuery("#writeFrm").serialize(),
			dataType: 'json',
			success:function(data){
				alert(data.message);
				if(data.success == "true"){
					goList();
				}
			}
		});
	}

}

//답글 쓰기
function contentsReply(){
	var f = document.writeFrm;

	$("#mode").val("R");

	f.target = "_self";
	f.action = boardContentsWriteUrl;
	f.submit();
}

//게시물 뷰
function contentsView(contentsid){
	var f = document.writeFrm;

	$("#contents_id").val(contentsid);

	f.target = "_self";
	f.action = boardContentsViewUrl;
	f.submit();
}

// 만족도 저장
function saveSatisfy(){

	// 로그인 여부 확인하기
	var sid = "";
	var yn  = "N";
	if(sid == ""){
		alert("로그인이 후 참여 가능합니다.");
		goPage('9100', '', '');
		return;
	}

	if(yn == "Y"){
		alert("이미 참여하였습니다.");
		return;
	}

	var url = saveSatisfyUrl;
	if (confirm('만족도를 저장하시겠습니까?')) {
		$.ajax({
			type: "POST",
			url: url,
			data :jQuery("#satisfyFrm").serialize(),
			dataType: 'json',
			success:function(data){
				alert(data.message);
				if(data.success == "true"){
					$(".satisfaction_area").hide();
				}
			}
		});
	}
}

// 추천하기
function saveRecommend(){

	// 로그인 여부 확인하기
	var sid = "";
	if(sid == ""){
		alert("로그인이 후 참여 가능합니다.");
		goPage('9100', '', '');
		return;
	}

	var url = saveRecommendUrl;
	$.ajax({
		type: "POST",
		url: url,
		data : {
			contents_id : "39547f2a0ee34a5097ff4e92f6df9f6e",
			recommend_yn : $("#recommend_yn").val()
		},
		dataType: 'json',
		success:function(data){
			alert(data.message);
			// 추천가져오기
			loadRecommend();
		}
	});
}

// 추천가져오기
function loadRecommend(){
	var url = loadRecommendUrl;
	$.ajax({
		type: "POST",
		url: url,
		data : {
			contents_id : "39547f2a0ee34a5097ff4e92f6df9f6e",
		},
		dataType: 'json',
		success:function(data){
			if(data.recommend_yn == "Y"){
				$("#recommend_cnt").html(data.recommend_cnt);
				$("#recommend_yn").val(data.recommend_yn);
				$(".btn_recommend").addClass("pick");
			}else{
				$("#recommend_cnt").html(data.recommend_cnt);
				$("#recommend_yn").val(data.recommend_yn);
				$(".btn_recommend").removeClass("pick");
			}
		}
	});
}

</script>
<form id="writeFrm" method="post" name="writeFrm" onsubmit="return false;">
<input id="mode" name="mode" type="hidden" value="E"/>
<input id="board_id" name="board_id" type="hidden" value="6"/>
<input id="contents_id" name="contents_id" type="hidden" value="39547f2a0ee34a5097ff4e92f6df9f6e"/>
<input id="recommend_yn" name="recommend_yn" type="hidden" value=""/>
<input id="miv_pageNo" name="miv_pageNo" type="hidden" value="1"/>
<input id="s_reply_ststus" name="s_reply_ststus" type="hidden" value=""/>
<input id="s_searchkey" name="s_searchkey" type="hidden" value="I"/>
<input id="s_searchtxt" name="s_searchtxt" type="hidden" value=""/>
<input id="s_cate_id" name="s_cate_id" type="hidden" value=""/>
</form>
<!--//S: 게시판 상세 -->
<div class="board_detail">
<div class="title_box">
<h3>
			[11/26 핀테크 주요뉴스]
		</h3>
<ul class="list">
<li>작성일 : 2025-11-26</li>
</ul>
</div>
<!-- view_area -->
<ul class="list">
</ul>
<!-- view_area -->
<!-- view_area -->
<!-- editor -->
<div class="content" style="min-height:300px;"><meta charset="utf-8"/>
<title>한국핀테크지원센터 오늘의 핀테크 뉴스</title>
<table background="https://fintech.or.kr/contents/commoneditor/2023060509104055668f3c-4a91-42e6-8c10-b38683dddbd4.jpg" border="0" cellpadding="0" cellspacing="0" height="546" style="margin-left:auto;margin-right:auto;" width="800">
<tbody>
<tr>
<td height="100" width="250"> </td>
<td height="100" width="300"><p align="center" style="font-family: 'Malgun Gothic'; font-weight: bolder; color: #FFFFFF; font-size:large;">2025년 11월 26일 수요일</p></td>
<td height="100" width="250"> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
</tr>
</tbody>
</table>
<table style="width:800px;margin-left:auto;margin-right:auto;table-layout:fixed;overflow-wrap:break-word;word-break:normal;">
<tbody><tr style="padding:0px;width:800px;height:57px;">
<td style="padding:0px;width:800px;height:57px;">
<br/>
<img height="57" src="https://fintech.or.kr/contents/commoneditor/20230605091104a13db107-e4a5-45c8-8a58-0a7709898024.jpg" width="800"/><br/>
</td>
</tr>
<tr style="width:800px;height:10px;"> <td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">1. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&amp;contents_id=ba9a817cc8434910a4c6f47ff2e19099&amp;menu_id=6300" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모집(~12.8.)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">2. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=1&amp;contents_id=1506a705524144328f7f1a6e88785b11&amp;menu_id=6100" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크산업협회] 네트워킹 행사 '핀테크 커넥팅 데이 2025' 개최(11.26.) ※신청: ~11.20.</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">3. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&amp;contents_id=e04c846efa67421db116e5533c0d8bd2&amp;menu_id=6300" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생 모집(상시)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr><td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">4. </span><a href="https://fintech.or.kr/web/board/boardContentsView.do?board_id=1&amp;contents_id=abc17a4ab12d4c79ae94d177994b4d57&amp;menu_id=6100" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) 참여기업 모집 (~예산 소진 시까지)</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"></span></td>
</tr>
<tr style="padding:0px;width:800px;height:57px;">
<td style="padding:0px;width:800px;height:57px;">
<br/>
<img height="57" src="https://fintech.or.kr/contents/commoneditor/20230605091116ca5c2c72-878f-4e89-b389-6ac5193954ae.jpg" width="800"/><br/>
</td>
</tr>
<tr style="width:800px;height:10px;"> <td style="padding:0 50px 0 60px;"><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-weight: bold; font-size: 12pt; line-height: 1.8;">1. </span><a href="https://n.news.naver.com/mnews/article/008/0005282738?sid=101" style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none;font-size: 12pt; line-height: 1.8; font-weight: bold;" target="_blank">"부산을 해양금융 허브로"…금감원·부산시·해진공·조선업계 총집결</a><span style="font-family: 'Malgun Gothic';color: #343434; text-decoration: none; font-size: 12pt; line-height: 1.8; font-weight: bold;"> (머니투데이, 11/25) </span></td>
</tr>

In [14]:
# 뉴스 리스트 목록
soup2.select("tbody td a")[0].text

"[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모집(~12.8.)"

In [15]:
soup2.select("tbody td a")[0]['href']

'https://fintech.or.kr/web/board/boardContentsView.do?board_id=3&contents_id=ba9a817cc8434910a4c6f47ff2e19099&menu_id=6300'

In [16]:
soup2.select("tbody td a")[6]['href']

'https://n.news.naver.com/mnews/article/003/0013620831?sid=101'

# 위에서 개별 작업한 코드 모으기

In [17]:
# 핀테크 뉴스 리스트, 날짜, content_id 수집
contents_id_list = []
for page in range(1, 20):
    url1 = "https://fintech.or.kr/web/board/boardContentsList.do"
    payload = dict(miv_pageNo=page, mode='W', board_id=6)
    r1 = requests.post(url1, data=payload)
    print(r1.status_code)
    soup = bs(r1.content, "lxml")

    for date, content_list in zip(soup.select("td.last"), soup.select("a.txtl")):
        date = date.text.strip()
        contents_id = content_list['href'].split("'")[1]
        contents_id_list.append((date, contents_id))
    time.sleep(2)

result = {}
# 날짜별 뉴스 리스트의 세부 뉴스 제목, 링크
for idx, (date, content_id) in enumerate(contents_id_list):
    print(f"{idx+1}/{len(contents_id_list)} 수집중", end="\r")
    url2 = "https://fintech.or.kr/web/board/boardContentsView.do"
    payload2 = dict(miv_pageNo=1, mode="W", contents_id=content_id, board_id=6, searchkey="I")
    r2 = requests.get(url2, params=payload2)
#     print(r2.status_code)
    soup2 = bs(r2.content,'lxml')

    for td in soup2.select("tbody td a"): 
        if "https://n.news.naver.com" in td['href'] or "https://fintech.or.kr/web/" in td['href']:
            result.setdefault('date', []).append(date)
            result.setdefault('제목', []).append(td.text)
            result.setdefault('뉴스링크', []).append(td['href'])
            
df = pd.DataFrame(result)
df

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

,date,제목,뉴스링크
0,2025-11-27,[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모...,https://fintech.or.kr/web/board/boardContentsV...
1,2025-11-27,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...
2,2025-11-27,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...
3,2025-11-27,"금융위, 제7회 코리아 핀테크 위크 2025 개막",https://n.news.naver.com/mnews/article/277/000...
4,2025-11-27,"금융위, 금융공공데이터 162종 추가 개방… 상장사 정보·차보험 통계 등 포함",https://n.news.naver.com/mnews/article/366/000...
...,...,...,...
11769,2024-12-18,"中 고강도 부양책 발표 효과?…차이나 ETF 수익률 ""괜찮네""",https://n.news.naver.com/mnews/article/003/001...
11770,2024-12-18,구글 급소 `검색` 노린 오픈AI...AI발 검색 춘추전국 오나,https://n.news.naver.com/mnews/article/029/000...
11771,2024-12-18,"""日 혼다, 닛산과 합병 협상""…세계 3위 車업체 탄생하나",https://n.news.naver.com/mnews/article/277/000...
11772,2024-12-18,프랑스 이어 독일도 내각 붕괴… 유럽 리더십 위기,https://n.news.naver.com/mnews/article/005/000...
11773,2024-12-18,[김앤장 법률사무소] 기업의 AI 도입에 따른 법적 이슈와 거버넌스 대응 웨비나(1...,https://fintech.or.kr/web/board/boardContentsV...

# 세부링크로 들어가서 뉴스 본문 수집

In [18]:
df2 = df[df['date'] > "2025-01-01"].copy()

In [19]:
df2['뉴스링크'][6]

'https://n.news.naver.com/mnews/article/003/0013621930?sid=101'

In [20]:
# 핀테크 지원센터 글
r3 = requests.get(df2['뉴스링크'][0])
soup3 = bs(r3.content, 'lxml')
soup3.select_one("div.content").text

'[한국핀테크지원센터x구름]「K-디지털 트레이닝 핀테크 인턴십 코스」4기 훈련생 모집(~12/8까지) \xa0  □ 프로그램 개요 - 국내 최대 핀테크 전문 지원기관인 한국핀테크지원센터와 국내 대기업(카카오, KT클라우드등) 부트캠프를 설계.운영해온 국내 대표 에듀테크 전문기관 구름(goorm)이 함께하는 핀테크 및 디지털 금융 산업 진출을\xa0목표로 하는 예비 실무자들을 위해 기획된 6개월 집중형 K-Digital Training 입니다.\ufeff \xa0  □ 신청 홈페이지 - (공식 신청 홈페이지) https://fintech-internship-course.goorm.io/ - (상세 안내 페이지)  https://www.notion.so/goormkdx/x-goorm-293c0ff4ce318024bea5ddcba23965d6 \xa0  □ 핀테크 인턴십 코스 과정 핵심 Point ① 핀테크 기업연계 현장형(인턴) 프로젝트 참여 : 한국핀테크지원센터의 협력기업과 현업 프로젝트 직접 참여 \xa0  ② 기업연계 매칭기업 서류전형 면제 : 프로젝트 진행 기업의 경우 채용전형 중 서류전형 면제 \xa0  ③ 우수 수료생 대상 인턴십 연계 : 수료자 중 우수 인재에게 협력기업 인턴십 또는 채용 연계 기회 제공 \xa0  ④ 핀테크 일자리 매칭 플랫폼 서비스 지원 : 수료 후 최대 2년간 취업 매칭, 채용 공고 연계, 1:1 커리어 컨설팅 제공 \xa0  ⑤ 현직자 멘토링 & 금융·핀테크 기업 및 기관 현장 견학 : 업계 선배 멘토링, 핀테크 기업 견학, 금융기관 방문 등 실무 인사이트 제공 \xa0  □ 주요 일정  구분일정비고서류접수2025.11.24(월) ~ 12.8(월)마감일 자정까지 서류 접수 가능발표2025.11.24(월) ~ 12.8(월)서류 제출 후 순차적 합격 통지교육기간2025.12.18(목) ~ 2026.06.18(금) 6개월 진행 (총 960시간) \xa0  □ 모집 과정 및 인원 과정명주요내용모집정원(명)핀테크 서비스 기획시장 분석, UX 기획, 기획서 작성,  데이터 기반 서비스 설계각 25명 내외핀테크 풀스택 개발HTML/CSS, JavaScript, Node.js,  DB설계, API 연동 등 ※ 과정별 모집 인원 초과 시 조기 마감될 수 있음. \xa0  □ 훈련 과정 구성 구분기간장소 및 방식주요 내용오프라인 25.12.18 –26.04.15구름 강남캠퍼스 (강남구 테헤란로 145)- 핀테크 산업 및 최신 기술 트렌드- 기획/개발 과정별 맞춤 실습- 프로젝트 기반 문제 해결형 학습- 현직자 멘토링 및 네트워킹 프로그램기업 연계26.04.16 – 06.18 온라인(Zoom) ※기업연계 프로젝트시 기업방문형 과정 진행- 기업 과제 기반 팀 프로젝트 수행- 실무 담당자와의 주기적 피드백- 중간/최종 발표 및 포트폴리오 제작- 우수자 대상 인턴십 및 채용 연계 \xa0  □ 참여조건 ① 내일배움카드 발급 가능자 (국민내일배움카드 소지 or 발급 예정자)   ② K-Digital Training 과정 수강 이력이 없는 자    ③ 주중 오전 9시 ~ 오후 6시, 하루 8시간 수업에 성실히 참여 가능한 자  ※ 위 조건을 모두 충족해야 참여가 가능합니다. \xa0  □ 문의사항 - 한국핀테크지원센터 글로벌사업부 교육 담당자 - 이메일: kgm1012@fintech.or.kr\xa0'

In [21]:
# 네이버뉴스 글
r3 = requests.get(df2['뉴스링크'][6])
soup3 = bs(r3.content, 'lxml')
soup3.select_one("#dic_area").text

'\n\n\n\n\n[서울=뉴시스]이지민 기자 = 금융감독원이 상장사 내부감사기구에 감사 품질 제고와 회계부정 방지를 위해 보다 적극적인 역할 수행에 나설 것을 주문했다. 금감원은 26일 서울 상장회사회관에서 상장사 감사위원·감사 및 유관기관 등과 \'내부감사기구 간담회\'를 개최했다.이날 간담회에 참석한 윤정숙 금감원 전문심의위원은 "신(新)외감법 시행 후 내부감사기구의 역할이 강화되며 회계투명성 확보의 실질적 주체로 자리 잡았다"며 "내부감사기구가 회계분식, 자금부정을 방지하기 위한 살아있는 내부통제의 핵심축으로 기능해야 한다"고 말했다. 이를 위해 ▲감사품질 중심의 외부감사인 선정 ▲내·외부감사인 간 유기적 협력 ▲절처한 내부통제시스템 감독 ▲독립성·전문성 확보 ▲회계부정 징후 발생 시 엄정 대응 등을 강조했다. 먼저, 감사품질을 높이기 위해 외부감사인 선정 시 독립성·전문성, 감사계획의 적정성, 투입시간의 충분성 등을 중점에 둘 것을 요청했다. 또 감사 과정에서 실제 투입시간, 인력 등을 점검해 감사 계획이 제대로 이행되는지 철저히 평가하도록 했다. 내·외부감사인 간의 긴밀한 협업도 강조했다. 경영진을 배제한 회의를 분기당 최소 1회 개최하고, 대면 회의를 통해 양방향으로 정보를 교류하는 등 실질적인 소통을 주문했다. 내부회계 평가에서는 통제 설계뿐 아니라 현장에서 통제가 제대로 작동하는지 확인하고, 미비점 발견 시 이사회에 충실히 보고하도록 했다.금감원은 내부감사기구에 독립된 보고체계 구축과 전문성 제고도 요청했다. 특히, 전담지원조직을 두고 임면 동의권과 직속 보고라인을 확보해 내부감사 기능을 강화해야 한다고 설명했다.아울러 회계부정이 발생하면 자체감사 또는 외부 전문가를 활용해 신속히 조사·시정하고, 결과를 금융당국과 감사인에게 제출해야 한다고도 했다. 내부감사기구는 조사 전 과정에 대한 감독의무를 지며, 주의의무 위반 시 책임을 질 수 있다고 경고했다.금감원 관계자는 "내부감사기구가 회계부정의 1차 방어선으로 기능할 수 있도록 제도·실무적 차원에서 적극 지원하는 한편, 앞으로도 다양한 이해관계자와 지속 소통해 나갈 계획"이라고 전했다.\n'

In [22]:
df2['뉴스본문'] = ""
df2

,date,제목,뉴스링크,뉴스본문
0,2025-11-27,[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모...,https://fintech.or.kr/web/board/boardContentsV...,
1,2025-11-27,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...,
2,2025-11-27,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...,
3,2025-11-27,"금융위, 제7회 코리아 핀테크 위크 2025 개막",https://n.news.naver.com/mnews/article/277/000...,
4,2025-11-27,"금융위, 금융공공데이터 162종 추가 개방… 상장사 정보·차보험 통계 등 포함",https://n.news.naver.com/mnews/article/366/000...,
...,...,...,...,...
11319,2025-01-02,"""당장 돈 안되고 성능향상 기대 못 미쳐도""… 세계는 AI인프라 `영끌`",https://n.news.naver.com/mnews/article/029/000...,
11320,2025-01-02,트럼프 2.0시대 중국…미 동맹국 이탈 기대하며 버티기[다시 만난 트럼프②],https://n.news.naver.com/mnews/article/032/000...,
11321,2025-01-02,'美 51번째 주' 모욕 당했는데…트럼프에 찍소리 못하는 이유 [김리안의 에네르기파...,https://n.news.naver.com/mnews/article/015/000...,
11322,2025-01-02,[산업은행] 2025년 상반기 KDB NextONE 참여 스타트업 모집(서울/부산)...,https://fintech.or.kr/web/board/boardContentsV...,
11323,2025-01-02,[우리금융그룹] 디노랩 부산 1기 참여 스타트업 모집(~25.1.12),https://fintech.or.kr/web/board/boardContentsV...,

In [27]:
for idx, link in enumerate(df2['뉴스링크'][:10]):
    print(f"{idx+1}/{len(df2['뉴스링크'][:10])} 수집중", end="\r")
    r4 = requests.get(link)
    soup4 = bs(r4.content, 'lxml')
    if "https://fintech.or.kr/web/" in link:
        r3 = requests.get(link)
        soup3 = bs(r3.content, 'lxml')
        article = soup3.select_one("div.content").text
        df2.loc[idx, '뉴스본문'] = article
    elif "https://n.news.naver.com" in link:
        r3 = requests.get(link)
        soup3 = bs(r3.content, 'lxml')
        article = soup3.select_one("#dic_area").text
        df2.loc[idx, '뉴스본문'] = article
    to_db("fintech_news", "news_articles", df2.loc[[idx], :])
    time.sleep(3)
df2

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [24]:
df2['뉴스본문']

0        [한국핀테크지원센터x구름]「K-디지털 트레이닝 핀테크 인턴십 코스」4기 훈련생 모집...
1
2
3
4
                               ...
11319
11320
11321
11322
11323
Name: 뉴스본문, Length: 11324, dtype: object

In [25]:
df2.to_csv("./data/fintech_news.csv")

In [26]:
df2 = pd.read_csv("./data/fintech_news.csv", index_col=0)
df2

,date,제목,뉴스링크,뉴스본문
0,2025-11-27,[한국핀테크지원센터X구름] K-디지털트레이닝 '핀테크 인턴십 코스' 4기 훈련생 모...,https://fintech.or.kr/web/board/boardContentsV...,[한국핀테크지원센터x구름]「K-디지털 트레이닝 핀테크 인턴십 코스」4기 훈련생 모집...
1,2025-11-27,[한국핀테크지원센터] (온라인) 핀테크를 통한 금융 AI 트렌드와 혁신 사례 교육생...,https://fintech.or.kr/web/board/boardContentsV...,NaN
2,2025-11-27,[한국핀테크지원센터] 2025년 핀테크기업 온라인 채용관 (사람인 saramin) ...,https://fintech.or.kr/web/board/boardContentsV...,NaN
3,2025-11-27,"금융위, 제7회 코리아 핀테크 위크 2025 개막",https://n.news.naver.com/mnews/article/277/000...,NaN
4,2025-11-27,"금융위, 금융공공데이터 162종 추가 개방… 상장사 정보·차보험 통계 등 포함",https://n.news.naver.com/mnews/article/366/000...,NaN
...,...,...,...,...
11319,2025-01-02,"""당장 돈 안되고 성능향상 기대 못 미쳐도""… 세계는 AI인프라 `영끌`",https://n.news.naver.com/mnews/article/029/000...,NaN
11320,2025-01-02,트럼프 2.0시대 중국…미 동맹국 이탈 기대하며 버티기[다시 만난 트럼프②],https://n.news.naver.com/mnews/article/032/000...,NaN
11321,2025-01-02,'美 51번째 주' 모욕 당했는데…트럼프에 찍소리 못하는 이유 [김리안의 에네르기파...,https://n.news.naver.com/mnews/article/015/000...,NaN
11322,2025-01-02,[산업은행] 2025년 상반기 KDB NextONE 참여 스타트업 모집(서울/부산)...,https://fintech.or.kr/web/board/boardContentsV...,NaN
11323,2025-01-02,[우리금융그룹] 디노랩 부산 1기 참여 스타트업 모집(~25.1.12),https://fintech.or.kr/web/board/boardContentsV...,NaN

In [65]:
# !pip install sqlalchemy pymysql

In [72]:
# !pip install python-dotenv

In [28]:
from dbio3 import to_db, load_data

In [29]:
df3 = load_data("fintech_news", "news_articles")
df3

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)