# TMDB 5000 Movie Dataset으로 장르기반 추천시스템 만들기
* 장르에 있는 텍스트를 벡터화 후 텍스트간 유사도를 구해 가까운 순서대로 정렬
* 유사도 척도: 코사인유사도

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [80]:
data = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/tmdb_5000_movies.csv")
data.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [82]:
data['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [83]:
import json

In [84]:
json.loads(data['genres'][0])[0]['name']

'Action'

In [85]:
data.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [86]:
dict_cols = ['genres', 'keywords', 'production_companies', 'production_countries', 'spoken_languages']
dict_cols

['genres',
 'keywords',
 'production_companies',
 'production_countries',
 'spoken_languages']

In [87]:
def dict_unpack(data):
    for col in dict_cols:
        temp = []
        for i in json.loads(data[col]):
            temp.append(i.get('name', 'None'))
        # print(temp)
        temp = " ".join(temp)
        print(temp)
        data[col] = temp
    return data

In [88]:
data.apply(dict_unpack, axis=1)

Action Adventure Fantasy Science Fiction
culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d
Ingenious Film Partners Twentieth Century Fox Film Corporation Dune Entertainment Lightstorm Entertainment
United States of America United Kingdom
English Español
Adventure Fantasy Action
ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger
Walt Disney Pictures Jerry Bruckheimer Films Second Mate Productions
United States of America
English
Action Adventure Crime
spy based on novel secret agent sequel mi6 british secret service united kingdom
Columbia Pictures Danjaq B24
United Kingdom United States of America
Français English Español Italiano Deutsch
Action Crime Drama Thriller
dc comics crime fighter terrorist secret identity burglar hostage drama time bomb gotham city vigilante cover-up superhero villainess tragic hero terrorism destruction catwoman cat burglar imax flood criminal underworld batman
Legendary Pictures Warner Bros. DC Entertainment Syncopy
United States of America
English
Action Adventure Science Fiction
based on novel mars medallion space travel princess alien steampunk martian escape edgar rice burroughs alien race superhuman strength mars civilization sword and planet 19th century 3d
Walt Disney Pictures
United States of America
English
Fantasy Action Adventure
dual identity amnesia sandstorm love of one's life forgiveness spider wretch death of a friend egomania sand narcism hostility marvel comic sequel superhero revenge
Columbia Pictures Laura Ziskin Productions Marvel Enterprises
United States of America
English Français
Animation Family
hostage magic horse fairy tale musical princess animation tower blonde woman selfishness healing power based on fairy tale duringcreditsstinger healing gift animal sidekick
Walt Disney Pictures Walt Disney Animation Studios
United States of America
English
Action Adventure Science Fiction
marvel comic sequel superhero based on comic book vision superhero team duringcreditsstinger marvel cinematic universe 3d
Marvel Studios Prime Focus Revolution Sun Studios
United States of America
English
Adventure Fantasy Family
witch magic broom school of witchcraft wizardry apparition teenage crush werewolf
Warner Bros. Heyday Films
United Kingdom United States of America
English
Action Adventure Fantasy
dc comics vigilante superhero based on comic book revenge super powers clark kent bruce wayne dc extended universe
DC Comics Atlas Entertainment Warner Bros. DC Entertainment Cruel & Unusual Films RatPac-Dune Entertainment
United States of America
English
Adventure Fantasy Action Science Fiction
saving the world dc comics invulnerability sequel superhero based on comic book kryptonite super powers superhuman strength lex luthor
DC Comics Legendary Pictures Warner Bros. Bad Hat Harry Productions
United States of America
English Français Deutsch
Adventure Action Thriller Crime
killing undercover secret agent british secret service
Eon Productions
United Kingdom United States of America
English Español Italiano Français Deutsch
Adventure Fantasy Action
witch fortune teller bondage exotic island monster captain card game east india trading company compass ship daughter pirate swashbuckler aftercreditsstinger
Walt Disney Pictures Jerry Bruckheimer Films Second Mate Productions
Jamaica United States of America Bahamas Dominica
English Türkçe ελληνικά 普通话
Action Adventure Western
texas horse survivor texas ranger partner outlaw escape lawyer train lone ranger comanche the lone ranger tonto
Walt Disney Pictures Jerry Bruckheimer Films Infinitum Nihil Silver Bullet Productions (II) Blind Wink Productions Classic Media
United States of America
English
Action Adventure Fantasy Science Fiction
saving the world dc comics superhero based on comic book superhuman alien invasion reboot super powers dc extended universe
Legendary Pictures Warner Bros. DC Entertainment Syncopy Cruel and Unusual Films
United Kingdom United States of America
English
Adventure Family Fantasy
based on novel fictional place brother sister relationship lion human being wretch leap in time matter of life and death faith uncle narnia fantasy world
Walt Disney Walden Media Stillking Films Ozumi Films Propeler Silverbell Films Revolution Sun Studios
Czech Republic Poland Slovenia United States of America
English
Science Fiction Action Adventure
new york shield marvel comic superhero based on comic book alien invasion superhero team aftercreditsstinger duringcreditsstinger marvel cinematic universe
Paramount Pictures Marvel Studios
United States of America
English
Adventure Action Fantasy
sea captain mutiny sword prime minister sailing silver ship duke mermaid pirate soldier battle swashbuckler aftercreditsstinger 3d
Walt Disney Pictures Jerry Bruckheimer Films Moving Picture Company (MPC)
United States of America
English Español
Action Comedy Science Fiction
time travel time machine alien fictional government agency seeing the future changing history
Amblin Entertainment Media Magik Entertainment Imagenation Abu Dhabi FZ Hemisphere Media Capital Parkes/MacDonald Productions
United States of America
English
Action Adventure Fantasy
corruption elves dwarves orcs middle-earth (tolkien) hobbit dragon battle unlikely friendship epic battle sword and sorcery
WingNut Films New Line Cinema Warner Bros. Pictures 3Foot7 Metro-Goldwyn-Mayer (MGM)
New Zealand United States of America
English
Action Adventure Fantasy
loss of father vigilante serum marvel comic scientific experiment spider bite masked vigilante reboot super powers genetic engineering social outcast duringcreditsstinger
Columbia Pictures Laura Ziskin Productions Marvel Entertainment
United States of America
English
Action Adventure
robin hood archer knight sherwood forest bow and arrow middle ages medieval king of england
Imagine Entertainment Universal Pictures Scott Free Productions Relativity Media
United Kingdom United States of America
English ภาษาไทย
Adventure Fantasy
elves dwarves orcs hobbit dragon wizard sword and sorcery
WingNut Films New Line Cinema Warner Bros. Pictures Metro-Goldwyn-Mayer (MGM)
New Zealand United States of America
English
Adventure Fantasy
england compass experiment lordship uncle polar bear orphan animal based on young adult novel
New Line Cinema Ingenious Film Partners Depth of Field Scholastic Productions
United Kingdom United States of America
Íslenska English Pусский Français
Adventure Drama Action
film business screenplay show business film making film producer exotic island monster indigenous ship dinosaur
WingNut Films Universal Pictures Big Primate Pictures MFPV Film
New Zealand United States of America Germany
English
Drama Romance Thriller
shipwreck iceberg ship panic titanic ocean liner epic rich woman - poor man love disaster tragic love class differences imax star crossed lovers steerage salvage rich snob 3d 1910s
Paramount Pictures Twentieth Century Fox Film Corporation Lightstorm Entertainment
United States of America
English Français Deutsch svenska Italiano Pусский
Adventure Action Science Fiction
civil war war marvel comic sequel superhero based on comic book imax aftercreditsstinger duringcreditsstinger marvel cinematic universe 3d
Studio Babelsberg Marvel Studios Walt Disney Studios Motion Pictures Vita-Ray Dutch Productions (III) Deluxe Digital Studios
United States of America
Română English Deutsch Pусский
Thriller Action Adventure Science Fiction
fight u.s. navy mind reading hong kong soccer scientist fictional war naval armada battleship naval combat jds myoko lost communication taser buoy communications expert joint chiefs of staff crash landing jet fighter pilot navy lieutenant permission to marry uss john paul jones based on board game aftercreditsstinger mighty mo uss missouri
Universal Pictures Hasbro Bluegrass Films Film 44
United States of America
English ภาษาไทย
Action Adventure Science Fiction Thriller
monster dna tyrannosaurus rex velociraptor island sequel suspense disaster escape dinosaur amusement park animal attack theme park jurassic park 3d animal horror
Universal Studios Amblin Entertainment Legendary Pictures Fuji Television Network Dentsu
United States of America
English
Action Adventure Thriller
spy secret agent sociopath killer art gallery british secret service istanbul turkey imax uzi booby trap impersonating a police officer macao
Columbia Pictures
United Kingdom United States of America
English
Action Adventure Fantasy
dual identity love of one's life pizza boy marvel comic sequel superhero doctor scientist tentacle death super villain
Columbia Pictures Laura Ziskin Productions Marvel Enterprises
United States of America
English Pусский 普通话
Action Adventure Science Fiction
terrorist war on terror tennessee malibu marvel comic superhero based on comic book tony stark iron man aftercreditsstinger marvel cinematic universe mandarin 3d war machine iron patriot extremis
Marvel Studios
China United States of America
English
Family Fantasy Adventure
based on novel fictional place queen fantasy alice in wonderland fantasy world 3d
Walt Disney Pictures Team Todd Tim Burton Productions Roth Films Zanuck Company, The
United States of America
English
Adventure Action Science Fiction Thriller
mutant marvel comic based on comic book superhuman beast cyclops aftercreditsstinger
Ingenious Film Partners Twentieth Century Fox Film Corporation Donners' Company Dune Entertainment Major Studio Partners Bad Hat Harry Productions thinkfilm Marvel Enterprises X3 Canada Productions X3US Productions XM3 Service
Canada United Kingdom United States of America
English
Animation Family
monster dormitory games animation best friend university scary aftercreditsstinger
Walt Disney Pictures Pixar Animation Studios
United States of America
English
Science Fiction Action Adventure
egypt sun chaos symbol artifact transformers tank robot imax duringcreditsstinger
Paramount Pictures DreamWorks SKG Amblin Entertainment Di Bonaventura Pictures Platinum Dunes Hasbro Studios Revolution Sun Studios
United States of America
English Español
Science Fiction Action Adventure
sequel alien transformers giant robot robot imax transforming robot
Paramount Pictures Amblin Entertainment Di Bonaventura Pictures Platinum Dunes China Movie Channel Hasbro Studios Ian Bryce Productions Revolution Sun Studios
United States of America
English
Fantasy Adventure Family
circus witch magic hope illusion lost magic trick wizard 3d
Walt Disney Pictures Roth Films
United States of America
English
Action Adventure Fantasy
obsession marvel comic sequel based on comic book electrocution medical experiment electricity super powers
Columbia Pictures Marvel Enterprises Avi Arad Productions Matt Tolmach Productions
United States of America
English
Adventure Action Science Fiction
artificial intelligence secret identity computer program dystopia computer deception duel motorcycle neon light autocracy
Walt Disney Pictures LivePlanet Prana Studios Sean Bailey Productions Revolution Sun Studios Kontsept Film Company
United States of America
English
Animation Family Adventure Comedy
car race sequel comedy anthropomorphism best friend duringcreditsstinger
Walt Disney Pictures Pixar Animation Studios
United States of America
English 日本語 Italiano Français
Adventure Action Thriller Science Fiction
dc comics transformation superhero alien alien infection magical object protector super powers origin 3d
De Line Pictures Warner Bros. DC Entertainment
United States of America
English
Animation Family Comedy
hostage college toy barbie animation escape day care teddy bear duringcreditsstinger toy comes to life personification inanimate objects coming to life toy story
Walt Disney Pictures Pixar Animation Studios
United States of America
English Español
Action Science Fiction Thriller
saving the world artificial intelligence prophecy san francisco cyborg killer robot gas station post-apocalyptic dystopia army firearm wartime los angeles
Columbia Pictures The Halcyon Company Wonderland Sound and Vision Warner Bros.
Germany Italy United Kingdom United States of America
English Italiano
Action
car race speed revenge suspense car race muscle car
Universal Pictures Original Film Fuji Television Network Dentsu One Race Films China Film Co. Québec Production Services Tax Credit Media Rights Capital (MRC) Abu Dhabi Film Commission Colorado Office of Film, Television & Media
Japan United States of America
English
Action Drama Horror Science Fiction Thriller
dystopia apocalypse zombie nuclear weapons multiple perspectives zombie apocalypse
Paramount Pictures GK Films Skydance Productions Hemisphere Media Capital Apparatus Productions Latina Pictures 2DUX²
United States of America Malta
English
Action Adventure Fantasy Science Fiction
1970s mutant time travel marvel comic based on comic book superhuman storm beast aftercreditsstinger changing the past or future
Twentieth Century Fox Film Corporation Donners' Company Marvel Entertainment Bad Hat Harry Productions TSG Entertainment Down Productions Revolution Sun Studios
United Kingdom United States of America
English
Action Adventure Science Fiction
spacecraft friendship sequel futuristic space alien imax space opera terrorist bombing 3d
Paramount Pictures Skydance Productions Bad Robot Kurtzman/Orci
United States of America
English
Action Family Fantasy
based on fairy tale giant
New Line Cinema Original Film Legendary Pictures Warner Bros. Big Kid Pictures Bad Hat Harry Productions
United States of America
English
Drama Romance
based on novel infidelity obsession hope 3d
Village Roadshow Pictures Bazmark Films Warner Bros. A&E Television Networks Red Wagon Entertainment Spectrum Films
United States of America Australia
English
Adventure Fantasy Action Romance
persia sandstorm brother against brother armageddon regent based on video game
Walt Disney Pictures Jerry Bruckheimer Films
United States of America
English
Action Science Fiction Adventure
dystopia giant robot giant monster apocalypse imax duringcreditsstinger 3d
Legendary Pictures Warner Bros. Disney Double Dare You (DDY) Indochina Productions
United States of America Canada
English
Action Science Fiction Adventure
moon spacecraft traitor bodyguard alien planet based on cartoon transformers giant robot sabotage word domination commando duringcreditsstinger
Paramount Pictures Di Bonaventura Pictures Indochina Productions Hasbro Studios
United States of America
English
Adventure Action
saving the world riddle whip treasure mexico city leather jacket machinegun alien phenomenons maya civilization peru treasure hunt nuclear explosion refrigerator archaeologist indiana jones archeology
Lucasfilm Paramount Pictures
United States of America
English Deutsch Pусский
Adventure Animation Family
tyrannosaurus rex friends alternate history dinosaur fear storm nature human journey
Walt Disney Pictures Pixar Animation Studios
United States of America
English
Animation Adventure Comedy Family Action Fantasy
scotland rebel bravery kingdom archer wish bear scot rebellious daughter turns into animal archery ruins aftercreditsstinger peace offering woman director courage 3d
Walt Disney Pictures Pixar Animation Studios
United States of America
English
Action Adventure Science Fiction
sequel stranded hatred space opera
Paramount Pictures Bad Robot Perfect Storm Entertainment Alibaba Pictures Group Skydance Media Sneaky Shark Huahua Media
United States of America
English
Animation Family
romantic comedy
Walt Disney Pictures Pixar Animation Studios FortyFour Studios
United States of America
English
Action Comedy Crime Thriller
ambassador
New Line Cinema
United States of America
Latin English Français 日本語 普通话
Action Adventure Science Fiction
civilization natural disaster end of the world disaster apocalypse destruction volcanic eruption mayan ark solar destruction  of mankind
Columbia Pictures Centropolis Entertainment The Mark Gordon Company Farewell Productions
Canada United States of America
English Français हिन्दी Italiano Latin 普通话 Português Pусский
Animation Drama
holiday based on novel victorian england money christmas eve scrooge christmas carol ghost lesson charles dickens christmas
Walt Disney ImageMovers
United States of America
English
Science Fiction Fantasy Action Adventure
jupiter space woman director 3d interspecies romance
Village Roadshow Pictures Dune Entertainment Anarchos Productions Warner Bros.
United States of America
English
Action Adventure
africa feral child tarzan jungle animal attack
Village Roadshow Pictures Dark Horse Entertainment Jerry Weintraub Productions RatPac-Dune Entertainment Beagle Pug Films Riche Productions Village Roadshow Films North America
Canada United Kingdom United States of America
English
Adventure Family Fantasy
saving the world witch based on novel brother sister relationship self sacrifice winter cupboard beaver lion fairy-tale figure battle narnia fantasy world duringcreditsstinger
Walt Disney Walden Media
United Kingdom United States of America
English Deutsch
Science Fiction
mutant supernatural powers marvel comic superhero based on comic book superhuman apocalypse superhero team world domination aftercreditsstinger 1980s
Twentieth Century Fox Film Corporation Donners' Company Marvel Entertainment Bad Hat Harry Productions TSG Entertainment Kinberg Genre
United States of America
English
Drama Action Crime Thriller
dc comics crime fighter secret identity scarecrow sadism chaos gotham city vigilante joker superhero based on comic book tragic hero organized crime criminal mastermind district attorney imax super villain super powers batman
DC Comics Legendary Pictures Warner Bros. DC Entertainment Syncopy
United Kingdom United States of America
English 普通话
Animation Comedy Family Adventure
age difference central and south america balloon animation floating in the air duringcreditsstinger exploring
Pixar Animation Studios
United States of America
English
Animation Family Adventure Science Fiction
alien giant robot duringcreditsstinger
DreamWorks Animation
United States of America
English
Action Science Fiction Adventure
middle east arms dealer malibu marvel comic superhero based on comic book tony stark iron man aftercreditsstinger marvel cinematic universe counter terrorism agent coulson
Marvel Studios
United States of America
English فارسی اردو العربية
Adventure Drama Family
library clock film director key toy boy love orphan robot automaton hiding filmmaking leg brace doberman 3d
Paramount Pictures Infinitum Nihil GK Films
France United States of America United Kingdom
English
Action Adventure Comedy Science Fiction Western
steampunk based on tv series steam locomotive drag
Todman, Simon, LeMasters Productions Warner Bros. Peters Entertainment Sonnenfeld Josephson Worldwide Entertainment
United States of America
English
Adventure Action Fantasy

Universal Pictures China Film Co-Production Corporation Relativity Media Alphaville Films Sommers Company, The
Germany United States of America
English 普通话
Action Adventure Crime Fantasy Science Fiction
dc comics shared universe anti hero secret mission villain superhero supervillain dc extended universe
DC Comics Dune Entertainment Atlas Entertainment Warner Bros. DC Entertainment
United States of America
English
Fantasy Comedy Family
father son relationship daily life married couple support father marriage faith baustelle rescue animal nature duringcreditsstinger noah's ark
Columbia Pictures Universal Pictures Spyglass Entertainment Shady Acres Entertainment Original Film Playtone Relativity Media
United States of America
English
Action Science Fiction
deja vu time warp restart dystopia war alien military officer soldier alien invasion exoskeleton

English
Animation Comedy Family
weather food science
Columbia Pictures Sony Pictures Animation
United States of America
English
Animation Comedy Family Adventure
ice age bridge insanity jungle dinosaur birth duringcreditsstinger 3d
Blue Sky Studios Twentieth Century Fox Animation
United States of America
English
Adventure Comedy Drama Fantasy
himalaya photographer magazine iceland daydream photograph shark fired from the job skateboard dreamer online dating daydreaming
New Line Cinema Ingenious Media Twentieth Century Fox Film Corporation Samuel Goldwyn Films Big Screen Productions Red Hour Films TSG Entertainment Down Productions
United States of America
English
Action Adventure Comedy Crime Thriller
martial arts female friendship millionaire agent
Columbia Pictures
United States of America
English Deutsch suomi 日本語 广州话 / 廣州話
Drama Thriller Crime
undercover boston police friends mafia undercover cop mobster mole state police police training realtor
Vertigo Entertainment Media Asia Films Warner Bros. Initial Entertainment Group (IEG) Plan B Entertainment
Hong Kong United States of America
English 广州话 / 廣州話
Animation Family Adventure
homeland musical training daughter cricket princess dragon luck
Walt Disney Pictures Walt Disney Feature Animation
United States of America
English 普通话
Action Comedy
film making satire jungle movie star southeast asia land mine shackles war filmmaking duringcreditsstinger blackface method acting
DreamWorks SKG Goldcrest Pictures Red Hour Films Internationale Filmproduktion Stella-del-Sud Second
United States of America United Kingdom Germany
English 普通话
Thriller Crime Mystery Drama
rape journalist based on novel journalism hacker nazis punk investigation remake antisocial personality disorder serial killer disappearance hacking computer hacker bible quote scandinavian abuse
Columbia Pictures Scott Rudin Productions Film Rites Metro-Goldwyn-Mayer (MGM) Yellow Bird Ground Control
Norway Sweden United States of America
English
Action Thriller
bomb taxi riddle robbery detective helicopter gold subway ship fistfight police sequel deception shootout new york city explosion violence car chase fbi agent simon says flashback dump truck aqueduct action hero federal reserve bank
Twentieth Century Fox Film Corporation Cinergi Pictures Entertainment
United States of America
English Deutsch Română
Action Adventure Crime Mystery
detective scotland yard coffin black magic arrest partner sherlock holmes murder steampunk pentagram clue
Village Roadshow Pictures Silver Pictures Warner Bros. Internationale Filmproduktion Blackbird Dritte Wigram Productions
Germany United Kingdom United States of America
English Français
Drama
betrayal vengeance
Paramount Pictures Metro-Goldwyn-Mayer (MGM) Sean Daniel Company LightWorkers Media
United States of America
English
Animation Family Adventure Science Fiction
sea atlantis animation underwater sea monster
Walt Disney Pictures Walt Disney Feature Animation
United States of America
English Français Español
Adventure Animation Comedy Family
chipmunk cgi talking animal aftercreditsstinger duringcreditsstinger
Regency Enterprises Fox 2000 Pictures Sunswept Entertainment Bagdasarian Productions TSG Entertainment
United States of America
English
Drama Thriller History War
berlin suicide bomb assassination resistance wife husband relationship world war ii adolf hitler plan friendship deception treason colonel military officer plot german officer piano wire medal violence
United Artists Achte Babelsberg Film Metro-Goldwyn-Mayer (MGM) Bad Hat Harry Productions
Germany United States of America
English Deutsch
Comedy Action
new york israel middle east hairdresser ladykiller mossad israeli palestinian heart-throb middle east conflict hairstyle hacky sack
Columbia Pictures Happy Madison Productions Sony Pictures Releasing Relativity Media
United States of America
English עִבְרִית
Action Comedy Science Fiction
video game nerd alien attack 3d pixels
Columbia Pictures Happy Madison Productions
United States of America
English
Drama Science Fiction Adventure
artificial intelligence prophecy prostitute android loss of mother extraterrestrial technology ice age adoption fairy tale pinocchio prosecution gigolo hologram dystopia alien destiny capture doppelganger
DreamWorks SKG Amblin Entertainment Stanley Kubrick Productions Warner Bros.
United States of America
English
Thriller Fantasy Comedy Family Mystery
secret passage magic estate agent haunted house family vacation ghost aftercreditsstinger
Walt Disney Pictures Gunn Films Doom Buggy Productions
United States of America
English
Drama Science Fiction Mystery
based on novel nasa new mexico extraterrestrial technology prime number star radio wave wormhole fanatic spirituality religion scientist sabotage ham radio alien contact mechanical engineering observatory eccentric man radio telescope
Warner Bros. South Side Amusement Company
United States of America
English
Action Science Fiction Thriller
killing human experimentation scientist invisible man science experiment
Columbia Pictures Corporation Global Entertainment Productions GmbH & Company Medien KG
Germany United States of America
English
Crime Thriller
new york dictator africa destruction of a civilization assassination resistance revenge murder united nations witness to murder fbi agent resistance fighter
Universal Pictures StudioCanal Mirage Enterprises Working Title Films Misher Films Motion Picture JOTA Produktions
France Germany United Kingdom United States of America
English Français Português
Adventure Family Fantasy
poison hermes poseidon demigod golden fleece olympus 3d kronos overthrow olympus based on young adult novel
1492 Pictures Dune Entertainment Fox 2000 Pictures Sunswept Entertainment Dune Entertainment III TSG Entertainment
United States of America
English
Action Adventure Fantasy Thriller
riddle treasure medallion kenia alexander the great pandora's box chinese mafia treasure hunt hong kong archaeologist based on video game archeology
Paramount Pictures Toho-Towa Mutual Film Company Lawrence Gordon Productions British Broadcasting Corporation (BBC) October Pictures Eidos Interactive
United States of America Germany Japan United Kingdom
English 普通话
Action Adventure Comedy Crime Mystery Thriller
london england china magic secret society vigilante sequel revenge heist on the run macau china magician
Summit Entertainment Lionsgate K/O Paper Products TIK Films
Canada China United Kingdom United States of America
普通话 English
Thriller Action Romance Science Fiction Adventure
berlin russia gas master thief the saint
Paramount Pictures Mace Neufeld Productions Rysher Entertainment
United States of America
English Pусский
Action Crime Thriller
spy china cia cold war
Universal Pictures Metropolitan Filmexport Toho-Towa Red Wagon Productions Beacon Communications Kalima Productions GmbH & Co. KG
United Kingdom United States of America
广州话 / 廣州話 English Deutsch العربية Français
Science Fiction
mars spacecraft space travel alien long take outer space astronaut dismemberment alien contact trapped in space
Spyglass Entertainment The Jacobson Company Touchstone Pictures Red Horizon Productions
United States of America
English
Animation Adventure Comedy Family
brazil pet bird musical canary samba animal duringcreditsstinger rio 1 río 1
Blue Sky Studios Twentieth Century Fox Animation
United States of America
English Português
Comedy Science Fiction
android hologram freedom futuristic robot
Laurence Mark Productions 1492 Pictures Columbia Pictures Corporation Touchstone Pictures Radiant Productions
Germany United States of America
English
Science Fiction Action Drama Thriller
subway lava volcano volcanologist los angeles
Twentieth Century Fox Film Corporation
United States of America
Deutsch Español English
Crime Thriller Drama
new york terrorist anonymity northern ireland
Columbia Pictures
United States of America
English
Drama History Thriller
submarine soviet union core melt north atlantic nuclear woman director
Paramount Pictures Intermedia Films National Geographic Society New Regency Pictures Palomar Pictures (II) First Light Production
Canada Germany United Kingdom United States of America
English
Adventure Fantasy Action
gladiator repayment despot barbarian sword and sorcery
Universal Pictures Dino De Laurentiis Company
United States of America
English
Romance Drama History
transporter netherlands world cup socially deprived family family's daily life boxer boxing match comeback training heavy weight folk hero biography daughter defeat sport
Miramax Films Imagine Entertainment Universal Pictures Parkway Pictures (I) Touchstone Pictures
United States of America
English
Fantasy Action Family

Vnesheconombank Nutcracker Holdings HCC Media Group Russian Roulette Ltd.
United Kingdom Hungary
Dansk English
Drama History
horse race american dream racehorse great depression
Universal Pictures Spyglass Entertainment The Kennedy/Marshall Company DreamWorks Pictures Touchstone Pictures
United States of America
English
Action Adventure Drama
wife husband relationship tornado twister oklahoma metereologist invention climate barn natural disaster cow truck disaster aunt niece relationship storm chaser divorce
Universal Pictures Amblin Entertainment Warner Bros. Constant c Productions
United States of America
English
Adventure Drama
exotic island suicide attempt volleyball loneliness airplane crash deserted island tropical island survival skills
DreamWorks SKG Twentieth Century Fox Film Corporation Playtone ImageMovers
United States of America
Pусский English
Animation Comedy
ocean fish zoo penguin tap dancing love crush snow anthropomorphism singing antarctica family duringcreditsstinger
Kennedy Miller Productions Animal Logic
Australia
English
Action Drama Thriller
berlin assassin based on novel amnesia sniper lie sequel suspense on the run shootout espionage violence foot chase car chase exploding house though guy one against many rail car dark past moscow hand to hand combat
Universal Pictures The Kennedy/Marshall Company Hypnotic Motion Picture THETA Produktionsgesellschaft Ludlum Entertainment
Germany United States of America
English Pусский Deutsch Italiano
Action Thriller
prison corruption journalist white house hostage ultimatum hostage-taking air force one aerial combat conspiracy gunfight fighter plane secret service american president hand to hand combat negotiation political prisoner airplane hijack
Columbia Pictures Corporation Beacon Communications Radiant Productions
Germany United States of America
English Pусский
Thriller Crime
prison pickpocket strip club con artist atlantic city cockney accent las vegas card dealer explosives expert black and white scene male salt lake city utah
Village Roadshow Pictures Section Eight NPV Entertainment Jerry Weintraub Productions Warner Bros. WV Films II
United States of America
Italiano English
Adventure Action Thriller
number in title historical fiction musketeer 17th century 3d
Impact Pictures Studio Babelsberg Nouvelles Éditions de Films (NEF) New Legacy Constantin Film Produktion
United States of America Germany France United Kingdom
English
Animation Comedy Family Fantasy
witch magic mummy vampire dracula skeleton backpacker frankenstein wolfman zombie invisible man duringcreditsstinger  nosferatu protective father fang vamp
Columbia Pictures Sony Pictures Animation
United States of America
English
Comedy Family Fantasy Romance
poison queen fairy tale musical princess portal animation fantasy world evil witch part animation
Walt Disney Pictures Josephson Entertainment Andalasia Productions Right Coast Productions
United States of America
English
Action Thriller
cia violence safe house rogue agent cape town south africa soccer stadium
Universal Pictures Dentsu Relativity Media Bluegrass Films
United States of America
English Afrikaans Español
Comedy Family
london england prison release from prison women's prison society for the prevention of cruelty to animals puppy pelz dog dalmatian
Walt Disney Pictures Cruella Productions
United States of America
English
Action Comedy
skyscraper thanksgiving billionaire parade fbi agent apartment high rise female agent ponzi scheme empty safe caper comedy planning safecracker recruiting heist movie deceit lobby
Universal Pictures Image Entertainment Relativity Media Rat Entertainment
United States of America
English
Comedy Romance
holiday london england film making christmas party country house room exchange surrey romantic comedy los angeles multiple storylines woman director christmas
Columbia Pictures Universal Pictures Waverly Films Relativity Media
United Kingdom United States of America
English
Action Drama Thriller
corruption washington d.c. helicopter falsely accused identity mexican standoff blackmail intelligence wiretap satellite national security agency (nsa) politics exploding building suspense mystery mafia conspiracy lawyer crime privacy surveillance baltimore maryland secret hideout
Jerry Bruckheimer Films Scott Free Productions Touchstone Pictures No Such Productions
United States of America
English
Comedy Romance
graduation ex husband woman director
Universal Pictures Scott Rudin Productions Waverly Films Dentsu Relativity Media
United States of America
English Français
Crime Thriller
casino thief revenge heist las vegas pretending to be rich labor strike
Village Roadshow Pictures Section Eight Jerry Weintraub Productions Warner Bros.
United States of America
Español English Français
Adventure Animation Family
hunter mountains garage grizzly bear bunny chase forest deer bear hunt
Sony Pictures Animation
United States of America
English
Adventure Action Science Fiction
based on novel dystopia youth dystopic future caste system divergent based on young adult novel
Summit Entertainment Red Wagon Entertainment
United States of America
English
War
winter sniper world war ii stalingrad
Paramount Pictures Swanford Films Mandalay Pictures Little Bird KC Medien Reperage DOS MP Film Management
Ireland United States of America Germany United Kingdom
Deutsch English Pусский
Adventure Action Comedy Thriller
hunter bounty bounty hunter fight amazon treasure hunt jungle
Columbia Pictures Universal Pictures Strike Entertainment WWE Studios Misher Films IM3 Entertainment
United States of America
Português English
Adventure Fantasy Action Comedy Family
magic movie in movie spoof magical object cartoon cat ticket self-referential projectionist child's point of view
Columbia Pictures Corporation Oak Productions
United States of America
English
Drama History Romance
japan prostitute sister sister relationship brothel world war ii geisha
DreamWorks SKG Spyglass Entertainment Columbia Pictures Corporation Red Wagon Productions
United States of America
English 日本語
Action Crime Drama Thriller
car race car journey car mechanic auto car garage auto-tuning drifting car automobile racing
Universal Pictures
Japan United States of America
English 日本語
Drama Animation Family Comedy
holiday santa claus duringcreditsstinger woman director christmas
Columbia Pictures Aardman Animations Sony Pictures Animation
United States of America
English
Fantasy Drama Mystery
life and death love at first sight broken engagement fireworks religion and supernatural teenage crush fate doctor millionaire
Universal Pictures City Light Films
United States of America
English
Action Thriller Drama
terrorist fbi colombia firemen revenge explosion car explosion bomb attack
David Foster Productions Bel Air Entertainment Warner Bros. Hacienda Productions
United States of America
English Español
Drama Music
show business film making tap dancing movie in movie divorce tv show in film stand-up comedian broadway rainstorm surgery dream sequence editing semi autobiographical restroom screening room amphetamine prescription drug abuse
Twentieth Century Fox Film Corporation Columbia Pictures Corporation
United States of America
English
Adventure Fantasy Drama Comedy Science Fiction Family
attempted murder fairy tale black magic cockroach villainess good vs evil woman fights man insecurity mirror snow kingdom snow white evil queen enchantress gala financial problem pendant half naked man returning money evil plot duringcreditsstinger
Relativity Media Misher Films Yucaipa Films Goldmann Pictures Rat Entertainment Misha Films
United States of America
English
Action Adventure Comedy
whipping hipster underage girlfriend animated flashback character's point of view camera shot unconsciousness girl fight vegan aftercreditsstinger
Universal Pictures Marc Platt Productions
United States of America Canada
English
Action Thriller Adventure Science Fiction
magnetic field center of the earth disaster film
Paramount Pictures David Foster Productions Horsepower Films LivePlanet Core Productions Munich Film Partners New Century & Company (MFP) Core Productions
United States of America Canada Germany
English
Fantasy Comedy Romance Science Fiction
alter ego mad scientist family dean duringcreditsstinger research laboratory
Imagine Entertainment Universal Pictures
United States of America
English
Mystery Adventure Comedy
amateur detective voodoo resort crime solving
Atlas Entertainment Mosaic Media Group Warner Bros.
United States of America
English
Action Science Fiction
usa corruption crime fighter judge metropolis law post-apocalyptic dystopia executive case police futuristic based on comic book gore survival gunfight gangster extreme violence psychic violence criminal justice drug lord based on graphic novel dystopic future dark humor expert marksman rookie dredd 2000 ad
DNA Films Reliance BIG Entertainment IM Global Rena Film Peach Trees
South Africa United Kingdom United States of America India
English
Comedy Drama Fantasy Romance
regret workaholic heart attack architect dying and death time travel remote control children liposuction hospital wedding dog second chance alternate reality fatherhood obese
Original Film Columbia Pictures Corporation Revolution Studios Happy Madison Productions
United States of America
English Português 日本語
Horror Comedy Fantasy
monster halloween meteor buried alive cockroach anthology based on comic book gore animated sequence zombie living dead
Warner Bros. Creepshow Films Inc. Laurel Entertainment Inc.
United States of America
English Italiano
Comedy Family
torture aftercreditsstinger duringcreditsstinger 3d
Village Roadshow Pictures
United States of America Australia
English ภาษาไทย
Adventure Fantasy Science Fiction
adolescence based on novel loss of child fight chase teleportation supernatural powers leap in time enemy motherly love
Dune Entertainment Hypnotic New Regency Pictures
Canada United States of America
Français
Adventure Fantasy Science Fiction
auction northern ireland resignation superhero rebellion violence spear cut arm split screen superhero team arm ripped off super villain remorse self exile vanishing figure father son conflict
Universal Pictures Dark Horse Entertainment Lawrence Gordon Productions Mid Atlantic Films Relativity Media Internationale Filmproduktion Eagle
Germany United States of America
English
Crime Drama Mystery Thriller
california san francisco killing journalist newspaper mass murder planned murder embassy victim threat to death victim of murder code police murder serial killer reporter
Paramount Pictures Warner Bros. Phoenix Pictures
United States of America
English
Science Fiction
clone future murder cloning laser gun dystopic future implanted memory sci-fi thriller
Phoenix Pictures
United States of America
English
Fantasy Comedy
christianity moon responsability moses street gang lovesickness journalism new love faith prayer god car crash
Universal Pictures Spyglass Entertainment Shady Acres Entertainment Pit Bull Productions
United States of America
English
Thriller Adventure Action
tattoo martial arts sniper island mercenary bridge rescue escape church drug blade ensemble cast duringcreditsstinger
Millennium Films
United States of America
English Español

dragon evolution fire chief animated map theatre audience dragonslayer tunnel construction fire repellent drilling iodine
The Zanuck Company Spyglass Entertainment World 2000 Entertainment Touchstone Pictures Tripod Entertainment
Ireland United Kingdom United States of America
English
Crime Drama Action Thriller
los angeles gangster
Village Roadshow Pictures Lin Pictures Warner Bros. Langley Park Production
United States of America
English
Comedy Adventure
temple slavery stone age circumcision hebrews cavemen prehistoric adventure duringcreditsstinger prehistoric times prehistoric man
Columbia Pictures Ocean Pictures Apatow Productions
United States of America
English
Drama History
stadium south africa apartheid nelson mandela sport nation rugby president racism poverty celebration duringcreditsstinger
Spyglass Entertainment Malpaso Productions Revelations Entertainment Mace Neufeld Productions Warner Bros. Liberty Pictures (II)
United States of America
English
Action
corruption assassination detective journalist assassin newspaper congress editor-in-chief conspiracy of murder politics election campaign government murder thriller blog reporter
Universal Pictures StudioCanal Andell Entertainment Relativity Media Working Title Films
France United Kingdom United States of America
广州话 / 廣州話 English
Romance Comedy Crime
spy
Universal Pictures Laura Bickford Productions Relativity Media Medienproduktion Poseidon Filmgesellschaft
Germany United States of America
English Deutsch Pусский Español
Comedy Drama Family Science Fiction
alien martian based on tv series fish out of water
Walt Disney Pictures
United States of America
English Italiano
Action Thriller Crime
usa president agent
Twentieth Century Fox Film Corporation Dune Entertainment Major Studio Partners Regency Enterprises Epsilon Motion Pictures New Regency Pictures Sentinel Productions Furthur Films
United States of America
English
Science Fiction Animation Family Comedy Adventure
flying saucer alien life-form spaceship alien alien planet planet duringcreditsstinger
TriStar Pictures Ilion Animation Studios Hand Made Films
Spain United Kingdom United States of America
English Español
Science Fiction Action Adventure Thriller
clone assassination ambush federation starfleet enterprise-e romulus android senate self sacrifice telepathy weapon romulans space opera
Paramount Pictures
United States of America
English
Crime Comedy Romance
california assassin infidelity fetish hitman tycoon court satire lawyer inheritance divorce
Imagine Entertainment Universal Pictures Mike Zoss Productions Alphaville Productions
United States of America
Français English
Drama Romance
women baseball pitcher home run aging sport talent-scout cigar smoking poor eyesight boston red sox draft motel room baseball scout failing eyesight blurry vision blurred sight
Malpaso Productions Warner Bros.
United States of America
English
Crime Drama Mystery Thriller
murder violence death of daughter homicide detective
Icon Productions BBC Films GK Films Warner Bros.
United Kingdom United States of America
English
Horror Mystery Thriller
chicago based on novel monster museum pile of dead bodies god dead body anthropologist indian tribe amazon jungle
Paramount Pictures Universal Pictures Toho-Towa Mutual Film Company Pacific Western PolyGram Filmed Entertainment Marubeni Tele München Fernseh Produktionsgesellschaft (TMG) British Broadcasting Corporation (BBC)
Germany Japan New Zealand United Kingdom United States of America
English
Comedy Crime
prison gold therapist gangster
Village Roadshow Pictures NPV Entertainment Warner Bros. Tribeca Productions Baltimore Spring Creek Pictures Face Productions
Australia United States of America
English
Action Crime Drama Thriller
revenge murder plot twist dirty cop
Grosvenor Park Media Ltd. InVenture Entertainment Millennium Films Emmett/Furla Films Nu-Image Films
United States of America
Pусский English Español
Action Crime Drama Thriller
assassin loss of family autism fbi bangkok national security agency (nsa) boy child in peril fbi agent autistic savant
Imagine Entertainment Universal Pictures
United States of America
English
Drama
newspaper cello musical violin los angeles
DreamWorks Universal Pictures StudioCanal Participant Media Krasnoff Foster Productions Working Title Films
United States of America
English
Fantasy Drama
competition world war i great depression caddy savannah
DreamWorks SKG Twentieth Century Fox Film Corporation Wildwood Enterprises Epsilon Motion Pictures Allied Filmmakers
United States of America
English
Drama Music
hotel room san diego drug addiction stewardess overdose groupie music journalist black sabbath rock concert swimming pool based on true story promiscuity coming of age on the road domineering mother reconciliation semi autobiographical innocence lost bus trip aspiring writer
Columbia Pictures Vinyl Films DreamWorks Pictures
United States of America
English
Animation Comedy Family
london england cat mistake in person luxury wretch nobility garfield
Twentieth Century Fox Film Corporation Dune Entertainment Davis Entertainment
United Kingdom United States of America
English Português
Action Adventure Crime Drama Mystery Thriller
washington d.c. helicopter usa president general coup d'etat military prison coup agent insurgent secretary of defense potus
Original Film Columbia Pictures Corporation Revolution Studios
United States of America
English
Action Science Fiction Fantasy Thriller Horror
vampire crucifixion post-apocalyptic dystopia vampire hunter disobey niece dark hero
Screen Gems Stars Road Entertainment Buckaroo Entertainment Michael De Luca Productions TOKYOPOP
United States of America
Português English ภาษาไทย
Family Animation Adventure
prince water monster
DreamWorks Animation
United States of America
广州话 / 廣州話 English Italiano
Horror Science Fiction Mystery
space marine nudity nightmare hallucination cryogenics space travel black hole insanity delusion crew alternate dimension evil spirit hellgate religion explosion violence burning man rescue team flashback supernatural power trapped in space distress signal derelict ship
Paramount Pictures Impact Pictures Golar Productions
United Kingdom United States of America
English Latin
Drama
pregnancy and birth voice dragonfly car crash jungle hospital doctor humanitarian spiritism
Universal Pictures Spyglass Entertainment Shady Acres Entertainment Gran Via Productions Kalima Productions GmbH & Co. KG NDE Productions
Germany United States of America
English Español
Drama
pornography observer los angeles murder hunt
Universal Pictures Davis-Films Signature Pictures Linson Entertainment Art Linson Productions Millennium Films Equity Pictures Medienfonds GmbH & Co. KG III Nu Image Entertainment GmbH
France Germany United States of America
English
Action Adventure Drama History Romance War
world war i biplane
Ingenious Film Partners Electric Entertainment Skydance Productions Flyboys Films
United Kingdom United States of America
English Français
Action Drama Thriller
prison general
DreamWorks SKG
United States of America
English
Horror Science Fiction Thriller
black people starships future star supernova blast
United Artists Metro-Goldwyn-Mayer (MGM) Hammerhead Productions Screenland Pictures
Switzerland United States of America
English
Drama Fantasy Mystery Romance
based on novel
Village Roadshow Pictures Weed Road Pictures Warner Bros.
United States of America
English
Action Adventure Drama Mystery Romance Fantasy
angel vampire werewolf warlock downworlder shadowhunter demon hunter based on young adult novel
Constantin Film Produktion Don Carmody Productions Unique Features Mr. Smith Productions
United States of America
English
Comedy Science Fiction Adventure Family
new york captain starships new love earth friendship crew car crash space alien survival planet duringcreditsstinger
Twentieth Century Fox Film Corporation Dune Entertainment Regency Enterprises Guy Walks into a Bar Productions Deep River Productions Friendly Films (II)
United States of America
English
Drama Horror Thriller
based on novel water remake teacher divorce apartment ghost manhattan, new york city
Vertigo Entertainment Touchstone Pictures Post No Bills Films Pandemonium Productions
United States of America
English
Comedy
tv show tv station simulated reality  reality tv tv star tv ratings
Imagine Entertainment Universal Pictures
United States of America
English
Adventure Family Fantasy
book fairy tale eavesdropping adventure writer's block
New Line Cinema Internationale Filmproduktion Blackbird Erste
Germany United Kingdom United States of America
English
Action Comedy Thriller Crime Science Fiction
secret identity robber mask frog based on comic strip back from the dead
DC Comics Lionsgate Odd Lot Entertainment Media Magik Entertainment Dark Lot Entertainment Continental Entertainment Group (CEG)
United States of America
English Français Pусский
Comedy Adventure
based on novel painting debt art dealer stolen painting
Lionsgate Mad Chance OddLot Entertainment Huayi Brothers Media
United States of America
English
Adventure Fantasy Action Drama
fictional place monster loss of family new love hero love of one's life magic fairy tale villain kingdom enchantment bad power son heir to the throne motherly love wizardry revenge royalty family based on video game medieval
Boll Kino Beteiligungs GmbH & Co. KG Brightlight Pictures Herold Productions
Canada Germany United States of America
English
Drama Romance Adventure War
london england cia landmine love of one's life cambodia ethiopia chechnya foreign aid
Mandalay Pictures CP Medien AG Camelot Pictures Networxx - Film Management Mel's Cite du Cinema
Germany United States of America
English   Deutsch
Action Adventure Fantasy
monkey king
Filmko Pictures
Hong Kong China
普通话
Action History War
based on novel world war ii prisoners of war narration archive footage rescue mission soldier 1940s inspired by true events fictionalized history
Lawrence Bender Productions Marty Katz Productions
United States of America
English 日本語
Action Adventure Comedy
anti hero mercenary marvel comic superhero based on comic book breaking the fourth wall aftercreditsstinger duringcreditsstinger self healing
Twentieth Century Fox Film Corporation Marvel Entertainment The Donners' Company TSG Entertainment Kinberg Genre
United States of America
English
Drama Comedy
salesclerk television tv ratings guru television producer
Caravan Pictures Touchstone Pictures
United States of America
English
War Action
sniper biography iraq navy seal u.s. soldier
Village Roadshow Pictures Malpaso Productions Warner Bros. RatPac-Dune Entertainment Mad Chance Productions 22 & Indiana Pictures
United States of America
English
Adventure Horror Comedy
based on novel magic fantasy werewolf family ventriloquist dummy book comes to life 3d
Columbia Pictures Village Roadshow Pictures Original Film Sony Pictures Animation Sony Pictures Entertainment (SPE) Scholastic Entertainment LStar Capital
Australia United States of America
English
Comedy Fantasy Romance
coma based on novel workaholic flirt architect romantic comedy ghost landscape architect
DreamWorks SKG UIP MacDonald/Parkes Productions
United States of America
English 普通话 Español
Science Fiction Comedy Family Romance
waitress marriage proposal flirt stone age best friend dinosaur
Universal Pictures Amblin Entertainment
United States of America
English
Action Adventure Thriller War
competition submachine gun soviet union liberation russian soviet troops thailand freedom fighter afghanistan war on freedom machinegun mujahid reality show western japanese food soap opera
TriStar Pictures Carolco Pictures
United States of America
English Pусский
Comedy Romance Drama
american football sports team stadium hero success sponsorship police games coach woman reporter the big game
Universal Pictures Casey Silver Productions Outlaw Productions (I) Smokehouse Pictures
Germany United States of America
English Deutsch
Comedy Western
wild west
Happy Madison Productions
United States of America
English
Comedy
witness protection comedy duringcreditsstinger
Columbia Pictures Castle Rock Entertainment Relativity Media Banter
United States of America
English Italiano Pусский Español Український
Comedy
job interview loss of job intern reference to google new job laid off transamerica pyramid
Twentieth Century Fox Film Corporation Regency Enterprises 21 Laps Entertainment Wild West Picture Show Productions TSG Entertainment
United States of America
English
Action Adventure Horror Science Fiction
post-apocalyptic dystopia undead biohazard evil corporation resident evil zombie based on video game duringcreditsstinger 3d
Impact Pictures Davis-Films Constantin Film Produktion
Germany United States of America France Canada
English Español 日本語
Drama Action Adventure History War
world war ii fighter pilot fighter plane
Lucasfilm Twentieth Century Fox Film Corporation Partnership Pictures
United States of America
English Français Deutsch
Drama Horror Mystery Thriller
child abuse southern usa obsession subway nudity bible seduction hallucination ambition devil's son marriage crisis pact with the devil crooked lawyer evil spirit satan religion lust courtroom temptation law firm manhattan, new york city seven deadly sins ethics gainesville florida
Regency Enterprises Monarchy Enterprises B.V. Kopelson Entertainment Warner Bros. New Regency Pictures Taurus Film
Germany United States of America
English Français Deutsch Italiano 普通话 Español
Comedy
deadbeat dad cheating fiancée teacher student sex brother sister incest
Columbia Pictures Happy Madison Productions Relativity Media
United States of America
English
Fantasy
magic kingdom despot immortality village forest army horror partner revenge knight battle medieval dragonheart
Universal Pictures
United States of America
English
Action Comedy Crime Drama
bahamas master thief crook couple
New Line Cinema Contrafilm Firm Films
United States of America
English
Action Fantasy Thriller
monk eastern europe skeleton biker marvel comic superhero motorcycle devil dark hero ghost rider
Columbia Pictures Imagenation Abu Dhabi FZ Marvel Entertainment Marvel Knights Hyde Park Entertainment Crystal Sky Pictures Michael De Luca Productions
United Arab Emirates United States of America
English
Drama History Romance
officer greek island mandolin italian soldier resistance fighter greek history italian army allied forces
Miramax Films Universal Pictures
United Kingdom United States of America France
English Deutsch ελληνικά Italiano
Action Comedy Drama Family Thriller
bodybuilder children body guard scientist family u.s. soldier death of husband male nanny
Walt Disney Pictures Spyglass Entertainment
Canada United States of America
English 한국어/조선말
Adventure Drama Action Thriller
casino sheriff home violence special forces ex soldier
Metro-Goldwyn-Mayer (MGM) Mandeville Films WWE Studios Hyde Park Entertainment Burke/Samples/Foster Productions Cub Eight Productions
United States of America
English
Comedy Drama Romance
vietnam veteran hippie mentally disabled running based on novel vietnam vietnam war friendship love family relationships bully mother son relationship military hugging shrimping wounded soldier flashback park bench amputee
Paramount Pictures
United States of America
English
Comedy Music Family Fantasy Animation
pop pop star record producer surprise approach forest music concert friendship performance chipmunk talking animal songwriter talking to animals duringcreditsstinger
Dune Entertainment Regency Enterprises Fox 2000 Pictures Bagdasarian Productions
United States of America
English Español Français 日本語
Comedy Romance
cia airport cat jew orderly airplane father-in-law epistaxis daughter lost baggage urn pavilion volleyball hospital wedding
DreamWorks SKG Universal Pictures Tribeca Productions Nancy Tenenbaum Films
United States of America
English
Adventure Animation Drama Family
culture clash settler forbidden love colony musical gold rush princess romance native american animation virginia star crossed lovers reference to pizarro jamestown virginia pug dog cross cultural relationship musket animate tree indian chief based on folk tale 17th century shamanism songs indians vs. settlers animal sidekick powhatan land claim
Walt Disney Pictures Walt Disney Feature Animation
United States of America
English
Action Adventure Fantasy Science Fiction
saving the world journalist dc comics crime fighter nuclear missile galaxy superhero based on comic book criminal sabotage north pole midwest kryptonite super powers superhuman strength aftercreditsstinger save the day
Warner Bros. Dovemead Films Film Export A.G.
United Kingdom United States of America
English
Fantasy Comedy Romance Science Fiction
overweight overweight man duringcreditsstinger
Imagine Entertainment Universal Pictures
United States of America
English
Comedy Drama Romance
speed date romantic comedy dating
Columbia Pictures Corporation Overbrook Entertainment
United States of America
English
Adventure Comedy Family Romance
africa san francisco gorilla lion feral child jungle
Walt Disney Pictures Mandeville Films
United States of America
English Español
Comedy Romance
handcuffs sister sister relationship spanner blow job stag night wedding
Universal Pictures Zide-Perry Productions LivePlanet Loumolo & Co.
United States of America
English
Action Drama Thriller
ship hijacking somalia fisherman blood poverty pirate terrorism commando hijack cargo ship ship captain ship hijacking somali commando unit
Columbia Pictures
United States of America
English Somali
Comedy
date corruption taxi expensive restaurant wife husband relationship gun boat taxi driver document restaurant roof married couple politician stripper shooting thief car crash stealing mistaken identity police corruption aftercreditsstinger duringcreditsstinger
Twentieth Century Fox Film Corporation Dune Entertainment 21 Laps Entertainment
United States of America
עִבְרִית English
Fantasy Comedy Family
halloween friendship supernatural afterlife friends danger ghost disorder young heroes imaginary supernatural ability mischievous children
Universal Pictures Amblin Entertainment The Harvey Entertainment Company
United States of America
English
Thriller Action Crime
corruption assassin hostage fbi hitman russian security camera sadism vigilante sociopath revenge suspense organized crime gore gangster violence teenage prostitute commando interrogation surveillance ex soldier faked death loner call girl black ops hand to hand combat mysterious past
Columbia Pictures Village Roadshow Pictures Escape Artists Mace Neufeld Productions LStar Capital Lonetree Entertainment
United States of America
English
Comedy Drama Romance
hotel politician mistaken identity maid class differences single mother public relations maid uniform hotel clerk wealth differences
Red Om Films
United States of America
English Français
Action Thriller Drama
submarine mutiny russia missile nuclear missile embassy u.s. navy battle for power torpedo military moral dilemma post cold war aircraft carrier chain of command launch code sonar
Hollywood Pictures Don Simpson/Jerry Bruckheimer Films
United States of America
English
Drama
san francisco single parent homeless person bus worker homelessness work church service bad luck biography salesman stockbroker
Columbia Pictures Corporation Escape Artists Relativity Media Overbrook Entertainment
United States of America
English 广州话 / 廣州話
Thriller Drama Mystery
berlin loss of father airplane baby-snatching
Imagine Entertainment Touchstone Pictures
United States of America
العربية Deutsch English Français Italiano 日本語
Drama Thriller Crime Mystery Romance
employee workplace sexual harassment intrigue
Warner Bros. Baltimore Pictures
United States of America
English
Drama Fantasy Romance
suicide angel life and death desperation operation heaven faith afterlife los angeles interspecies romance

Drama History Romance
ancient rome historical figure cleopatra julius caesar
Twentieth Century Fox Film Corporation MCL Films S.A. Walwa Films S.A.
United Kingdom United States of America Switzerland
English Português
Comedy
high school teacher prize money physics teacher fighting movie budget cutting
Columbia Pictures Happy Madison Productions Broken Road Productions
United States of America
English
Drama Mystery Thriller Crime
based on novel witness village court love murder lawyer defense trial justice husband u.s. marine arrested classified
Twentieth Century Fox Film Corporation Regency Enterprises Monarch Pictures Epsilon Motion Pictures New Regency Pictures Manifest Film Company
United States of America
English Español
Comedy Drama Romance
sex professor wedding woman director columbia university
TriStar Pictures Phoenix Pictures
United States of America
English
Drama Horror Mystery
based on novel small town dream motel hallucination bridge alien life-form warning tumor west virginia urban legend premonition telephone call hospital reporter psychic car wreck death of wife mothman mysterious events chemical plant
Lakeshore Entertainment
United States of America
English
Comedy
gay fame mockumentary hollywood lgbt duringcreditsstinger
Universal Pictures
United States of America
Český English Deutsch
Adventure Action Thriller
corruption florida secret identity liberation of prisoners drug traffic floatplane transport of prisoners tank car florida keys coast guard airplane british secret service
Eon Productions
United Kingdom United States of America
English Español
Fantasy Thriller Horror
winter fantasy fairy tale hood werewolf aftercreditsstinger duringcreditsstinger woman director red riding hood
Appian Way Warner Bros. Random Films
Canada United States of America
English
Action Crime Thriller
new york female nudity prison prostitute rape robbery fire detective airport shotgun prisoner ex-detainee attempted murder paranoia russian eastern europe video knife fistfight police thief revenge video camera escape breast dead body lawyer shot to death torture fear new york city urination violence home invasion criminal police detective death drunk nypd news report gun violence graveyard death of boyfriend
New Line Cinema Industry Entertainment Tribeca Productions New Redemption Pictures
Germany United States of America
Český English ελληνικά Pусский
Adventure Comedy Family Fantasy
saving the world brother brother relationship royalty dinosaur based on video game woman director multiple dimensions
Hollywood Pictures Cinergi Pictures Entertainment Allied Filmmakers Walt Disney Nintendo
United Kingdom United States of America
English
Crime Drama Thriller
cold war weapon arms dealer
Saturn Films Ascendant Pictures Endgame Entertainment Entertainment Manufacturing Company Rising Star Copag V
France United States of America Germany
العربية Deutsch English Français Pусский Español Український Türkçe
Drama Adventure Action History
countryside loss of lover right and justice patriot
Beijing New Picture Film Co. Ltd. China Film Co-Production Corporation
China
普通话
Action Comedy Crime
bounty hunter based on novel romance framed bail jumper woman director
Lakeshore Entertainment Sidney Kimmel Entertainment
United States of America
English
Action Comedy
cia coup d'etat north korea assassination attempt evil dictator
Columbia Pictures Point Grey Pictures
United States of America
한국어/조선말 English
Adventure Fantasy Action Western Thriller
assassin small town forest revenge deception super speed surprise ending
Boram Entertainment Inc.
New Zealand South Korea
English ภาษาไทย
Action Comedy Crime
unemployment contortionist human cannonball
France 2 Cinéma France 3 Cinéma Epithète Films France 3 (FR 3) Région Ile-de-France France 2 (FR2) Orange Cinéma Séries Tapioca Films Warner Bros. Entertainment France
France
Français
Drama
individual street gang adolescence rap music hip-hop rhyme battle trailer park ethnic stereotype single detroit eminem
Imagine Entertainment Mikona Productions GmbH & Co. KG
United States of America
English
Adventure Comedy Animation
animation evolution humanity
Pathé Films Boréales
France
English Français
Adventure Drama Romance Action
poetry knight tournament duel torture writer impostor church game jousting aftercreditsstinger
Columbia Pictures Corporation Escape Artists Black and Blu Entertainment Finestkind
United States of America
English
Thriller Fantasy Action Comedy
detective medallion leather jacket wretch fighter wizardry interpol
Living Films Emperor Multimedia Group (EMG) Golden Port Productions Ltd.
Hong Kong United States of America
English
Mystery Thriller Drama
child abuse sense of guilt loss of child confidence psychology dying and death marriage crisis afterlife single paranormal phenomena cowardliness child spiritism
Spyglass Entertainment The Kennedy/Marshall Company Hollywood Pictures Barry Mendel Productions
United States of America
Latin Español English
Action Thriller Crime
deception new york city rooftop diamond heist framed for a crime escaped prisoner negotiator
Summit Entertainment Di Bonaventura Picture
United States of America
English
Comedy
helicopter based on novel honeymoon airplane birding birdwatching duringcreditsstinger
Ingenious Media Dune Entertainment Fox 2000 Pictures Deuce Three Productions Sunswept Entertainment Red Hour Films
United States of America
English
Drama
flat taskmaster karate egg kids and family motorcycle
Columbia Pictures Corporation Jerry Weintraub Productions Delphi Films
United States of America
English
Drama Crime
con artist scam mobster fbi agent
Columbia Pictures Atlas Entertainment Annapurna Pictures
United States of America
English
Comedy Romance Drama
fictitious marriage deportation immigration law romantic comedy alaska naked scene co-worker humiliation book editor fake boyfriend duringcreditsstinger woman director pretend relationship
Touchstone Pictures Mandeville Films Kurtzman/Orci
United States of America
English
Crime Drama Mystery Thriller
prison sailboat sailing trip new orleans women's prison probation murder hunt
Paramount Pictures
Canada United States of America
English
Adventure Comedy Family Science Fiction
skateboarding flying car car race delorean lightning almanac inventor time travel sequel diner alternate history teenager electric guitar walking cane high school dance hoverboard video phone
Universal Pictures Amblin Entertainment U-Drive Productions
United States of America
English
Action Science Fiction
artificial intelligence telepathy intelligence drug mule telekinesis futuristic drug superpower tough girl imax surgery brain capacity synthetic drug human brain
Universal Pictures TF1 Films Production Canal+ EuropaCorp Ciné+
France United States of America
普通话 English Français Español 한국어/조선말
Drama Romance Thriller
based on novel perversion spanking billionaire bdsm woman director
Focus Features Trigger Street Productions Michael De Luca Productions
United States of America
English
Action Adventure Comedy Family Science Fiction
video game intelligence liberation child hero mission
Dimension Films
United States of America
English
Crime Drama Thriller
ku klux klan rape mississippi jurors blackmail attempted murder forgiveness court shooting murder suspense lawyer trial courtroom racial tension kkk racial issues courtroom drama
Regency Enterprises Warner Bros.
United States of America
English
Comedy
big family new job aspiring actor smart kid
Twentieth Century Fox Film Corporation Robert Simonds Productions
United States of America
English
Action Drama Thriller War
war survival navy seal military dangerous mission
Universal Pictures Weed Road Pictures Herrick Entertainment Leverage Management Closest to the Hole Productions Emmett/Furla Films Envision Entertainment Corporation Film 44 Foresight Unlimited Hollywood Studios International Spikings Entertainment
United States of America
English
Comedy
baseball world war ii sport baseball player female athlete home front woman director 1940s
Columbia Pictures Corporation Parkway Productions
United States of America
English
Horror
london england england 1970s spirit single mother demon paranormal investigation demonic possession valak annabelle
New Line Cinema Dune Entertainment The Safran Company Evergreen Media Group warner bross Turkey Soho VFX Atomic Monster
Canada United States of America
English
Drama
hacker hacking creator frat party social network deposition intellectual property entrepreneur arrogance young entrepreneur facebook
Columbia Pictures Scott Rudin Productions Relativity Media
United States of America
English
Comedy Romance Drama
relationship ensemble cast duringcreditsstinger
New Line Cinema Flower Films (II) Internationale Filmproduktion Blackswan
Netherlands United States of America Germany
English
Comedy
haunted house alien life-form riesen-ipod
Dimension Films
United States of America
English
Horror Mystery
mask metal detector film director ex-cop reporter slasher scream series of murders
Konrad Pictures Craven-Maddalena Films Dimension Films
United States of America
English
Adventure Comedy Family Science Fiction
railroad robber california delorean indian territory sports car inventor locomotive saloon horseback riding time travel outlaw sequel mad scientist native american western shootout gunfight train wild west cavalry
Universal Pictures Amblin Entertainment U-Drive Productions
United States of America
English
Comedy
prison training framed embezzlement
Gary Sanchez Productions Warner Bros.
United States of America
English
Romance Horror
adultery maze vampire bite remake rough sex wake religious conflict bestiality correspondence vampire sex autonomous shadow vlad fang vamp
American Zoetrope Columbia Pictures Corporation Osiris Films
United States of America
Latin Română български език ελληνικά English
Romance Drama
cooking book cookbook blog recipe woman director publishing
Columbia Pictures Scott Rudin Productions Easy There Tiger Productions
United States of America
English Français
Drama
baseball biography sport brooklyn dodgers
Warner Bros.
United States of America

Thriller Crime Drama
venice italy gay new york lovesickness double life dual identity jealousy secret identity new love homicide atlantic ocean new identity planned murder prosecution yacht ship inferiority false identity beguilement rejection inferiority complex ocean liner friendship homosexuality wealth cowardliness envy
Paramount Pictures Miramax Films Timnick Films Mirage Enterprises
United States of America
English Italiano
Comedy
friendship sequel road movie buddy comedy
New Line Cinema Universal Pictures Conundrum Entertainment Red Granite Pictures
United States of America
English
Adventure Drama Family
expedition pilot survival sled dogs seal
Walt Disney Pictures Spyglass Entertainment Vertigo Entertainment Kennedy/Marshall Company, The Mandeville Films Winking Productions
United States of America
English
Comedy
intern woman director
Waverly Films Warner Bros.
United States of America
English
Action Comedy
police sequel police officer brother-in-law brother-in-law relationship black men buddy film
Universal Pictures Cube Vision Will Packer Productions Reel Chefs Catering
United States of America
English
Action Adventure Drama History Romance War
secret love mohawk native american 18th century french and indian war
Morgan Creek Productions
United States of America
English Français
Drama Music
black people soul country music loss of brother 1970s jazz blindness and impaired vision georgia overdose bus ride record producer biography from rags to riches childhood trauma gospel indianapolis record label recording studio
Universal Pictures Bristol Bay Productions Baldwin Entertainment Group Anvil Films
United States of America
English
Action Thriller Crime
dystopia based on comic book held captive based on graphic novel black and white and color black and white scene black and white to color mysterious killer doing the right thing mercedes silhouette neo-noir
Dimension Films Troublemaker Studios Miramax
United States of America
English
Drama Action Thriller Crime
bomb terror spain usa president terrorist war against terror camera car journey press television camcorder bodyguard safety terror cell limousine media security guard
Columbia Pictures Original Film Kanzaman Relativity Media Art In Motion
United States of America
Español English
Comedy
poker bondage duringcreditsstinger
The Montecito Picture Company De Line Pictures Bernard Gayle Productions
United States of America
English
Comedy Romance
overweight beauty hypnosis overweight man overweight woman oberflächlichkeit kompliment obesity fat suit beauty standards fat man fat woman attractiveness
Twentieth Century Fox Film Corporation
United States of America
English
Drama Thriller History
assassination cia homophobia new orleans vietnam war john f. kennedy investigation government historical figure president conspiracy death kennedy assassination
Camelot Productions Canal Plus Group Ixtlan Productions Warner Bros.
United States of America
English Español
Comedy Crime
undercover nanny computer virus stress undercover agent overweight woman children disguise fbi agent impersonation
Twentieth Century Fox Film Corporation Regency Enterprises Epsilon Motion Pictures Firm Films Deep River Productions New Regency Pictures Ed Friendly Productions Runteldat Entertainment Big Lou House Productions
United States of America
English
Action Comedy Crime Romance
kidnapping pistol
DreamWorks SKG Newmarket Capital Group Lawrence Bender Productions Pistolero Productions LLC
Mexico United States of America
English Español
Comedy
high school bullying high school sports fake identity adult as a child do over
New Line Cinema Offspring Entertainment
United States of America
English
Comedy Romance
infidelity revenge unfaithful boyfriend woman sitting on a toilet public toilet marital infidelity laxative unfaithful husband
Twentieth Century Fox Film Corporation LBI Productions
United States of America
English
Horror Mystery
car race dying and death plan stock-car-race car crash premonition gore vision
New Line Cinema Practical Pictures Parallel Zide
United States of America
English
Thriller Drama
spy cia cold war soviet union pilot lawyer american
DreamWorks SKG Amblin Entertainment Studio Babelsberg Fox 2000 Pictures Marc Platt Productions Participant Media Reliance Entertainment TSG Entertainment
India United States of America Germany
Pусский English Deutsch
Action Drama Thriller War
helicopter war crimes sniper bosnia and herzegovina fighter pilot bosnian war of 1992-1995 rescue escape tank atrocity gunfight combat military mine field action hero aircraft carrier reconnaissance mass grave
Twentieth Century Fox Film Corporation Davis Entertainment
United States of America
Český English Español
Comedy
aftercreditsstinger
Universal Pictures Spyglass Entertainment Relativity Media Apatow Productions
United States of America
English
Drama Romance Comedy
jealousy wife husband relationship dancing master
Miramax Films
United States of America
English
Comedy Adventure Fantasy Science Fiction Action
defense industry toy shop technical toy soldier prototype killer toys toy comes to life
Universal Pictures Amblin Entertainment DreamWorks Pictures
United States of America
English Français Magyar Español
Action Adventure Fantasy Horror Science Fiction Thriller
anti hero secret agent fistfight based on comic book burn victim
New Line Cinema Pull Down Your Pants Pictures Todd McFarlane Entertainment
United States of America
English
Action Adventure Drama Thriller
loss of lover lover (female) ex-lover torture napoleon bonaparte
Spyglass Entertainment World 2000 Entertainment Count of Monte Cristo Ltd. Touchstone Pictures
United States of America
English
Crime Drama Thriller
judge arrest jury private investigator
Lakeshore Entertainment Sidney Kimmel Entertainment Lionsgate
United States of America
English
Action Mystery Thriller
taxi hotel coma taxi driver prince briefcase hospital stolen identity
Studio Babelsberg StudioCanal Dark Castle Entertainment TF1 Films Production Canal+ Panda Productions Inc. Horticus UK
France Germany United Kingdom
English Deutsch Türkçe العربية
Drama Mystery Thriller
competition secret obsession magic dying and death class society illusion tricks hostility class rivalry
Warner Bros. Touchstone Pictures Syncopy
United States of America
English
Comedy
prison kidnapping sequel car chase sex addict sex tape
New Line Cinema BenderSpink RatPac Entertainment
United States of America
English
Animation Comedy Adventure Family Science Fiction
spaceship alien rescue escape planet astronaut Γη mission control
Rainmaker Entertainment Mainframe Entertainment Weinstein Company, The
Canada United States of America
English
Action Adventure Drama Thriller
loss of family solar eclipse slavery jaguar village maya civilization forest tribe human sacrifice central america maya ancient civilization yucatec maya language
Icon Productions Icon Entertainment International Touchstone Pictures
United States of America
English
Action Adventure Thriller
london england smuggling of arms prison england assassination spy falsely accused secret identity country estate arms deal russia drug traffic secret mission secret intelligence service kgb villain renegade special car tangier morocco big wheel pipeline cello orchestra freedom fighter czechoslovakia bratislava afghanistan airplane schloss schönbrunn escape moscow vienna
United Artists Eon Productions
United Kingdom United States of America
English العربية Français Deutsch Pусский Český Slovenčina
Action Science Fiction Adventure Thriller
hunter predator yakuza hunting human beings alien life-form sequel alien alien planet jungle soldier warrior
Twentieth Century Fox Film Corporation Davis Entertainment Dune Entertainment III Troublemaker Studios
United States of America
English Español Pусский
Comedy Crime Drama Romance Thriller
court case client lawyer courtroom
Universal Pictures Mirage Enterprises Northern Lights Entertainment
United States of America
English
Thriller Mystery
alcohol adultery detective mississippi jealousy isolation paranoia motel window nightmare letter ax notebook police murder mystery arson writer divorce
Columbia Pictures Corporation Pariah Entertainment Group Grand Slam Productions Mel's Cite du Cinema
United States of America
English
Romance Drama Mystery
chicago writing architect future time architecture mysterious letter near future first kiss romantic drama passage of time
Village Roadshow Pictures Vertigo Entertainment Sound for Film Warner Bros.
United States of America
English
Drama Horror Mystery Thriller
nurse secret dream fight kidnapping new orleans key plantation voodoo party lawyer blood violence mirror attic occult
Universal Pictures MFPV Film Double Feature Films ShadowCatcher Entertainment Daniel Bobker Productions Brick Dust Productions LLC
Germany United States of America
English
Fantasy Drama Comedy Family
green dodgeball incredibile timothy
Walt Disney Pictures
United States of America
English Español
Comedy Romance
scotland love of one's life ladykiller one-night stand bridesmaid forbidden love male female relationship best friends in love
Columbia Pictures Original Film
United Kingdom United States of America
English Français Pусский
Music Drama
biography based on play
Warner Bros.
United States of America
English
Drama Crime Thriller
jurors proof court case leukemia lawyer courtroom
Paramount Pictures Constellation Entertainment
United States of America
English
Horror Thriller
amnesia mental institution patient trust false accusations medication gothic mental illness
Columbia Pictures Corporation Dark Castle Entertainment Warner Bros.
United States of America
English
Drama History Mystery
cuba mutiny slavery sentence historical figure havanna tall ship slave trade
DreamWorks SKG
United States of America
English Español
Adventure

United States of America
English Italiano Português
Drama
diving u.s. navy
Fox 2000 Pictures
United States of America
English
Action Crime Drama Thriller
heist
Rainforest Films
United States of America
English
Comedy
adoption marriage divorce birth mother
Millenium Films Two Ton Films
United States of America
English Español Latin
Crime Comedy Action
undercover fbi sequel comedy disguise fbi agent impersonation duringcreditsstinger
Twentieth Century Fox Film Corporation Regency Enterprises New Regency Pictures The Collective Studios Runteldat Entertainment Friendly Films (II) Friendly Films Productions
United States of America
English
Thriller Science Fiction Mystery
bomb identity fantasy bomber suspicion time travel investigation surrealism soldier helicopter pilot
The Mark Gordon Company Vendome Pictures
Canada United States of America
English
Action Adventure Drama Thriller
rugby stranded survival plane wreck airplane crash freezing disaster movie
Paramount Pictures Touchstone Pictures
United States of America
English Português
Thriller Drama Mystery
suicide based on novel hotel room obsession sadomasochism psychological thriller killer family numbers
New Line Cinema Contrafilm Firm Films
Germany United States of America
English
Adventure Drama Family
train cartographer
Epithète Films Cross Creek Pictures Tapioca Films
Canada France
English
Action Comedy
submarine california world war ii war ship pearl harbor satire los angeles anarchic comedy
Columbia Pictures Universal Pictures A-Team
United States of America
English Deutsch 日本語
Drama Family
horse race horse kentucky sport based on true story family relationships father daughter relationship
DreamWorks SKG Hyde Park Entertainment

English
Drama Thriller Crime
robbery double life dual identity small town indiana distrust fight self-defense marriage family relationships mistaken identity diner lawyer mobster violence attempted robbery
New Line Cinema DC Comics BenderSpink
United States of America Canada Germany
English
Action Thriller Crime
martial arts war on drugs kidnapping bodyguard baby-snatching
Canal Plus Twentieth Century Fox Film Corporation Current Entertainment TF 1 Film Productions TPS Star EuropaCorp Revolution Sun Studios
France United States of America
English Français Italiano
Action Western
gunslinger revenge prairie shootout pistol
TriStar Pictures
Japan United States of America
English
Action Comedy Romance Thriller
irland rock star court case rivalry falling in love divorce lawyer
New Line Cinema Irish Dreamtime Deep River Productions Initial Entertainment Group (IEG)
Germany Ireland United Kingdom
English
Drama
new york coma ambulance night life drug addiction hallucination dying and death night ambulance man alcoholism teacher hospital violence city drug illegal prostitution road movie euthanasia
Paramount Pictures Touchstone Pictures De Fina-Cappa
United States of America
English
Action Science Fiction Thriller Crime
dystopia evil corporation repo man aftercreditsstinger
Universal Pictures Stuber Productions Dentsu Relativity Media
Canada United States of America
English
Fantasy Drama Horror Action Thriller Science Fiction
giant snake korea building dagger south korea
Younggu-Art Movies Showbox Entertainment
South Korea
English 한국어/조선말
Fantasy Comedy Family
circus magic aunt imaginary friend
Regency Enterprises Yorktown Productions Warner Bros.
United States of America
English
Comedy
magic las vegas
New Line Cinema Benderspink Carousel Productions
United States of America
English
Animation Comedy Family Music
dance musical furry talking animal anthropomorphism hollywood singing acting movies
Warner Bros. Pictures David Kirschner Productions Turner Feature Animation
United States of America
English Deutsch
Drama

Touchstone Pictures
United States of America
English
War Crime Drama Mystery Romance Thriller
berlin corruption nazi background love of one's life chauffeur black market missile postwar period war correspondent allied truth murder humanity
Warner Bros. Section Eight Productions Sunset Gower Studios
United States of America
English Deutsch 普通话 Pусский
Adventure
swordplay hero sword dragon
Carousel Picture Company ApolloMedia Distribution Ravenhouse Entertainment
Germany United Kingdom United States of America Luxembourg
English
Drama War
guerrilla river vietnam vietcong cambodia army insanity tribe green beret jungle apocalypse death napalm
United Artists Zoetrope Studios
United States of America
 English Français Tiếng Việt
Comedy Drama Romance
male nudity sex san francisco waitress newspaper bar nudity airplane male female relationship writer new york city masturbation phone sex text messaging intern long distance relationship woman director record company skype
New Line Cinema Offspring Entertainment
United States of America
English
Music Drama Family
composer mentor deaf-mute musical apprentice private life music disabled
Hollywood Pictures The Charlie Mopic Company PolyGram Filmed Entertainment Interscope Communications
United States of America
English
Action
cia memory convict implant
Lionsgate BenderSpink Millennium Films Fipex Holding Campbell Grobman Films Criminal Productions
United Kingdom United States of America
English
Drama
dancing train station denmark fire cemetery compass lion picnic fireworks grave passion farm worker plantation kenia coffee plantation safari banker airplane wedding night adventure aggression by animal friendship syphillis
Universal Pictures Mirage Entertainment
United States of America
English Kiswahili
Drama
confession airplane f word hangover airplane crash syringe denial porn actress jesus freak baseball stadium perjury national transportation safety board flying upside down narcissist relapse substance abuse
Paramount Pictures Parkes/MacDonald Productions ImageMovers
United States of America
English
Action Adventure Thriller Science Fiction
venice mass murder space marine space suit marcus square space battle secret base utopia space travel boat chase astronaut lasers british secret service weightlessness
United Artists Eon Productions
France United Kingdom United States of America
English Italiano
Comedy Drama
hotel painting wartime gunfight theft mentor protégé relationship european hotel lobby renaissance painting
Fox Searchlight Pictures Scott Rudin Productions Studio Babelsberg Indian Paintbrush TSG Entertainment American Empirical Pictures
United Kingdom United States of America Germany
English Français
Drama Mystery
american football billard baseball bat richard nixon psychic power american flag wager lingerie slip single mother moving stranger childhood childhood friends ferris wheel straw hat informant mysterious stranger woman crying library card low men bronko nagurski culvert floating on inner tube wind chime jack of spades clairvoyant hires root beer wrong number
Castle Rock Entertainment
Australia United States of America
English
Comedy Horror
small town outbreak exterminator spider bite creature feature spider queen animal attack spiders invasive species arachnophobia animal horror spider general
Amblin Entertainment Hollywood Pictures Tangled Web Productions
United States of America
English Español
Crime Drama Science Fiction Thriller
new york mother detective baseball radio firemen future time race against time investigation father history murder paranormal rescue family relationships escape crime explosion flashback phenomenon amateur radio aurora borealis altering history
New Line Cinema
United States of America
English
Comedy
route 66 grand canyon cow vacation road trip sequel dysfunctional family family vacation amusement park trucker roller coaster theme park airline pilot bipolar disorder plano texas
New Line Cinema BenderSpink David Dobkin Productions
United States of America
English
Comedy Thriller Crime
gambling miami based on novel job murder travel mafia money debt mobster business hollywood gangster crime violence drug producer con
Jersey Films Metro-Goldwyn-Mayer (MGM)
United States of America
English
Action Comedy Crime Drama Music
chicago based on stage musical prison matron jazz age nude man murdered
Miramax Films Producers Circle Storyline Entertainment
United States of America
Magyar English
Comedy Drama
bachelor law vomit syracuse university law school young boy politically incorrect wetting pants central park public urination child's point of view responsibility immaturity
Columbia Pictures
United States of America
English Italiano
Comedy Romance
sex party summer beach house group of friends gross out comedy tantra mistaken for a special education student superglue sex comedy
Universal Pictures Liveplanet Zide-Perry Productions
United States of America
English
Animation Comedy Family
jealousy toy boy friendship friends rivalry boy next door new toy toy comes to life
Pixar Animation Studios
United States of America
English
Action Adventure Crime
bomb airport bus bus ride highway bomb planting
Twentieth Century Fox Film Corporation
United States of America
English
Drama Romance
coma amnesia based on true story memory loss car accident romantic drama
Spyglass Entertainment Screen Gems
United States of America
English
Drama

Double Feature Films CBS Films
United States of America
English
Drama
ku klux klan american football trainer sports team race politics coaction apartheid sport high school racial segregation racist based on true story american football player xenophobia head coach
Walt Disney Pictures Jerry Bruckheimer Films Technical Black Run It Up Productions Inc.
United States of America
English
Action Adventure Thriller
submarine cold war russian defection jack ryan
Paramount Pictures Nina Saxon Film Design Mace Neufeld Productions
United States of America
English Pусский
Drama
white house butler biography civil rights
Laura Ziskin Productions Lee Daniels Entertainment Follow Through Productions Salamander Pictures Pam Williams Productions Windy Hill Pictures
United States of America
English
Comedy
underdog competition bank bar ball cheerleader diet wife sport gymnasium pleite fitness-studio love mail order bride cheerleading pirate aftercreditsstinger duringcreditsstinger
Twentieth Century Fox Film Corporation Red Hour Films Mediastream Vierte Film GmbH & Co. Vermarktungs KG
Germany United States of America
English Deutsch
Horror Comedy Fantasy
dead wish vampire black humor uncle eccentric werewolf macabre loan shark accountant
Paramount Pictures Orion Pictures Scott Rudin Productions
United States of America
English
Crime Comedy Adventure
africa indigenous human animal relationship bat
O Entertainment Morgan Creek Productions
United States of America
English
Comedy Family Romance
heir to the throne grandmother granddaughter relationship high school princess royalty teenager popularity social outcast based on young adult novel
Walt Disney Pictures BrownHouse Productions Bottom of the Ninth Productions
United States of America
English
Comedy
divorce divorced woman reunited friends
Scott Rudin Productions
United States of America
English
Crime Mystery Thriller
self-fulfilling prophecy detective s.w.a.t. drug dealer evisceration lust and impulsiveness rage and hate pride and vanity immoderateness insomnia investigation pension police serial killer
New Line Cinema Juno Pix Cecchi Gori Pictures
United States of America
English
Science Fiction
slum street gang mutation south africa johannesburg dystopia genetics government satire alien prawn mockumentary alternate history racism metamorphosis xenophobia internment camp body transformation alien technology segregation
WingNut Films TriStar Pictures Key Creatives Block / Hanson Canadian Film or Video Production Tax Credit (CPTC) The Department of Trade and Industry of South Africa QED International Province of British Columbia Production Services Tax Credit District 9 New Zealand Post Digital and Visual Effects Grant
United States of America New Zealand Canada South Africa
Afrikaans    isiZulu English
Animation Comedy Family
ocean sea star water freeze spongebob
Paramount Pictures Nickelodeon Movies United Plankton Pictures Paramount Animation
United States of America
English
Thriller Crime Drama Mystery
child abuse sexual abuse loss of child repayment suppressed past arbitrary law boston workers' quarter reference to sprite child
Village Roadshow Pictures Malpaso Productions NPV Entertainment Warner Bros.
United States of America
English
Drama
transporter suicide attempt strong woman boxer dying and death stroke of fate training advancement sport female protagonist boxing trainer determination
Lakeshore Entertainment Malpaso Productions Epsilon Motion Pictures Warner Bros. Albert S. Ruddy Productions
United States of America
English Gaeilge
Comedy Crime
new york mafia boss wedding psychiatrist
Spring Creek Productions Warner Bros. Tribeca Productions Baltimore Pictures
Australia United States of America
English
Romance Drama
poem river sadness fight love of one's life dementia class secret love tears candle mailbox
New Line Cinema
United States of America
English
Comedy Romance
lovesickness newspaper bar sister sister relationship new love wedding planer witness bride bridesmaid sister music romantic comedy sibling rivalry reporter wedding woman director
Spyglass Entertainment Fox 2000 Pictures Dune Entertainment III
United States of America
English
Comedy Drama Family Music Romance
double life pop star musical tennessee teenage girl teen movie teenager hometown famous
Walt Disney Pictures It's a Laugh Productions Millar Gough Ink
United States of America
English
Adventure Animation Comedy Family
paris invention
Paramount Pictures Nickelodeon Movies Paramount Animation
Germany United States of America
English
Drama Romance
american football trainer twin sister suppressed past psychiatrist extramarital affair woman director
Columbia Pictures
United States of America
English
Adventure Drama Romance War
brother brother relationship montana based on novel world war i journey round the world
Bedford Falls Productions TriStar Pictures Pangaea
United States of America
 English
Drama Romance
suitcase business omaha on the road downsizing cross country duringcreditsstinger
Paramount Pictures Rickshaw Productions Cold Spring Pictures Montecito Picture Company, The DW Studios Right of Way Films
United States of America
English
Drama Comedy
wife husband relationship channel surfing mullet spiritual journey life changing pioneer village family gathering
New Line Cinema Avery Pix
United States of America
English
Horror Comedy Romance
post-apocalyptic dystopia zombie zombie apocalypse interspecies romance based on young adult novel
Summit Entertainment
Canada
English
Action Thriller Science Fiction
suicide assassin drug addiction future time travel dystopia retirement boy murder organized crime tragedy execution violence criminal drug addict contract killer neo-noir
Endgame Entertainment FilmDistrict DMG Entertainment Ram Bergman Productions
China United States of America
English
Fantasy Comedy Science Fiction Romance

Paramount Pictures Alphaville Films
United States of America
English
Fantasy Drama Comedy Family
sheep pig affection piglet heroism talking animal separation german shepherd grandson talking pig
Universal Pictures Kennedy Miller Productions
Australia United States of America
English
Drama Comedy Romance
renewing wedding vows marriage counselling
Columbia Pictures Mandate Pictures Escape Artists Management 360 Metro-Goldwyn-Mayer (MGM)
United States of America
English
Comedy Romance Drama
hawaii one-night stand beauty
Universal Pictures Apatow Productions
United States of America
English 日本語 Deutsch
Action Crime
brother brother relationship robbery arbitrary law adoptive mother revenge murder violence detroit duringcreditsstinger interracial adoption
Paramount Pictures Di Bonaventura Pictures
United States of America
Español English
Comedy
pregnancy and birth surrogate mother
Relativity Media Michaels-Goldwyn
United States of America
English
Drama Romance
texas telegram despair leaving one's family funeral costume loss high school judgment dog pond
Twentieth Century Fox Film Corporation Fortis Films
United States of America
English
Comedy
bride friendship engagement rivalry wedding family feud
Dune Entertainment Regency Enterprises Fox 2000 Pictures Dune Entertainment III New Regency Pictures Sunrise Entertainment (II) Biride Productions
United States of America
English
Action Adventure Comedy Thriller
death of a friend treasure hunt
Paramount Pictures De Line Pictures
United States of America
English
Comedy Fantasy Romance
new york photographer editor-in-chief wish michael jackson child as an adult best friends in love
Columbia Pictures Revolution Studios Thirteen Productions
United States of America
English Français Português
Fantasy Comedy Romance
paris painter detective based on novel screenwriter forbidden love time travel midnight nostalgia past sculpture hemingway
Gravier Productions Televisió de Catalunya (TV3) Versátil Cinema Mediapro Pontchartrain Productions
Spain United States of America
English Français Deutsch Español
Animation Comedy Family Adventure
squirrel 3d
Open Road Films Gulfstream Pictures Red Rover International ToonBox Entertainment
Canada South Korea
English
Crime Drama
1970s war on drugs drug addiction drug traffic drug smuggle rise and fall
New Line Cinema
United States of America
English
Romance Drama
sailboat anonymous letter sailing love letter bottle
Bel Air Entertainment DiNovi Pictures Tiger Productions
United States of America
English
Science Fiction Action Adventure Thriller
federation starfleet uss enterprise-a sha-ka-ree loss of brother self sacrifice hostage liberation of hostage romulans klingon vulcan space opera
Paramount Pictures
United States of America
English
Comedy Drama Family Fantasy
bet lightning sports team sport basketball bullying orphanage teenager
Twentieth Century Fox Film Corporation Josephson Entertainment NBA Entertainment Heller Highwater Productions Like Mike Productions
United States of America
English
Comedy Crime
undercover spoof state prison
Paramount Pictures
United States of America
English
Adventure Action Thriller
paris london england france england san francisco horse race fire helicopter drug abuse terrorist secret identity firemen fire engine villain ascot silicon valley zeppelin earthquake snowboarding microchip doping racehorse flooding pipeline snow british secret service skiing
Eon Productions
France Iceland United Kingdom United States of America
English
Adventure Animation Comedy Family
competition garden vegetable stop motion animation contest dog rabbit pest control giant vegetable wallace & gromit
Aardman Animations DreamWorks Animation
United Kingdom United States of America
English
Drama Romance
job-hopping irland shoe seller letter dying and death loss of husband
Wendy Finerman Productions Alcon Entertainment Grosvenor Park Productions
United States of America
English
Comedy
love of animals horse identity crisis farm zebra
Alcon Entertainment
United States of America South Africa
English
Drama Romance
based on novel sister sister relationship flirt loss of sister new love world war ii book mistake innocence author redemption summer
Universal Pictures Studio Canal Relativity Media Working Title Films
United Kingdom France United States of America
English Français
Comedy Drama Romance
italy letter romantic comedy american abroad boyfriend girlfriend italian stereotype verona italy quest
Summit Entertainment Applehead Pictures
United States of America
English Italiano Español
Action Thriller Crime
japan yakuza japanese mafia
Paramount Pictures Pegasus Film Partners Jaffe-Lansing
United States of America
English 日本語
Comedy
duringcreditsstinger
Wessler Entertainment
United States of America
English
Romance Fantasy Animation Music
shyness england cheating old town grave skeleton musical marriage wedding ring stop motion animation money wedding corpse wedding ceremony parents dark fantasy european ring piano

Canada United States of America
English
Fantasy Comedy Family
loss of mother nanny education wizardry children single father
Universal Pictures Three Strange Angels Studio Canal Metro-Goldwyn-Mayer (MGM) Working Title Films Nanny McPhee Productions
France United Kingdom United States of America
English
Action Crime Drama Thriller
miami corruption capitalism cuba prohibition brother sister relationship loss of sister cocaine cult film bitterness
Universal Pictures
United States of America
English Español
Action Adventure Comedy
rap music infidelity security camera loss crook sociopath revenge artifact f word racism criminal on the road desert security guard shoplifting screwball reckless driving road movie buddy comedy unlikely friendship carjacker advertising executive suv aftercreditsstinger
Touchstone Pictures
United States of America
English
Drama History
buddhism japan suicide china suicide attempt war crimes becoming an adult isolation war on drugs revolution emperor arranged marriage manchuria dynasty reeducation camp cultural revolution human experimentation war coup d'etat teacher beijing decadence communism
Columbia Pictures Hemdale Film Corporation Recorded Pictures Company Soprofilms TAO Film Yanco
France China United Kingdom Italy
Český English 日本語 普通话 Pусский
Thriller Action Drama Crime
head wound criminal security guard contraband
Universal Pictures StudioCanal Relativity Media Leverage Management Closest to the Hole Productions Farraday Films Leverage Entertainment Working Title Films Blueeyes Productions
United States of America United Kingdom France
English
Action Adventure Comedy
prison diamant liberation of prisoners transport of prisoners interview arrest
New Line Cinema
United States of America
English
Drama
brother brother relationship deaf-mute american dream fanatic pipeline petrol father step father oil money killer alcoholic
Miramax Films Ghoulardi Film Company Paramount Vantage
United States of America
English
Animation Adventure Family
sister sister relationship safari wildlife baboon chimpanzee woman director
Paramount Pictures Nickelodeon Movies Paramount Animation
United States of America
English Italiano
Animation Family
kids and family
Nickelodeon Movies Paramount Animation
United States of America
English
Action Comedy
usa president double life policy and organisations undercover intelligence partner duringcreditsstinger
Universal Pictures
United States of America
English
Drama Comedy
holiday female friendship jeans coming of age teenage girl summer based on young adult novel
DiNovi Pictures Alcon Entertainment Alloy Entertainment
United States of America
English ελληνικά Español
Action Crime Thriller
paris prostitute drug
Twentieth Century Fox Film Corporation Current Entertainment Immortal Entertainment Canal+ EuropaCorp Quality Growth International Ltd.
France United States of America
English Français 普通话
Romance Comedy
virgin nudity college costume yoga bikini party playboy jail sorority pregnancy model car wash fraternity pledge
Columbia Pictures Happy Madison Productions Relativity Media Alta Loma Entertainment
United States of America
English
Comedy Romance

Metro-Goldwyn-Mayer (MGM)
United States of America
English
Drama
baseball sport duringcreditsstinger
Walt Disney Pictures
United States of America
हिन्दी English
Drama Science Fiction
dystopia black and white based on young adult novel
The Weinstein Company Walden Media Tonik Productions Asis Productions
United States of America
English
Comedy
london england england daughter politician teenage girl father daughter relationship american abroad teen comedy woman director
DiNovi Pictures Gerber Pictures Gaylord Films Warner Bros. Sloane Square Films HSI Tomorrow Film
United States of America
English
Horror Thriller
father son relationship scarecrow peasant farm immortality mythical creature father
United Artists American Zoetrope Myriad Pictures Jeepers Creepers II
United States of America
English
Comedy Drama Romance
sex aquarium nudity one-night stand bride man-woman relation love curse wedding dentist based on short story duringcreditsstinger
Lionsgate Karz Entertainment
Canada United States of America
English
Action Crime Drama
robbery diamant intelligence bank robber thief bank robbery financial transactions hoodlum
Silver Pictures Warner Bros.
United States of America
English 한국어/조선말 Pусский
Drama
london england suicide gay poetry aids drowning depression home way of life self-destruction province literature empowerment country life family's daily life sense of life homelessness leaving one's family delusion
Paramount Pictures Miramax Films Scott Rudin Productions
United States of America
English
Comedy Drama Family Romance
roommate twin sister sport boarding school twin brother mistaken identity soccer teenager teen comedy tomboy fake identity disguised voice the big game
DreamWorks SKG Lakeshore Entertainment
United States of America
English
Family Comedy
holiday france film director chaos clumsy fellow to drop brick aftercreditsstinger
Tiger Aspect Productions Working Title Films
United Kingdom France Germany
English
Adventure Action Horror Science Fiction Thriller
snake expedition traitor research orchid jungle animal horror
Screen Gems Middle Fork Productions
United States of America
English Pусский
Thriller Crime Drama

Wild Bunch LGM Productions Les Productions du Trésor Mars Distribution Canal+ France Télévision Worldview Entertainment Ciné+ M6 France 3 Cinema Caneo Films Grisbi Productions France 4 W9 Chi-Fou-Mi Productions Treasure Company
France United States of America
Español English Italiano
Drama
date loss of son love at first sight child labour guitar loss of child lover (female) love of one's life harmonica lie choir church choir rock star cello forbidden love music lover organ kiss affection music concert tenderness motherly love children's home death of a child orphanage secret love crush children falling in love relationship woman director piano
Warner Bros. CJ Entertainment Southpaw Entertainment
United States of America
English
Drama History
duke historical figure treason catholic protestant
Channel Four Films PolyGram Filmed Entertainment Working Title Films
United States of America
Français English
Horror Comedy
route 66 puppet evil doll killer doll killer toys toy comes to life chucky
Universal Pictures Midwinter Productions Inc.
Canada United States of America
English
History Action Drama Adventure War
japan world war ii pearl harbor soldier imperial japan
Twentieth Century Fox Film Corporation
Japan United States of America
English 日本語
Adventure Fantasy Drama Comedy Music
pop pop culture pop star
Columbia Pictures Corporation
United Kingdom
English
Comedy
babysitter duringcreditsstinger
Twentieth Century Fox Film Corporation Michael De Luca Productions Rough House Pictures
United States of America
English
Action Comedy Music
rap music hip-hop
Paramount Pictures MTV Films Wayans Bros. Entertainment
United States of America
English
Drama Crime
prison corruption police brutality prison cell delinquent parole board escape from prison wrongful imprisonment framed for murder 1940s
Castle Rock Entertainment
United States of America
English
Adventure Comedy
crocodile traffic jam los angeles stolen painting
Bungalow Productions Silver Lion Films Vision View Entertainment
Australia United States of America
English
Comedy
sport handicap sexual favor star spangled banner bowling team hair loss biblical interpretation comb over female stripper inflatable doll combover unlikely lovers kingpin carriage lancaster, pa
Motion Picture Corporation of America Metro-Goldwyn-Mayer (MGM)
United States of America
English
Thriller Crime Drama
gambling gun professor beating gambler loan shark
Paramount Pictures Closest to the Hole Productions Leverage Entertainment Chartoff-Winkler Productions
United States of America
English
Comedy Drama
suicide drug addiction funeral dysfunctional family based on play midwest southern bleak comedy mental disorders
Jean Doumanian Productions Smokehouse Pictures
United States of America
English
Drama Comedy Family
sport figure skating teenage girl teen movie teenager
Walt Disney Pictures Bridget Johnson Films Skate Away Productions
United States of America Canada
English
Comedy
new york shyness career flight romantic comedy travel male female relationship los angeles
Mile High Productions Kevin Messick Productions Touchstone Pictures Beacon Pictures
United States of America
English
Comedy Drama History
underdog olympic games ski jump biography sport based on true story britain skiing feel good
Studio Babelsberg Twentieth Century Fox Film Corporation Marv Films Saville Productions
Germany United Kingdom United States of America
English Deutsch Norsk
Drama
prison father son relationship homicide begnadigung release from prison forgiveness college basketball independent film
40 Acres & A Mule Filmworks Touchstone Pictures
United States of America
English
Romance Drama Comedy
sex addiction love mental institution patient psychiatrist don juan
New Line Cinema American Zoetrope
United States of America
English
Drama Romance War
based on novel army love u.s. soldier
Screen Gems
United States of America
English
Action Adventure Crime Mystery Thriller
hospital black ops reference to macgyver sucked into jet engine
DC Comics Weed Road Pictures Dark Castle Entertainment Warner Bros. DC Entertainment
United States of America
English
Fantasy Horror Thriller
monster remake creature bathtub teeth old house scary little people
Miramax Films Gran Via Productions FilmDistrict Necropia Tequila Gang
United States of America Australia Mexico
English
Action Thriller Crime
fbi revenge fbi agent
Mosaic Media Group Current Entertainment Lionsgate Fierce Entertainment Province of British Columbia Production Services Tax Credit Rogue Films
United States of America Canada
广州话 / 廣州話 English 日本語 普通话
Comedy Drama Romance
shyness brother sister relationship business man
Columbia Pictures New Line Cinema Ghoulardi Film Company
United States of America
English
Comedy
paris berlin alcohol sex nudity adventure pen pals travel nudism marijuana teenager duringcreditsstinger
DreamWorks SKG The Montecito Picture Company Blue Sea Productions
United States of America
English Français Italiano 日本語 Deutsch
Crime Action Thriller
resistance undercover alcatraz stolen money
Franchise Pictures Screen Gems
Germany United States of America
English
Comedy Family
holiday


English
Drama
magazine writer drug fashion show
United Artists Mirage Enterprises CST Telecommunications Star Partners
Japan United States of America
English
Animation Family Fantasy
italy father son relationship pinocchio love school crime having fun poor people boys
New Line Cinema The Kushner-Locke Company Savoy Pictures
Czech Republic France Germany United Kingdom United States of America
English Italiano
Drama Family
sport
Walt Disney Pictures
United States of America
English
Thriller Science Fiction
experiment homicide key sacrifice research test decision police control stalker murder alien gift conspiracy money scientist violence button stranger box
Media Rights Capital Lin Pictures Warner Bros. Darko Entertainment Radar Pictures
United States of America
English
Drama Horror
maya civilization carnivorous plant cancún ruins
Spyglass Entertainment Pacific Film and Television Commission DreamWorks Pictures Red Hour Films Internationale Filmproduktion Prometheus
United States of America Germany Australia
English Polski Pусский
Comedy
gay parents kids relationship custody battle flush yoga single best friend los angeles single father co-parenting
Paramount Pictures Lakeshore Entertainment
United States of America
Français English
Drama Horror Mystery Thriller
soul serial killer slasher teenager 3d
Relativity Media Rogue
United States of America
English
Comedy
porn actor pornographic video high school school party blonde girl next door
Regency Enterprises Epsilon Motion Pictures New Regency Pictures Daybreak
United States of America
English
Action Adventure Thriller
mistake in person dying and death twin brother russian mafia
Columbia Pictures
United States of America
English
Action Comedy Drama
robbery fool studies house uncle independent film money
Columbia Pictures Imagine Entertainment Revolution Studios
United States of America
English
Crime Thriller
biography based on true story gangster twins
Working Title Films Cross Creek Pictures Anton Capital Entertainment (ACE)
United Kingdom United States of America France
English
Action Comedy
stuntman step father swimming pool aftercreditsstinger
Paramount Pictures
United States of America
English
Horror Thriller
shark attack louisiana dirty cop shark aftercreditsstinger
Incentive Filmed Entertainment
United States of America
English Português
Drama
emigration irish-american hunger socially deprived family famine alcoholism brooklyn new york city
Paramount Pictures Universal Pictures
Ireland United States of America
English
Drama
sport duringcreditsstinger
Summit Entertainment Lionsgate
United States of America
English
Fantasy Horror Science Fiction Thriller
space marine vampire flying saucer comet alien halley's comet
TriStar Pictures Golan-Globus Easedram
United Kingdom
English Español
Crime Drama History
president history conspiracy lawyer trial boarding house military tribunal historical union private club
Wildwood Enterprises American Film Company
United States of America
English
Drama
skateboarding success independent film woman director
Columbia Pictures TriStar Pictures
Germany United States of America
English Español
Drama History
mining chile based on true story survival woman director mining accident
Alcon Entertainment Phoenix Pictures Fabula Half Circle
United States of America Chile
Español English
Action Adventure Comedy Fantasy
kung fu chinatown magic mystery
Twentieth Century Fox Film Corporation TAFT Entertainment Pictures
United States of America
广州话 / 廣州話 English
Comedy Romance

TF1 Films Production Quad Productions
France
Français Italiano Polski
Action Drama
bank training beating mixed martial arts teacher muscleman combat alcoholic gym exercise
Solaris Film Lionsgate Mimran Schur Pictures Filmtribe
United States of America
English
Drama Thriller
civil war fight presidential election freedom fighter chinese civil war ireland
Geffen Pictures Warner Bros.
Ireland United Kingdom
English
War Drama History
civil war independence troops army battle union soldier confederate soldier american civil war
TriStar Television Esparza / Katz Productions
United States of America
English
Drama War
post traumatic stress  disorder iraq war veteran u.s. soldier woman director
Paramount Pictures Scott Rudin Productions MTV Films Peirce Pictures
United States of America
English
Drama Mystery Thriller
alcohol detective dancer nightmare college job party elite suspense drug boyfriend thesis pressure
Paramount Pictures Spyglass Entertainment Touchstone Pictures
Australia United States of America
Italiano English
Drama Thriller
holiday prison thailand drug injustice
Twentieth Century Fox Film Corporation Fox 2000 Pictures Adam Fields Productions Two Girls Productions
United States of America
English ภาษาไทย
Horror Thriller

Ghost House Pictures North Box Productions
United States of America Canada
English
Comedy Romance Drama
role reversal mistaken identity train wreck
TriStar Pictures
United States of America
English
Drama Thriller
southern usa rape bar wife husband relationship barn machismo rifle home invasion
Battleplan Productions
United States of America
English
Comedy Drama
flying 1970s false identity biography
Miramax Films The Mark Gordon Company Yari Film Group Bob Yari Productions
United States of America
English
Action Crime Thriller
undercover fbi biker cop motorcycle gang
Stone Group Pictures Vision International
United States of America
English
Adventure Drama
post-apocalyptic dystopia paternity duringcreditsstinger
2929 Productions Dimension Films Nick Wechsler Productions Chockstone Pictures
United States of America
English
Action Adventure Comedy Fantasy Science Fiction
africa mercenary adventure female hero jungle girl
Columbia Pictures Corporation Delphi II Productions Colgems Productions Ltd.

English
Action Comedy
police high school undercover cop
Miramax Films
United States of America
English
Comedy Romance

Twentieth Century Fox Film Corporation Conundrum Entertainment Say It Isn't So Productions
United States of America
English
Drama
new zealand utah life's dream independent film motorcycle motorcycle racing trailer mortgage
New Zealand Film Commission 2929 Productions OLC / Rights Entertainment Tanlay New Zealand Film Production Fund 3 Dogs and a Pony Park Road Post WFI Productions Ltd.
New Zealand Switzerland Japan United States of America
English Français Pусский
Action Comedy Fantasy Science Fiction
destroy dystopia reincarnation desert artial arts woman director
Trilogy Entertainment Group
United States of America
English
Comedy Crime
caper action

Canada United States of America
English
Drama Mystery Science Fiction Thriller
fight blindness and impaired vision asylum leader society eye specialist uprising doomsday plague
Rhombus Media O2 Filmes Téléfilm Canada Bee Vine Pictures Alliance Films Asmik Ace Entertainment GAGA Fox Filmes do Brasil Ancine BNDES Cinema Investment Corus Entertainment Movie Central Network
Brazil Canada Japan
日本語 English
Action Adventure Fantasy Horror
vampire vampire hunter based on video game romania
Boll KG
United States of America
English Português
Comedy Drama
flat mobile phone hamster insult dark comedy writer tulips meeting puke pants liberal
Wild Bunch Zanagar Films Canal+ Constantin Film Produktion CinéCinéma Versátil Cinema SBS Productions Polski Instytut Sztuki Filmowej France Télévisions France 2 Cinéma SPI Film Studio
Spain France Germany Poland
English
Drama Mystery Thriller
sex journalist journalism 1970s entertainer one-night stand extramarital affair sex party
Serendipity Point Films
United States of America
English
Fantasy Family
clown music mimes cirque du soleil carnies aerialist
Reel FX Creative Studios
United States of America
English
Drama
running olympic games sport athlete
Cruise/Wagner Productions Warner Bros.
United States of America
English
Comedy Drama Romance
new york based on novel historical figure theater 1930s
Isle of Man Film Freestyle Releasing CinemaNX
United States of America
English
Drama Romance Crime Mystery
painting auctioneer confidence game fine art honey pot
Paco Cinematografica Warner Bros. Regione Lazio Business Location Sudtirol Alto Adige Friuli Venezia Giulia Film Commission UniCredit Group
Italy
English
Drama Crime
police brutality organized crime policeman illegal drugs murder investigation corrupt cop
Saturn Films Nu Image Films Edward R. Pressman Film Millennium Films Polsky Films Osiris Productions Lieutenant Productions
United States of America
Español English
Animation Family
global warming sea turtle 3d
Motion Investment Group nWave Pictures Illuminata Pictures
France Belgium
English
Comedy Drama
american football country house motorboat male female relationship thirty something beach house organic food weasel group of friends reprimand declaration of love parent child relationship texting low tide forced interrupted vacation osteopath lovesick
M6 Films Les Productions du Trésor EuropaCorp
France
Français
Drama
independent film
Capitol Films Rising Star
United States of America Germany
English
Family Adventure Animation
cat surrealism cartoon cat
Herold and Family
France
Český English Français Polski
Family Animation
russia space mission space outer space dog
CN Film
United States of America Russia
Pусский
Thriller Crime Drama
poetry lawyer drug smuggling drug trafficking red dress
Ingenious Media Fox 2000 Pictures Scott Free Productions Kanzaman Nick Wechsler Productions Big Screen Productions Chockstone Pictures Translux TSG Entertainment
United Kingdom United States of America
English

English
Drama Music
rock and roll music style success john f. kennedy advancement bob dylan rock biography music beatnik motor-bike accident
Endgame Entertainment Rising Star Killer Films John Wells Productions Dreamachine Film & Entertainment VIP Medienfonds 4 GmbH & Co. KG (I) Grey Water Park Productions John Goldwyn Productions Wells Productions
United States of America
English
Action Thriller
kidnapping spying government
Summit Entertainment Intrepid Pictures Film Rites Galavis Film Picture Machine Fria Luz Del Dia, A.I.E.
United States of America
English Español
Adventure Comedy Drama Romance
con man estafa
The Weinstein Company Summit Entertainment Endgame Entertainment
United States of America
English Français Český 日本語
Drama
new york man-woman relation writer
Likely Story
United States of America
English
Adventure Fantasy Animation
fight wolf village and town iron pan wild boar territory friendship princess good vs evil anime
Miramax Films Studio Ghibli Nibariki Nippon Television Network (NTV)
Japan
日本語
Comedy Drama Foreign


France
Italiano Français Deutsch English
Comedy Music
camp disco woman director village people
EMI Films
United States of America
English
Action Adventure Crime Drama Thriller Western
gallows australia psychopath outlaw misanthrope gang shootout sadist brutality violence hideout retribution flogging whipping sunset aborigine savagery
Autonomous UK Film Council Surefire Film Productions Pictures in Paradise Pacific Film and Television Commission Film Consortium National Lottery through UK Film Council
Australia United Kingdom
English
Drama
american football biography sport championship
Paul Schiff Productions Anthem Productions
United States of America
English
Comedy

Paramount Pictures
United States of America
English
Action Science Fiction Thriller
resistance fascism totalitarian regime destroy phasing dystopia book burning outlaw government agent
Dimension Films Blue Tulip Productions
United States of America
English
Drama War
based on true story duringcreditsstinger
Australian Film Finance Corporation Zero Fiction Film Ming Productions Bluewater Pictures Cheerland Entertainment Organization
Australia China Germany
日本語 普通话 English
Drama Action Thriller Crime
corruption subway infiltration criminal
Miramax Films Industry Entertainment
United States of America
English Español
Family


United States of America
English
Drama Romance
france hotel 1970s grief travel unhappiness marriage problems woman director
Plan B Entertainment Jolie Pas Pellikola
France United States of America
Український English Français
Animation Fantasy Science Fiction
england inventor ball boy industrial revolution kugel steampunk energy 19th century steam
Bandai Visual Company Sunrise Studio 4°C
Japan
English 日本語 Polski
Drama
sport
Bristol Bay Productions Baldwin Entertainment Group Crusader Entertainment Independent Film Channel Peter Newman/Interal
United States of America
English
Drama Mystery Thriller Crime Romance
difficult childhood patriarch childhood trauma dysfunctional marriage
The Weinstein Company
United States of America
English
Adventure
in love with enemy indigenous island
Tig Productions Majestic Films International Warner Bros. Newcomm RCS
United States of America
English
Comedy Drama Family Fantasy Science Fiction
little boy ufo extraterrestrial
Columbia Pictures Film Production Asia
Hong Kong
广州话 / 廣州話
Comedy Fantasy
mephisto french revolution time travel leap in time knight wedding middle ages
Gaumont Canal+ France 3 Cinema Centre National de la Cinématographie (CNC)
France
Français
Action Comedy Horror Mystery Science Fiction Thriller
detective vampire supernatural zombie werewolf ghouls
Hyde Park Films platinum studios Long Distance Films
United States of America
English Türkçe
Drama Thriller
drug addiction press release from prison women's prison party exzess independent film drug intrigue

Germany United States of America
English
Drama Fantasy
shakespeare sword island frog sorcery banishment spirit storm staff woman director sorceress loincloth
Miramax Films Touchstone Pictures
United States of America
English
Horror Mystery Thriller
investigation memory loss
The Weinstein Company Himenóptero First Generation Films Mod Producciones FilmNation Entertainment Telefónica Studios
Canada Spain
English
Action History Drama
warrior woman number in title
Visualizer Film Productions Taewon Entertainment
China Hong Kong South Korea
普通话
Crime Drama Thriller
chicago infidelity man-woman relation revenge
Icon Productions Infinity Features Entertainment Irish Dreamtime Icon Entertainment International Canadian Film or Video Production Tax Credit (CPTC) Province of British Columbia Film Incentive BC Butterfly Productions Chum Television
Canada United Kingdom United States of America
English
Comedy Animation Adventure Family
falcon bird origin
Industrial Development Corporation of South Africa 120dB Films The Department of Trade and Industry of South Africa Cinema Management Group The National Film and Video Foundation of SA Wonderful Works Triggerfish Animation
South Africa
English
Drama History
mathematician biography prodigy ramanujam math genius
Camphor Cinema
India
தமிழ்
Animation


United States of America
English
Drama

Weinstein Company, The La Piedra Films Fuego Films Epicentral Studios
Panama United States of America
English Español
Thriller
new year's eve fire showdown terrorist embassy hand grenade truck laboratory on the run orphan death cigarette lighter microscope hazmat suit
Nu Image Films Winkler Films Millennium Films Survivor Productions
United Kingdom United States of America
English
Thriller Crime
gun escape serial killer man hunt hunting
Grindstone Entertainment Group Cheetah Vision K5 International Paradox Entertainment Emmett/Furla Films Picture Perfect Corporation Court Five Envision Entertainment Valentina Films
United States of America
English
Drama Romance
china cholera foreign aid epidemic loveless marriage
Emotion Pictures The Mark Gordon Company Class 5 Films Yari Film Group Warner China Film HG Corporation Stratus Film Co. WIP Bob Yari Productions The Colleton Company Dragon Studios
Canada China United States of America
Français 普通话 English
Action Crime Drama History Thriller
terror raf 1970s
Nouvelles Éditions de Films (NEF) Degeto Film Constantin Film Produktion Westdeutscher Rundfunk (WDR) Norddeutscher Rundfunk (NDR) Bayerischer Rundfunk (BR) Dune Films G.T. Film Production
Czech Republic France Germany
English Français Deutsch svenska
Adventure Drama Western
countryside based on novel suicide attempt culture clash loss of family deserter interpreter language barrier self-discovery dakota buffalo chief unsociability freedom native american 19th century lakota
Tig Productions Majestic Films International
United Kingdom United States of America
English
Comedy
classroom teacher school workplace humor
Columbia Pictures Mosaic Media Group
United States of America
English
Drama Crime Mystery
new york alcohol sex detective newspaper nudity suspect police murder suspense serial killer neo-noir
Universal Pictures Corporation
United States of America
English
Comedy
jealousy cinderella work step mother high school school party orphan teenager disguise american football player teenage romance step sister modern fairy tale
Gaylord Films Warner Bros. Dylan Sellers Productions Clifford Werber Productions
Canada United States of America
Český English Deutsch
Crime Horror Mystery
halloween gore serial killer slasher tabloid news reporter self-referential meta film
Woods Entertainment Dimension Films
United States of America
English
Horror Thriller
hunter nanny nudity collector house supernatural hell uncle revenge lawyer inheritance blood psychic violence devil trapped machine evil glass
Columbia Pictures Corporation Dark Castle Entertainment Warner Bros. 13 Ghosts Productions Canada Inc.
Canada United States of America
English
Horror Thriller
hotel isolation hotelier colorado maze bartender ax delusion loneliness caretaker vision snow writer alcoholic snowed in off season
Hawk Films Warner Bros. Peregrine
United States of America United Kingdom
English
Adventure Comedy Science Fiction Family
clock tower car race terrorist delorean lightning guitar plutonium sports car inventor journey in the past time travel race against time partner misfit mad scientist fish out of water teenage love destiny hidden identity odd couple escapade disorder chases and races love and romance teenage life misfit partners changing the past or future getting home inventions and discoveries
Universal Pictures Amblin Entertainment U-Drive Productions
United States of America
English
Horror Mystery Thriller
lunatic asylum aftercreditsstinger
Dark Castle Entertainment Warner Bros.
United States of America
English
Drama Comedy
aunt duringcreditsstinger
Lions Gate Films
United States of America
English
Action Drama
new jersey martial arts sister sport murder mixed martial arts justice underground fighting gym ultimate fighting championship
Cinestyle Media Group
United States of America
Português English
Comedy Romance Drama
alcohol single parent baby restaurant aquarium sperm little boy male female relationship pregnant artificial insemination
Mandate Pictures Bona Fide Productions Echo Films
United States of America
English
Comedy
venice france prison fire europe married couple honeymoon castle just married chewing gum marriage police vacation
Twentieth Century Fox Film Corporation Robert Simonds Productions Mediastream Dritte Film GmbH & Co. Beteiligungs KG
Germany United States of America
English Italiano Deutsch Français
Drama Action Thriller Crime War
palace impostor pervertion
Corrino Media Corporation Corsan Staccato Films
Netherlands Belgium
English
Animation Drama Family Science Fiction

Destination Films Isle of Man Film Britt Allcroft Productions
United Kingdom United States of America
English Deutsch
Mystery Horror Action
terror biological weapon cover-up splatter duringcreditsstinger virus
Penn Station Entertainment Participant Media Imagenation Abu Dhabi FZ Overture Films
United States of America
English
Fantasy Adventure Animation Family
witch parents kids relationship magic twilight darkness village and town bath house pig ghost world biology train amusement park yokai japanese mythology anime
Studio Ghibli
Japan
日本語
Action Crime
robbery street war gun battle rogue cop
Focus Films Sil-Metropole Organisation Edko Films
Hong Kong China
普通话 广州话 / 廣州話
Action Drama History
female nudity exotic island mutiny lake nudity sailing ship adventure tahiti murder pregnancy great barrier reef sailor native peoples storm at sea whipping british sailor based on true events fiji
Dino De Laurentiis Company
United States of America United Kingdom
English
Drama
world war ii book nazi germany jewish
Studio Babelsberg Fox 2000 Pictures Sunswept Entertainment
Germany United States of America
English Deutsch
Comedy Adventure Romance
sex jealousy virgin nudity community friendship high school road trip friends romance redneck loss of virginity hitchhiker teen movie boyfriend pickup knoxville
Summit Entertainment, LLC Alloy Entertainment Goldcrest Pictures
United States of America
English
Romance Comedy
taxi bar wales marriage proposal airplane pub cow wedding ring wedding proposal cardiologist ireland cliffs
Universal Pictures Spyglass Entertainment Octagon Films BenderSpink Birnbaum / Barber Productions
Ireland United States of America
English
Drama History
roman empire ancient rome
Paramount Pictures Samuel Bronston Productions
United States of America
English
Comedy Drama Romance
becoming an adult lie night sister job party friends deception best friend
Imagine Entertainment Rogue Pictures Relativity Media Internationale Filmproduktion Blackbird Dritte
United States of America Germany
English
Drama
based on true story
Gran Via Productions Walden Media Lemodeln Model & Talent Agency
United States of America
English
Family Fantasy Music
ballet
Warner Bros. Family Entertainment
United States of America
English
Thriller Drama Music Crime
politician kansas city election jazz music
Fine Line Features CiBy 2000 Sandcastle 5 Productions
United States of America
English
Drama
based on novel jewish life ohio 1950s
Likely Story
United States of America
English
Horror Thriller Drama
holy water long island remake family dinner paranormal violence wood chopping backwards tortured to death moving in based on supposedly true story
Platinum Dunes Dimension Films Metro-Goldwyn-Mayer (MGM) Radar Pictures
United States of America
English
Comedy Crime Drama
alligator marriage crisis writer's block orchid
Beverly Detroit Propaganda Films Clinica Estetico Intermedia Good Machine Magnet Productions
United States of America
English Latin
Horror
cage dystopia survivor zombie zombie apocalypse
Universal Pictures Atmosphere Entertainment MM Romero-Grunwald Productions Exception Wild Bunch
Canada France United States of America
English Français Italiano Polski Español
Action

Sun Entertainment Culture Universe Entertainment
Hong Kong China
广州话 / 廣州話
Adventure Drama Comedy
gonzo journalist sweaty face fake identity wedding chapel grapefruit cadillac convertible gibberish corvette stingray police convention
Universal Pictures Summit Entertainment Rhino Films Fear and Loathing LLC Shark Productions
United States of America
English
Comedy Romance Fantasy

Media Rights Capital Lin Pictures Warner Bros. Wintergreen Productions Lynda Obst Productions 1821 Pictures Radar Pictures
United States of America
English Português
Comedy
alcohol baby party family fraternity fraternity house neighbor neighbor relationship bathroom humor
Universal Pictures Point Grey Pictures Good Universe
United States of America
English
Romance Comedy Crime Fantasy
dual identity bank mockery green balloon jail cell norse mythology
New Line Cinema Dark Horse Entertainment
United States of America
svenska English
Fantasy Drama Comedy Romance Family
baseball co-worker bronx pinball machine toy maker duet job promotion homesick new toy quarter unplugged electronic works yankee stadium bronx new york city walking on piano keys wish fulfillment bunk bed woman director
Gracie Films Twentieth Century Fox Film Corporation American Entertainment Partners II L.P.
United States of America
English
Comedy
male nudity usa california prostitute journalist rodeo kazakhstan demeanor course chicken driving school anti semitism bear mockumentary reporter aftercreditsstinger duringcreditsstinger
Twentieth Century Fox Film Corporation Four By Two Productions
United States of America
English עִבְרִית қазақ
Comedy
harvard law school black female judge smart blonde girl power
Marc Platt Productions Metro-Goldwyn-Mayer (MGM)
United States of America
English
Science Fiction Action Adventure Thriller

Paramount Pictures
United States of America
English Pусский
Crime Drama Horror Thriller
epilepsy possession teenage girl spirit umbrella cross prosecutor catholicism negligent homicide archdiocese agnostic malnutrition burning psychotic epileptic disorder
Lakeshore Entertainment Firm Films Screen Gems
United States of America
English
Comedy
fish aquarium carnival house callboy vacation illegal prostitution
Happy Madison Productions Quinta Communications Touchstone Pictures
United States of America
English
Thriller Action Science Fiction
airplane the rapture remake pilot hero
Stoney Lake Entertainment
United States of America
English
Comedy Drama Romance
holiday christmas
Fox 2000 Pictures
United States of America
English
Comedy Drama
blaxploitation
Metro-Goldwyn-Mayer (MGM)
United States of America
English
Drama Comedy Crime
holiday elves christmas party department store safe drink little people christmas eve christmas
Columbia Pictures Triptych Pictures Dimension Films (US version)
Germany United States of America
English
Science Fiction Comedy Crime
android undercover missile group therapy airplane dancing scene time travel penthouse apartment judo trapdoor clowning telescope swinging james bond spoof swinging 60s aftercreditsstinger duringcreditsstinger
New Line Cinema Capella International Eric's Boy
Germany United States of America
English
Romance Comedy Family
comedy wedding
Universal Pictures Playtone HBO Films Gold Circle Films
Canada United States of America
English
Family Comedy
based on novel middle school
Fox 2000 Pictures Color Force
United States of America
English
Science Fiction Action Adventure Thriller
central and south america predator alien stalking invisible commando 3d
Twentieth Century Fox Film Corporation Lawrence Gordon Productions Davis Entertainment Silver Pictures Amercent Films American Entertainment Partners L.P.
United States of America
English Español
Drama History Music
italy composer opera talent musician marriage crisis god murder vienna austria envy 18th century
Warner Bros.
United States of America
English Deutsch Italiano Latin
Crime Horror
aunt remake blood on shirt slasher death of family masturbation kicked in the face renovation black stereotype chest
Alliance Films
United States of America
Italiano English
Comedy
female friendship high school fish out of water best friend teenager popularity gossip teen comedy high school rivalry new girl at school
Paramount Pictures Broadway Video M.G. Films
United States of America
Kiswahili English Deutsch Tiếng Việt
Comedy Drama Romance
depression toscana recreation author divorce woman director
Timnick Films Blue Gardenia Productions Touchstone Pictures Tatiale Films
Italy United States of America
Český English Français Deutsch Italiano Polski Español
Drama Mystery Thriller
servant money shooting party
USA Films
Germany United Kingdom United States of America
English
Comedy Drama Fantasy Romance
time travel high school reunion
American Zoetrope TriStar Pictures
United States of America
English
Drama Comedy
times square superhero long take new york city play broadway actor
Worldview Entertainment New Regency Pictures TSG Entertainment Le Grisbi Productions M Productions
United States of America
English
Comedy Drama
san francisco sister sister relationship new york city rich narcissism xanax
Perdido Productions
United States of America
English
Drama History Crime Thriller Action
airplane hijacking terror cell emergency landing war on terror
Universal Pictures StudioCanal Sidney Kimmel Entertainment Working Title Films
France United Kingdom United States of America
English العربية Deutsch
Romance Music Family
new york dancing hip-hop dream dance blackmail harassment career video teacher business sabotage choreographer club harlem youth center
Universal Pictures Marc Platt Productions NuAmerica Entertainment
United States of America
English
Action Comedy
atomic bomb spoof james bond spoof
Hollywood Pictures
United States of America
English
Horror
prophecy sea beach gold small town beheading sword narration fog leprosy ship lighthouse church
AVCO Embassy Pictures EDI Debra Hill Productions
United States of America
English
Action Drama
competition based on novel shark attack surfing biography sport duringcreditsstinger
Mandalay Pictures TriStar Pictures Brookwell-McNamara Entertainment FilmDistrict Affirm Films
United States of America
English
War Comedy Drama
world war ii island bomber pianosa american
Paramount Pictures Filmways Productions
United States of America
English Italiano
Comedy Crime Drama
robbery unrequited love security guard mall
Legendary Pictures De Line Pictures
United States of America
English
Adventure Fantasy Action
swordplay sword magic warrior woman lone wolf wizardry royalty barbarian sword and sorcery
De Laurentiis Entertainment Group
United States of America
English
Drama
transporter jealousy violent husband paranoia boxer biography fistfight broken nose sport domestic violence extreme violence over-the-hill fighter
United Artists
United States of America
English
Drama Romance
hotel florist forest grief seminar motivational speaker

Drama Crime
father son relationship bounty hunter boat way of life coffin denver godmother paranoia hitman friendship psychopath revenge murder independent film mafia diner blood gangster violence illegal prostitution extramarital affair
Miramax Films
United States of America
English
Action Drama History
assassin tang dynasty ancient china wuxia slow cinema
Media Asia Films Sil-Metropole Organisation Central Motion Pictures Zhejiang Huace Film & TV China Dream Film Culture Industry SpotFilms
China France Hong Kong Taiwan
普通话
Drama Comedy War Crime Thriller
germany corruption sex based on novel investigation army police base drug rogue
Grosvenor Park Films LLP Film4 Good Machine
Germany United Kingdom United States of America
English
Thriller Drama Mystery
return brother heavy rain speedo journal
Ren Film
Russia
Pусский
Adventure Action Thriller
sequel
Iyara Films
Thailand
Český 普通话 Pусский ภาษาไทย
Adventure Action Drama
roman empire ancient rome ancient world violence britain behind enemy lines sole survivor
Pathé Pictures International UK Film Council Celador Films Canal+ Warner Bros. CinéCinéma
France United Kingdom
English
Drama Action Thriller

Newmarket Capital Group Cine Grande Corporation Filmline International Conquistador Entertainment Algonquin Productions Limited
Canada United Kingdom
English
Mystery Drama Crime Thriller Horror
photographer butcher vegetarian midnight blood splatter gore stalking diner decapitation blood violence subway train very little dialogue
Lions Gate Films Lakeshore Entertainment GreeneStreet Films Midnight Picture Show
United States of America
English Français
Drama
biography nelson mandela


English
Drama Thriller Crime

Millennium Films
United States of America
English
Action Comedy Drama History
transvestism world war ii

Austria Hungary
English Deutsch
Comedy Drama Romance Fantasy Music
dream midlife crisis lucid dreaming
Destination Films Tempesta Films Good Night Productions
Germany United Kingdom United States of America
English Italiano
Drama Fantasy
sex legend countess
Lunar Films Fonds Eurimages du Conseil de l'Europe Eurofilm Stúdió Státní Fond CR pro Podporu a Rozvoj Ceské Kinematografie Jakubisko Film Slovakia J&J Jakubisko Film Concorde Film Trust Ministry of Culture of the Slovak Republic
Czech Republic Hungary Slovakia United Kingdom
English
Animation Adventure Family
3d khumba
Triggerfish Animation
South Africa
English
Thriller Science Fiction
artificial intelligence rain future dystopia robot ecology desert child hitman
Green Moon Productions Nu Boyana Viburno
Spain
English
Action Adventure Fantasy
fighter royalty curse dragon
Skyline Films Sweetpea Entertainment Studio Hamburg WorldWide Pictures Zinc Entertainment Inc.
Germany United Kingdom United States of America
English
Drama
pope biography
Taodue Film
Italy
Español
Drama Action Thriller Crime
drug stealing yakluza shinjuku criminal syndicate taiwanese
JCE Movies
Hong Kong
日本語 普通话 广州话 / 廣州話 English
Drama Foreign

Arts Council of England
United Kingdom
English
Romance Fantasy Drama Comedy
deja vu groundhog weather forecast telecaster pennsylvania alarm clock winter time warp time loop cult film existentialism groundhog day
Columbia Pictures
United States of America
English Français Italiano
Comedy Drama Music
male friendship strip club road trip strip tease strip
Warner Bros. Iron Horse Entertainment (II)
United States of America
English
Drama Romance
shakespeare forbidden love gun violence star crossed lovers shakespeare in modern dress teenage romance masquerade shakespeare's romeo and juliet gangster grip
Bazmark Films Twentieth Century Fox Film Corporation
United States of America
English
Drama War

France 2 Cinéma Studio 37 Canal+ TPS Star France Télévision TF1 Droits Audiovisuels Région Ile-de-France Hugo Productions A Plus Image
France
English Français Deutsch Italiano
Drama
ship freedom slave
Production One
United States of America
English
Western
prostitute sheriff bounty regret right and justice revenge mutilation one last job reputation englishman
Malpaso Productions Warner Bros.
United States of America
English
Drama
southern usa slavery duringcreditsstinger
Zentropa Entertainments Danmarks Radio (DR) Arte Memfis Film Isabella Films BV Degeto Film Ognon Pictures Sveriges Television (SVT) Canal+ Yleisradio (YLE) Arte France Cinéma Westdeutscher Rundfunk (WDR) Alan Young Pictures Nederlandse Programma Stichting (NPS) Canal+ Television AB Film i Väst Invicta Capital Edith Film Oy Pain Unlimited GmbH Filmproduktion Sigma Films Manderlay
Denmark France Germany Italy Netherlands Sweden United Kingdom
English
Drama Romance
slum indian lead cheating suspicion game show orphan duringcreditsstinger
Fox Searchlight Pictures Celador Films Warner Bros. Film4
India United Kingdom United States of America
Français हिन्दी English
Drama Romance Thriller
sexual obsession wife husband relationship deceived wife marriage crisis suspense lawyer extramarital affair erotic movie
Paramount Pictures
United States of America
English
Romance Comedy
prostitute capitalism cinderella expensive restaurant sports car workaholic fire escape friendship los angeles piano
Touchstone Pictures Silver Screen Partners IV
United States of America
English Italiano 日本語
Adventure Comedy
new york crocodile australia large knife aftercreditsstinger
Paramount Pictures
Australia United States of America
English
Thriller Mystery Drama Crime

Reliance Entertainment
United States of America
English
Drama War
vietnam veteran post traumatic stress  disorder bar 1970s wheelchair vietnam war desert spit in the face drunkenness 1950s 1960s
Universal Pictures Ixtlan
United States of America
English Español
Comedy
winter trainer olympic games jamaica training camp reggae bobsleighing sport
Walt Disney
United States of America
English Français Deutsch Pусский
Mystery Horror
sheriff miner delusion head injury remake slaughter blood aftercreditsstinger 3d
Lionsgate
United States of America
English
Drama Music
love at first sight loss of brother breakdance daughter
Rainforest Films
United States of America
English
Adventure Action Thriller
london england submarine england assassination spy cairo terrorist egypt mass murder pyramid russia planned murder secret intelligence service kgb villain nuclear missile tanker sphinx sardinien warhead jet ski utopia murder shark killer british secret service skiing
United Artists Eon Productions Danjaq
United Kingdom United States of America
English Italiano العربية
Horror Thriller
college murder urban legend slasher killer death
Original Film TriStar Pictures Phoenix Pictures Canal+ Droits Audiovisuels
Canada France United States of America
English Italiano
Comedy Drama Romance
african american single mother fiancé fiancée relationship corporation rich man - poor woman

United States of America
English
Action Adventure Drama Family
based on novel gold treasure coffin human animal relationship friendship alaska shootout dog prospector klondike yukon boy dog relationship gold miner
Walt Disney Pictures Silver Screen Partners IV Hybrid Productions Inc.
United States of America
English
Comedy Family

SNL Studios
Canada
English
History Drama
capitalism prime minister argentina margaret thatcher british overseas territory war propaganda british politics british prime minister female politician falklands war political leader female prime minister right wing falklands woman director 1980s
UK Film Council Canal+ DJ Films CinéCinéma Pathé Film4 Goldcrest Pictures Yuk Films
France United Kingdom
English
Action Adventure Animation Comedy Family Fantasy Romance

Big Idea Productions
United States of America
Český English
Drama Romance
loss of lover sadness los angeles road movie
Columbia Pictures
United States of America
English Français
Action Adventure Comedy
record store sexuality autograph underwear painting safe sexual attraction motorcycle juvenile delinquent stoner music store hand on crotch premarital sex raised middle finger employer employee relationship cupcake twenty something money bag sidewalk storem
New Line Cinema
United States of America
English Français
Comedy Horror Romance
vampire half vampire
Paramount Pictures
United States of America
English
Horror Thriller Fantasy
exorcism examination pact with the devil possession priest devil demonic possession locust
Warner Bros.
United States of America
English Français Español
Horror Thriller
witch independent film curse suitor family
Media Pro Pictures Allan Zeman Productions After Dark Films Remstar Productions Sweetpea Entertainment Redbus Pictures Midsummer Films
United Kingdom United States of America
English
Comedy Romance

Dimension Films
United States of America
English
Thriller Mystery Adventure
hawaii honeymoon double murder murder
Davis Entertainment Relativity Media Rogue QED International Tooley Productions
United States of America
English
Comedy
interracial marriage wedding duringcreditsstinger
Fox Searchlight Pictures Dune Entertainment Sneak Preview Entertainment Pointe Studios
United States of America
English
Comedy
college drug fraternity house pot teen suicide autopsy room
Paramount Pictures MTV Films
United States of America
English
Comedy Drama War
italy hotel loss of mother ambassador world war ii loss of parents widow benito mussolini independent film
Medusa Produzione Cattleya Cineritmo Film and General Productions
United Kingdom Italy
English Italiano Pусский
Horror Thriller
blow job curse fat suit steven king
Paramount Pictures Spelling Films
United States of America
English
Drama Music Romance
new york jazz saxophonist falling in love
United Artists Chartoff-Winkler Productions
United States of America
English
Comedy Drama
black people 1970s jazz musician straßenkids dysfunctional family independent film teacher urban parenthood
Universal Pictures 40 Acres & A Mule Filmworks
United States of America
English
Comedy Romance

Fox Searchlight Pictures
India United States of America
English
Horror Science Fiction
places and planets space marine future cryogenics space slaughter series of murders scientist freeze
New Line Cinema Sean S. Cunningham Films Crystal Lake Entertainment
United States of America
English
History Drama
hotel senator kitchen marriage crisis politics xenophobia
The Weinstein Company Bold Films Holly Wiersma Productions
United States of America
English Deutsch Español
Comedy Romance
supermodel stalking models
Universal Studios
United States of America
English
Comedy
halloween friends little brother trick or treating boyfriend girlfriend relationship
Paramount Pictures Nickelodeon Movies Anonymous Content Fake Empire
United States of America
English
Drama
writing lover (female) psychological stress dying and death editor-in-chief french independent film patient disabled
France 3 Cinéma The Kennedy/Marshall Company Pathé Renn Productions Banques Populaire Image 7 Canal+ CinéCinéma C.R.R.A.V. Nord Pas de Calais Région Nord-Pas-de-Calais
France United States of America
Français
Romance Drama
skateboarding mother american football adultery wife husband relationship small town eroticism vororte pedophilia loser infant housewife bourgeoisie deceived wife playground stay-at-home dad castration psychopath ex-cop children mother daughter relationship psychopathy masturbation extramarital affair
New Line Cinema Standard Film Company Bona Fide Productions
United States of America
English
Drama Mystery Thriller
college suspense gossip rumor social experiment
Village Roadshow Pictures NPV Entertainment Warner Bros. Outlaw Productions (I)
United States of America
English Italiano
Drama Romance
adultery woodstock 1960s
Miramax Films Village Roadshow Pictures Groucho II Film Partnership Punch 21 Productions
Australia United States of America
English
Action Drama Thriller
police brutality resistance south africa apartheid african national congress right and justice
Mirage Enterprises Studio Canal Working Title Films
France United Kingdom United States of America South Africa
Afrikaans English isiZulu
Horror Mystery Thriller
hallucination car crash death sole survivor

United States of America
English
Drama Romance
france revolution biography president history
Merchant Ivory Productions Touchstone Pictures
United States of America
English
Comedy Romance

BBC Films Endgame Entertainment Ealing Studios Fragile Films Odyssey Entertainment Prescience Joe Abrams Productions
Canada United Kingdom
English
Action Adventure Drama Romance

Universal Pictures Ibex Films FIDCI
United States of America

History Drama
painter
Film4 Lipsync Productions Thin Man Films Focus Features International (FFI) France 3 Cinema Xofa Productions Untitled 13
United Kingdom
English
Drama Romance
whiskey experimental film wallet cult director
France 2 Cinéma BIM Distribuzione Centre National de la Cinématographie Eurimages Canal+ Studio Canal TPS Star Région Ile-de-France F Comme Film Cinémage 3
France Italy
Français
Drama History
vatican pope concentration camp holocaust schutzstaffel nazis nazi germany doctor conscience catholicism euthanasia
Renn Productions TF1 Films Production Canal+ K.G Productions KC Medien Katharina
France Germany Romania
English Français Deutsch Italiano
History Action
martial arts sword fight wuxia
Lion Rock Productions Media Asia Films Beijing Gallop Horse Film & TV Production Lumiere Motion Picture Company Beijing Heguchuan TV & Film Stellar Entertainment
China Taiwan Hong Kong
普通话 English
Comedy Drama History
friendship war road trip independent film soldier

United States of America
English
Drama
new york bus nightmare witness investigation police truth teacher blood student relationship family
Fox Searchlight Pictures Scott Rudin Productions Mirage Enterprises Gilbert Films
United States of America
English
Comedy Horror
halloween slapstick duringcreditsstinger
Insight Productions
Canada United States of America
English
Romance Drama
shyness based on novel unrequited love neighbor family relationships first crush young love opposites attract adolescent boy based on young adult novel
Reiner / Greisman Productions
United States of America
English
Drama Romance
gay countryside homophobia loss of lover wyoming rodeo father murder horseback riding intolerance daughter marriage crisis secret love cowboy star crossed lovers
River Road Entertainment Alberta Film Entertainment Focus Features Good Machine
Canada United States of America
English
Comedy Drama Romance
puberty high school make a match spoiled child gay interest conflict woman director
Paramount Pictures
United States of America
Español English
Drama Romance
black people wife husband relationship botanist homosexuality
Clear Blue Sky Productions
United States of America
English
Comedy
time travel sequel hot tub duringcreditsstinger
Paramount Pictures United Artists Metro-Goldwyn-Mayer (MGM)
United States of America
English
Drama
asylum french revolution french smuggling maid
Fox Searchlight Pictures Industry Entertainment Walrus & Associates Hollywood Partners Charenton Productions
Germany United Kingdom United States of America
English
Comedy Crime
suicide alcohol sex screenwriter underworld fight kidnapping party murder scam los angeles gangster explosion criminal shih tzu struggling
Blueprint Pictures CBS Films British Film Institute (BFI) Film4
United Kingdom
English Tiếng Việt
Drama Mystery Thriller
woman director
Franchise Pictures Focus Features Jersey Shore
United States of America
English
Drama History War
berlin poison dictator clerk ideology world war ii traitor despair destroy testament capitulation soviet troops race politics national socialism adolf hitler ultimate victory minister national socialist party dying and death historical figure german shepherd
Degeto Film EOS Entertainment Rai Cinema Österreichischer Rundfunk (ORF) Constantin Film Produktion Westdeutscher Rundfunk (WDR) Norddeutscher Rundfunk (NDR)
Austria Germany Italy
Magyar Deutsch Pусский
Drama
brother brother relationship paraplegic intensive care ladykiller wheelchair dying and death biography galicia bathing accident freedom romance lawyer sailor euthanasia dignity
Canal Plus Sogecine Himenóptero Eurimages Televisión Española (TVE) Union Générale Cinématographique (UGC) Televisión de Galicia (TVG) S.A. Ministerio de Cultura Sogepaq Eyescreen S.r.l. Filmanova
Spain France Italy
Galego Español
Thriller Science Fiction Drama
male nudity scotland edinburgh alien very little dialogue
Scottish Screen UK Film Council FilmNation Entertainment Nick Wechsler Productions Creative Scotland British Film Institute Film4 Silver Reel JW Films A24
United Kingdom Switzerland United States of America
English
Comedy Drama War
rock and roll radio station war crimes entertainer explosive cynic radio vietnam war vietcong gi u.s. air force dying and death radio presenter humor saigon provocation right and justice
Silver Screen Partners III Touchstone Pictures
United States of America
English
Action Comedy Thriller



한국어/조선말
Documentary Music Family
manager canada pop singer star prayer music competition tour bus aftercreditsstinger duringcreditsstinger justin bieber
Insurge Pictures Magical Elves Productions Scooter Braun Films
United States of America
English
Drama Thriller
dancing competition sex dancer obsession paranoia insanity suspense ballet new york city heartbreak mental illness madness swan lake ballerina body horror
Fox Searchlight Pictures Dune Entertainment Protozoa Pictures Cross Creek Pictures
United States of America
English Français Italiano
Drama Crime
italo-american cuba vororte melancholy praise revenge mafia lawyer blood corrupt politician bloody body of child man punches woman
Paramount Pictures The Coppola Company
United States of America
English Italiano Latin Español
Drama Family Romance Music
ballet dancer musical ballet
MTV Films Cort/Madden Productions
United States of America
English
Horror Thriller
martial arts nightmare supernatural high school resurrection sequel diner alcoholic disfigurement dreams
New Line Cinema
United States of America
English
Drama
miracle christian cure woman director accident
TriStar Pictures Sony Pictures Entertainment
United States of America
English
Comedy
dude amnesia idiot auto friendship cannabis hangover spoof teenager drug alcohol abuse celebration car duringcreditsstinger child
Twentieth Century Fox Film Corporation Alcon Entertainment
United States of America
English Français 日本語
Crime Action Adventure Drama Western
corruption sheriff deputy sheriff ranch billy the kid outlaw neighbor
Twentieth Century Fox Film Corporation Morgan Creek Productions
United States of America
English
Comedy
babysitter friendship neighbor divorce child of divorce
The Weinstein Company Crescendo Productions Chernin Entertainment Goldenlight Films
United States of America
English
Comedy Romance
duringcreditsstinger
Screen Gems, Inc. Rainforest Films Olive Bridge Entertainment
United States of America
English
Comedy Romance Drama
shakespeare sister high school cannabis deception teen movie shrew archery feel-good ending opposites attract duringcreditsstinger teenage romance play adaptation overprotective father
Mad Chance Jaret Entertainment Touchstone Pictures
United States of America
English Français
Comedy Family
prison dual identity identity loser high school los angeles duringcreditsstinger
Revolution Studios Frontier Pictures Bedlam Pictures
United States of America
English Italiano Português
Comedy
cocaine police spoof los angeles
New Line Cinema
United States of America
English
Horror Drama Thriller
mexico beach surfer island survival young woman shark great white shark trapped animal attack animal horror prey
Columbia Pictures Ombra Films Weimaraner Republic Pictures
United States of America
English
Science Fiction Thriller
amnesia chaos theory blackout time travel flashback
New Line Cinema FilmEngine Katalyst Films BenderSpink Province of British Columbia Production Services Tax Credit
Canada United States of America
English
Comedy Family

Paramount Pictures Nickelodeon Movies

English Français Deutsch ελληνικά
Drama Family Music
pickpocket musical victorian england orphan
Columbia Pictures Corporation Warwick Film Productions Romulus Films
United Kingdom
English
Drama Comedy
hotel based on novel india ensemble cast elderly jaipur india personal growth outsourcing
Participant Media Imagenation Abu Dhabi FZ
United Arab Emirates United Kingdom United States of America
हिन्दी English
Science Fiction Animation Comedy Family
holiday elementary school friends based on tv series summer classmates recess
Walt Disney Television Animation Disney Toon Studio
United States of America
English
Action Adventure Science Fiction
arena sandstorm dystopia oasis sequel post nuclear ozploitation
Kennedy Miller Productions
Australia
English
Action Adventure Thriller
kidnapping lone wolf daughter father rescue mission
Twentieth Century Fox Film Corporation SLM Production Group Silver Pictures
United States of America
English
Horror Mystery Thriller
suicide england fire country house shower nanny mask boy murder mansion violence doll burn victim secret passageway broken mirror loss of a child
Lakeshore Entertainment Vertigo Entertainment Diamond Films Showtime Networks STX Entertainment
United States of America China Canada
English
Horror Mystery Thriller
claustrophobia trapped in an elevator
Universal Pictures Media Rights Capital Night Chronicles Relativity Media
United States of America
Español English Український
Comedy
guard shopping mall thief drug
New Line Cinema
United States of America
English Français Português
Drama Horror Thriller
sequel
Sony Pictures
Canada United States of America
English ภาษาไทย
Action Adventure Comedy
martial arts pizzeria limousine music
TriStar Pictures Motown Productions Delphi III Productions
United States of America
English
Horror Thriller Science Fiction
dream chimp manipulation botanist virtual reality lemonade intelligent
New Line Cinema Allied Vision
United Kingdom Japan United States of America
English
Comedy Music Romance
concert teenager one night based on young adult novel secret location
Columbia Pictures Mandate Pictures Depth of Field Screen Gems
United States of America
English
Fantasy Comedy Adventure
angel wisconsin church service church aftercreditsstinger duringcreditsstinger
Lions Gate View Askew Productions
United States of America
English
Comedy Drama
tattoo rock star groupie past family
Fox Searchlight Pictures
United States of America
English
Drama Fantasy Horror Science Fiction Thriller
nazis anthology remake twilight zone
Warner Bros.
United States of America
English Français Deutsch Tiếng Việt
Action Thriller
new love protection money nightclub rausschmeißer revenge hoodlum brawl
United Artists Star Partners II Ltd. Silver Pictures
United States of America
English Português
Action Comedy Crime
fbi drug crime violence drug private detective blast
Caravan Pictures Hollywood Pictures
United States of America
English
Drama Thriller
competition coma infidelity obsession bathing high school femme fatale athlete hospital swimmer swimming troubled teen
Twentieth Century Fox Film Corporation Greenestreet Films Cobalt Media Group Furthur Films Forrest Films
United States of America
English
Comedy Romance
salesclerk midlife crisis prenzlauer berg vulgar slacker business consultant
Lionsgate
United States of America
English Magyar
Comedy Drama Romance
alcohol regret homophobia radio cheerleader love letter college graduation groupie costume nerd high school party friends dating break-up rock band pop music american football player infatuation washed up star unlikely friendship social outcast woman director jocks having fun revenge plot
Columbia Pictures
United States of America
English
Crime Drama
street gang children's home coming of age gang juvenile delinquent based on young adult novel
American Zoetrope Warner Bros.
United States of America
English
Adventure Family Fantasy
feral child remake dragon orphan 1980s live action and animation
Walt Disney Pictures Walt Disney Studios Motion Pictures
United States of America
English
Horror Science Fiction Thriller
coma sheriff based on novel sacrifice suspense psychopathic killer premonition independent film vision doctor car accident series of murders psychic dark hero gothic madness flashback
Paramount Pictures Lorimar Film Entertainment Dino De Laurentiis Company
United States of America
English Pусский
Horror
haunted house sequel twins
Alliance Films Blumhouse Productions IM Global Automatik Entertainment Entertainment One Tank Caterpillar Steady Aim
United States of America
English
Drama Music
soong sisters duringcreditsstinger
TriStar Pictures Phoenix Pictures Stage 6 Films Akil Production Company
United States of America
English Français
Horror Thriller
mobbing success violence against women revenge serial killer valentine's day
Village Roadshow Pictures NPV Entertainment Warner Bros.
United States of America
English
Mystery Science Fiction Thriller
brother sister relationship wheelchair hypnosis investigation cover-up ufo alaska disappearance hospital alien abduction patient psychotherapy fake documentary based on supposedly true story nome alaska faked footage audio cassette ancient astronaut anchorage alaska police fake duringcreditsstinger
Universal Pictures Saga Film Focus Films Gold Circle Films Chambara Pictures Dead Crow Productions Fourth Kind Productions
United States of America
English
Drama Comedy Music
usa country music commercial radio presenter radio transmission bühnenauftritt backstage singer
River Road Entertainment GreeneStreet Films Picturehouse Entertainment Sandcastle 5 Productions Prairie Home Productions
United States of America
English Norsk
Drama Action Thriller

Beacon Communications Beacon Pictures South Street Films Ghiznoz Productions
United States of America
English
Action Thriller

Cannon Films
United States of America
English
Comedy Drama Family

Fox Searchlight Pictures
United States of America
English Español
Comedy Drama
private school lone wolf theatre play theatre group theatre director independent film
Touchstone Pictures
United States of America
Français English Latin Español
Science Fiction
missile light transformation low-budget alien fireplace los angeles cell phone rooftop duringcreditsstinger
Rogue Pictures Relativity Media Hydraulx Rat Entertainment Transmission Pictures
United States of America
English
Drama Comedy
india retirement home
Fox Searchlight Pictures Participant Media Blueprint Pictures
United Kingdom United States of America
English
Comedy Drama Family
cincinnati woman director
New Line Cinema Goldsmith-Thomas Productions Red Om Films HBO Films Picturehouse Front Street Films American Girl Brands
United States of America
English
Comedy Drama Family Romance
mother man-woman relation single matchmaking single mother catfishing
Universal Pictures
United States of America
English Deutsch
Drama Romance
musical
Universal Pictures 40 Acres & A Mule Filmworks
United States of America
English
Action Comedy
loss of family loss of parents supernatural powers invulnerability spoof evil murder hunt
Twentieth Century Fox Film Corporation O Entertainment
Hong Kong United States of America
English
Action Horror
nevada small town tractor stranded cult favorite tentacle rural graboids seismologist binoculars man eaten by monster giant worm
Universal Pictures No Frills Film Production
United States of America
English
Horror Thriller
life and death death of a friend parts of dead body
Summit Entertainment Newmarket Capital Group Regency Enterprises Constantin Film Produktion Stan Winston Studio Media Cooperation One DCP Wrong Turn Productions
Germany United States of America
English
Western History
brother brother relationship jesse james cole younger
United Artists
United States of America
English svenska
Action Crime Mystery Thriller
new york life and death gang war police china town triad
New Line Cinema Illusion Entertainment Group
United States of America
广州话 / 廣州話 English 普通话
Drama
river snake arkansas fugitive river boat
FilmNation Entertainment Everest Entertainment
United States of America
English
Action Adventure Comedy Crime
sex terrorist beach nudity police parody attack shootout mockumentary explosion drug
Paramount Pictures Double Feature Films Jersey Films Twentieth Century Fox Film Corporation Comedy Central Films Principato-Young Entertainment High Sierra Carpeting
United States of America
English Español
Documentary Music
concert
Columbia Pictures Sony Pictures
United States of America
Português English
Comedy
duringcreditsstinger
Paramount Vantage Kevin Messick Productions Gary Sanchez Productions
United States of America
English
Animation Family

Paramount Pictures Nickelodeon Movies Nickelodeon Animation Studios Paramount Animation Snee-Oosh Productions
United States of America
English
Drama
based on novel biography historical figure marilyn monroe
BBC Films The Weinstein Company UK Film Council Lip Sync Post Trademark Films
United Kingdom
English
Action Comedy Crime Drama Thriller
mexico city midlife crisis cocktail independent film stranger hit man
Miramax Films
Germany United States of America
English Polski
Comedy Drama Romance
sex ex-boyfriend independent film african american
New Line Cinema Addis Wechsler Pictures
United States of America
English
Thriller Mystery
detective stalker gift bully psychological thriller
Blumhouse Productions Blue-Tongue Films Huayi Brothers Media STX Entertainment Ahimsa Films
United States of America
English
Adventure Drama
drama
Bearing Fruit Entertainment every tribe entertainment
United States of America
English Español
Comedy Romance
theatre play theatre group high school falling in love
Miramax
United States of America
English
Comedy Crime
suburbia downsizing software engineer burnout dallas texas beach resort coworker relationship laziness duringcreditsstinger business rivalry
Twentieth Century Fox Film Corporation Cubicle Inc.
United States of America
English
Comedy
minnesota mother role beauty contest girl from the province hicktown evil mother mother daughter relationship envy pretty woman mocumentary
New Line Cinema Capella International KC Medien AG
United States of America
English
Drama
wife husband relationship artist court case
The Weinstein Company Silverwood Films Electric City Entertainment Tim Burton Productions
Canada United States of America
Italiano English Français
Comedy Crime Thriller
prostitute hotel cocaine nudity psychopath stag night friends murder independent film marijuana blood wedding las vegas violence death accident
Initial Entertainment Group (IEG) Interscope Communications VBT Productions Ballpark Productions Partnership
United States of America
English
Comedy Family
high school scavenger hunt teenage crush slumber party teenager teen comedy

United States of America
Português English
Crime Mystery Horror Thriller
female nudity pornography claustrophobia nudity witness police movie in movie murder neighbor los angeles peeping tom porn actress struggling actor voyeurism actor
Columbia Pictures Corporation Delphi II Productions
United States of America
English
Action Adventure Comedy
aftercreditsstinger duringcreditsstinger
Relativity Media
United States of America
English Pусский
Crime Drama Thriller
london england prostitute hotel night watchman illegal immigration immigration law transplanted organ turk delinquency
Miramax Films BBC Films Celador Productions Jonescompany Productions
United Kingdom
Français Somali Español English
Comedy
slapstick ensemble cast duringcreditsstinger woman director laxative
Greenestreet Films Relativity Media Virgin Produced Wessler Entertainment Witness Protection Films
United States of America
English
Comedy
diary romantic comedy death of lover spirit death by accident psychic moving on
The Safran Company Gold Circle Films Dead Fiancée Productions
United States of America
English
Comedy Drama Romance Science Fiction
asteroid road trip end of the world woman director
Mandate Pictures Indian Paintbrush Anonymous Content Focus Features
United States of America
English
Comedy
hotel infidelity one-night stand friendship swimming pool drinking naive duringcreditsstinger
Ad Hominem Enterprises
United States of America
English
Drama
usa neo-nazi prison skinhead brother brother relationship rape fascism brother basketball jail school swastika los angeles family hate neo nazism xenophobia interracial friendship nazism prison rape
New Line Cinema The Turman-Morrissey Company Savoy Pictures
United States of America
English
Horror Thriller
mercenary party sequel gore escape serial killer masked killer trap
Fortress Features LD Entertainment
United States of America
English
Animation Drama Family Music

Walt Disney Pictures Walt Disney Television Animation
United States of America
English
Drama Thriller Mystery Music Romance
auction violin
Rhombus Media Channel Four Films
Canada Italy United Kingdom
English Français Deutsch Italiano 普通话 Español
Drama
brother brother relationship mississippi wisconsin lawnmower iowa biography based on true story independent film family relationships family road movie
Walt Disney Pictures Channel Four Films Asymmetrical Productions Les Films Alain Sarde The Picture Factory StudioCanal Canal+ CiBy 2000 The Straight Story, Inc
United States of America
English
Action Crime Drama Romance
gang new york city drug overdose
United Artists
Germany United States of America
English
Comedy
competition satire spelling bee estranged father unlikely friendship anger issues
Darko Entertainment Aggregate Film
United States of America
English
Comedy Romance
father son relationship new love fiancé training rent jogging marathon wedding pregnancy
Entertainment Films Material Entertainment Beech Hill Films
United Kingdom
English
Comedy Romance Family
servant future chase lovers outlaw robot
Universal Pictures
United States of America
English
Drama
grieving widower widower
Treehouse Pictures
United States of America
English
Comedy Family Romance

Miramax Films Tapestry Films A Happy Place
United States of America
English Français Magyar
Adventure Drama War
war crimes violence laotian soldier pipe smoking rice paddy letter from home ant's nest net fishing dragging someone
Metro-Goldwyn-Mayer (MGM)
United States of America
English
Comedy Drama Music
rock star middle age
Big Indie Pictures ShivHans Pictures
United States of America
English Italiano
Drama Comedy
slacker basement destiny glue stoner wrong number mumblecore
Indian Paintbrush
United States of America
English
Drama Romance
adultery restaurant textile industry male friendship bourgeoisie food chef high society
Rai Cinema
Italy
English Italiano Pусский
Drama Science Fiction Mystery
ayn rand
Cinema Vehicle Services Atlas 2 Productions
United States of America
English
Action Crime Drama Thriller
police operation sex addiction police mafia boss suspense bad cop hitwoman
Working Title Films Polygram Filmed Entertainment Hilary Henkin
United Kingdom United States of America
English
Action Crime Drama Mystery Thriller
prison release from prison suitcase record producer investigation daughter loss revenge stakeout ex-con warehouse hired killer narcotics motel room neo-noir 1960s
Artisan Entertainment
United States of America
English Français
Drama
race politics daughter installer police fall car crash racism los angeles bigotry social services collision
Blackfriars Bridge Films Yari Film Group Bob Yari Productions ApolloProScreen Filmproduktion Bull's Eye Entertainment DEJ Productions Harris Company
Germany United States of America
English فارسی Español 普通话 한국어/조선말
Drama Romance

Granada Film Productions Arts Council of England Diaphana Films The Glasgow Film Fund National Lottery Showtime Networks Filmfour Scottish Arts Council, The Three Rivers Production Progres Film Distribution Kinowelt Median
United Kingdom France Germany United States of America
English Français
Action Thriller
cia assassin
Orion Pictures
United States of America
English
Drama Romance

Universal
Germany United States of America
English
Comedy
porno star hollywood
Columbia Pictures Happy Madison Productions
United States of America
English Polski
Comedy Drama

New Line Cinema 40 Acres & A Mule Filmworks
United States of America
English Magyar
Horror Thriller
japan forest
Lava Bear Films AI-Film Phantom Four Films
United States of America
English
Adventure Mystery Thriller
cairo based on novel egypt pyramid museum mummy murder independent film curse egyptologist archeologist
Orion Pictures S & L Films
Netherlands United States of America
English
Comedy Drama Mystery
father-in-law marriage documentary filmmaking hipster middle age documentary filmmaker generation-x generation-z psychedelic drug
Scott Rudin Productions A24
United States of America
English
Drama
california garden immigrant truck illegal immigrant gardener stolen truck
Summit Entertainment Witt/Thomas Productions Depth of Field McLaughlin Films Lime Orchard Productions
United States of America
English Español
Drama Mystery Thriller
secret asylum bed and breakfast place past psychopath
Téléfilm Canada Capitol Films Canadian Film or Video Production Tax Credit (CPTC) Metropolitan Films Grosvenor Park Productions Odeon Films Catherine Bailey Ltd. Artists Independent Network
Canada United Kingdom
English
Action Comedy Romance Thriller
female nudity drug cartel nervous breakdown
Hollywood Pictures Fortis Films
United States of America
English
Adventure Drama Action Family

United Artists Corporation Hart-Sharp Entertainment Potboiler Productions
United Kingdom United States of America
English
Thriller Crime Drama
new jersey restaurant hitman van arrest psychopath based on true story jail serial murder stabbing crime family bombing ice cream man   drug deal contract killer crime syndicate poisoning
Bleiberg Entertainment Millennium Films
United States of America
English
Action Science Fiction



हिन्दी
Thriller Comedy Crime
heroin blindfold bong perversion burned alive independent film
Canal+ Artic Productions LLC Polar Entertainment Corporation
France United States of America
English
Crime Drama Thriller
trailer park gun texas deal psychopath sexual humiliation money lingerie arson police detective physical abuse neo-noir burial pizza shop drugs
Voltage pictures Worldview Entertainment ANA Media Picture Perfect (I)
United States of America
English
Comedy Drama
independent film duringcreditsstinger
Echo Lake Productions Premiere Picture
United States of America
Český English Français
Crime Drama Thriller
female nudity gambling casino nudity banker toronto fraud niagara falls based on true story atlantic city money las vegas surveillance gambler bank fraud
Alliance Atlantis Communications Natural Nylon Entertainment Téléfilm Canada Astral Media Canadian Film or Video Production Tax Credit (CPTC) Ontario Film and Television Tax Credit (OFTTC)
Canada United Kingdom
English
Comedy
brother brother relationship jealousy pregnancy and birth autoritian education arctic
Revolution Studios TriStar Pictures Carsey-Werner Company
United States of America
English
Drama Romance
usa kaffeehaus poker lovesickness waitress bar night life night melancholy approach loneliness
Block 2 Pictures Jet Tone Production StudioCanal Lou Yi Inc.
China France Hong Kong
English
Drama
playwright critic theater
Overseas FilmGroup GreeneStreet Films JVC Entertainment Networks Sogepaq CDI
Spain United States of America Japan
English
Comedy Romance
adultery island shipwreck tropical island
Screen Gems SKA Films Codi S.p.a.
Italy United Kingdom
Italiano ελληνικά English
Action Adventure Comedy Thriller
hitman political satire

Bulgaria
English
Action Comedy
martial arts stadium champion shaolin steel helmet soccer
Star Overseas Universe Entertainment
China Hong Kong
广州话 / 廣州話 普通话 Português ภาษาไทย
Drama
rape ambulance ex-girlfriend memory unsimulated sex motorcycle
Wild Bunch Kinétique Inc. Vincent Gallo Productions
France Japan United States of America
English Deutsch
Comedy Crime Thriller


Comedy Romance
hong kong macau woman director
Bona International Film Group
China
普通话
Drama Comedy Romance
london england flower shop homosexuality lesbian lgbt
BBC Films Filmstiftung Nordrhein-Westfalen X-Filme Creative Pool Ealing Studios Fragile Films Focus Features RTL Cougar Films Ltd. Minotaur Film Partnership No. 3
Germany United Kingdom United States of America
English
Drama
cook friendship
Envision Media Arts Cinelou Films Shenghua Entertainment
United States of America
English
Thriller Crime
london england female nudity women countryside based on novel subway provence country house writing innkeeper generations confilct dying and death daughter swimming pool murder suspense author drug
France 2 Cinéma Canal Plus Fidélité Productions Gimages FOZ Headforce Ltd.
France United Kingdom
English Français
Action Drama

Tea Shop & Film Company
United States of America
English
Action Adventure Science Fiction
martial arts post-apocalyptic sport revenge independent film blood violence desert combat
Handistom Investment Kings Road Entertainment Kamisha Corporation
United States of America Australia
English
Action Crime Thriller

Steamroller Productions Premiere Entertainment Group
United States of America
English Deutsch
Comedy Drama
individual black people chauffeur atlanta widow anti semitism jewish african american car old age
The Zanuck Company Majestic Films International
United States of America
English Magyar Polski
Comedy Drama
sister family relationships unity
Fox 2000 Pictures Edmonds Entertainment Group (EEG)
United States of America
Italiano English
Crime Action Comedy Thriller
new york martial arts supermarket gang war disabled child gang wedding diamond bronx duringcreditsstinger
New Line Cinema Golden Harvest Company
Hong Kong
广州话 / 廣州話 English
Drama War
fire classroom hostage rain horse rifle children teacher school rural setting school teacher based on short story algeria journey 1950s algerian war mountain
Procirep Canal+ One World Films Pathé Ciné+ Centre National de la Cinématographie (CNC) Media Programme of the European Community Backup Media Cinémage 8 Indéfilms 2 Perceval Pictures Kaléo Films Jouror Développement B Media 2012 SofiTVCiné Dévelopimage 2 Ciclic - Région Centre
France
العربية Français Español
Comedy Drama
father son relationship capitalism based on novel smoking lie cigarette research law health marketing politics politician tobacco liar dark comedy cancer independent film money morality social satire cigarette smoking business advertising guilt humiliation lobby bribe corporation lung cancer lobbyist tobacco industry nicotine
Fox Searchlight Pictures Room 9 Entertainment
United States of America
English
Horror
prague bratislava castration ladies' man student torture penis torture porn
Lions Gate Films Next Entertainment Screen Gems
United States of America
English Polski
Drama Romance
adolescence age difference self-discovery coming of age love affair youth family woman director teaching the ways of the world parents and children love and romance teenage life
BBC Films
United Kingdom United States of America
English
Comedy Drama Romance
salesclerk
Epsilon Motion Pictures Hyde Park Films Shopgirl Touchstone Pictures
United States of America
English Polski
Comedy Drama
suicide bomb prostitute rape sex hotel based on novel terrorist fight nudity satire
Orion Pictures Woodfall Film Productions Filmline Productions
Canada United Kingdom United States of America
English
Action Crime Drama Thriller
assertion investigation internal affairs narcotics cop
Paramount Pictures Lions Gate Films Cruise/Wagner Productions
Canada United States of America
English Deutsch Polski
Comedy
sport

Canada
English
Action Adventure Comedy Crime

Parallel Films
United States of America
English
Drama Romance



English
Comedy
infidelity con man thief independent film business manufacturing industrial accident duringcreditsstinger sexless marriage misfortune
Miramax Films
United States of America
English
Drama Music
journalist musical concert independent film
BBC Films Intermedia Films
United States of America United Kingdom
English
Drama Thriller Crime Foreign



Français
Drama Romance Science Fiction Thriller
seattle shanghai future insurance salesman dystopia
BBC Films
United Kingdom
English
Comedy
racehorse

United Kingdom
English
Drama
butler dublin maid
Chrysalis Films
United Kingdom Ireland
English Français
Drama Action Crime

Wells & Jeta Entertainment
United States of America Nigeria

Family Comedy Romance
new york from rags to riches family relationships bollywood racer starvation
Yash Raj Films
India
English हिन्दी
Animation Drama
civil war parents kids relationship 1970s puberty totalitarian regime cutting the cord punk bomb alarm war adult animation punk band woman director
Sony Pictures Classics Procirep Soficinéma France 3 Cinéma Diaphana Films Sofica Europacorp Celluloid Dreams The Kennedy/Marshall Company Région Ile-de-France Centre National de la Cinématographie (CNC) Fondation GAN pour le Cinéma 2.4.7. Films French Connection Animations Société des Producteurs de L'Angoa
France United States of America
English Français Deutsch فارسی
Thriller Adventure Fantasy
basement hole little brother
Bold Films BenderSpink
United States of America
English
Drama Thriller
dictator trainer classroom fascism group dynamics education national socialism training squatter anarchist group gymnasium learning and teaching violence in schools homepage social experiment
Constantin Film Produktion
Germany
Deutsch
Thriller Horror
model
Bold Films Amazon Studios Vendian Entertainment Space Rocket Nation
Denmark France United States of America
English
Thriller Crime Drama Action
self-defense widower
HanWay Films UK Film Council Marv Films
United Kingdom
English
Horror Thriller
bible suspense biblical code revelation (book)
Code Productions

English Italiano
Comedy Drama Romance
sexuality becoming an adult puberty first time oscar award pregnancy and birth pregnant minor precocity partnership teenager teenage pregnancy
Fox Searchlight Pictures Mandate Pictures
United States of America
English
Action

Odyssey Media Rodin Entertainment Ace Film Company Chunqiu Time Culture Co.
Canada
English
Adventure Action Thriller
spy fight secret organization satellite secret agent plastic surgery smuggling murder extortion violence millionaire fingerprints dirt bike woman drowned casino owner old woman murdered high dive gender disguise aftercreditsstinger master villain
United Artists Eon Productions Danjaq
United Kingdom United States of America
English Deutsch
Drama Crime
italy love at first sight loss of father patriarch organized crime mafia lawyer italian american crime family rise to power mob boss 1940s
Paramount Pictures Alfran Productions
United States of America
English Italiano Latin
Drama Music Romance
dancing dance locksmith welder
Paramount Pictures
United States of America
English Português
Comedy Drama Romance
date sex jealousy fight architect gallery interview sister party love friends fate los angeles summer ikea year heartache
Fox Searchlight Pictures Watermark Dune Entertainment III
United States of America
English Français svenska
Drama Romance
love triangle scotland mother adultery sexuality jealousy culture clash isolation eroticism strangeness penalty violent husband new zealand maori arranged marriage piano lessons settler wilderness deceived husband marriage secret love woman director
New South Wales Film & Television Office The Australian Film Commission CiBy 2000 Jan Chapman Productions
New Zealand Australia France
English
Drama Comedy
dancing florida strip club male stripper novice
Extension 765 Iron Horse Entertainment (II)
United States of America
English
Thriller Horror
witch loss of mother small town death penalty lighthouse cowardliness spirit witch hunt
Village Roadshow Pictures Revolution Studios Distant Corners Entertainment Group Inc. Blue Star Productions Morningstar Films
Australia United States of America
English
Adventure Action Thriller
london england new york bomb england spy sheriff dual identity secret identity drug traffic tarot cards heroin crocodile jamaica secret mission secret intelligence service motorboat drug smuggle voodoo tombstone aftercreditsstinger
United Artists Eon Productions Danjaq
United Kingdom
English Magyar
Comedy Drama Family
mississippi childhood memory dog
Alcon Entertainment Warner Bros.
United States of America
English
Comedy Romance
lovesickness love of one's life narration lovers kiss daughter affection relation make a match sex education relationship divorce father daughter relationship past relationship
Universal Pictures StudioCanal Working Title Films Ringerike Erste Filmproduktion
France Germany United Kingdom United States of America
English
Comedy
african american wedding class differences martha's vineyard
TriStar Pictures Stage 6 Films Sony Pictures Worldwide Acquisitions (SPWA) TDJ Enterprises / New Dimensions Entertainment Our Stories Films
United States of America
English
Drama History
telecaster communist political activism tv show politician government anti-communism
2929 Productions Participant Productions Warner Independent Pictures (WIP) Davis Films Section Eight Productions Redbus Pictures Tohokushinsha
France Japan United Kingdom United States of America
English
Crime Drama
gay self-fulfilling prophecy based on novel journalism identity dream literature research literature dying and death biography
Sony Pictures Classics Cooper's Town Productions Eagle Vision Inc. Manitoba Film and Video Production Tax Credit Province of British Columbia Production Services Tax Credit Infinity Media A-Line Pictures
Canada United States of America
English
Thriller Action Crime
gunslinger anti terror ambush mexico showdown guitar nudity hitman bartender revenge tragic hero shootout mariachi explosion extreme violence brutality drug lord leg brace concealed weapon flashback bookstore
Columbia Pictures Los Hooligans Productions
United States of America
English
Adventure Action Romance Science Fiction
female nudity killer robot nudity utopia teleportation post-apocalyptic dystopia plastic surgery escape fugitive robot domed city dystopic future totalitarianism population control
Metro-Goldwyn-Mayer (MGM)
United States of America
English
Adventure Action Thriller
london england england martial arts assassin exotic island gold hitman secret mission villain bangkok thailand floatplane karate hong kong duel pistol secret service aftercreditsstinger
United Artists Eon Productions Danjaq
United Kingdom United States of America
ภาษาไทย 广州话 / 廣州話 English
Action Adventure Comedy Crime Drama
showdown suspicion of murder boxer suspension organized crime shootout car chase detroit drug addict one against many megalomaniac maverick cop framed for murder bar fight exploding boat action hero
Silver Pictures Lorimar Motion Pictures
United States of America
English Français
Adventure Horror
mutant expedition cave darkness rope climbing bestie appalachia friends female protagonist survival horror
Celador Films Pathé Northmen Productions
United Kingdom
English
Documentary
sport
IMAX
United States of America
English
Horror
found footage
Twentieth Century Fox Film Corporation Davis Entertainment TSG Entertainment
United States of America
English
Comedy Romance
lsd looking for  birth parents half-brother independent film
Miramax Films
United States of America
English
Drama Horror Crime
sadistic killing fire sheriff bounty hunter cocaine motel ax sadism psychopath road trip sequel murder rampage antisocial personality disorder serial killer shootout torture corpse sadist extreme violence brutality maniac violence stabbing killing spree held at gunpoint cult film roadkill macabre misogynist road movie killer clown painted face evil clown homicidal maniac sadistic horror
Lions Gate Films Cinerenta Medienbeteiligungs KG Firm Films Cinelamda Internationale Filmproduktionsgesellschaft
Germany United States of America
Español English
Crime Drama Comedy
california hip-hop harvard university geek coming of age teenager drug high school student
Forest Whitaker's Significant Productions Revolt Films IamOTHER Entertainment
United States of America
English
Drama Action Thriller Crime

Suntaur Entertainment Company
United States of America
Italiano English Pусский
Horror
upper class halloween psychopath urban legend youth satanic ritual
Universal Pictures Spectacle Entertainment Group
United States of America
English
Horror Action Thriller Science Fiction


United States of America
English
Comedy Drama
professor dark comedy telephone call aftercreditsstinger 1960s
Mike Zoss Productions Studio Canal Relativity Media Focus Features Working Title Films
United States of America United Kingdom France
English עִבְרִית
Comedy Drama Mystery
independent film
K5 International Zanuck Independent David Gundlach Productions
United States of America
English Français
Adventure Comedy Fantasy Horror
witch cemetery magic time travel aging curse warlock witch hunter
New World Pictures
United States of America
English
Romance Drama
talent success musician woman director
Relativity Media Homegrown Pictures Black Entertainment Television (BET) Relativity Sports Undisputed Cinema
United States of America
English
Drama Romance
gay based on novel suicidal death of lover teacher student relationship grieving 1960s
Depth of Field Artina Films Fade to Black Productions
United States of America
English Español
Drama
christianity traitor jesus christ roman crucifixion longing moral conflict cross blasphemy temptation mary magdalene
Universal Pictures Cineplex-Odeon Films
United States of America Canada
English
Romance Comedy Drama
suicide sex sexuality college police campus party love revenge prank independent film student teenager drug humiliation flashback accident
Miramax Films Eagle Beach Productions
United States of America
English
Drama Comedy Music Romance
indian lead bollywood modern day adaptation pride & prejudice woman director

United Kingdom United States of America
English हिन्दी Magyar Italiano ਪੰਜਾਬੀ Español
Adventure Drama Action History
child abuse sister sister relationship prosecution australia approved school  based on true story independent film tracker survival outback colonialism australian aborigine australian outback aboriginal aborigine perth
Showtime Australia Australian Film Finance Corporation (AFFC) Rumbalara Films Olsen Levy
Australia
English
Comedy
sport
The Weinstein Company Dimension Films Metro-Goldwyn-Mayer (MGM)
United States of America
English
Thriller Action Horror Science Fiction Crime
flooding futuristic police detective
Entertainment Muse Productions Challenge Film Corporation XYZ Funding N.V.
United Kingdom
English
Action Adventure Drama Family
based on novel biography
3Mark Entertainment
United States of America
English
Drama Romance
love of one's life pilot class society pakistan india kashmir conflict
Yash Raj Films
India
हिन्दी
Drama
film making film producer video surveillance sport interracial marriage auto accident instructor jujitsu movie star nightstick husband life relationship set up window smashing
Sony Pictures Classics
United States of America
English
Comedy Drama Romance
mumblecore
Scott Free Productions
United States of America
English Polski
Drama Family



English
Drama Crime
male nudity adultery based on novel infidelity tv show blow job video biography sex addiction based on true story independent film sex addict
Sony Pictures Classics Propaganda Films Good Machine
United States of America
English
Drama
new york alcohol sex infidelity nudity artist gallery interview studio biography addiction party love independent film singer art drug gay man socialite scene film warhol
The Weinstein Company L.I.F.T. Production Holly Wiersma Productions
United States of America
English Français Slovenčina
Drama Thriller
suburb violence killing spree prison visit guinea pig broken arm potty training woman director
BBC Films Oscilloscope Laboratories
United Kingdom United States of America
English
Drama Family
angel miracle village christian candle christmas
Impact Productions LLC Pinewood Studios Big Book Media EchoLight Studios
United Kingdom United States of America
English
Action Drama
sport catholic mother superior catholic school convent school

United States of America
English
Comedy
male nudity female nudity mexico prostitute nudity high school locker room independent film teen sex comedy teenager canuxploitation virginity
Tijuana Productions Tiberius Film Productions
Canada United States of America
English Español
Drama Romance
adoptive mother nymphomaniac mother daughter relationship
Mockingbird Pictures Everest Entertainment
Spain United States of America
English
Action Adventure Drama War
gypsy middle east foreign legion wilderness archaeologist
Associated General Films Sir Lew Grade
United Kingdom
English
Fantasy Comedy Science Fiction
servant time travel clumsy fellow middle ages nobility
Canal Plus Gaumont International France 3 Cinema
France
Français
Comedy Drama
milan independent film luxury hotel man in towel  woman director
American Zoetrope Focus Features Pathé! Tohokushinsha
United States of America
English Italiano
Comedy Drama
female nudity based on novel stripper flop dark comedy aftercreditsstinger


English
Comedy
inventor invention scandal
101st Street Films
United States of America
English
Drama
loss of mother clerk grocery loss of relative loss of wife briefs duringcreditsstinger
DRO Entertainment The Last Picture Company CatchPlay Corner Store Entertainment Filmula Handsomecharlie Films American Work Dreamagine Entertainment
United States of America
English
Comedy Crime Drama
growing up money crime fatherhood
BBC Films Isle of Man Film Commission Recorded Picture Company (RPC) Pinewood Studios
United Kingdom
English
Mystery Drama Adventure
desperation highway wilderness getting lost friendship murder best friend desert very little dialogue tarkovskyesque friend
Epsilon Motion Pictures Tango Films My Cactus
United States of America Argentina
English
Drama Romance

British Broadcasting Corporation (BBC)
Germany United Kingdom
English Français
Romance Drama
new jersey equality lesbian relationship cancer
Double Feature Films Endgame Entertainment High Frequency Entertainment
United States of America
English
Comedy
independent film woman director
Wild Bunch Likely Story Tax Credit Finance 3 Arts Entertainment
France United States of America
English
Drama Science Fiction

Lenfilm Studio Sever Studio Kanal Russia 1
Russia
Pусский
Crime Thriller Comedy
independent film money
Immortal Thoughts Three Good Men
United States of America
English Français
Drama
adultery brain tumor south africa alcoholism divorce
Reeleyes Film Wah Film Productions Ltd. Scion Films Loma Nasha
United Kingdom South Africa France
English
Action Thriller Crime
arbitrary law boston twin brother russian mafia prologue irish police station pager duringcreditsstinger
Franchise Pictures Brood Syndicate B.D.S. Productions Inc.
Canada United States of America
English Español
Crime Thriller

Pegasus Motion Pictures
China Hong Kong
广州话 / 廣州話
Horror Thriller
sheriff vampire orphanage writer edgar allen poe ghost murder mystery
American Zoetrope
United States of America
English
Animation Fantasy

Bazelevs Production
Russia
Pусский
Family Animation Comedy Adventure

Crest Animation Production LionsGate
United States of America
English
Romance Western
gunslinger showdown marshal blackmail mine settler gold mining town violence killer preacher gold miner strange person
Warner Bros. Malpaso Company
United States of America
English
Adventure Science Fiction
wormhole space travel supernatural powers spaceship alien
Metro-Goldwyn-Mayer (MGM) Kawoosh! Productions DTV I
Canada United States of America
English
Comedy Drama
1970s texas high school comedy coming of age summer teenager period drama great soundtrack
Gramercy Pictures Alphaville Productions The Criterion Collection
United States of America

Drama
civil war dictator journalist guerrilla loss of lover revolution war correspondent civil rights movement  picture journalist el salvador dictatorship
Hemdale Film
United Kingdom United States of America
English Español
Comedy
wife husband relationship stress children mother daughter relationship parenthood parenting parent child relationship duringcreditsstinger
TriStar Pictures Provident Films Pure Flix Entertainment Affirm Films FourBoys Entertainment
United States of America
English
Fantasy Drama Mystery
parents kids relationship airplane time travel school presentation school performance suburbia vision morality teenager
Pandora Cinema Flower Films Adam Fields Productions
United States of America
English
Action Comedy Foreign




Drama Foreign History
law and ethics
First Floor Features Almerica Films
Netherlands Belgium
Nederlands English Français Deutsch
Comedy Crime Drama
independent film speed freak junky cop boy toy porn magazine dope selling crank handcuffed to a bed cctv veterinary clinic needlepoint needle older woman younger woman relationship telephone sex
Muse Productions Brink Films Silver Nitrate
United States of America
English
Comedy Drama
dark comedy independent film
Werc Werk Works
United States of America
English
Drama Thriller
independent film
CJ Capital Investment Korea Capital Investment Moho Films TSJ Entertainment Samsung Venture Capital Ilshin Capital Investments Centurion Investment
South Korea
English 日本語 한국어/조선말
Drama
royal court overbearing father harpsichord 18th century
Les Films Alyne
France
Français
Comedy Drama
prison sport amateur soccer soccer coach
SKA Films
United Kingdom United States of America
English Italiano
Action Crime Thriller

Media Asia Films Milky Way Image Company
Hong Kong
广州话 / 廣州話
Adventure Action Western
robbery miner treachery sundance kid native peoples butch cassidy
Quickfire Films Televisión Española (TVE) Arcadia Motion Pictures Noodles Production Canal+ España Instituto de la Cinematografía y de las Artes Audiovisuales (ICAA) Instituto de Crédito Oficial (ICO) ONO Ariane Mararía Films Nix Films Eter Pictures Manto Films Pegaso Producciones Ibermedia European Community Program Audiovisual Aval SGR
Bolivia France Spain United Kingdom
Español English
Crime Drama
suicide sex sweden underground nightclub nudity escape poverty prostitution violence disturbing
Det Danske Filminstitut Memfis Film Film i Väst
Denmark Sweden
Pусский svenska English
Drama Horror Mystery Thriller
wheelchair nightmare funeral injection crying casket shovel lily argument crucifix woman director
Plum Pictures Harbor Light Entertainment Lleju Productions
United States of America
English
Comedy Drama Thriller


India
हिन्दी English
Drama
individual rebel self-destruction wheelchair lunatic asylum dying and death rage and hate freedom insanity basic rights and human rights psychiatrist
United Artists Fantasy Films Warner Bros.
United States of America
English
Comedy Horror

EveryWhere Studios
United States of America
English
Comedy
screenplay stuntman slapstick mime hollywood silent film
Crossbow Productions
United States of America
Français
Thriller Action Drama History
evacuation war based on true story iraq war
T-Series Hari Om Entertainment Co. Cape Of Good Films
India
العربية हिन्दी
Drama Family
based on novel brother sister relationship canada village love school miniseries best friend orphan historical kids redhead girl
Sullivan Entertainment
United States of America
English
Adventure Action
yakuza marine fighting
Strohberry Films
United States of America
English
Action Drama Crime
british based on tv series
Vertigo Films Exponential Films Embargo Films
United Kingdom
Srpski English
Crime Drama Thriller
spain sex nudity psychopath murder heist money gangster violence criminal retired hunting safecracker brutal leisure
Fox Searchlight Pictures Kanzaman Filmfour Recorded Picture Company (RPC)
Spain United Kingdom
English
Drama Thriller Crime
consignment
Tre Vänner Produktion AB Swedish Film Institute Film i Väst
Denmark Sweden Germany
Deutsch English Español Srpski svenska
Drama Family
ocean loss of mother tradition loss of brother becoming an adult role of women empowerment new zealand maori tradition chief grandfather granddaughter relationship modern society whale patriarch stick fighting canoe patriarchy loss of wife woman director
South Pacific Pictures
New Zealand
English
Drama Family Foreign

A B Corp
India
हिन्दी
Thriller Mystery Science Fiction
space colony space travel simulated reality  spaceship suspense cargo ship suspended animation loneliness in space
Telepool Atlantis Pictures Schweizerische Radio- und Fernsehgesellschaft (SRG) Ascot Elite Entertainment Group Egli Film Teleclub AG Centauri Media
Switzerland
Français Deutsch
Comedy Drama Family Music TV Movie
becoming an adult musical music high school school performance high school sports jock teenager clique theater peer pressure teenage romance
Disney Channel
United States of America
English
Drama Romance Foreign
obsession love obsessive love actor
Arts Council of England British Broadcasting Corporation (BBC) British Screen Productions
Canada United Kingdom
English
Fantasy Action Thriller
witch subway fight airplane owl todfeind guard blood moscow
Bazelevs Production Channel One Russia TABBAK The First Channel
Russia
Deutsch Pусский
Romance Crime Drama Thriller
transvestism gay hostage love of one's life northern ireland homosexuality gay interest teenage crush soldier political unrest
Miramax Films Channel Four Films Palace Pictures Nippon Film Development and Finance Inc. Eurotrustees British Screen Productions
Japan United Kingdom Ireland
English
Comedy
male nudity female nudity sex florida virgin nudity stripper redneck school loss of virginity hijinks racism teenager lust mischief peeping tom teaching misadventure duringcreditsstinger voyeur canuxploitation virginity
Melvin Simon Productions Astral Bellevue Pathé
United States of America Canada
English
Horror Science Fiction
zombie
Devonshire Productions Artfire Films New Romero Sudden Storm Productions Blank of the Dead Productions
Canada United States of America
English
Horror
brother sister relationship cemetery gun gas station loss of father cellar house barricade zombie trapped bitten
Laurel Group Off Color Films Image Ten Market Square Productions
United States of America
English
Drama
upper class hotel room age difference commercial karaoke homesickness culture clash jet lag pop star unsociability aftercreditsstinger woman director
American Zoetrope
Japan United States of America
日本語 English
Comedy Drama Romance
narration neurosis comedian job interview love singer jewish breaking the fourth wall talking to the audience volkswagen beetle
United Artists
United States of America
English Deutsch
Action Drama Romance
circus travelling circus
Paramount Pictures
United States of America
English Deutsch
Drama Romance
southern usa waitress parents kids relationship overweight child loss of child new love unsociability ethnic stereotype independent film electric chair xenophobia
Lions Gate Films Lee Daniels Entertainment
United States of America
English
Horror
post-apocalyptic dystopia zombie
Lionsgate Grindstone Entertainment Group Silver Reel Sly Predator Matt Baer Films Gold Star Films Lotus Entertainment (I)
Switzerland United States of America
English
Drama Romance
individual prostitute alcohol casino love at first sight lovesickness film producer screenwriter hotel room dying and death rage and hate unsociability alcoholism los angeles alcohol abuse attempted suicide
United Artists Intial Productions
United States of America
English
Horror Comedy
witch marijuana succubus power company cannibalism
Tribeca Productions
United States of America
English
Romance Drama Comedy
chicago journalist newspaper marriage proposal stress father-in-law newspaper man
Universal Studios
United States of America
English
Thriller
male nudity female nudity sex adultery infidelity obsession blackmail villain hidden camera blind date death of a friend insanity high school stalker sociopath unrequited love neighbor unfaithfulness los angeles principal car accident violence sex scene extramarital affair tied up car explosion high school teacher fatal attraction mother son relationship older woman younger man relationship critically bashed loss of friend woman in jeopardy crying woman damsel in distress erotic thriller muscular
Universal Pictures Nuyorican Productions Blumhouse Productions Smart Entertainment
United States of America
English
Drama
circus trapeze artist
Joanna Productions
United States of America
English Italiano
Comedy Drama
lesbian relationship lesbian dinner motorcycle argument biological father artificial insemination control freak vegetable garden woman director lgbt family
Mandalay Vision 10th Hole Productions Focus Features Gilbert Films Saint Aire Production Artist International Antidote Films (I) Artist International Management
United States of America
English
Action Horror Science Fiction Thriller
dystopia social commentary alien invasion sunglasses brawl
Universal Pictures Alive Films Larry Franco Productions
United States of America
English
Adventure Drama History Thriller War
based on novel optimism switzerland baseball famous score prisoner shower world war ii prisoners of war claustrophobia nazis machinegun attempt to escape uniform freedom based on true story prison guard escape swastika barbed wire solitary confinement motorcycle motorcycle jump alps
United Artists The Mirisch Corporation
United States of America
English Deutsch Français Pусский
Documentary
alternate dimension new age parallel world pseudoscience theology consciousness quantum mysticism fantasy docudrama woman director
Lord of the Wind
United States of America
English Deutsch Español
Horror Thriller
found footage
StudioCanal CBS Films
United States of America
English
Drama
daily life family's daily life urban life growing up domestic abuse coming of age parenting divorce family divorced parents abusive husband
IFC Films Detour Filmproduction
United States of America
Español English
Comedy Mystery
upper class prostitute journalist drowning newspaper magic tarot cards magic show lordship suspicion of murder headline funeral investigation daughter music instrument afterlife swimming pool murder wealth american united kingdom
BBC Films Ingenious Film Partners Ingenious Media Perdido Prod.
United Kingdom
English
Action Comedy
sex fight music illegal drug black american stereotype cashier disgruntled worker low rider caller id duringcreditsstinger
Lionsgate
United States of America
English
Action Comedy Romance
sport

United States of America
English
Drama Romance
casino jinx bad luck
ContentFilm Pierce/Williams Entertainment
United States of America
English Pусский
Drama Action Romance
decision reno mustang falling in love divorce
United Artists Seven Arts Productions
United States of America
English
Drama Thriller
radio station radio presenter radio transmission independent film
Miramax Films IFC Films Fortissimo Films
United States of America
English
Comedy Crime
new york telephone joke gangster
Caravan Pictures Touchstone Pictures
United States of America
English
Horror Drama Thriller
schizophrenia suppressed past wife
Wild Bunch Telecinco Telecinco Cinema Televisió de Catalunya TV3 Esta Vivo! Laboratorio de Nuevos Talentos Grupo Rodar Rodar y Rodar Cine y Televisión Warner Bros. Pictures de España
Spain Mexico
Español
Comedy Horror
haunted house
Automatik Entertainment Open Road Films
United States of America
English
Comedy Drama Romance
love triangle independent film multiple storylines
Kingsgate Films
Germany United States of America
English Deutsch
Action Drama Mystery Thriller
new york cia cuba cold war suspense
Universal Pictures
United States of America
English Français Pусский Español
Comedy Crime
loss of father condom vulgar parole board alcohol abuse
Universal Pictures
United States of America
English Polski Português Español
Crime Comedy
hotel new year's eve witch bet hotel room sperm los angeles hoodlum woman director episode film
Miramax Films A Band Apart
United States of America
English
Comedy Drama Romance
suicide clerk fetish sadomasochism lawyer hospital secretary masturbation typewriter kinky cutting pantyhose bdsm workplace romance
Slough Pond double A Films
United States of America
English
Documentary
independent film

United States of America
English
Drama
anonymity radio presenter success dangerous radio transmission independent film
Cineplex-Odeon Films Ten-Four Productions
Canada United States of America
English
Music Comedy
missouri independent film mechanic in the closet mockumentary improvisation whispering travel agent amateur theater dairy queen alien contact fake documentary city council wagon train chinese restaurant product licensing hidden character
Sony Pictures Classics Castle Rock Entertainment Pale Morning Dun All Night Productions
United States of America
English
Comedy Romance
behind the scenes spa planetarium art imitates life

United States of America
Português English
Comedy Crime Thriller Romance
new york san francisco alcoholism serial killer alcoholic
Echo Lake Productions Bi-polar Pictures Code Entertainment Independent Film Group Carol Baum Productions Dillinger Productions Green Tulip Productions
United States of America
English
Comedy Drama
becoming an adult thumb first time hypnosis thumb sucking attention deficit hyperactivity disorder (adhd) elocution high school independent film teenage crush youth family
Sony Pictures Classics Bob Yari Productions
United States of America
English
Horror Action Thriller
christianity homophobia pastor protest christian sign gay interest social commentary religious fundamentalism aftercreditsstinger duringcreditsstinger
The Harvey Boys NVSH Productions Phase 4 Films
United States of America
English
Fantasy
fictional place dream fantasy
Destination Films Jim Henson Company, The
United Kingdom United States of America
English
Drama Documentary
eating around the world fast motion scene balance skyline sunset modern life moonrise
Magidson Films
United States of America
English
Fantasy Adventure
dragon barbarian
Cannon Films
Italy United States of America
English Italiano Español
Drama Romance
philosophy mentor artist painting friendship teen movie teenager sketching rebellious youth
Goldcrest Films International Atlantic Pictures Gigi Productions
United States of America
English
Thriller Drama
woman director
Protozoa Pictures Cargo Entertainment 33 Pictures
United States of America
English
Comedy Drama Thriller
hustler independent film pool
Gold Circle Films
United States of America
English
Drama

Summit Entertainment Newmarket Capital Group Red Mullet Productions
United Kingdom United States of America
English
Drama Fantasy
limousine multiple identities wig penis talking car sewer of paris traveling through a sewer multiple roles
Pandora Filmproduktion Canal+
France
Français
Drama
child abuse prostitute bar brothel snake rain pedophilia bridge beer police wine fellatio truck woods murder dogfight cigar smoking underage drinking teenager facial scar alcoholic ex-con cigarette lighter grocery store shot search for dog trees dirt road assaulting an officer gallon of water
Worldview Entertainment Muskat Filmed Properties Dreambridge Films Rough House Pictures
United States of America
English
Crime Comedy Romance
london england nightclub chase fraud liar love thief wealth money scam hospital secretary business wedding parole con dishonesty
Arts Council of England National Lottery Gruber Bros. Tomboy Films Winchester Multimedia PLC
United Kingdom
English
Crime Drama Horror Thriller
prison prisoner revenge haunting electric chair
Empire Pictures
United States of America
English
Comedy
gay dancing detective confession beach surfer satire party malibu friends revenge murder based on play independent film diner spoof summer killer drag
New Oz Productions Red Horse Films
Australia United States of America
English
Comedy Foreign
hairdresser hairstylist


English
Drama
germany mexican
Eficine 226 Beanca Films Fondo de Inversión y Estímulos al Cine (FIDECINE) MPN Cologne Film 3
Mexico Germany
Deutsch Español
Crime Drama Thriller
rape obsession lie job independent film teenage girl school internet best friend counselor internet chat duringcreditsstinger online chat catfishing online hookup online predator
Nu Image Films Millennium Films Dark Harbor Stories
United States of America
English
Comedy Crime
toupee scalper
Columbia Pictures DreamWorks SKG Baltimore Spring Creek Productions Bayahibe Films Ltd.
United States of America
English
Comedy Romance
yorkshire love friends
Arts Council of England British Broadcasting Corporation (BBC) British Screen Productions
United Kingdom
English
Drama
lovers woman director
Gaumont Ciné@ Canal+ Screen Australia Screen NSW France Télévisions France 2 Cinéma Hopscotch Features Mon Voisin Productions
France Australia
English
Drama Romance

Ventanarosa Productions Cineville Columbia TriStar Home Video Dan Lupovitz Productions
United States of America
English
Drama
spain bar ship drama friends shipyard peseta
Vía Digital Eurimages Continental Producciones Instituto de la Cinematografía y de las Artes Audiovisuales (ICAA) Televisión de Galicia (TVG) S.A. Antena 3 Televisión Sogepaq Elías Querejeta Producciones Cinematográficas S.L. Mediapro Quo Vadis Cinéma Eyescreen S.r.l.
Spain France Italy
Español Deutsch
Drama Horror Action Thriller Science Fiction
male nudity canada vampire
Glass Eye Pix Belladonna Productions Off Hollywood Pictures
United States of America
English
Drama
independent film
Tapestry Films The Kushner-Locke Company Bates Entertainment
United States of America
English
Drama
germany gay portugal drowning nudity travel brothers
Coração da Selva Hank Levine Film Detailfilm Watchmen Productions
Brazil Germany
Deutsch Português
Comedy Drama

Filmula
United States of America
English Français Deutsch
Adventure Action Thriller Crime
terror scotland kidnapping nudity wilderness mountaineer hiking climbing torture
Carnaby International Molinare Studios Eigerwand Pictures
United Kingdom
English Italiano
Comedy Fantasy Science Fiction
loser bullying leere independent film best friend cowardliness

Canada
English
Drama
alcohol adultery river camping province russia wife canoe daughter friendship alcoholism school teaching schoolboy geography kama perm
Marmot-film
Russia
Pусский
Drama Comedy History Music
usa congress musical
Columbia Pictures Corporation
United States of America
English
Thriller Romance
woman director
IFC Films Myriad Pictures Alliance Films
Canada Germany South Africa
العربية English
Action Drama History
world war i zeppelin royal air force royal flying corps dogfight airship
The Caddo Company
United States of America
Français English Deutsch
Comedy Drama Romance
independent film


English Italiano
Horror
cult
Blumhouse Productions
United States of America
English
Horror
killing high school female killer revenge prom escape teenager
Omnilab Media Ambience Entertainment Screen Australia Film Victoria
Australia
English
Horror

Brian Barrett Pictures
United States of America
English
Comedy Romance TV Movie

Annuit Coeptis Entertainment Inc. Annuit Coeptis Entertainment II
United States of America
English
Romance Adventure Drama
biography christian romance
Divine Inspiration, The Fabulous Boomtown Boys
South Africa
English
Drama History
england pope beheading death penalty thomas more protestant church thomas cromwell oath henry viii
Columbia Pictures Corporation Highland Films
United Kingdom
English Français Latin Español
Drama
corruption sex adultery television profit nudity power tv ratings murder corporate reporter co-worker meeting news fired network anchor structure rant
United Artists Metro-Goldwyn-Mayer (MGM)
United States of America
English Deutsch
Drama Romance War

Drama Romance
paris journalist dialogue talking soulmates walking bookshop love of one's life author
Castle Rock Entertainment Detour Film Production Warner Independent Pictures (WIP)
United States of America
English Français
Drama Thriller
homeless person mexico city daughter secret love dogfight money dog nonlinear timeline multiple storylines new mexican cinema
Altavista Films Zeta Film
Mexico
Español
Crime Drama
cheating dysfunctional family teen angst underage drinking domestic violence makeover drug overdose teacher student relationship street life movie theater razor blade tattoo shop peer pressure shoe store overachiever reference to jack black flunking out of school promiscuous mother glue sniffing woman director
Fox Searchlight Pictures Sound for Film Working Title Films Antidote Films (I)
United States of America
English Português Español
Drama Romance
anti semitism soldier
Twentieth Century Fox Film Corporation
United States of America
English
Drama
father court bail drug trade girl aftercreditsstinger duringcreditsstinger woman director
Anonymous Content Winter's Bone Productions
United States of America
English
Documentary Action Adventure
wound mountaineer peru sport glacier climbing rescue snow cordillera huayhuash
Darlow Smithson Productions UK Film Council PBS Film4
United Kingdom
English
Drama Music Romance
dance ragtime concert tour
Twentieth Century Fox Film Corporation
United States of America
English
Comedy Drama
brother brother relationship playground independent film sex talk art gallery separation self mutilation shoe salesman chat session female artist meeting on the internet hope chest woman director
IFC Films
United States of America
English
Documentary
corruption capitalism globalization bank banker fraud wall street finances global economy banking crisis money economics financial crisis stock market corporation
Sony Pictures Classics Sony Pictures Home Entertainment
United States of America
English
Drama Music Romance
dj
Working Title Films
United Kingdom United States of America France
English Italiano
Crime Drama
deportation hitman mission of murder book code telescope beating mafia park pigeon hagakure ice cream haitian cd player rouge arm sling racial slur
Bac Films Pandora Filmproduktion Degeto Film ARD JVC Entertainment Networks Canal+ Plywood Productions
United States of America
English
Crime Drama Thriller Action
watching a movie playing pool vinegar
The Weinstein Company
United States of America
English Español 한국어/조선말
Crime Drama Thriller
hostage based on true story murder independent film single mother drug drug addict recovering drug addict auto theft based on true events
Itaca Films BN Films Brightside Entertainment 1019 Entertainment Yoruba Saxon Productions
United States of America
English
Comedy Drama Romance
independent film
Miramax Films Populist Pictures Monophonic Inc.
United States of America
English
Horror
ax possession psychic power ouija ouija board evil spirit

United Kingdom United States of America
Deutsch
Romance Drama Comedy
gay new york free love swinger club transsexuality sex heterosexual suicide attempt eroticism group sex orgasm sex therapy video dominatrix homosexuality unsimulated sex
Fortissimo Films Process Productions Q Television
United States of America
English
Drama Animation War
israel palestine middle east lebanon nightmare middle east conflict
Les Films d'Ici Bridgit Folman Film Gang Razor Film Produktion
Israel France Germany
עִבְרִית العربية Deutsch English





Documentary
white house occupying power independent film incompetence irak superpower warfare


English
Drama Romance
1970s teenage girl older man younger woman relationship based on graphic novel teenage sexuality woman director
Caviar Films Cold Iron Pictures Archer Gray
United States of America
English
Documentary
nasa space mission rocket moon landing space astronaut apollo s
Film4 Passion Pictures Discovery Films
United Kingdom United States of America
Magyar
Drama Western
gold oregon thirst tree settler family relationships native american salt lake city pioneer woman director
Film Science Evenstar Films Oscilloscope Laboratories
United States of America
English
History Documentary
usa 1970s sexual revolution unsimulated sex

United States of America
English
Drama Action Thriller

Access Motion Picture Group Giraldi-Suarez-DiGiaimo Productions
United States of America
English Français Italiano
Comedy Drama
independent film woman director


English
Comedy
loss of virginity teenage boy teen comedy teenage sexuality found footage sex comedy virginity
Gary Sanchez Productions Principato-Young Entertainment
United States of America
English Français
Action Thriller
paris culture clash subway metropolis blackmail document criminal socialite punk band
Gaumont
France
Français
Comedy Drama
self-discovery friendship
Tribeca Productions Bob Yari Productions Southpaw Entertainment Jeff Skoll Productions
United States of America
English Français
Comedy Horror

Teeth
United States of America
English
Action Adventure Science Fiction
independent film
HSX Films
United States of America
English





Drama Comedy Music
disc jockey loss of family cocaine comeback recording studio british ibiza based on true story disabled

Canada United Kingdom
English
Comedy
independent film aftercreditsstinger

United States of America
English Italiano
Comedy Drama Romance
transporter sport friends nottingham
Scala Films
United Kingdom
English
Drama
stonewall riot
Centropolis Entertainment Mel's Cite du Cinema
United States of America
English
Animation Family Foreign

Walt Disney Pictures Yash Raj Films Walt Disney Studios Motion Pictures Disney World Cinema
India United States of America
English हिन्दी
Drama Action Thriller
heist mafia internet



Adventure Family

Kaos Entertainment
United States of America
English Deutsch
Comedy Drama Music Romance
wife musical marriage divorce
Lucky Monkey Pictures Sh-K-Boom Records Grand Peaks Entertainment Radius-TWC
United States of America
English
Comedy Drama Mystery Thriller
detective independent film train alcoholic missing person
Strand Releasing The 7th Floor Apropos Films
United States of America
English
Comedy Science Fiction Romance Horror
gang zombie
Ozla Productions
United States of America
Český English Italiano
Drama Action Romance
new york celebration
Destination Films Silver Nitrate Films National Film and Television School (NFTS) LHR Productions Inc.
United Kingdom United States of America
English
Drama
independent film mother daughter relationship woman director
Red Envelope Entertainment
United States of America
English
Horror Science Fiction
survival execution stranger no memory
Votiv Films Taggart Productions
United States of America
English
Horror Thriller
beach wife husband relationship lake camping rottweiler sadism forest revenge survival fear violence couple gang violence teenage killer
Aramid Entertainment Fund Rollercoaster Films
United Kingdom
English
Thriller
woman director
Blumhouse Productions IM Global Octane Reliance
United States of America
English
Horror Comedy
female nudity horror dark comedy female homosexuality female vampire
AV Pictures
United Kingdom
English
Drama Action Crime Foreign
hearing gang of thieves organized crime
Muti Films
South Africa
Afrikaans English
Thriller Drama Crime
loss of family camcorder alibi suspect murder

United Kingdom Ireland
English
Thriller Horror
camcorder reality insane asylum paranormal haunting psychiatric hospital ghost hunting paranormal investigation labyrinth mental asylum found footage
Darclight Twin Engine Films Digital Interference Productions
Canada United States of America
English
Horror
slapstick teen angst slaughter dark comedy supernatural being killer clown revenge killing
Bórd Scannán na hÉireann Irish Film Board Fantastic Films MPI Media Group Tailored Films Solid Entertainment
Ireland
English
Crime Drama Horror Thriller
kidnapping murder suspense
Hartbreak Films
United States of America
English
Documentary
music actors legendary perfomer classic hollywood frank sinatra singers
Eyeline Entertainment
United Kingdom

Comedy
revolution political activism loser
United Artists Jack Rollins & Charles H. Joffe Productions
United States of America
 English
Thriller


United States of America Hong Kong
English
Action Adventure Drama

Rockaway the Movie Off Hollywood Pictures Panamax Films Crook Brothers Productions
United States of America
English Deutsch Pусский Español
Crime Drama Mystery
new york san francisco aquarium shanghai yacht romantic rivalry insurance fraud court blonde suspense classic noir film noir
Columbia Pictures Corporation Mercury Productions
United States of America
广州话 / 廣州話 English
Horror Thriller
sheriff robber burned alive gore serial killer grim reaper desert held at gunpoint death taser hit by a car exploding gasoline station flashback
Institution, The
United States of America
English Polski
Action Adventure Drama
road movie
Alex Entertainment Inc.
United States of America
English
Comedy Crime

Deviant Films Morocco Junction Pictures 1812 Productions
United States of America
English
Comedy
coffee shop slacker thirty something carefree

United States of America
English
Comedy Fantasy Music



English
Comedy Drama
christmas tree salesman french canadian
Sidney Kimmel Entertainment Touchy Feely Films GreenStreet Films
United States of America
English
Mystery Horror History
snake cut-off arm pit revitalization descendant count surrealism
Constantin Film Produktion
Germany
Deutsch
Comedy Drama
brother brother relationship drug addiction sister-in-law
Nu Image Films Millennium Films The Group Films
United States of America
English
Comedy Music
virgin ancient rome freedom sondheim slave based on stage musical slave owner
United Artists Melvin Frank Production
United Kingdom United States of America
English
Documentary
presidential elections

United States of America
English
Action Adventure History Western
based on real events
Silver Sail Entertainment 4Go West Productions Flatiron Pictures
United States of America
English Français
Science Fiction Comedy
spoof zombie
Splendid Film
United States of America
English Deutsch
Thriller Mystery Horror Drama
self-defense car mechanic graduation high school shooting party murder curse blood teenager attempted rape aftercreditsstinger
Myriad Pictures AliBella Pictures Bystander Films Management Production Entertainment (MPE) Mangrove Media
United States of America
English
Thriller
lake shark attack
FLF Films Bottom Line Entertainment Parkside Pictures
United States of America
English
Crime Drama
sex police friends murder
Hemdale Film Island
United States of America
English
Fantasy Drama Science Fiction


United States of America
English
Thriller Action

WWE Studios
Canada
English
Drama Thriller Mystery
isolation coffin race against time buried alive survival terrorism danger cell phone desert psychological aftercreditsstinger captivity chases and races mind and soul confined
Studio 37 Versus Entertainment The Safran Company Dark Trick Films
Spain United States of America France
English
Drama Comedy Romance
beach wales friendship bullying teenage girl loss of virginity
Film4 Film Agency for Wales Red Hour Films Warp (Submarine) Warp Films
United Kingdom United States of America
English
Documentary Drama History
woman director
Roast Beef Productions Worldview Entertainment Noujaim Films
United Kingdom United States of America Egypt
العربية
Drama
france musician investigation sadomasochism independent film relationship incest bisexual
Région Provence Côte d'Azur La Fabrique de Films Canal+ Toloda Centre National de la Cinématographie (CNC) Soficinéma 2
France
Français
Drama Music
underdog competition dance musical drama
UTV Motion Pictures
India
हिन्दी
Thriller Documentary Crime History
judge juggler passion reality street artist jail independent film fame hiding tower
UK Film Council Red Box Films Discovery Films BBC Storyville Wall to Wall
United Kingdom United States of America
English Français
Drama Thriller
supervivencia
Making Movies
New Zealand
English
Drama



English
Horror Drama Thriller
exorcism fraud evil spirit human sacrifice mockumentary preacher satanic ritual found footage satanic cult
Strike Entertainment StudioCanal Arcade Pictures
United States of America France
English
Drama
musician musical biography teenager dark past hit by a car new brighton england woman director 1950s aspiring musician
Ecosse Films UK Film Council Film4 Lipsync Productions Aver Media North West Vision
Canada United Kingdom
English
Drama
southern usa rape sister sister relationship loss of sense of reality brother-in-law violent husband new orleans middle aged woman brother-in-law sister-in-law relationship light bulb expectant father off screen rape
Charles K. Feldman Group Warner Bros.
United States of America
English
Drama Comedy War
usa president general cold war strategic air command nuclear missile war room bomber pilot nuclear weapons ex nazi doomsday device absurdism
Hawk Films Columbia Pictures Corporation
United Kingdom United States of America
English
Drama Romance
heart attack drug traffic drug crime mexican province celibacy priest pregnancy catholicism new mexican cinema
Instituto Mexicano de Cinematografía Alameda Films Cinecolor-México Cinecolor-Argentina Artcam y Fonds Sud Cinéma
Mexico
Español
Drama Fantasy
refugee camp hurricane fantasy flooding global warming drama bayou crab storm celebration auroch tough love defrost levee prehistoric creature lost mother melting ice caps shrimp salt water explosives crawfish shrimping submerged grits african american child wild man
Journeyman Pictures Court 13 Pictures Cinereach
United States of America
English
Action Science Fiction
post-apocalyptic dystopia ape
Twentieth Century Fox Film Corporation Apjac International
United States of America
English
Drama Music
musical independent film woman director
Rigas Entertainment ErgoArts
United States of America
English
Drama Thriller
baby wife husband relationship christian faith independent film evangelical christianity woman director

United States of America
English
Comedy Romance
teenage love
Nic Arts Simbu Cine Arts
India
தமிழ்
Comedy Documentary
comedian comedy duringcreditsstinger
Snoot Entertainment
United States of America
English
Comedy
chainsaw macabre uncle nephew relationship


English
Adventure Drama Foreign
illusion independent film bhutan story in story weaver storytelling
Prayer Flag Pictures
Bhutan United Kingdom Australia

Western
prison judge marshal death penalty oklahoma widow cattle drive hanging law man lynching search party
United Artists
United States of America
English
Crime Drama

Twentieth Century Fox Film Corporation
United States of America
English Deutsch
Horror Thriller
nurse psychology suspense blood hospital
Raw Feed
United States of America
English
Thriller Comedy Horror
snuff


English
Action Science Fiction
ufo extraterrestrial spaceship alien
Independence Day Productions
Canada
English Français Deutsch
Comedy Romance


United States of America
English
Action Drama Thriller
berlin casino nun red hair running homeless person supermarket ambulance subway daughter money fate
X-Filme Creative Pool Westdeutscher Rundfunk (WDR)
Germany
Deutsch English 日本語
Drama Horror Thriller Romance
difficult childhood psychoterror murder loneliness artificial
A Loopy Production LLC 2 Loop Films
United States of America
English
Adventure Family
cave plane wreck salmon bears northern canada wolves alaskan malamute dove "family-approved"
Against the Wild Films
Canada
English
Drama
independent film woman director
The Weinstein Company Fidecine Creando Films Potomac Pictures
Mexico United States of America
English Español
Action Science Fiction
circus pet human being dystopia insurrection army ape
Twentieth Century Fox Film Corporation APJAC Productions
United States of America
English
Drama Thriller
age difference fishing arbitrary law conductor ex husband single independent film
Miramax Films GreeneStreet/SKE Films
United States of America
 English
Thriller Crime Horror
rape fondling revenge writer strangulation female writer garden shears rape and revenge
Anchor Bay Films Cinetel Films Family of the Year Productions
United States of America
English
Comedy Crime
small town texas con man fraud independent film mistaken identity in the closet fish out of water escaped convict stolen identity small town sheriff ruse beauty pageant confidence man small town thieves gender stereotypes gay couple
Miramax Films Marked Entertainment
United States of America
English
Drama Thriller Romance
england brother sister relationship becoming an adult northern england female friendship moped lesbian relationship homosexuality summer tomboy lgbt

United States of America
English
Drama Romance

UTV Motion Pictures
India France Germany
English हिन्दी
Drama Romance
woman director
GreeneStreet Films UK Film Council Studio Fierberg Adventure Pictures
United Kingdom United States of America
English
Comedy Romance
monopoly tycoon house love friends eccentric secretary free spirit rich snob stenographer
Columbia Pictures
United States of America
English Pусский
War Drama Romance
hawaii harassment pearl harbor bombing military life army base
Columbia Pictures Corporation
United States of America
English
Western
captain fort retirement attack cavalry
RKO Radio Pictures
United States of America
English
Drama Music
christian
Coram Deo Studios Birchwood Pictures
United States of America
English
Comedy Drama
independent film sexual humor drug humor
No Limit Films Shooting Star Pictures
United States of America
English
Drama Crime Thriller




Drama Comedy Romance
women hairdresser sister sister relationship new love unexpected happiness virgin beauty dressmaker cosmetics and hygiene strafzettel wedding police officer existence woman director
Bac Films Les Films des Tournelles Les Films de Beyrouth Roissy Films Sunnyland Arte France Cinéma Centre National de la Cinématographie (CNC) Fonds Sud Cinéma Ministère de la Culture et de la Communication Ministère des Affaires étrangères et du Développement International Cinéfondation Ministère Libanais de la Culture
Lebanon France
Français العربية
Thriller Horror

Participant Media Imagenation Abu Dhabi FZ Dynamo Apaches Entertainment XYZ Films Cactus Flower Producciones Fast Producciones
Spain United States of America Colombia
English
Drama Romance
gay
Metro Productions Israeli Film Fund Keshet Hot Uchovsky Fox Ronen Ben-Tal Films Feingold Productions
France Israel
עִבְרִית
Crime Drama Mystery
san francisco paranoia audio tape wiretap shadowing
Paramount Pictures The Coppola Company The Directors Company
United States of America
English
Romance

Entertainment One Pvt. Ltd.
India
English हिन्दी
Crime Drama Romance
exotic island secret love of one's life plantation marriage mail order bride french noir
Les Films du Carrosse Les Productions Artistes Associés Produzioni Associate Delphos
France Italy
Français
Drama Mystery



Deutsch
Horror
vacation remake woods burned alive murder gore marijuana blood teenager cabin in the woods disease dog flesh eating virus
Armory Films Pelican Point Media Contend
United States of America
English
Comedy
waitress unwillingly pregnant woman director
Night and Day Pictures
United States of America
English
Action
martial arts biography sport sensei mixed martial arts hong kong
Cannon Films
United States of America
English
Comedy Drama
corruption washington d.c. senate senator governor politician camp conservative usa politics political drama
Columbia Pictures
United States of America
English
Drama Crime
puberty first time
Miramax Films
United States of America
English
Comedy Drama
childhood memory uniform independent film private tryst
Destination Films Samuel Goldwyn Films Sony Pictures International
United States of America
English Français
Comedy
jew based on play independent film gay relationship lesbian bisexual bisexual woman

United States of America
English
Horror
racist religion
Splendid Film
United States of America
English
Horror Thriller



English
Romance Drama

Baleuko S.L. Departamento de Cultura del Gobierno Vasco Bitart New Media
Spain
Español
Comedy Drama Romance


United States of America
English
Comedy Romance

Triumphant Pictures
United States of America
English
Western

Rapid Heart Pictures
United States of America

Thriller Horror
friends remote island woman director
Submarine Entertainment Distributors LD Entertainment
United States of America
English
Horror Thriller Mystery

Corona Pictures
United Kingdom
English
Drama Thriller
independent film


Deutsch
Science Fiction Drama Music
small town rock star musical idol teenager 1960s chemical leak mutations
JoBro Productions & Film Finance Scythia Films
Canada
English
Horror
phobia doctor fear
Dry County Films Anchor Bay Entertainment Movie Machine
United States of America
English
Comedy Action Science Fiction Thriller
mutant post-apocalyptic zombie
Arrowstorm Entertainment The Klimax
United States of America
English
Drama



English
Drama Romance Science Fiction
experiment mouse intelligence test genius
ABC Pictures Cinerama Releasing Corporation
United States of America
English
Horror Thriller
lsd government conspiracy tension video camera drug use writer desert radio broadcast mind bender number stations lovecraftian mk ultra experimental drug
Before the Door Pictures Sunchaser Entertainment Favorit Film
United States of America Germany
English
Drama Mystery Thriller
college blog dark secrets
Decipher Entertainment Presque Isle Films LA Publicity Tait Productions
United States of America
English
Comedy Romance



English
Documentary



English
Crime Drama
murder suspense union dock longshoreman pigeon
Columbia Pictures Horizon Pictures
United States of America
English
Comedy
baby roommate friendship single los angeles dating pregnancy woman director
Stardust Pictures Dot Dot Dot Productions
Canada United States of America
English
Drama
rape hotel room totalitarian regime cohabitant female friendship dormitory best friend contraception romanian new wave
Saga Film Mobra Films Mindshare Media Centrul National al Cinematografiei (CNC) McCann-Erickson Televiziunea Romana (TVR1) Hubert Bals Fund of the Rotterdam Festival, The
Belgium Romania
Română
Horror
anthology



Drama Thriller
suicide rape age difference photographer ice shower menace lie pedophilia manipulation bedroom sadism electric shock coffee shop castration insanity vigilante sociopath deception neighbor teenage girl crying torture sadist pedophile cruelty older man younger woman relationship one day justice drinking rooftop held captive mental illness threat sexual torture screaming electrical torture childhood sexual abuse photo studio verbal abuse
Vulcan Productions Inc.
United States of America
English
Drama Thriller
depression christmas party deaf-mute daughter high school sports blood splatter independent film mother daughter relationship incest woman director
Destination Films
United States of America
English
Drama
sexual identity lesbian relationship homosexuality woman director
A Space Between Marakesh Films Bago Pictures
France Iran United States of America
English Français فارسی
Drama
police brutality based on true story racism docudrama day in a life
Forest Whitaker's Significant Productions OG Project
United States of America
English
Comedy Fantasy Thriller
fantasy based on comic book money magical object woman director
Laundry Films
United States of America
English
Animation Drama Family
forest coming of age best friend loss of loved one
Walt Disney Productions
United States of America
English
Comedy
transporter sport independent film
Bentley Filmgroup Eden Wurmfeld Films Hammer The Movie
United States of America
English
Drama Comedy Romance
gay coming out religion mormon
TLA Releasing
United States of America
English
Drama
france caribbean islands caribbean woman director
France Télévision Aztec Musique Canal Plus Overseas
Guadaloupe France
Français
Drama
drug addiction father daughter relationship semi autobiographical

United States of America
English
Comedy
crude humor best friend phone sex innuendo dirty joke
AdScott Pictures
United States of America
English
Comedy Drama Romance
relationship problems male female relationship divorce best friends in love
Team Todd
United States of America
English
Comedy Drama Family Science Fiction
time travel time machine christian film
Christiano Film Group
United States of America
English
Crime Drama Thriller
suspense
Steel Mill Pictures LTB Films Limited Wellington Films
United Kingdom
English
Action Comedy Science Fiction

Screen Media Films Vertigo Films Protagonist Pictures
United States of America
English
Thriller Mystery
woman director
Absinthe Productions
United States of America
English
Drama
emigration class money maid divorce iran caregiver alzheimer's disease marital separation iranian
Asghar Farhadi Productions Dreamlab Films MPA APSA Academy Film Fund
Iran France
فارسی
Comedy Drama Thriller
kidnapping stand-up comedy dark comedy night club landlord alcoholic stand-up comedian dark humor swearing
Scottish Screen EM Media BBC Scotland Synchronicity Films Wellington Films
United Kingdom
English
Comedy Drama
parents kids relationship sister sister relationship mockery ugliness independent film little girl school life

United States of America
English
Drama Romance
independent film
Ruby in Paradise Full Crew/Say Yea
United States of America
English
Drama Romance
independent film

United States of America
English Español
Drama Thriller Romance
london england casino irony forbidden love loss of husband reward silent film
Nero Films
Germany
Deutsch





Drama Foreign

Libido Cine Aquafilms Filmanova
Argentina
Español
Action Drama Mystery Thriller
diner judgment call
Battleplan Productions TF1 International Moonstone Entertainment
United States of America
English
Drama
chicken bullying rape of a male misfit homosexuality independent film coming of age gay sex

United States of America
English
Drama
woman director


English
Comedy
sex thanksgiving friendship high school love coming of age wild party
Steeltown Entertainment Point Park University Shaderville
United States of America
English
Horror Comedy
norway undead zombie wintry
Euforia Film FilmCamp Miho Film Barentsfilm Yellow Bastard Production News On Request (NOR) Zwart Arbeid
Norway
Norsk
Action Adventure Drama History War
winter belgium world war ii nazis bravery ardennen slaughter nazi germany soldier
Excel Entertainment
United States of America
English Deutsch
Horror Science Fiction

Baker's Dozen Productions
United States of America
English
Comedy Drama
farewell rock and roll robbery love at first sight car race radio station car breakdown vandalism radio radio presenter airplane car child
Lucasfilm Universal Pictures The Coppola Company
United States of America
English
Documentary



English
Animation Comedy
africa blood splatter surrealism blood robot adult animation
Warner Bros. Williams Street First Look Pictures Cartoon Network
United States of America
English
Comedy Romance Science Fiction Drama
time travel
Duplass Brothers Productions Big Beach Films
United States of America
English
Comedy Documentary
stand-up comedy
Comedy Central Films Codeblack Entertainment Hartbeat Productions
United States of America
English
Horror Thriller Crime
hotel wife husband relationship hitman infection forest cult priest murderer brutality bonfire ceremony ex soldier ritual sacrifice contract killer video tape folk horror mumblegore
Rook Films Warp X
United Kingdom
svenska English
Horror Thriller
anti terror terror beer supernatural towel inn phone whispering casa encantada mumblegore
Glass Eye Pix Dark Sky Films
United States of America
English
Drama
paris italy assassin fascism benito mussolini
Paramount Pictures Mars Films Marianne Productions Maran Film
Italy Germany France
English Français Italiano Latin 普通话
Drama Thriller
assassination paranoia suspense conspiracy
Magnolia Pictures


Horror Drama Thriller Crime

Warp X Madman Entertainment
United Kingdom
English
Horror Mystery Thriller
suicide attempt gun texas mass murder farm worker planned murder beauty dying and death fraud plan surprise farm victim of murder conspiracy of murder high school murder youth beautiful girl female corpse
Occupant Films
United States of America
English
Horror
vampire daywalker


Deutsch English
Western
gunslinger showdown fistfight morality u.s. marshal battle justice one against many quick draw brawl street shootout
United Artists Stanley Kramer Productions
United States of America
English
Documentary
chicago sports team ghetto narration college sport basketball high school sports independent film inner city high school student
Fine Line Features Kartemquin Films
United States of America
English
Documentary
street gang hip-hop dance fight breakdance ghetto musical clowning gang los angeles
David LaChapelle Studios HSI Productions Darkfibre Entertainment Ltd. Got Films
United States of America
English
Drama
independent film

United States of America
English
Mystery Drama Thriller
witch woman director


English
Crime Drama Music
dancing hip-hop b-girl street dance b-boying b-girling dance crew woman director
Two Camels Films
United States of America
English
Drama
date ex-girlfriend bicycle crack independent film
Thinkfilm Hunting Lane Films Journeyman Pictures Original Media Silverwood Films Traction Media
United States of America
English
Drama
native american racism family woman director
Red-horse Native
United States of America
English
Action Comedy Romance Science Fiction Thriller


United States of America
English
Thriller Crime Drama



English
Horror Fantasy

Mankurt Media
United States of America
English
Documentary Foreign



English
Documentary


United States of America
English
Mystery Thriller
coma crash accepting death
Seabourne Pictures Quite Quick Productions
United States of America
English
Drama




Drama Comedy
god woman director

United States of America
English
Comedy Music Romance
venice dance musical tap dancing stage show fashion designer mistaken identity fashion valet rapier
RKO Radio Pictures
United States of America
English Italiano
Horror Mystery
witch voodoo legend sorcery maryland forest footage horror true student lost found footage film
Artisan Entertainment Haxan Films
United States of America
English
History Documentary Music
hippie free love musical music woodstock music festival rock music summer
Wadleigh-Maurice Warner Bros.
United States of America
English
Comedy
journalism commercial television tv show manipulation of the media tv ratings satire television producer
Kentucky Fried Theatre
United States of America
English
Action Adventure Drama
suspense


English
Thriller Mystery

The Picture Factory B.Sting Entertainment
United States of America
English
Drama




Crime Drama




Music Documentary
woman director
Spring Films Together Films Mojo Musique
United Kingdom
Français English Bamanankan





Drama Comedy
hospital doctor
France 2 Cinéma Le Pacte 31 Juin Films Cinefrance Les Films du Parc
France
Français
Thriller


United States of America
English
Comedy Music
adolescence culture clash press conference behind the scenes police chase mockumentary older man younger woman relationship shaving the beatles song railway station performer psychotronic generation gap television director
Proscenium Films Walter Shenson Films Maljack Productions
United Kingdom
English
Documentary
migration immigration agriculture food human rights pesticide environment children's rights migrant farmworker labor latino child labor



Drama Thriller
obsession radio nudity letter love romance lingerie extramarital affair woman director
New World Pictures Millennium Films
United States of America
English
Comedy Drama
pornography sex love teenager death
Perfo Production Televizija Slovenija
Slovenia
English Slovenščina
Drama
father son relationship fire firemen christian advice marriage faith christian film dysfunctional marriage religious conversion hospital
Carmel Entertainment Provident Films Samuel Goldwyn Films Affirm Films Sherwood Pictures
United States of America
English
Documentary Drama
himalaya hindu pilgrimage faith hinduism little boy spirituality new age religion orphan india religious child abandonment ganja kumbh mela ganga
Jungle Book Entertainment
France India
हिन्दी
Adventure Family Romance
hostage affection rescue dog animal actor benji

United States of America
English
Drama Thriller
diving cataclysm nightmare panic red sea primal fear scuba diving shark scuba
Plunge Pictures LLC
United States of America
English
Comedy


United States of America
English
Horror Science Fiction
hotel small town siege independent film corpse tarantula death animal attack spiders
Arachnid Productions Ltd.
United States of America
English
Documentary Family
competition documentary dance contest ballroom dancing kids woman director

United States of America
English Español
Drama Comedy
train station new jersey small person friendship newfoundland
Next Wednesday Productions SenArt Films
United States of America
English
Drama
christian independent film

United States of America
English
Documentary
competition documentary contest crossword puzzle


English
Documentary
wrestling sport controversial ecw wwe
Imagine Entertainment Universal Pictures Lionsgate
United States of America
English
Comedy Drama Family Romance

Halestorm entertainment
United States of America

Drama
independent film
Hubert Bals Fund NHK LeBrocquy Fraser Productions Barmak Film
Afghanistan Ireland Japan
English Français Magyar پښتو
Documentary




Drama Music Romance
independent film

United States of America
English
Comedy Crime Family

Halestorm entertainment
United States of America
English
Drama Romance
independent film


English
Crime Drama
suicide alcohol secret birthday lake oregon brother party love friends prank bully drug gay man naked invite dare
Whitewater Films
United States of America
English
Romance Crime Drama
prison new mexico smuggling gang theft
United Artists Posthorn Pictures Giv'en Films
United States of America
English
Comedy Romance
romantic comedy


English
Crime Drama Thriller
woman director

United States of America
English
Comedy Drama Romance
sexuality parents kids relationship indiana anti hero melancholy brother uncle
Plum Pictures

English
Romance Drama
male female relationship co-worker relationship mumblecore
Burn Later Productions
United States of America
English
Documentary
magic woman director
Kino Lorber
United States of America
English
Action Drama
japan samurai peasant looting rice fencing village moral ambiguity battle practice 16th century
Toho Company
Japan
日本語
Documentary
olympic games sport basketball basketball team


English
Comedy Romance
sex nightclub nudity musician song rock idol music rent liar independent film
Vega Film Balthazar Productions Starr Arena
Switzerland France United States of America
English
Comedy
satire independent film spoof

United States of America
English
Comedy Drama Fantasy Horror Mystery
exploding building duringcreditsstinger
Canal+ Backup Films Arte France Arte France Cinéma Elle Driver 1.85 Films Realitism Films Sindika Dokolo
France Angola
English
Drama Comedy Romance
gay interest

United States of America
English
Drama


United States of America
English
Drama Thriller Science Fiction
monster pyramid radio dystopia infection forest low-budget alien alien invasion central america vigil cattle dead fish
Vertigo Entertainment
United Kingdom
Español English
Drama Comedy

Parker Film Company
United States of America
English
Comedy
independent film



Comedy Horror
high school independent film zombie extreme violence
Gala Film
United States of America
English
Action Comedy


China Hong Kong
普通话
Documentary Music
music

France United Kingdom United States of America
English
Drama
independent film
Furst Films
United States of America
English
Action Drama Thriller
pilot suspicion drone u.s. military air force base combat drone
Voltage Pictures Sobini Films Dune Films
United States of America
English




English
Drama Romance
cancer teenager teen drama bucket list based on young adult novel
Goldcrest Pictures
United Kingdom
English Français Deutsch
Horror Comedy

Spy Global Media
United States of America
English





Action Thriller Mystery
submarine woman director
Rainsworth Productions Hilton Media Management Underwater Productions
United States of America
English
Mystery Science Fiction Thriller
cabin time travel woods cabin in the woods lost german soldier time paradox
Caliber Media Company
United States of America
English Deutsch
Crime Drama


Dominican Republic
Español
Romance Action
sport fighting
Triple D Productions CalTex Films
United States of America
English
Music Horror
carnival musical sequel devil dark carnival
Limb from Limb Pictures Execution Style Entertainment
United States of America

Thriller Comedy Mystery

Veracity Productions
United States of America
English
Family

Be Your Own Hollywood
United States of America
English
Documentary
woman director

United States of America United Kingdom
English




English
Science Fiction Action Comedy Horror
corruption mayor anti hero sadism toxic movie reference person on fire t shirt workout health club rabid anger disfigured face superhero spoof strong man car run over shock humor
Troma Entertainment
United States of America
English
Drama




Action Adventure Drama History
northern ireland independent film civil rights
Portman Entertainment Group Bórd Scannán na hÉireann Hell's Kitchen Films Granada Television
Ireland United Kingdom
English Gaeilge





Drama Romance
dialogue talking bridesmaid wedding reception wedding dialogue driven
Prophecy Pictures Ltd. Gordonstreet Pictures
United Kingdom United States of America
English
Horror Comedy
musical zombie
Troma Entertainment Poultry Productions LLC
United States of America
English




English
Music Comedy Romance
philadelphia musical stage show director broken ankle chorus line pet dog broadway fainting chorus girl opening night crutch theatrical backer eviction show producer chorine plaster cast show must go on financial crisis sock on the jaw
Warner Bros.
United States of America
English





Comedy Drama
upper class new york independent film debutante young adult
Allagash Films
United States of America
English
Romance Drama Comedy Music
individual underdog mentally disabled loss of mother sweden pastor suppressed past heart attack loss of father conductor choir violent husband church choir choirmaster dying and death village music concert secret love
GF Studios AB Lefwander Kapitalförvaltning AB Sonet Film AB
Sweden
English Italiano svenska
Horror Drama




Comedy
underdog brother brother relationship idaho high school chat independent film teenager school dance social outcast aftercreditsstinger
Paramount Pictures Fox Searchlight Pictures MTV Films Access Films Napoleon Pictures Limited Carnival Films
United States of America
English
Crime Thriller
revenge drifter virginia character study neo-noir visual storytelling mumblegore
Film Science The Lab Of Madness Neighborhood Watch Paradise City
United States of America
English
Horror Mystery
haunting psychic entity demonic possession found footage
Blumhouse Productions Solana Films
United States of America
English
Documentary
skateboarding independent film
Agi Orsi Productions Vans Off the Wall
United States of America
English
Adventure Comedy Fantasy
holy grail monk scotland yard swordplay camelot round table chapter aggression by animal knight king arthur wedding reception midnight movie monty python knights of the round table anarchic comedy
Python (Monty) Pictures Limited Michael White Productions National Film Trustee Company Twickenham Film Studios
United Kingdom
Français Latin English
Drama


United States of America
English

woman director



Documentary Drama

English
Horror
high school murder slasher teenager


English
Documentary Music
1970s music
FM Productions Last Waltz Inc.
United States of America
English
Thriller Horror
revenge murder
Little Big Film Company Abundant Productions Faith vs. Fate Productions
United States of America
English
Drama Romance
independent film


English
Action Western




Drama Comedy
musician romance independent film mumblecore


English
Horror




Drama Action Comedy
murder dark comedy crime family

United Kingdom
English
Comedy
salesclerk loser aftercreditsstinger
Miramax Films View Askew Productions
United States of America
English
Drama Romance
dream prostitution
Strand Releasing
United States of America
English Français
Drama Comedy
mumblecore

United States of America
English
Comedy Drama
office love independent film secretary misogynist
Alliance Atlantis Communications Fair and Square Productions
Canada United States of America
English
Drama


United States of America
Español English
Action Drama Crime Thriller
rampage massacre killing spree
Boll Kino Beteiligungs GmbH & Co. KG Brightlight Pictures Pitchblack Pictures Inc. Event Film Distribution Amok Productions
Canada Germany
English
Comedy
moon philosophy burglar texas dream atomic bomb tent anarchist telescope ufo independent film cigarette smoking african american writer cafe sunglasses pap smear austin texas hit and run dallas texas twenty something reference to jack ruby dairy queen restaurant moon walk anarchic comedy

United States of America
English
Thriller Crime Drama




Comedy Romance
dating divorce sex scene sex comedy anti romantic comedy

United States of America
English
Drama Family
christianity father son relationship georgia ark of the covenant minister christian film repentance

United States of America
English
Thriller Horror
possession
GO Productions Vicarious Entertainment Bloodline Productions Shallow Focus
United States of America
English
Drama Comedy Romance
mumblecore



Drama


Kenya
Kiswahili English
Comedy Romance
independent film

United States of America
English
Science Fiction Thriller
superhero
Grindfest

English
Horror Comedy Crime
gay trailer park pop culture drug dealer heroin fetishism spanner excrements  disgust dog dirt van independent film adult humor unsimulated sex cult classic drag hitchhike
Dreamland Productions
United States of America
English
Drama
addiction recovering drug addict estranged son

United Kingdom France Canada
广州话 / 廣州話 English Français
Drama Foreign

Jafar Panahi Film Productions
Iran
فارسی
Horror
home invasion
Park Films Camera Stylo Films
Ireland
English
Crime Horror Mystery Thriller
japan prostitute hotel based on novel hallucination interview investigation murder junkyard interrogation stranger psychosis record player mental hospital neo-noir personality disorder serial kiler
Daiei Studios
Japan
日本語
Drama
confession hazing gang member latino lgbt catholic priest shakespeare's romeo and juliet latino lgbt gang initiation gunplay
Iconoclast Films
United States of America

Thriller Horror Comedy

Gold Lion Films T-Street Productions
United States of America
English
Drama
gang audition police fake homeless actress
Asylum Films FM Entertainment Eagle Eye Films Inc.
United States of America
English
Science Fiction Drama Thriller
distrust garage identity crisis time travel time machine mathematics independent film paradox mechanical engineering
Thinkfilm
United States of America
English
Foreign Thriller




Action Crime Thriller
united states–mexico barrier legs arms paper knife guitar case
Columbia Pictures
Mexico United States of America
Español
Comedy Romance




Comedy Drama Romance TV Movie
date love at first sight narration investigation team postal worker
Front Street Pictures Muse Entertainment Enterprises
United States of America
English



United States of America China
English
Documentary
obsession camcorder crush dream girl
rusty bear entertainment lucky crow films
United States of America
English

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,Ingenious Film Partners Twentieth Century Fox ...,United States of America United Kingdom,2009-12-10,2787965087,162.0,English Español,Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,Walt Disney Pictures Jerry Bruckheimer Films S...,United States of America,2007-05-19,961000000,169.0,English,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6 bri...,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,Columbia Pictures Danjaq B24,United Kingdom United States of America,2015-10-26,880674609,148.0,Français English Español Italiano Deutsch,Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,Legendary Pictures Warner Bros. DC Entertainme...,United States of America,2012-07-16,1084939099,165.0,English,Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,Walt Disney Pictures,United States of America,2012-03-07,284139100,132.0,English,Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,Action Crime Thriller,NaN,9367,united states–mexico barrier legs arms paper k...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,Columbia Pictures,Mexico United States of America,1992-09-04,2040920,81.0,Español,Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,Comedy Romance,NaN,72766,,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,,,2011-12-26,0,85.0,,Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,Front Street Pictures Muse Entertainment Enter...,United States of America,2013-10-13,0,120.0,English,Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,,http://shanghaicalling.com/,126186,,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,,United States of America China,2012-05-03,0,98.0,English,Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,rusty bear entertainment lucky crow films,United States of America,2005-08-05,0,90.0,English,Released,NaN,My Date with Drew,6.3,16

In [89]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [90]:
data = data[['original_title', 'genres', 'popularity', 'runtime', 'vote_average', 'vote_count']]

In [91]:
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4801 entries, 0 to 4802
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   original_title  4801 non-null   object
 1   genres          4801 non-null   object
 2   popularity      4801 non-null   float64
 3   runtime         4801 non-null   float64
 4   vote_average    4801 non-null   float64
 5   vote_count      4801 non-null   int64
dtypes: float64(3), int64(1), object(2)
memory usage: 262.6+ KB

# 장르기반 추천시스템 만들기
* 장르 컬럼의 텍스트를 숫자로 벡터화
* 코사인 유사도를 구해 비슷한 장르의 행 검색
* 유사도가 높은 행을 기준으로 내림차순 정렬

In [92]:
from sklearn.feature_extraction.text import CountVectorizer

In [93]:
cv = CountVectorizer(ngram_range=(1,2))
genres_mat = cv.fit_transform(data['genres'])
print(len(cv.get_feature_names_out()))
genres_mat_df = pd.DataFrame(genres_mat)
genres_mat_df

126

                                                      0
0       (np.int32(0), np.int32(66))\t4\n  (np.int32(...
1       (np.int32(0), np.int32(66))\t3\n  (np.int32(...
2       (np.int32(0), np.int32(66))\t3\n  (np.int32(...
3       (np.int32(0), np.int32(66))\t4\n  (np.int32(...
4       (np.int32(0), np.int32(66))\t3\n  (np.int32(...
...                                                 ...
4796    (np.int32(0), np.int32(66))\t3\n  (np.int32(...
4797    (np.int32(0), np.int32(66))\t2\n  (np.int32(...
4798    (np.int32(0), np.int32(66))\t4\n  (np.int32(...
4799
4800    (np.int32(0), np.int32(66))\t1\n  (np.int32(...

[4801 rows x 1 columns]

In [94]:
genres_mat_df.loc[0,:]

0      (np.int32(0), np.int32(66))\t4\n  (np.int32(...
Name: 0, dtype: object

* 코사인 유사도를 이용해 genres_mat의 유사도 산출 후 genres_sim 생성
* 비슷한 장르의 영화를 찾기 위해서 계산
* 코사인 유사도는 주로 문자, 문서의 유사도를 계산하는데 사용 됨

In [97]:
from sklearn.metrics.pairwise import cosine_similarity

In [98]:
genres_sim = cosine_similarity(genres_mat, genres_mat)
print(genres_sim.shape)

(4801, 4801)

In [99]:
genres_sim_df = pd.DataFrame(genres_sim)
genres_sim_df

,0,1,2,3,4,5,6,7,8,9,...,4791,4792,4793,4794,4795,4796,4797,4798,4799,4800
0,1.000000,0.917936,0.805993,0.678680,0.936333,0.917936,0.486190,0.936333,0.805993,0.917936,...,0.400501,0.537328,0.400501,0.675031,0.486190,0.671660,0.486190,0.561404,0.0,0.400501
1,0.917936,1.000000,0.828571,0.660971,0.805867,0.971429,0.465340,0.805867,0.857143,0.971429,...,0.383326,0.514286,0.383326,0.500193,0.465340,0.657143,0.465340,0.537328,0.0,0.383326
2,0.805993,0.828571,1.000000,0.797724,0.833655,0.828571,0.465340,0.833655,0.685714,0.857143,...,0.383326,0.514286,0.383326,0.500193,0.465340,0.828571,0.465340,0.537328,0.0,0.383326
3,0.678680,0.660971,0.797724,1.000000,0.665027,0.683763,0.494951,0.665027,0.547011,0.683763,...,0.662541,0.660971,0.662541,0.775864,0.649623,0.934477,0.494951,0.678680,0.0,0.407718
4,0.936333,0.805867,0.833655,0.665027,1.000000,0.805867,0.452589,1.000000,0.666924,0.833655,...,0.372822,0.500193,0.372822,0.675676,0.452589,0.666924,0.452589,0.522604,0.0,0.372822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,0.671660,0.657143,0.828571,0.934477,0.666924,0.685714,0.465340,0.666924,0.514286,0.685714,...,0.383326,0.657143,0.383326,0.639136,0.659232,1.000000,0.465340,0.537328,0.0,0.383326
4797,0.486190,0.465340,0.465340,0.494951,0.452589,0.465340,0.421053,0.452589,0.465340,0.465340,...,0.346844,0.659232,0.346844,0.452589,0.421053,0.465340,1.000000,0.820445,0.0,0.346844
4798,0.561404,0.537328,0.537328,0.678680,0.522604,0.537328,0.486190,0.522604,0.537328,0.537328,...,0.650814,0.649272,0.650814,0.653255,0.486190,0.537328,0.820445,1.000000,0.0,0.400501
4799,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
4800,0.400501,0.383326,0.383326,0.407718,0.372822,0.383326,0.346844,0.372822,0.383326,0.383326,...,0.285714,0.383326,0.285714,0.372822,0.346844,0.383326,0.346844,0.400501,0.0,1.000000

In [101]:
sorted_genres_sim = genres_sim.argsort()[:, ::-1]

In [102]:
sorted_genres_sim[:1]

array([[  14,  813,  870, ..., 4609, 4655, 4714]])

In [103]:
data.loc[0,:]

original_title                                               Avatar
genres            [{"id": 28, "name": "Action"}, {"id": 12, "nam...
popularity                                               150.437577
runtime                                                       162.0
vote_average                                                    7.2
vote_count                                                    11800
Name: 0, dtype: object

In [104]:
data.loc[14,:]

original_title                                         Man of Steel
genres            [{"id": 28, "name": "Action"}, {"id": 12, "nam...
popularity                                                99.398009
runtime                                                       143.0
vote_average                                                    6.5
vote_count                                                     6359
Name: 14, dtype: object

In [105]:
data.loc[813,:]

original_title                                             Superman
genres            [{"id": 28, "name": "Action"}, {"id": 12, "nam...
popularity                                                48.507081
runtime                                                       143.0
vote_average                                                    6.9
vote_count                                                     1022
Name: 813, dtype: object

In [106]:
data.loc[870,:]

original_title                                          Superman II
genres            [{"id": 28, "name": "Action"}, {"id": 12, "nam...
popularity                                                30.515175
runtime                                                       127.0
vote_average                                                    6.5
vote_count                                                      629
Name: 870, dtype: object

# 영화 이름과 추천 받을 개수를 입력받아 추천영화 출력하기

In [109]:
movie_index = data[data['original_title'] == 'Avatar'].index.values[0]

In [111]:
recommaned_idx = sorted_genres_sim[movie_index, 1:11]

In [112]:
data.loc[recommaned_idx, :]

,original_title,genres,popularity,runtime,vote_average,vote_count
813,Superman,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",48.507081,143.0,6.9,1022
870,Superman II,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",30.515175,127.0,6.5,629
3493,Morvern Callar,"[{""id"": 18, ""name"": ""Drama""}]",2.507912,97.0,7.2,34
46,X-Men: Days of Future Past,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",118.078691,131.0,7.5,6032
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",150.437577,162.0,7.2,11800
10,Superman Returns,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",57.925623,154.0,5.4,1400
232,The Wolverine,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",15.953444,126.0,6.3,4053
61,Jupiter Ascending,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",85.369080,124.0,5.2,2768
3207,Awake,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",18.172736,84.0,6.3,395
1296,Superman III,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 28, ""nam...",22.164202,125.0,5.3,490

In [115]:
def find_sim_movie(data, sorted_genres_sim, title_name, top_n=10):
    title_movie = data[data['original_title'] == title_name]
    title_index = title_movie.index.values[0]
    similar_idxs = sorted_genres_sim[title_index, 1:top_n+1]
    return data.iloc[similar_idxs]

In [116]:
find_sim_movie(data, sorted_genres_sim, "Superman III", 5)

,original_title,genres,popularity,runtime,vote_average,vote_count
1932,Sheena,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",4.020194,117.0,5.0,22
618,Mystery Men,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",12.948627,121.0,5.7,250
238,Teenage Mutant Ninja Turtles,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",143.350376,101.0,5.8,2636
1191,Small Soldiers,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 12, ""nam...",23.088571,110.0,6.2,511
859,Thunderbirds,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",9.278750,95.0,4.2,91